/*
 * test_gf2n.c — self-test for GF(2^n) arithmetic.
 *
 * Verifies, for each supported n:
 *   - X * X == X^2 (i.e. element "2" squared == "4")
 *   - X^n mod phi == (phi without its leading term)  [reduction correctness]
 *   - a * a^{-1} == 1 for a random fixed a
 *   - a specific known vector matches the Python reference (hard-coded below)
 *
 * Build: see Makefile target test_gf2n.
 */
#include <stdio.h>
#include <string.h>
#include "gf2n.h"
#include "gf2n_vectors.h"

static int fail_count = 0;
#define CHECK(cond, msg) do { if (!(cond)) { printf("FAIL [%s]\n", msg); fail_count++; } \
                           else { printf("ok   [%s]\n", msg); } } while (0)

/* Known test vectors generated by params/parameter_gen.py semantics:
   for each n, a fixed a, b and the expected a*b (little-endian bytes). */
static const struct {
    unsigned n;
    const uint8_t a[64];
    const uint8_t b[64];
    const uint8_t expected[64];
} VEC[] = {
    /* n=128: a=3 (X+1), b=5 (X^2+1) => a*b = X^3+X^2+X+1 = 0x0F */
    {128,
     {3,0},{5,0},
     {0x0F,0}},
    /* n=160: a=3, b=5 => 0x0F as well (no reduction needed at this size) */
    {160,
     {3,0},{5,0},
     {0x0F,0}},
    /* n=256: same trivial product */
    {256,
     {3,0},{5,0},
     {0x0F,0}},
    {384,
     {3,0},{5,0},
     {0x0F,0}},
    {512,
     {3,0},{5,0},
     {0x0F,0}},
};

/* expected X^n mod phi = phi's low bytes (the constant term of phi minus X^n) */
static const struct { unsigned n; uint8_t xpow_n[64]; } XPOW[] = {
    /* X^128 mod (X^128+X^7+X^2+X+1) = X^7+X^2+X+1 = 0x87 */
    {128, {0x87, 0}},
    /* X^160 mod (X^160+X^5+X^3+X^2+1) = X^5+X^3+X^2+1 = 0x2D */
    {160, {0x2D, 0}},
    /* X^256 mod (X^256+X^10+X^5+X^2+1) = X^10+X^5+X^2+1 = 0x425 */
    {256, {0x25, 0x04, 0}},
    /* X^384 mod (X^384+X^16+X^15+X^6+1) = X^16+X^15+X^6+1 = 0x18041 */
    {384, {0x41, 0x80, 0x01, 0}},
    /* X^512 mod (X^512+X^8+X^5+X^2+1) = 0x125 */
    {512, {0x25, 0x01, 0}},
};

int main(void) {
    for (size_t v = 0; v < sizeof(VEC)/sizeof(VEC[0]); ++v) {
        char label[64];
        gf_ctx ctx;
        unsigned n = VEC[v].n;
        if (gf_init(&ctx, n) != 0) { printf("FAIL gf_init n=%u\n", n); fail_count++; continue; }
        gf_limb_t a[GF_LIMBS(512)], b[GF_LIMBS(512)], r[GF_LIMBS(512)], e[GF_LIMBS(512)];
        gf_from_bytes(&ctx, a, VEC[v].a);
        gf_from_bytes(&ctx, b, VEC[v].b);
        gf_from_bytes(&ctx, e, VEC[v].expected);
        gf_mul(&ctx, r, a, b);
        snprintf(label, sizeof(label), "n=%u  a*b matches known vector", n);
        CHECK(memcmp(r, e, ctx.nbytes) == 0, label);

        /* X^n mod phi: build by multiplying X into an accumulator n times. */
        gf_limb_t xn[GF_LIMBS(512)], xpow_e[GF_LIMBS(512)];
        gf_from_bytes(&ctx, xpow_e, XPOW[v].xpow_n);
        gf_limb_t base[GF_LIMBS(512)];
        gf_zero(&ctx, base); base[0] = 2; /* X */
        /* acc = 1, then acc *= X, n times => X^n */
        gf_limb_t acc[GF_LIMBS(512)]; gf_zero(&ctx, acc); acc[0] = 1;
        for (unsigned k = 0; k < n; ++k) {
            gf_limb_t t[GF_LIMBS(512)];
            gf_mul(&ctx, t, acc, base);
            gf_copy(&ctx, acc, t);
        }
        gf_copy(&ctx, xn, acc);
        snprintf(label, sizeof(label), "n=%u  X^n mod phi == phi-low", n);
        CHECK(memcmp(xn, xpow_e, ctx.nbytes) == 0, label);

        /* inv: a * a^{-1} == 1 for a = some nonzero fixed value */
        gf_limb_t aa[GF_LIMBS(512)], inv[GF_LIMBS(512)], one[GF_LIMBS(512)];
        /* aa = a random-ish nonzero: build from a few set bits */
        gf_zero(&ctx, aa); aa[0] = 0x123456789abcdef0ULL; aa[ctx.nlimbs-1] |= 1;
        gf_inv(&ctx, inv, aa);
        gf_mul(&ctx, one, aa, inv);
        gf_limb_t expect_one[GF_LIMBS(512)]; gf_zero(&ctx, expect_one); expect_one[0] = 1;
        snprintf(label, sizeof(label), "n=%u  a * a^-1 == 1", n);
        CHECK(memcmp(one, expect_one, ctx.nbytes) == 0, label);
    }
    printf("\n%s (%d failures)\n", fail_count ? "FAIL" : "ALL PASS", fail_count);

    /* Strengthen with random mul vectors from the Python reference. */
    for (size_t v = 0; v < GFV_LEN; ++v) {
        gf_ctx ctx;
        if (gf_init(&ctx, GFV[v].n) != 0) { fail_count++; continue; }
        gf_limb_t a[GF_LIMBS(512)], b[GF_LIMBS(512)], r[GF_LIMBS(512)], e[GF_LIMBS(512)];
        gf_from_bytes(&ctx, a, GFV[v].a);
        gf_from_bytes(&ctx, b, GFV[v].b);
        gf_from_bytes(&ctx, e, GFV[v].mul);
        gf_mul(&ctx, r, a, b);
        if (memcmp(r, e, ctx.nbytes) != 0) {
            printf("FAIL [random mul n=%u]\n", GFV[v].n); fail_count++;
        }
    }
    printf("random-vector mul checks: %zu, total failures: %d\n", (size_t)GFV_LEN, fail_count);
    return fail_count ? 1 : 0;
}
