#ifndef CRETAKE_PARAMS_H
#define CRETAKE_PARAMS_H

#include "primitive_interfaces.h"

#define PKI_LEN BIT_PUBLICKEYBYTES
#define SKI_LEN BIT_SECRETKEYBYTES
#define PKR_LEN BIT_PUBLICKEYBYTES
#define SKR_LEN BIT_SECRETKEYBYTES

#define TPK_LEN ZEN_INDCPA_PUBLICKEY_LEN_BYTES
#define TSK_LEN ZEN_INDCPA_SECREKEY_LEN_BYTES

#define C_TILDE_LEN ZEN_INDCPA_CIPHERTEXT_LEN_BYTES
#define KEM_K_LEN ZEN_SHAREDKEY_LEN_BYTES
#define K_LEN 2 * KEM_K_LEN
#define SIG_LEN BIT_SIGNBYTES

#define MSG_LEN_BYTES ZEN_INDCPA_MSG_LEN_BYTES
#define SEED_BYTES SEED_LEN_BYTES

#endif
