CC = /usr/bin/cc
CFLAGS = -Wall -Wextra -march=native -mtune=native -O3 -fomit-frame-pointer -mpopcnt -Wno-incompatible-pointer-types
NISTFLAGS = -O3 -fomit-frame-pointer -march=native -fPIC
SOURCES = sign.c polyvec.c packing.c poly.c ntt.c fips202.c hashkdf.c pspm.c\
  fips202x4.c keccak4x/KeccakP-1600-times4-SIMD256.o auxfunc.c SIG_AlgorithmInstance.c drng.c sample.c
HEADERS = api.h params.h sign.h polyvec.h packing.h poly.h ntt.h pspm.h sample.h align.h\
  fips202.h fips202x4.h hashkdf.h auxfunc.h SIG_AlgorithmInstance.h drng.h randombytes.h

RANDOM = randombytes.c

DRANDOM = rng.c


SPEED_TARGETS = speed256_sha3
KAT_TARGETS = PQCgenKAT_sign256_iccs

all: $(SPEED_TARGETS) $(KAT_TARGETS)

keccak4x/KeccakP-1600-times4-SIMD256.o: keccak4x/KeccakP-1600-times4-SIMD256.c \
  keccak4x/align.h keccak4x/brg_endian.h keccak4x/KeccakP-1600-times4-SnP.h \
  keccak4x/KeccakP-1600-unrolling.macros keccak4x/SIMD256-config.h
	$(CC) $(CFLAGS) -c $< -o $@

speed128_sha3: $(SOURCES) $(RANDOM) aigis_sig.c \
  speed.c cpucycles.c $(HEADERS) speed.h \
  cpucycles.h
	$(CC) $(CFLAGS)  -DPARAMS=1 -DUSE_SHA3 $(SOURCES) $(RANDOM) aigis_sig.c \
	  speed.c cpucycles.c -o $@

speed256_sha3: $(SOURCES) $(RANDOM) aigis_sig.c \
  speed.c cpucycles.c $(HEADERS)  speed.h \
  cpucycles.h
	$(CC) $(CFLAGS)  -DPARAMS=2 -DUSE_SHA3 $(SOURCES) $(RANDOM) aigis_sig.c \
	  speed.c cpucycles.c -o $@

speed512_sha3: $(SOURCES) $(RANDOM) aigis_sig.c \
  speed.c cpucycles.c $(HEADERS) speed.h \
  cpucycles.h
	$(CC) $(CFLAGS)  -DPARAMS=3 -DUSE_SHA3 $(SOURCES) $(RANDOM) aigis_sig.c \
	  speed.c cpucycles.c -o $@

PQCgenKAT_sign128_iccs: KAT_SIG.c $(SOURCES) $(HEADERS) $(DRANDOM)
	$(CC) $(CFLAGS) -DPARAMS=1 -DUSE_ICCS $(SOURCES) $(DRANDOM) KAT_SIG.c -o $@

PQCgenKAT_sign256_iccs: KAT_SIG.c $(SOURCES) $(HEADERS) $(DRANDOM)
	$(CC) $(CFLAGS) -DPARAMS=2 -DUSE_ICCS $(SOURCES) $(DRANDOM) KAT_SIG.c -o $@

PQCgenKAT_sign512_iccs: KAT_SIG.c $(SOURCES) $(HEADERS) $(DRANDOM)
	$(CC) $(CFLAGS) -DPARAMS=3 -DUSE_ICCS $(SOURCES) $(DRANDOM) KAT_SIG.c -o $@


SPEED: $(SPEED_TARGETS)
	@echo "test speed..."
	./$(SPEED_TARGETS)

KAT: $(KAT_TARGETS)
	@echo "generate kat files..."
	./$(KAT_TARGETS)

.PHONY: clean SPEED KAT all

clean:
	-rm $(SPEED_TARGETS)
	-rm $(KAT_TARGETS)
	-rm -rf output

