

# This file was *autogenerated* from the file precompute_torsion_constants.sage
from sage.all_cmdline import *   # import sage library

_sage_const_9 = Integer(9); _sage_const_8 = Integer(8); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_3 = Integer(3); _sage_const_7 = Integer(7)#!/usr/bin/env sage
proof.all(False)  # faster

from sage.misc.banner import require_version
if not require_version(_sage_const_9 , _sage_const_8 , print_message=True):
    exit('')

################################################################

from parameters import p, B, f, Tpls, Tmin, Dcom, Dchall

################################################################

Lpls = sorted(set(Tpls.prime_factors()) - {_sage_const_2 })
Epls = [Tpls.valuation(l) for l in Lpls]

Lmin = sorted(set(Tmin.prime_factors()) - {_sage_const_2 })
Emin = [Tmin.valuation(l) for l in Lmin]

tors2part = (p+_sage_const_1 ).p_primary_part(_sage_const_2 )
tors3part = (p+_sage_const_1 ).p_primary_part(_sage_const_3 )
tors23part = tors2part * tors3part

defs = {
        'TORSION_2POWER_BYTES': (int(tors2part).bit_length() + _sage_const_7 ) // _sage_const_8 ,
        'TORSION_3POWER_BYTES': (int(tors3part).bit_length() + _sage_const_7 ) // _sage_const_8 ,
        'TORSION_23POWER_BYTES': (int(tors23part).bit_length() + _sage_const_7 ) // _sage_const_8 ,
    }

from cformat import Ibz, Object, ObjectFormatter

objs = ObjectFormatter([
        Object('uint64_t', 'TORSION_PLUS_EVEN_POWER', int(f)),
        Object('uint64_t[]', 'TORSION_ODD_PRIMES', Lpls + Lmin),
        Object('uint64_t[]', 'TORSION_ODD_POWERS', Epls + Emin),
        Object('uint64_t[]', 'TORSION_PLUS_ODD_PRIMES', Lpls),      # TODO deduplicate?
        Object('size_t[]', 'TORSION_PLUS_ODD_POWERS', Epls),        # TODO deduplicate?
        Object('uint64_t[]', 'TORSION_MINUS_ODD_PRIMES', Lmin),     # TODO deduplicate?
        Object('size_t[]', 'TORSION_MINUS_ODD_POWERS', Emin),       # TODO deduplicate?
        Object('size_t[]', 'DEGREE_COMMITMENT_POWERS', [Dcom.valuation(l) for l in Lpls+Lmin]), #FIXME should be ec_degree_odd_t
        Object('ibz_t', 'CHARACTERISTIC', Ibz(p)),
        Object('ibz_t', 'TORSION_ODD', Ibz(Tpls * Tmin)),
        Object('ibz_t[]', 'TORSION_ODD_PRIMEPOWERS', [Ibz(l**e) for Tpm in (Tpls,Tmin) for l,e in Tpm.factor()]),
        Object('ibz_t', 'TORSION_ODD_PLUS', Ibz(Tpls)),
        Object('ibz_t', 'TORSION_ODD_MINUS', Ibz(Tmin)),
        Object('ibz_t', 'TORSION_PLUS_2POWER', Ibz(tors2part)),
        Object('ibz_t', 'TORSION_PLUS_3POWER', Ibz(tors3part)),
        Object('ibz_t', 'TORSION_PLUS_23POWER', Ibz(tors23part)),
        Object('ibz_t', 'DEGREE_COMMITMENT', Ibz(Dcom)),
        Object('ibz_t', 'DEGREE_COMMITMENT_PLUS', Ibz(gcd(Dcom, Tpls))),
        Object('ibz_t', 'DEGREE_COMMITMENT_MINUS', Ibz(gcd(Dcom, Tmin))),
        Object('ibz_t', 'DEGREE_CHALLENGE', Ibz(Dchall)),
    ])

with open('include/torsion_constants.h','w') as hfile:
    with open('torsion_constants.c','w') as cfile:
        print(f'#include <intbig.h>', file=hfile)
        print(f'#include <stddef.h>', file=cfile)
        print(f'#include <stdint.h>', file=cfile)
        print(f'#include <torsion_constants.h>', file=cfile)

        for k,v in defs.items():
            print(f'#define {k} {v}', file=hfile)

        objs.header(file=hfile)
        objs.implementation(file=cfile)


