/**
 * @file polarkem_params.h
 * @brief Frozen parameters and serialized-object layout for PolarKEM-256.
 *
 * This header describes the functional consistency-evaluation profile.  It is
 * not a claim that the compact public signed permutation provides the security
 * properties of the lattice basis transformation in the frozen paper.
 */
#ifndef POLARKEM_PARAMS_H
#define POLARKEM_PARAMS_H

#include <stddef.h>
#include <stdint.h>

/** Official instance name used by the KAT driver. */
#define POLARKEM_INSTANCE_NAME "PolarKEM-256"
/** Lattice/code dimension in coefficients. */
#define POLARKEM_N 1024U
/** Base-two logarithm of POLARKEM_N. */
#define POLARKEM_LOGN 10U
/** Number of packed 64-bit words holding one binary codeword. */
#define POLARKEM_WORDS (POLARKEM_N / 64U)
/** Prime coefficient modulus retained from the PolarKEM-256 parameter table. */
#define POLARKEM_Q 12289U
/** Magnitude used for the centered binary coefficient embedding. */
#define POLARKEM_PEAK (POLARKEM_Q / 4U)
#define POLARKEM_AMPLITUDE POLARKEM_PEAK
/** Quantized bits stored for each ciphertext coefficient. */
#define POLARKEM_D 9U
#define POLARKEM_QUANT_BITS POLARKEM_D

/** Public-key byte length. */
#define POLARKEM_PK_BYTES 2048U
/** Secret-key byte length. */
#define POLARKEM_SK_BYTES 4096U
/** Ciphertext byte length. */
#define POLARKEM_CT_BYTES 1280U
/** Shared-secret and encapsulated-message byte length. */
#define POLARKEM_SS_BYTES 32U
#define POLARKEM_MU_BYTES 32U
#define POLARKEM_MU_BITS (POLARKEM_MU_BYTES * 8U)
#define POLARKEM_MESSAGE_BYTES POLARKEM_MU_BYTES
#define POLARKEM_MESSAGE_BITS POLARKEM_MU_BITS
#define POLARKEM_INFO_BITS POLARKEM_MESSAGE_BITS
#define POLARKEM_FROZEN_BITS (POLARKEM_N - POLARKEM_INFO_BITS)

/* Compatibility aliases used by shared build/test code. */
#define POLARKEM_PUBLICKEYBYTES POLARKEM_PK_BYTES
#define POLARKEM_SECRETKEYBYTES POLARKEM_SK_BYTES
#define POLARKEM_CIPHERTEXTBYTES POLARKEM_CT_BYTES
#define POLARKEM_SSBYTES POLARKEM_SS_BYTES

/** Common object header length and this parameter set's instance identifier. */
#define POLARKEM_HEADER_BYTES 16U
#define POLARKEM_INSTANCE_ID 0x03U
/** Transform seed, rejection seed, and digest/tag lengths in bytes. */
#define POLARKEM_SEED_BYTES 32U
#define POLARKEM_Z_BYTES 32U
#define POLARKEM_HASH_BYTES 32U
#define POLARKEM_TAG_BYTES 32U
#define POLARKEM_ERROR_STREAM_BYTES ((2U * POLARKEM_N) / 8U)

/** Public-key field offsets. */
#define POLARKEM_PK_SEED_OFFSET POLARKEM_HEADER_BYTES
#define POLARKEM_PK_PAD_OFFSET (POLARKEM_PK_SEED_OFFSET + POLARKEM_SEED_BYTES)
#define POLARKEM_PK_PAD_BYTES (POLARKEM_PK_BYTES - POLARKEM_PK_PAD_OFFSET)

/** Secret-key field offsets. */
#define POLARKEM_SK_Z_OFFSET POLARKEM_HEADER_BYTES
#define POLARKEM_SK_PK_OFFSET (POLARKEM_SK_Z_OFFSET + POLARKEM_Z_BYTES)
#define POLARKEM_SK_PAD_OFFSET (POLARKEM_SK_PK_OFFSET + POLARKEM_PK_BYTES)
#define POLARKEM_SK_PAD_BYTES (POLARKEM_SK_BYTES - POLARKEM_SK_PAD_OFFSET)

/** Ciphertext payload and authentication field layout. */
#define POLARKEM_CT_PAYLOAD_OFFSET POLARKEM_HEADER_BYTES
#define POLARKEM_CT_PAYLOAD_BITS (POLARKEM_N * POLARKEM_D)
#define POLARKEM_CT_PAYLOAD_BYTES (POLARKEM_CT_PAYLOAD_BITS / 8U)
#define POLARKEM_CT_TAG_OFFSET (POLARKEM_CT_PAYLOAD_OFFSET + POLARKEM_CT_PAYLOAD_BYTES)
#define POLARKEM_CT_PAD_OFFSET (POLARKEM_CT_TAG_OFFSET + POLARKEM_TAG_BYTES)
#define POLARKEM_CT_PAD_BYTES (POLARKEM_CT_BYTES - POLARKEM_CT_PAD_OFFSET)

/** Bytes generated by each signed-permutation XOF block. */
#define POLARKEM_PERM_BLOCK_BYTES 4096U
#define POLARKEM_PERM_XOF_BLOCK_BYTES POLARKEM_PERM_BLOCK_BYTES

/* C99 compile-time parameter and exact-layout assertions. */
typedef char polarkem_assert_n_is_power_of_two[
    ((POLARKEM_N & (POLARKEM_N - 1U)) == 0U) ? 1 : -1];
typedef char polarkem_assert_words_exact[
    ((POLARKEM_WORDS * 64U) == POLARKEM_N) ? 1 : -1];
typedef char polarkem_assert_logn_exact[
    ((1U << POLARKEM_LOGN) == POLARKEM_N) ? 1 : -1];
typedef char polarkem_assert_mu_fits[
    (POLARKEM_MU_BITS <= POLARKEM_N) ? 1 : -1];
typedef char polarkem_assert_payload_byte_aligned[
    ((POLARKEM_CT_PAYLOAD_BITS & 7U) == 0U) ? 1 : -1];
typedef char polarkem_assert_peak_exact[(POLARKEM_PEAK == 3072U) ? 1 : -1];
typedef char polarkem_assert_pk_layout[
    ((POLARKEM_PK_SEED_OFFSET == 16U) &&
     (POLARKEM_PK_PAD_OFFSET == 48U) &&
     (POLARKEM_PK_PAD_BYTES == 2000U)) ? 1 : -1];
typedef char polarkem_assert_sk_layout[
    ((POLARKEM_SK_Z_OFFSET == 16U) &&
     (POLARKEM_SK_PK_OFFSET == 48U) &&
     (POLARKEM_SK_PAD_OFFSET == 2096U) &&
     (POLARKEM_SK_PAD_BYTES == 2000U)) ? 1 : -1];
typedef char polarkem_assert_ct_layout[
    ((POLARKEM_CT_PAYLOAD_OFFSET == 16U) &&
     (POLARKEM_CT_PAYLOAD_BYTES == 1152U) &&
     (POLARKEM_CT_TAG_OFFSET == 1168U) &&
     (POLARKEM_CT_PAD_OFFSET == 1200U) &&
     (POLARKEM_CT_PAD_BYTES == 80U) &&
     ((POLARKEM_CT_PAD_OFFSET + POLARKEM_CT_PAD_BYTES) ==
      POLARKEM_CT_BYTES)) ? 1 : -1];

#endif /* POLARKEM_PARAMS_H */
