

# This file was *autogenerated* from the file precompute_sizes.sage
from sage.all_cmdline import *   # import sage library

_sage_const_9 = Integer(9); _sage_const_8 = Integer(8); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_3 = Integer(3); _sage_const_0 = Integer(0); _sage_const_63 = Integer(63); _sage_const_64 = Integer(64); _sage_const_4 = Integer(4); _sage_const_55 = Integer(55); _sage_const_7 = Integer(7); _sage_const_5 = Integer(5)#!/usr/bin/env sage
proof.all(False)  # faster

from sage.misc.banner import require_version
if not require_version(_sage_const_9 , _sage_const_8 , print_message=True):
    exit('')

################################################################

from parameters import lvl, f, p

################################################################

logp = ceil(log(p, _sage_const_2 ))
tors2part = (p+_sage_const_1 ).p_primary_part(_sage_const_2 )
tors3part = (p+_sage_const_1 ).p_primary_part(_sage_const_3 )

#XXX first load the constants from klpt_constants.h
import re
klpt_consts = dict()
for l in open('include/klpt_constants.h'):
    m = re.search(r'#define *([^ ]+) *([x0-9]+)$', l)
    if m:
        k,v = m.groups()
        klpt_consts[k] = int(v, _sage_const_0 )

defs = dict()

fp2sz = (logp + _sage_const_63 )//_sage_const_64 *_sage_const_8  * _sage_const_2 
defs['FP2_ENCODED_BYTES'] = fp2sz
defs['EC_CURVE_ENCODED_BYTES'] = fp2sz  # just the A
defs['EC_POINT_ENCODED_BYTES'] = fp2sz  # just the x
defs['EC_BASIS_ENCODED_BYTES'] = _sage_const_3  * defs['EC_POINT_ENCODED_BYTES']

defs['CHAIN_LENGTH'] = klpt_consts['SQISIGN_keygen_length']

defs['QUAT_ALG_ELEM_ENCODED_BITS'] = ceil(((logp/_sage_const_4 ) + klpt_consts['KLPT_keygen_length'])/_sage_const_2   +_sage_const_55 )  #TODO FIXME figure this out XXX XXX
defs['QUAT_ALG_ELEM_ENCODED_BYTES'] = (defs['QUAT_ALG_ELEM_ENCODED_BITS'] + _sage_const_7 )//_sage_const_8 
defs['ID2ISO_LONG_TWO_ISOG_ENCODED_BYTES'] = defs['CHAIN_LENGTH'] * (defs['EC_CURVE_ENCODED_BYTES'] + defs['EC_POINT_ENCODED_BYTES'] + _sage_const_2 )

defs['ZIP_CHAIN_LEN'] = klpt_consts['SQISIGN_signing_length']
defs['ID2ISO_COMPRESSED_LONG_TWO_ISOG_ZIP_CHAIN_BYTES'] = (f + _sage_const_7 ) // _sage_const_8 
defs['ID2ISO_COMPRESSED_LONG_TWO_ISOG_BYTES'] = defs['ZIP_CHAIN_LEN'] * defs['ID2ISO_COMPRESSED_LONG_TWO_ISOG_ZIP_CHAIN_BYTES'] + _sage_const_1 

defs['SIGNATURE_LEN'] = defs['ID2ISO_COMPRESSED_LONG_TWO_ISOG_BYTES'] + ((tors2part*tors3part).bit_length()+_sage_const_7 )//_sage_const_8  + _sage_const_1  + (tors2part.bit_length()+_sage_const_7 )//_sage_const_8  + (tors3part.bit_length()+_sage_const_7 )//_sage_const_8 
defs['PUBLICKEY_BYTES'] = defs['EC_CURVE_ENCODED_BYTES']
defs['SECRETKEY_BYTES'] = defs['EC_CURVE_ENCODED_BYTES'] + _sage_const_5 *defs['QUAT_ALG_ELEM_ENCODED_BYTES'] + defs['EC_POINT_ENCODED_BYTES'] + defs['EC_BASIS_ENCODED_BYTES'] + defs['EC_BASIS_ENCODED_BYTES']

size_privkey = defs['SECRETKEY_BYTES']
size_pubkey = defs['PUBLICKEY_BYTES']
size_signature = defs['SIGNATURE_LEN']

algname = f'lvl{lvl}'

################################################################

with open('include/encoded_sizes.h','w') as hfile:
    for k,v in defs.items():
        v = ZZ(v)
        print(f'#define {k} {v}', file=hfile)


