#ifndef VIPER_PARAMS_H
#define VIPER_PARAMS_H

/* MAMBA-Viper implementation and implementation support layer where applicable. */

#include <stddef.h>
#include <stdint.h>

#ifndef VIPER_LEVEL
#define VIPER_LEVEL 128
#endif

#define VIPER_N 256
#define VIPER_SEEDBYTES 32
#define VIPER_MU_BYTES 32
#define VIPER_HBYTES 32
#ifndef VIPER_USE_E8_CODEC
#define VIPER_USE_E8_CODEC 0
#endif

#if VIPER_LEVEL == 128
#define VIPER_Q 4096
#define VIPER_QLOG 12
#define VIPER_K 2
#define VIPER_ETA_S 2
#define VIPER_ETA_R 2
#define VIPER_T_PK 9
#define VIPER_T_U 9
#define VIPER_T_V 4
#define VIPER_MSG_BITS_PER_COEFF 1
#define VIPER_MSGBITS 128
#define VIPER_MSGBYTES 16
#define VIPER_SSBYTES 16
#define VIPER_ALGNAME "MAMBA-Viper-128"
#elif VIPER_LEVEL == 192
#define VIPER_Q 4096
#define VIPER_QLOG 12
#define VIPER_K 3
#define VIPER_ETA_S 3
#define VIPER_ETA_R 3
#define VIPER_T_PK 10
#define VIPER_T_U 9
#define VIPER_T_V 6
#define VIPER_MSG_BITS_PER_COEFF 1
#define VIPER_MSGBITS 192
#define VIPER_MSGBYTES 24
#define VIPER_SSBYTES 24
#define VIPER_ALGNAME "MAMBA-Viper-192"
#elif VIPER_LEVEL == 256
#define VIPER_Q 4096
#define VIPER_QLOG 12
#define VIPER_K 4
#define VIPER_ETA_S 3
#define VIPER_ETA_R 3
#define VIPER_T_PK 10
#define VIPER_T_U 10
#define VIPER_T_V 5
#define VIPER_MSG_BITS_PER_COEFF 1
#define VIPER_MSGBITS 256
#define VIPER_MSGBYTES 32
#define VIPER_SSBYTES 32
#define VIPER_ALGNAME "MAMBA-Viper-256"
#elif VIPER_LEVEL == 384
#define VIPER_Q 8192
#define VIPER_QLOG 13
#define VIPER_K 7
#define VIPER_ETA_S 1
#define VIPER_ETA_R 1
#define VIPER_T_PK 11
#define VIPER_T_U 11
#define VIPER_T_V 5
#define VIPER_MSG_BITS_PER_COEFF 2
#define VIPER_MSGBITS 384
#define VIPER_MSGBYTES 48
#define VIPER_SSBYTES 48
#define VIPER_ALGNAME "MAMBA-Viper-384"
#elif VIPER_LEVEL == 512
#define VIPER_Q 8192
#define VIPER_QLOG 13
#define VIPER_K 9
#define VIPER_ETA_S 1
#define VIPER_ETA_R 1
#define VIPER_T_PK 11
#define VIPER_T_U 11
#define VIPER_T_V 8
#define VIPER_MSG_BITS_PER_COEFF 2
#define VIPER_MSGBITS 512
#define VIPER_MSGBYTES 64
#define VIPER_SSBYTES 64
#define VIPER_ALGNAME "MAMBA-Viper-512"
#else
#error "Unsupported VIPER_LEVEL; use 128, 192, 256, 384, or 512"
#endif

#define VIPER_QMASK (VIPER_Q - 1)
#define VIPER_Q_MASK VIPER_QMASK
#define VIPER_SHARED_SECRET_BYTES VIPER_SSBYTES
#define VIPER_FALLBACK_KEY_BYTES VIPER_SSBYTES
#define VIPER_MSG_COEFFS ((VIPER_MSGBITS + VIPER_MSG_BITS_PER_COEFF - 1) / VIPER_MSG_BITS_PER_COEFF)
#define VIPER_E8_RATE (VIPER_MSG_BITS_PER_COEFF)
#define VIPER_E8_BITS_PER_BLOCK (8 * VIPER_E8_RATE)
#define VIPER_E8_TOTAL_BLOCKS (VIPER_N / 8)
#define VIPER_E8_ACTIVE_BLOCKS (VIPER_MSGBITS / VIPER_E8_BITS_PER_BLOCK)
#define VIPER_E8_ALPHA (VIPER_Q / (1 << VIPER_E8_RATE))
#define VIPER_E8_RESIDUE_BITS (VIPER_E8_RATE + 1)

#define VIPER_SECRET_POLYBYTES (VIPER_N * VIPER_QLOG / 8)
#define VIPER_SECRETKEY_PKE_BYTES (VIPER_K * VIPER_SECRET_POLYBYTES)
#define VIPER_PACKED_PK_POLYBYTES (VIPER_N * VIPER_T_PK / 8)
#define VIPER_PACKED_U_POLYBYTES (VIPER_N * VIPER_T_U / 8)
#define VIPER_PACKED_V_BYTES (VIPER_N * VIPER_T_V / 8)
#define VIPER_PACKED_B_BYTES (VIPER_K * VIPER_PACKED_PK_POLYBYTES)
#define VIPER_PACKED_U_BYTES (VIPER_K * VIPER_PACKED_U_POLYBYTES)

#define VIPER_PUBLICKEYBYTES (VIPER_SEEDBYTES + VIPER_PACKED_B_BYTES)
#define VIPER_CIPHERTEXTBYTES (VIPER_MU_BYTES + VIPER_PACKED_U_BYTES + VIPER_PACKED_V_BYTES)
#define VIPER_SECRETKEYBYTES (VIPER_SECRETKEY_PKE_BYTES + VIPER_PUBLICKEYBYTES + VIPER_HBYTES + VIPER_SSBYTES)

#define VIPER_DERIVED_PUBLICKEYBYTES (VIPER_SEEDBYTES + VIPER_PACKED_B_BYTES)
#define VIPER_DERIVED_CIPHERTEXTBYTES (VIPER_MU_BYTES + VIPER_PACKED_U_BYTES + VIPER_PACKED_V_BYTES)
#define VIPER_DERIVED_SECRETKEYBYTES (VIPER_SECRETKEY_PKE_BYTES + VIPER_PUBLICKEYBYTES + VIPER_HBYTES + VIPER_SSBYTES)

#define VIPER_EXPECTED_PUBLICKEYBYTES (32 + VIPER_K * VIPER_N * VIPER_T_PK / 8)
#define VIPER_EXPECTED_CIPHERTEXTBYTES (32 + VIPER_K * VIPER_N * VIPER_T_U / 8 + VIPER_N * VIPER_T_V / 8)
#define VIPER_EXPECTED_SECRETKEYBYTES (VIPER_SECRETKEY_PKE_BYTES + VIPER_PUBLICKEYBYTES + VIPER_HBYTES + VIPER_SSBYTES)

enum {
  VIPER_PUBLICKEY_SIZE_CHECK = 1 / (int)(VIPER_PUBLICKEYBYTES == VIPER_DERIVED_PUBLICKEYBYTES),
  VIPER_CIPHERTEXT_SIZE_CHECK = 1 / (int)(VIPER_CIPHERTEXTBYTES == VIPER_DERIVED_CIPHERTEXTBYTES),
  VIPER_SECRETKEY_SIZE_CHECK = 1 / (int)(VIPER_SECRETKEYBYTES == VIPER_DERIVED_SECRETKEYBYTES),
  VIPER_EXPECTED_PUBLICKEY_SIZE_CHECK = 1 / (int)(VIPER_PUBLICKEYBYTES == VIPER_EXPECTED_PUBLICKEYBYTES),
  VIPER_EXPECTED_CIPHERTEXT_SIZE_CHECK = 1 / (int)(VIPER_CIPHERTEXTBYTES == VIPER_EXPECTED_CIPHERTEXTBYTES),
  VIPER_EXPECTED_SECRETKEY_SIZE_CHECK = 1 / (int)(VIPER_SECRETKEYBYTES == VIPER_EXPECTED_SECRETKEYBYTES),
  VIPER_MESSAGE_COEFFS_CHECK = 1 / (int)(VIPER_MSG_COEFFS <= VIPER_N),
  VIPER_E8_BLOCKS_CHECK = 1 / (int)(VIPER_E8_TOTAL_BLOCKS == 32),
  VIPER_E8_ACTIVE_BLOCKS_CHECK = 1 / (int)(VIPER_E8_ACTIVE_BLOCKS <= VIPER_E8_TOTAL_BLOCKS),
  VIPER_E8_ALPHA_CHECK = 1 / (int)(VIPER_E8_ALPHA * (1 << VIPER_E8_RATE) == VIPER_Q)
};

#endif
