#ifndef CONFIG_H
#define CONFIG_H

//#define COMPASS_SIG_MODE 2
//#define COMPASS_SIG_RANDOMIZED_SIGNING
//#define USE_RDPMC
//#define DBENCH

#ifndef COMPASS_SIG_MODE
#define COMPASS_SIG_MODE 256
#endif

#if COMPASS_SIG_MODE == 128
#define CRYPTO_ALGNAME "COMPASS_SIG128"
#define COMPASS_SIG_NAMESPACETOP pqcrystals_COMPASS_SIG128_ref
#define COMPASS_SIG_NAMESPACE(s) pqcrystals_COMPASS_SIG128_ref_##s
#elif COMPASS_SIG_MODE == 256
#define CRYPTO_ALGNAME "COMPASS_SIG256"
#define COMPASS_SIG_NAMESPACETOP pqcrystals_COMPASS_SIG256_ref
#define COMPASS_SIG_NAMESPACE(s) pqcrystals_COMPASS_SIG256_ref_##s
#elif COMPASS_SIG_MODE == 384
#define CRYPTO_ALGNAME "COMPASS_SIG384"
#define COMPASS_SIG_NAMESPACETOP pqcrystals_COMPASS_SIG384_ref
#define COMPASS_SIG_NAMESPACE(s) pqcrystals_COMPASS_SIG384_ref_##s
#elif COMPASS_SIG_MODE == 512
#define CRYPTO_ALGNAME "COMPASS_SIG512"
#define COMPASS_SIG_NAMESPACETOP pqcrystals_COMPASS_SIG512_ref
#define COMPASS_SIG_NAMESPACE(s) pqcrystals_COMPASS_SIG512_ref_##s
#endif

#endif
