#!/usr/bin/env python3

from __future__ import annotations

import argparse
import math
import re
from pathlib import Path


def read_define_int(text: str, name: str) -> int:
    pattern = re.compile(
        rf"^\s*#\s*define\s+{re.escape(name)}\s+([0-9]+)\b",
        re.MULTILINE,
    )
    match = pattern.search(text)
    if match is None:
        raise SystemExit(f"missing integer define: {name}")
    return int(match.group(1))


def ceil_log2(x: int) -> int:
    if x <= 1:
        return 0
    return (x - 1).bit_length()


def max_binom_u64_r(t: int, k: int) -> int:
    limit = (1 << 64) - 1
    best = 0
    for r in range(0, k + 1):
        if math.comb(t, r) <= limit:
            best = r
        else:
            break
    return best


def u64_limbs_le(x: int) -> list[int]:
    mask = (1 << 64) - 1
    values: list[int] = []

    while x != 0:
        values.append(x & mask)
        x >>= 64

    if not values:
        values.append(0)

    return values


def fmt_u64(x: int) -> str:
    return f"UINT64_C(0x{x:x})"


def fmt_u256_initializer(x: int) -> str:
    limbs = u64_limbs_le(x)
    if len(limbs) == 1 and limbs[0] == 0:
        return "{{0}}"
    return "{{" + ", ".join(fmt_u64(v) for v in limbs) + "}}"


def fmt_u64_value(x: int) -> str:
    return "0" if x == 0 else fmt_u64(x)


def resolve_params(param_dir: Path, paramset: str) -> Path:
    params = param_dir / f"params-{paramset}.h"
    if not params.is_file():
        raise SystemExit(f"params file not found: {params}")
    return params


def default_out_path(param_dir: Path, paramset: str) -> Path:
    return param_dir / f"pors_precomputed-{paramset}.h"


def write_wrapped_values(
    f,
    values: list[str],
    indent: str = "    ",
    max_width: int = 118,
) -> None:
    line = indent

    for i, value in enumerate(values):
        token = value
        if i + 1 != len(values):
            token += ","

        if len(line) > len(indent) and len(line) + 1 + len(token) > max_width:
            f.write(line.rstrip() + "\n")
            line = indent + token + " "
        else:
            line += token + " "

    if line.strip():
        f.write(line.rstrip() + "\n")


def write_preamble(f, paramset: str) -> None:
    f.write("#ifndef PORS_PRECOMPUTED_TABLE_H\n")
    f.write("#define PORS_PRECOMPUTED_TABLE_H\n\n")
    f.write("/* This file was generated by gen_pors_precomputed_refactored.py. */\n")
    f.write(f"/* Parameter set: {paramset} */\n\n")
    f.write("#include <stdint.h>\n\n")


def write_checks(f, n: int, t: int, k: int) -> None:
    f.write("#ifndef SPX_N\n")
    f.write('#error "SPX_N is not defined"\n')
    f.write("#endif\n")
    f.write("#ifndef SPX_PORS_FP_T\n")
    f.write('#error "SPX_PORS_FP_T is not defined"\n')
    f.write("#endif\n")
    f.write("#ifndef SPX_PORS_FP_K\n")
    f.write('#error "SPX_PORS_FP_K is not defined"\n')
    f.write("#endif\n\n")

    f.write(f"#if SPX_N != {n}\n")
    f.write('#error "pors precomputed table was generated for a different SPX_N"\n')
    f.write("#endif\n")
    f.write(f"#if SPX_PORS_FP_T != {t}\n")
    f.write('#error "pors precomputed table was generated for a different SPX_PORS_FP_T"\n')
    f.write("#endif\n")
    f.write(f"#if SPX_PORS_FP_K != {k}\n")
    f.write('#error "pors precomputed table was generated for a different SPX_PORS_FP_K"\n')
    f.write("#endif\n\n")


def write_defines(
    f,
    limbs: int,
    total_bits: int,
    tree_height: int,
    stride: int,
    binom_u64_max_r: int,
) -> None:
    f.write(f"#define PORS_U256_LIMBS {limbs}u\n")
    f.write("#define PORS_U256_MAX_BYTES (PORS_U256_LIMBS * 8u)\n")
    f.write(f"#define PORS_TOTAL_COMBINATION_BITS {total_bits}u\n")
    f.write("#define PORS_TOTAL_COMBINATION_BYTES ((PORS_TOTAL_COMBINATION_BITS + 7u) / 8u)\n")
    f.write("#define PORS_HPORS_INPUT_BYTES (SPX_N + PORS_TOTAL_COMBINATION_BYTES)\n")
    f.write(f"#define PORS_TREE_HEIGHT_CONST {tree_height}u\n")

    if tree_height == 0:
        f.write("#define PORS_BASE_WIDTH_CONST 1u\n")
    else:
        f.write("#define PORS_BASE_WIDTH_CONST (1u << (PORS_TREE_HEIGHT_CONST - 1u))\n")

    f.write("#define PORS_SHORT_LEAF_START_CONST (SPX_PORS_FP_T - PORS_BASE_WIDTH_CONST)\n")
    f.write("#define PORS_DEEP_LEAF_COUNT_CONST (2u * PORS_SHORT_LEAF_START_CONST)\n")
    f.write(f"#define PORS_BINOM_STRIDE {stride}u\n")
    f.write(f"#define PORS_BINOM_U64_MAX_R {binom_u64_max_r}u\n\n")
    f.write("#include \"../pors_u256.h\"\n\n")


def write_binom_helpers(f) -> None:
    f.write("typedef struct {\n")
    f.write("    const uint32_t *offsets;\n")
    f.write("    const uint64_t *data;\n")
    f.write("} pors_precomp_binom_table;\n\n")

    f.write("static inline void pors_precomp_step_binom_up(pors_u256 *x,\n")
    f.write("                                               uint32_t m,\n")
    f.write("                                               uint32_t r)\n")
    f.write("{\n")
    f.write("    uint32_t a = m + 1u;\n")
    f.write("    uint32_t d = m + 1u - r;\n")
    f.write("    uint32_t g = pors_u32_gcd(a, d);\n\n")
    f.write("    a /= g;\n")
    f.write("    d /= g;\n")
    f.write("    if (d != 1u) {\n")
    f.write("        pors_u256_div_u32_exact(x, d);\n")
    f.write("    }\n")
    f.write("    if (a != 1u) {\n")
    f.write("        pors_u256_mul_u32(x, a);\n")
    f.write("    }\n")
    f.write("}\n\n")

def write_total_combination(f, total: int) -> None:
    f.write("static const pors_u256 pors_total_combination = ")
    f.write(fmt_u256_initializer(total))
    f.write(";\n\n")


def write_packed_binom_tables(f, t: int, k: int, stride: int) -> list[tuple[int, int]]:
    block_count = t // stride + 1
    metadata: list[tuple[int, int]] = []

    for r in range(2, k + 1):
        first_block = (r + stride - 1) // stride
        if first_block >= block_count:
            first_block = block_count - 1

        offsets = [0]
        data: list[int] = []

        for block in range(first_block, block_count):
            n = block * stride
            value = math.comb(n, r) if n >= r else 0
            limbs = u64_limbs_le(value)
            data.extend(limbs)
            offsets.append(len(data))

        metadata.append((r, first_block))

        f.write(f"static const uint32_t pors_binom_r{r}_offsets[] = {{\n")
        write_wrapped_values(f, [f"{x}u" for x in offsets])
        f.write("};\n\n")

        f.write(f"static const uint64_t pors_binom_r{r}_data[] = {{\n")
        write_wrapped_values(f, [fmt_u64_value(x) for x in data])
        f.write("};\n\n")

    return metadata


def write_binom_table_index(f, metadata: list[tuple[int, int]]) -> None:
    f.write("static const pors_precomp_binom_table pors_binom_tables[] = {\n")
    f.write("    {0, 0},\n")
    f.write("    {0, 0}")
    if metadata:
        f.write(",")
    f.write("\n")

    for i, (r, _) in enumerate(metadata):
        f.write(f"    {{pors_binom_r{r}_offsets, pors_binom_r{r}_data}}")
        if i + 1 != len(metadata):
            f.write(",")
        f.write("\n")

    f.write("};\n\n")


def write_binom_accessor(f, k: int, metadata: list[tuple[int, int]]) -> None:
    first_block_by_r = {r: first_block for r, first_block in metadata}

    f.write("static inline void pors_precomp_binom_get(pors_u256 *out,\n")
    f.write("                                             uint32_t n,\n")
    f.write("                                             uint32_t r)\n")
    f.write("{\n")
    f.write("    uint32_t base;\n")
    f.write("    uint32_t block;\n")
    f.write("    uint32_t row;\n")
    f.write("    uint32_t off;\n")
    f.write("    uint32_t len;\n\n")

    f.write("    if (r > n || r > SPX_PORS_FP_K || n > SPX_PORS_FP_T) {\n")
    f.write("        pors_u256_zero(out);\n")
    f.write("        return;\n")
    f.write("    }\n")
    f.write("    if (r == 0u) {\n")
    f.write("        pors_u256_set_u64(out, 1u);\n")
    f.write("        return;\n")
    f.write("    }\n")
    f.write("    if (r == 1u) {\n")
    f.write("        pors_u256_set_u64(out, n);\n")
    f.write("        return;\n")
    f.write("    }\n\n")

    f.write("    base = (n / PORS_BINOM_STRIDE) * PORS_BINOM_STRIDE;\n")
    f.write("    if (base < r) {\n")
    f.write("        base = r;\n")
    f.write("        pors_u256_set_u64(out, 1u);\n")
    f.write("    } else {\n")
    f.write("        block = base / PORS_BINOM_STRIDE;\n")
    f.write("        switch (r) {\n")

    for r in range(2, k + 1):
        first_block = first_block_by_r[r]
        f.write(f"        case {r}u:\n")
        f.write(f"            row = block - {first_block}u;\n")
        f.write(f"            off = pors_binom_r{r}_offsets[row];\n")
        f.write(f"            len = pors_binom_r{r}_offsets[row + 1u] - off;\n")
        f.write(f"            pors_u256_load_limbs(out, pors_binom_r{r}_data + off, len);\n")
        f.write("            break;\n")

    f.write("        default:\n")
    f.write("            pors_u256_zero(out);\n")
    f.write("            return;\n")
    f.write("        }\n")
    f.write("    }\n\n")

    f.write("    for (uint32_t m = base; m < n; m++) {\n")
    f.write("        pors_precomp_step_binom_up(out, m, r);\n")
    f.write("    }\n")
    f.write("}\n\n")


def write_byte_mod_table(f, total: int, hpors_input_bytes: int) -> None:
    f.write("static const pors_u256 pors_hpors_byte_mod_table[PORS_HPORS_INPUT_BYTES][256] = {\n")

    for pos in range(hpors_input_bytes):
        weight = pow(256, hpors_input_bytes - 1 - pos, total)
        values = [fmt_u256_initializer((byte * weight) % total) for byte in range(256)]

        f.write("    {\n")
        write_wrapped_values(f, values, indent="        ", max_width=118)
        f.write("    }")
        if pos + 1 != hpors_input_bytes:
            f.write(",")
        f.write("\n")

    f.write("};\n\n")


def generate(paramset: str, params: Path, out: Path, stride: int) -> None:
    if stride <= 0:
        raise SystemExit("--binom-stride must be positive")

    text = params.read_text(encoding="utf-8")

    n = read_define_int(text, "SPX_N")
    t = read_define_int(text, "SPX_PORS_FP_T")
    k = read_define_int(text, "SPX_PORS_FP_K")

    if k > t:
        raise SystemExit(f"invalid PORS parameters: k={k} > t={t}")

    total = math.comb(t, k)
    total_bits = max(1, total.bit_length())
    total_bytes = (total_bits + 7) // 8
    limbs = max(1, (total_bits + 63) // 64)
    tree_height = ceil_log2(t)
    hpors_input_bytes = n + total_bytes
    binom_u64_max_r = max_binom_u64_r(t, k)

    out.parent.mkdir(parents=True, exist_ok=True)

    with out.open("w", encoding="utf-8", newline="\n") as f:
        write_preamble(f, paramset)
        write_checks(f, n, t, k)
        write_defines(f, limbs, total_bits, tree_height, stride, binom_u64_max_r)
        write_binom_helpers(f)
        write_total_combination(f, total)
        metadata = write_packed_binom_tables(f, t, k, stride)
        write_binom_table_index(f, metadata)
        write_binom_accessor(f, k, metadata)
        write_byte_mod_table(f, total, hpors_input_bytes)
        f.write("#endif\n")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--paramset", required=True, help="parameter set name, e.g. flextree-160f")
    parser.add_argument("--param-dir", default="params", help="directory containing params-*.h")
    parser.add_argument("--out", help="generated precomputed header path")
    parser.add_argument("--binom-stride", type=int, default=1, help="checkpoint stride for binomial table")

    args = parser.parse_args()

    param_dir = Path(args.param_dir)
    params = resolve_params(param_dir, args.paramset)
    out = Path(args.out) if args.out is not None else default_out_path(param_dir, args.paramset)

    generate(args.paramset, params, out, args.binom_stride)


if __name__ == "__main__":
    main()
