//======================================================================
//
// tb_duet_1024.v
// ---------------
// Self-checking testbench for the Duet-1024 hash, driving the public
// 32-bit memory-mapped interface of the duet_1024 wrapper exactly as a
// host CPU would. Modelled directly on tb_duet.v (Duet-512) and
// tb_duet_768.v (Duet-768).
//
// Scope: three short vectors (msg_len 0, 1, 2 bits), generated from the
// reference C implementation (CryptHash_Duet-1024v2.c). Each is padded
// by the host into a single 768-bit block (M || 1 || 0^k) per
// pad_message_block() in the C reference, then absorbed in one shot
// (0 full blocks + 1 padding block).
//
// NOTE: the supplied KAT_2_12_Duet-1024.txt / KAT_2_23_Duet-1024.txt
// vectors do not match this C reference implementation (confirmed by
// direct compilation), so the expected digests below were generated by
// compiling and running CryptHash_Duet-1024v2.c directly rather than
// taken from those KAT files.
//
//   #1 : msg_len = 0
//   #2 : msg_len = 1, msg = 0x80
//   #3 : msg_len = 2, msg = 0x40
//
// Flow:
//   - pulse INIT   : clear A, B, C to zero
//   - write the padded 768-bit block (24 x 32-bit words, MSB word first)
//   - pulse ABSORB : run f1 (18 rounds) then f2 (18 rounds) sequentially
//   - read the 1024-bit digest (the high 1024 bits of the 1152-bit C
//     register; no extra squeeze calls are needed since 1024 <= 1152)
//
//======================================================================

`default_nettype none
`timescale 1ns/1ps

module tb_duet_1024;

  //----------------------------------------------------------------
  // Parameters.
  //----------------------------------------------------------------
  localparam CLK_HALF = 5;

  localparam ADDR_CTRL    = 8'h08;
  localparam ADDR_STATUS  = 8'h09;
  localparam ADDR_BLOCK0  = 8'h10;
  localparam ADDR_DIGEST0 = 8'h40;

  localparam CTRL_INIT   = 32'h1;
  localparam CTRL_ABSORB = 32'h2;

  localparam NUM_BLOCK_WORDS  = 24;
  localparam NUM_DIGEST_WORDS = 32;


  //----------------------------------------------------------------
  // DUT connections.
  //----------------------------------------------------------------
  reg          tb_clk;
  reg          tb_reset_n;
  reg          tb_cs;
  reg          tb_we;
  reg  [7 : 0] tb_address;
  reg  [31: 0] tb_write_data;
  wire [31: 0] tb_read_data;
  wire         tb_error;

  integer      errors;
  integer      tests;
  reg [1023:0]  digest_result;


  //----------------------------------------------------------------
  // DUT.
  //----------------------------------------------------------------
  duet_1024 dut(
           .clk(tb_clk),
           .reset_n(tb_reset_n),
           .cs(tb_cs),
           .we(tb_we),
           .address(tb_address),
           .write_data(tb_write_data),
           .read_data(tb_read_data),
           .error(tb_error)
          );


  //----------------------------------------------------------------
  // Clock.
  //----------------------------------------------------------------
  always
    begin : clk_gen
      #CLK_HALF tb_clk = !tb_clk;
    end


  //----------------------------------------------------------------
  // write_word / read_word : single-cycle bus transactions.
  //----------------------------------------------------------------
  task write_word(input [7:0] addr, input [31:0] data);
    begin
      @(negedge tb_clk);
      tb_cs         = 1'b1;
      tb_we         = 1'b1;
      tb_address    = addr;
      tb_write_data = data;
      @(negedge tb_clk);
      tb_cs         = 1'b0;
      tb_we         = 1'b0;
    end
  endtask

  task read_word(input [7:0] addr, output [31:0] data);
    begin
      @(negedge tb_clk);
      tb_cs      = 1'b1;
      tb_we      = 1'b0;
      tb_address = addr;
      @(negedge tb_clk);
      data       = tb_read_data;
      tb_cs      = 1'b0;
    end
  endtask


  //----------------------------------------------------------------
  // wait_ready / wait_busy / wait_valid.
  //----------------------------------------------------------------
  task wait_ready;
    reg [31:0] s;
    begin
      s = 32'h0;
      while (s[0] == 1'b0)
        read_word(ADDR_STATUS, s);
    end
  endtask

  task wait_busy;
    reg [31:0] s;
    begin
      s = 32'hffffffff;
      while (s[0] == 1'b1)
        read_word(ADDR_STATUS, s);
    end
  endtask

  task wait_valid;
    reg [31:0] s;
    begin
      s = 32'h0;
      while (s[1] == 1'b0)
        read_word(ADDR_STATUS, s);
    end
  endtask


  //----------------------------------------------------------------
  // pulse_init : clear A,B,C (single cycle, core stays ready).
  //----------------------------------------------------------------
  task pulse_init;
    begin
      write_word(ADDR_CTRL, CTRL_INIT);
      @(negedge tb_clk);
      wait_ready;
    end
  endtask


  //----------------------------------------------------------------
  // load_block : write a 768-bit block (24 x 32-bit words, MSB word
  // first) into BLOCK0..BLOCK23.
  //----------------------------------------------------------------
  task load_block(input [767:0] blk);
    integer i;
    begin
      for (i = 0; i < NUM_BLOCK_WORDS; i = i + 1)
        write_word(ADDR_BLOCK0 + i[7:0], blk[(NUM_BLOCK_WORDS - 1 - i)*32 +: 32]);
    end
  endtask


  //----------------------------------------------------------------
  // run_absorb : absorb one padded 768-bit block and capture the digest.
  //----------------------------------------------------------------
  task run_absorb(input [767:0] blk);
    integer i;
    reg [31:0] w;
    begin
      load_block(blk);
      write_word(ADDR_CTRL, CTRL_ABSORB);
      wait_busy;
      wait_valid;
      digest_result = 1024'h0;
      for (i = 0; i < NUM_DIGEST_WORDS; i = i + 1)
        begin
          read_word(ADDR_DIGEST0 + i[7:0], w);
          digest_result[(NUM_DIGEST_WORDS - 1 - i)*32 +: 32] = w;
        end
      wait_ready;
    end
  endtask


  //----------------------------------------------------------------
  // hash_short : init + absorb the single padded block.
  //----------------------------------------------------------------
  task hash_short(input [767:0] padded_block);
    begin
      pulse_init;
      run_absorb(padded_block);
    end
  endtask


  //----------------------------------------------------------------
  // check : compare digest against expected, report.
  //----------------------------------------------------------------
  task check(input [8*32-1:0] name, input [1023:0] expected);
    begin
      tests = tests + 1;
      if (digest_result === expected)
        $display("  [PASS] %0s", name);
      else
        begin
          errors = errors + 1;
          $display("  [FAIL] %0s", name);
          $display("         got = %h", digest_result);
          $display("         exp = %h", expected);
        end
    end
  endtask


  //----------------------------------------------------------------
  // Test sequence.
  //----------------------------------------------------------------
  initial
    begin : main
      $display("==================================================");
      $display(" Duet-1024 testbench (short vectors, from C reference)");
      $display("==================================================");

      tb_clk        = 1'b0;
      tb_reset_n    = 1'b0;
      tb_cs         = 1'b0;
      tb_we         = 1'b0;
      tb_address    = 8'h0;
      tb_write_data = 32'h0;
      errors        = 0;
      tests         = 0;

      // reset
      repeat (4) @(negedge tb_clk);
      tb_reset_n = 1'b1;
      repeat (2) @(negedge tb_clk);
      wait_ready;

      //--------------------------------------------------------
      // #1 : msg_len = 0  -> padded block = 0x80 || 0^760
      //--------------------------------------------------------
      hash_short(768'h800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000);
      check("msg_len=0",
            1024'h92B3AD87B10576CED88B978B62BBFB2B4ADCDCAF97654297614C16887EE045DADF8AA89BBC0793971E621B92DAFCBE8F8E1A4EB6FC17AED16315E564F048D2BA8C3AA3D05DB33011F857C8192630516C772504DAAC117C6AF53C1AE2011307AF7FB32530A29EF8178E93148F0A139DB980285237F14CFBACFDEA121CA7A32E0E);

      //--------------------------------------------------------
      // #2 : msg_len = 1, msg = 0x80 -> padded block = 0xC0 || 0^760
      //--------------------------------------------------------
      hash_short(768'hC00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000);
      check("msg_len=1",
            1024'h8DFD779CEDD7F28EDF6A0AE0B9F07D3E67E977FF94CAC65BE34C57FEF5BE494F09165AFF099CA73913F62A7A71270E9C37044369866C5437C09A03E5CCCB35E46D2E9F30AC7094F8FCD8F0E5C77418B599D0FF323BA66E870ED6BD506E145BAF5DB9C86927932203E9E182A05DB5A1F785BECE1BD84BCA4C52B7D4A59E617927);

      //--------------------------------------------------------
      // #3 : msg_len = 2, msg = 0x40 -> padded block = 0x60 || 0^760
      //--------------------------------------------------------
      hash_short(768'h600000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000);
      check("msg_len=2",
            1024'h88BDB051D7BFFB259A66117A6EFD56F0CC99ED576CE2CBDBB7D970C45A5FD5559ECCC5419897CD5EC24AE622B53409ACB5C1AC387726B3AC3F512E8FF681F924037F801E395135DF4FDF0B6D9BC84FD53B98E58A5CC431D58823AC95451476E05C9F3F59AA89273281A8B24C63C014EE112FB61F59C9F1D6F543D339AB9853AC);

      //--------------------------------------------------------
      // Summary.
      //--------------------------------------------------------
      $display("--------------------------------------------------");
      $display(" Tests run : %0d", tests);
      $display(" Failures  : %0d", errors);
      if (errors == 0)
        $display(" RESULT    : ALL TESTS PASSED");
      else
        $display(" RESULT    : %0d TEST(S) FAILED", errors);
      $display("==================================================");
      $finish;
    end

endmodule // tb_duet_1024

//======================================================================
// EOF tb_duet_1024.v
//======================================================================
