//======================================================================
//
// tb_duet_1024_2_23.v
// ---------------------
// Self-checking testbench for the Duet-1024 hash, covering all-zero and
// all-one 8388608-bit messages. Modelled directly on tb_duet_2_23.v
// (Duet-512) and tb_duet_768_2_23.v (Duet-768). Unlike tb_duet_1024.v
// (short vectors, which absorb a single padded block with no full
// blocks), these vectors drive 10922 full 768-bit blocks plus one
// final padded block (512-bit remainder + 1 || 0^k padding),
// exercising the multi-block chaining of A, B, and C across many
// absorb_block() calls.
//
// NOTE: the supplied KAT_2_23_Duet-1024.txt vectors do not match the C
// reference implementation (confirmed by direct compilation), so the
// expected digests below were generated by compiling and running
// CryptHash_Duet-1024v2.c directly rather than taken from that KAT
// file.
//
//   #1 : msg_len = 8388608, msg = all-zero
//   #2 : msg_len = 8388608, msg = all-one
//
// 8388608 / r=768 = 10922 full blocks with a 512-bit remainder
// (8388608 mod 768 = 512), so the final block carries that 512-bit
// message remainder followed by 1 || 0^k padding.
//
// Each vector absorbs 10923 blocks total (10922 full + 1 padded), at
// roughly 40 cycles/block (18+18 permutation rounds plus load/capture
// overhead), for a few hundred thousand simulated clock cycles. This
// completes in well under a minute under a standard event simulator
// (iverilog/vvp); it is not a synthesis-time concern.
//
//======================================================================

`default_nettype none
`timescale 1ns/1ps

module tb_duet_1024_2_23;

  //----------------------------------------------------------------
  // Parameters.
  //----------------------------------------------------------------
  localparam CLK_HALF = 5;

  localparam ADDR_CTRL    = 8'h08;
  localparam ADDR_STATUS  = 8'h09;
  localparam ADDR_BLOCK0  = 8'h10;
  localparam ADDR_DIGEST0 = 8'h40;

  localparam CTRL_INIT   = 32'h1;
  localparam CTRL_ABSORB = 32'h2;

  localparam NUM_BLOCK_WORDS  = 24;
  localparam NUM_DIGEST_WORDS = 32;

  localparam NUM_FULL_BLOCKS = 10922; // 8388608 / 768
  // remainder = 8388608 mod 768 = 512 bits -> one extra padded block


  //----------------------------------------------------------------
  // DUT connections.
  //----------------------------------------------------------------
  reg          tb_clk;
  reg          tb_reset_n;
  reg          tb_cs;
  reg          tb_we;
  reg  [7 : 0] tb_address;
  reg  [31: 0] tb_write_data;
  wire [31: 0] tb_read_data;
  wire         tb_error;

  integer      errors;
  integer      tests;
  reg [1023:0]  digest_result;


  //----------------------------------------------------------------
  // DUT.
  //----------------------------------------------------------------
  duet_1024 dut(
           .clk(tb_clk),
           .reset_n(tb_reset_n),
           .cs(tb_cs),
           .we(tb_we),
           .address(tb_address),
           .write_data(tb_write_data),
           .read_data(tb_read_data),
           .error(tb_error)
          );


  //----------------------------------------------------------------
  // Clock.
  //----------------------------------------------------------------
  always
    begin : clk_gen
      #CLK_HALF tb_clk = !tb_clk;
    end


  //----------------------------------------------------------------
  // write_word / read_word.
  //----------------------------------------------------------------
  task write_word(input [7:0] addr, input [31:0] data);
    begin
      @(negedge tb_clk);
      tb_cs         = 1'b1;
      tb_we         = 1'b1;
      tb_address    = addr;
      tb_write_data = data;
      @(negedge tb_clk);
      tb_cs         = 1'b0;
      tb_we         = 1'b0;
    end
  endtask

  task read_word(input [7:0] addr, output [31:0] data);
    begin
      @(negedge tb_clk);
      tb_cs      = 1'b1;
      tb_we      = 1'b0;
      tb_address = addr;
      @(negedge tb_clk);
      data       = tb_read_data;
      tb_cs      = 1'b0;
    end
  endtask


  //----------------------------------------------------------------
  // wait_ready / wait_busy / wait_valid.
  //----------------------------------------------------------------
  task wait_ready;
    reg [31:0] s;
    begin
      s = 32'h0;
      while (s[0] == 1'b0)
        read_word(ADDR_STATUS, s);
    end
  endtask

  task wait_busy;
    reg [31:0] s;
    begin
      s = 32'hffffffff;
      while (s[0] == 1'b1)
        read_word(ADDR_STATUS, s);
    end
  endtask

  task wait_valid;
    reg [31:0] s;
    begin
      s = 32'h0;
      while (s[1] == 1'b0)
        read_word(ADDR_STATUS, s);
    end
  endtask


  //----------------------------------------------------------------
  // pulse_init.
  //----------------------------------------------------------------
  task pulse_init;
    begin
      write_word(ADDR_CTRL, CTRL_INIT);
      @(negedge tb_clk);
      wait_ready;
    end
  endtask


  //----------------------------------------------------------------
  // load_block : write a 768-bit block (24 x 32-bit words, MSB word
  // first) into BLOCK0..BLOCK23.
  //----------------------------------------------------------------
  task load_block(input [767:0] blk);
    integer i;
    begin
      for (i = 0; i < NUM_BLOCK_WORDS; i = i + 1)
        write_word(ADDR_BLOCK0 + i[7:0], blk[(NUM_BLOCK_WORDS - 1 - i)*32 +: 32]);
    end
  endtask


  //----------------------------------------------------------------
  // run_absorb_block : absorb one block (no digest read; used for the
  // full blocks in a multi-block message).
  //----------------------------------------------------------------
  task run_absorb_block(input [767:0] blk);
    begin
      load_block(blk);
      write_word(ADDR_CTRL, CTRL_ABSORB);
      wait_busy;
      wait_ready;
    end
  endtask


  //----------------------------------------------------------------
  // run_absorb_final : absorb the final (padded) block and capture
  // the digest.
  //----------------------------------------------------------------
  task run_absorb_final(input [767:0] blk);
    integer i;
    reg [31:0] w;
    begin
      load_block(blk);
      write_word(ADDR_CTRL, CTRL_ABSORB);
      wait_busy;
      wait_valid;
      digest_result = 1024'h0;
      for (i = 0; i < NUM_DIGEST_WORDS; i = i + 1)
        begin
          read_word(ADDR_DIGEST0 + i[7:0], w);
          digest_result[(NUM_DIGEST_WORDS - 1 - i)*32 +: 32] = w;
        end
      wait_ready;
    end
  endtask


  //----------------------------------------------------------------
  // hash_long : absorb NUM_FULL_BLOCKS repeats of fill_block, then the
  // final padded block.
  //----------------------------------------------------------------
  task hash_long(input [767:0] fill_block, input [767:0] final_padded_block);
    integer blk;
    begin
      pulse_init;
      for (blk = 0; blk < NUM_FULL_BLOCKS; blk = blk + 1)
        run_absorb_block(fill_block);
      run_absorb_final(final_padded_block);
    end
  endtask


  //----------------------------------------------------------------
  // check.
  //----------------------------------------------------------------
  task check(input [8*32-1:0] name, input [1023:0] expected);
    begin
      tests = tests + 1;
      if (digest_result === expected)
        $display("  [PASS] %0s", name);
      else
        begin
          errors = errors + 1;
          $display("  [FAIL] %0s", name);
          $display("         got = %h", digest_result);
          $display("         exp = %h", expected);
        end
    end
  endtask


  //----------------------------------------------------------------
  // Test sequence.
  //----------------------------------------------------------------
  initial
    begin : main
      $display("==================================================");
      $display(" Duet-1024 testbench (all-zero / all-one, %0d blocks)", NUM_FULL_BLOCKS+1);
      $display(" msg_len = 8388608 bit (%0d full blocks + 1 padded block)", NUM_FULL_BLOCKS);
      $display("==================================================");

      tb_clk        = 1'b0;
      tb_reset_n    = 1'b0;
      tb_cs         = 1'b0;
      tb_we         = 1'b0;
      tb_address    = 8'h0;
      tb_write_data = 32'h0;
      errors        = 0;
      tests         = 0;

      // reset
      repeat (4) @(negedge tb_clk);
      tb_reset_n = 1'b1;
      repeat (2) @(negedge tb_clk);
      wait_ready;

      //--------------------------------------------------------
      // #1 : msg_len = 8388608, msg = all-zero.
      // Final 512-bit remainder (all-zero) padded -> 0^512 || 1 || 0^255
      //--------------------------------------------------------
      $display(" running #1 (all-zero, %0d full blocks + 1 padded)...", NUM_FULL_BLOCKS);
      hash_long(768'h0,
                768'h000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000);
      check("all-zero (8388608 bit)",
            1024'h284038D2638105310EA1F61141C6FF0D4BD8EDEA862B3ECFAB3189B8C361587B8C8BCAF1C8E6C8163DE2436487FDEEE0E25C041CEB6045D952311581DBE3C5CBB2F5611F7D1845BE723771039A76127214D15768D00FF2BC4DC46496AF090F0BBB8D4E11CE744970DE47DA086FF1A898F488353105FAD4A1667D4753BD9B435B);

      //--------------------------------------------------------
      // #2 : msg_len = 8388608, msg = all-one.
      // Final 512-bit remainder (all-one) padded -> 1^512 || 1 || 0^255
      //--------------------------------------------------------
      $display(" running #2 (all-one, %0d full blocks + 1 padded)...", NUM_FULL_BLOCKS);
      hash_long({768{1'b1}},
                768'hFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8000000000000000000000000000000000000000000000000000000000000000);
      check("all-one (8388608 bit)",
            1024'h687177A7BBC9EFCF873E282BB7BEE6CF76EB99DC64011AAC1CFA346D23AA621D15CCD8C193E90C8D13723D490CCB2CA4FF7B1BCE2E744C5FB96F763945B328DC9B836BCA7F956322C9DFA493B9F8EC183DE9474B487EF2D9E97381503DF73BD37BFE2E8A685093F4632473C2647C5CF40AFB8B3202B7F4A0C8D2AECCCA84461E);

      //--------------------------------------------------------
      // Summary.
      //--------------------------------------------------------
      $display("--------------------------------------------------");
      $display(" Tests run : %0d", tests);
      $display(" Failures  : %0d", errors);
      if (errors == 0)
        $display(" RESULT    : ALL TESTS PASSED");
      else
        $display(" RESULT    : %0d TEST(S) FAILED", errors);
      $display("==================================================");
      $finish;
    end

endmodule // tb_duet_1024_2_23

//======================================================================
// EOF tb_duet_1024_2_23.v
//======================================================================
