/*
 * approx_exp.h -- SHUTTLE accept-branch exp(), integer-only constant-time.
 *
 * This is the in-tree wrapper around the byte-frozen, audited kernel body
 * in tools/approx_exp_poly.h (generated by tools/gen_approx_exp_poly.py;
 * verified by tools/verify_approx_exp_poly.c against a quadmath expq
 * reference).  The wrapper #include's that header and re-exports the entry
 * points under the project namespace so callers in the wide sampler
 * (SampleDGauss / SampleY) never include the raw tools header.  Shared
 * VERBATIM across all
 * three parameter sets (SHUTTLE-128/256/512) -- there is no per-set table
 * or per-set #if; the kernel depends only on r=825,k=256, which are
 * identical for all sets.
 *
 * ============================ WHAT IT COMPUTES
 * ============================
 *
 * The Gaussian accept test inside SampleDGauss draws a BaseSampler output
 * x in {0..36} (truncation L=36) and one uniform byte y in {0..255}
 * (k=256), then accepts with probability
 *
 *     exp(p),   p = -N/(2 r^2),   N = y(y + 2 k x) = y(y + 512 x),
 *
 * with r = 825 the wide std-dev and 2 r^2 = 1,361,250.  Over the whole
 * domain 37x256 = 9472 points N <= 4,765,185 < 2^23 and p in [-3.500595..,
 * 0] (minimum at (x,y)=(36,255)).  shuttle_exp_accept_poly_q64(x,y)
 * returns this acceptance probability as a Q64 UNSIGNED fixed-point value
 *
 *     p_hat = round(2^64 * exp(p))  in {0 .. 2^64-1},
 *
 * i.e. a 64-bit Bernoulli threshold: the caller squeezes 8 uniform bytes
 * u in {0..2^64-1} and RESTARTS the SampleDGauss loop iff u >= p_hat.
 *
 * =========================== FIXED-POINT Q-FORMAT
 * =========================
 *
 * Identity used (see ApproxExp.tex): with s = N/2^23 in [0,1) and the
 * scaled decay rate a = 2^23 / (128 * 2 r^2) = 0.04814398530762167..., we
 * have exp(p) = (exp(-a s))^128.  The kernel approximates the SMALL
 * exponential exp(-a s) by a degree-8 Taylor polynomial in s, evaluated by
 * Horner in a Q64 fixed-point accumulator, then SQUARES the result 7 times
 * to realise the 128th power (2^7 = 128, the SPLIT).  Total core
 * multiplies = 8 + 7 = 15.
 *   - s is held as Q63: s_q63 = (int64)(N << 40), exact since 2^23 is a
 * power of two (40 = 63 - 23); NO division.
 *   - coefficients C_i = round(2^64 (-a)^i / i!) are signed Q64 stored in
 *     kShuttleExpPolyCoeff[0..7] = C_1..C_8 (max 60 signed bits, fit
 * int64); C_0 is the literal UINT64_MAX (= 2^64-1, NOT round(2^64) which
 * would overflow) injected as the Horner loop's final addend -- this index
 *     off-by-one is intentional and KAT-critical.
 *   - the two wide-multiply primitives consume only the HIGH 64 bits:
 *     Q64xQ63->Q64 = 2*shuttle_high64_s128(acc, s_q63) (signed arithmetic
 *     >>64), Q64xQ64->Q64 = shuttle_high64_u64 (unsigned >>64).
 *
 * ============================ CONSTANT-TIME =============================
 *
 * Fully unrolled Horner + 7 squarings: NO table (so no data-dependent
 * address at all), NO branch, NO division, NO float.  Portability caveat:
 * shuttle_high64_s128 relies on GNU __int128 ARITHMETIC right shift
 * of a signed intermediate -- correct on GCC/Clang two's-complement;
 * re-audit on a compiler lacking that semantic.
 *
 * ====================== PRECISION vs SECURITY GATE ======================
 *
 * Measured worst-case RELATIVE error (verify_approx_exp_poly.c, quadmath
 * expq, all 9472 points) = 2^-54.4857, worst at (x,y)=(36,248).  The
 * accept-branch gate (Error-analysis) requires eta <= eta_max per set
 * (tools/log/Security.txt): SHUTTLE-128: eta_max = 2^-51.25   margin ~3.24
 * bits   OK SHUTTLE-256: eta_max = 2^-51.98   margin ~2.51 bits   OK
 *     SHUTTLE-512: eta_max = 2^-52.97   margin ~1.52 bits   RISK
 * (thinnest) The SHUTTLE-512 margin (~1.52 bits) is the watch item: if
 * sigma/r/k/N change for 512, re-run the verifier (the same-cost fallback
 * t6d9 reaches 2^-55.25; the rejected t8d7 reaches only 2^-53.52 and would
 * FAIL the 512 gate).  test/test_approx.c re-asserts these margins.
 *
 * ============================ BATCH WIRING (lane-equivalence)
 * ==========================
 *
 * shuttle_exp_accept_poly_q64_x4 evaluates 4 INDEPENDENT (x,y) tuples
 * sharing one coefficient-table load per Horner step (4 interleaved
 * Horner+squaring chains, only 4 accumulators live -- low register
 * pressure, no scan).  It is verified BIT-IDENTICAL to four scalar calls.
 * Wire it in the wide sampler on the AVX2/AVX512 multi-coefficient SampleY
 * accept path where 4 candidate (x,y) are available; fall back to the
 * scalar shuttle_exp_accept_poly_q64 where independents are not (e.g. the
 * z=0 fold-restart path).  Batching only reorders the arithmetic, NEVER
 * the PRNG draw order -- byte consumption is the caller's concern and is
 * unchanged.  The reference *_x4 form IS the bit-exact spec that any
 * hand-written AVX2/AVX512 path must reproduce.
 */
#ifndef SHUTTLE_APPROX_EXP_H
#define SHUTTLE_APPROX_EXP_H

#include <stdint.h>

/*
 * The frozen kernel uses GNU __int128 for the wide-multiply accumulators.
 * __int128 is a GCC/Clang extension that ISO C does not support, so a
 * strict -Wpedantic build flags it.  This is the DOCUMENTED -Wpedantic
 * exception: localise the suppression to JUST the tools-header include
 * (the byte-frozen autogen body must not be edited).  The high-half
 * __int128 right-shift relies on two's-complement arithmetic shift (the
 * portability caveat).
 */
#if defined(__GNUC__) || defined(__clang__)
#    pragma GCC diagnostic push
#    pragma GCC diagnostic ignored "-Wpedantic"
#endif
#include "approx_exp_poly.h" /* @@AUTOGEN-CONSUMER: kShuttleExpPolyCoeff, macros, \
                                      shuttle_exp_accept_poly_q64{,_x4},                  \
                                      shuttle_high64_{s128,u64} */
#if defined(__GNUC__) || defined(__clang__)
#    pragma GCC diagnostic pop
#endif

/*
 * Re-export under the project namespace.  namespace.h renames the
 * shuttle_* identifiers to shuttle<set>_<backend>_* at compile time,
 * so these thin aliases give callers a stable, tools-header-free
 * name.  The aliases are macros (not wrapper functions) so the
 * static-inline kernel still inlines straight into the SIMD-lane caller.
 */
#define approx_exp_accept_q64 \
    shuttle_exp_accept_poly_q64 /* (int x, int y) -> uint64 Q64 */
#define approx_exp_accept_q64_x4                                       \
    shuttle_exp_accept_poly_q64_x4 /* (const int x[4], const int y[4], \
                                      uint64 out[4]) */

/*
 * Compile-time guards pinning the integration contract (the
 * SHUTTLE_EXP_POLY_* structural constants are OWNED by the autogen header
 * and are BINDING).  If the header is ever regenerated with a different
 * scheme these assertions break the build before any caller silently
 * mis-wires.
 */
_Static_assert(SHUTTLE_EXP_POLY_X_MAX == 36,
               "ApproxExp X_MAX must equal BaseSampler truncation L=36");
_Static_assert(
    SHUTTLE_EXP_POLY_Y_MAX == 255,
    "ApproxExp Y_MAX must equal k-1 = 255 (k=256, one uniform byte)");
_Static_assert(SHUTTLE_EXP_POLY_DEGREE == 8,
               "ApproxExp Taylor degree must be 8");
_Static_assert(SHUTTLE_EXP_POLY_SQUARINGS == 7,
               "ApproxExp must square 7 times (2^7 = 128)");
_Static_assert(SHUTTLE_EXP_POLY_SPLIT == 128,
               "ApproxExp split must be 128 = 2^SQUARINGS");

#endif /* SHUTTLE_APPROX_EXP_H */
