#ifndef HARE_RS_GENERATOR_CONSTANTS_GENERATED_H
#define HARE_RS_GENERATOR_CONSTANTS_GENERATED_H

/*
 * Generated by tools/generators/generate_rs_generator_constants.py.
 *
 * For each implemented shortened RS[n1,k] code over GF(2^8), this header
 * contains g(x)=prod_{i=1}^{n1-k}(x+alpha^i), using primitive polynomial
 * x^8+x^4+x^3+x^2+1 (0x11D). All selectors are public compile-time parameters.
 */

#if (PARAM_K == 16 && PARAM_N1 == 32)
/* HARE-128 KR / HARE-2; PARAM_G=17. */
static const uint16_t rs_generator_poly_const[PARAM_G] = {
    79, 44, 81, 100, 49, 183, 56, 17, 232, 187, 126, 104, 31, 103, 52, 118,
    1,
};
#elif (PARAM_K == 32 && PARAM_N1 == 81)
/* HARE-256 KR / HARE-5; PARAM_G=50. */
static const uint16_t rs_generator_poly_const[PARAM_G] = {
    167, 202, 61, 210, 5, 146, 109, 134, 184, 133, 170, 61, 131, 156, 1, 86,
    227, 223, 208, 96, 143, 63, 217, 247, 85, 51, 213, 72, 207, 80, 116, 148,
    36, 64, 142, 44, 36, 184, 161, 65, 199, 101, 250, 61, 7, 193, 16, 197,
    246, 1,
};
#elif (PARAM_K == 48 && PARAM_N1 == 91)
/* HARE-384 KR / HARE-7; PARAM_G=44. */
static const uint16_t rs_generator_poly_const[PARAM_G] = {
    49, 251, 191, 160, 142, 196, 33, 252, 213, 78, 124, 104, 11, 146, 172, 107,
    13, 31, 193, 149, 237, 3, 8, 10, 137, 154, 215, 237, 40, 77, 78, 15,
    114, 147, 54, 202, 106, 69, 138, 54, 64, 47, 175, 1,
};
#elif (PARAM_K == 64 && PARAM_N1 == 151)
/* HARE-512 KR / HARE-9; PARAM_G=88. */
static const uint16_t rs_generator_poly_const[PARAM_G] = {
    8, 105, 198, 6, 158, 61, 19, 203, 151, 134, 121, 199, 24, 40, 31, 125,
    69, 65, 28, 229, 30, 239, 14, 17, 104, 67, 196, 221, 187, 150, 99, 168,
    149, 219, 100, 4, 118, 23, 73, 50, 185, 121, 24, 82, 13, 170, 131, 128,
    40, 171, 194, 72, 90, 151, 45, 130, 95, 108, 75, 54, 12, 246, 1, 227,
    231, 91, 180, 70, 40, 216, 57, 217, 96, 194, 241, 111, 161, 47, 197, 185,
    107, 48, 114, 245, 157, 211, 84, 1,
};
#else
#error "Unsupported HARE optimized RS parameter set"
#endif

#endif /* HARE_RS_GENERATOR_CONSTANTS_GENERATED_H */
