#ifndef PARAMS_H
#define PARAMS_H

/* Fixed parameter set for BW_KEM_C256 submission bundle. */
#define KYBER_K 4


/* Don't change parameters below this line */
#define KYBER_NAMESPACE(s) pqcrystals_kyber1024_avx2_##s

#define KYBER_N 256
#define KYBER_Q 3329

#define KYBER_SYMBYTES 32   /* size in bytes of hashes, and seeds */
#define KYBER_SSBYTES  32   /* size in bytes of shared key */

#define KYBER_POLYBYTES		384
#define KYBER_POLYVECBYTES	(KYBER_K * KYBER_POLYBYTES)

#define KYBER_EQ 12
#define KYBER_POLYVECCOMPRESSEDBYTES (KYBER_K * 320)    /* C256: u k*256*10/8 */

#define KYBER_ETA1 3
#define KYBER_POLYCOMPRESSEDBYTES    160                /* C256: v 256*5/8 */

#define KYBER_ETA2 3

#define KYBER_INDCPA_MSGBYTES       (KYBER_SYMBYTES)
#define KYBER_INDCPA_PUBLICKEYBYTES (KYBER_POLYVECBYTES + KYBER_SYMBYTES)
#define KYBER_INDCPA_SECRETKEYBYTES (KYBER_POLYVECBYTES)
#define KYBER_INDCPA_BYTES          (KYBER_POLYVECCOMPRESSEDBYTES + KYBER_POLYCOMPRESSEDBYTES)

#define KYBER_PUBLICKEYBYTES  (KYBER_INDCPA_PUBLICKEYBYTES)

/* 33 bytes of additional space to save ID(pk) */
#define PREFIXHASHBYTES 33

#define KYBER_SECRETKEYBYTES  (KYBER_INDCPA_SECRETKEYBYTES + KYBER_INDCPA_PUBLICKEYBYTES + PREFIXHASHBYTES + KYBER_SYMBYTES)
#define KYBER_CIPHERTEXTBYTES (KYBER_INDCPA_BYTES)

#endif
