//======================================================================
//
// tb_cuishen_2_23.v
// ------------------
// Self-checking testbench for the Cuishen-512 hash, covering the first
// two vectors of KAT_2_23 (msg_len = 8388608 bit = 8192 full 1024-bit
// blocks). Unlike tb_cuishen.v (KAT_2_12, short messages only, which
// never exercises the compression / lsb_separate path), these vectors
// drive 8192 real "next" compression blocks before finalization, so
// they actually cover the block-to-block chaining and lsb_separate
// logic that the short vectors cannot reach.
//
//   KAT_2_23 #1 : msg_len = 8388608, msg = all-zero
//   KAT_2_23 #2 : msg_len = 8388608, msg = all-one
//   KAT_2_23 #3 : msg_len = 8388608, msg = DRNG(seed) -- NOT INCLUDED.
//       This vector's plaintext is generated by the DRNG from
//       Msg_Seed; the DRNG source was not available when this
//       testbench was written, so the 8192 message blocks cannot be
//       reconstructed here. Only #1 and #2, whose plaintext is fully
//       determined by the spec (all-0 / all-1), are included.
//
// Each vector takes ~549000 clock cycles in simulation (8192 blocks x
// ~67 cycles/block on the parallel "latency" core, plus the
// finalization). This runs in seconds under a standard event simulator
// (iverilog/vvp); it is not a synthesis-time concern.
//
//======================================================================

`default_nettype none
`timescale 1ns/1ps

module tb_cuishen_2_23;

  //----------------------------------------------------------------
  // Parameters.
  //----------------------------------------------------------------
  localparam CLK_HALF = 5;

  localparam ADDR_CTRL     = 8'h08;
  localparam ADDR_STATUS   = 8'h09;
  localparam ADDR_COUNTER0 = 8'h0a;
  localparam ADDR_COUNTER1 = 8'h0b;
  localparam ADDR_BLOCK0   = 8'h10;
  localparam ADDR_TAIL0    = 8'h30;
  localparam ADDR_DIGEST0  = 8'h60;

  localparam CTRL_INIT  = 32'h1;
  localparam CTRL_NEXT  = 32'h2;
  localparam CTRL_FINAL = 32'h4;

  localparam NUM_BLOCKS    = 8192;          // 8388608 bit / 1024 bit
  localparam MSG_LEN_BITS  = 64'd8388608;


  //----------------------------------------------------------------
  // DUT connections.
  //----------------------------------------------------------------
  reg          tb_clk;
  reg          tb_reset_n;
  reg          tb_cs;
  reg          tb_we;
  reg  [7 : 0] tb_address;
  reg  [31: 0] tb_write_data;
  wire [31: 0] tb_read_data;
  wire         tb_error;

  integer      errors;
  integer      tests;
  reg [511:0]  digest_result;


  //----------------------------------------------------------------
  // DUT.
  //----------------------------------------------------------------
  cuishen dut(
              .clk(tb_clk),
              .reset_n(tb_reset_n),
              .cs(tb_cs),
              .we(tb_we),
              .address(tb_address),
              .write_data(tb_write_data),
              .read_data(tb_read_data),
              .error(tb_error)
             );


  //----------------------------------------------------------------
  // Clock.
  //----------------------------------------------------------------
  always
    begin : clk_gen
      #CLK_HALF tb_clk = !tb_clk;
    end


  //----------------------------------------------------------------
  // write_word / read_word : single-cycle bus transactions.
  //----------------------------------------------------------------
  task write_word(input [7:0] addr, input [31:0] data);
    begin
      @(negedge tb_clk);
      tb_cs         = 1'b1;
      tb_we         = 1'b1;
      tb_address    = addr;
      tb_write_data = data;
      @(negedge tb_clk);
      tb_cs         = 1'b0;
      tb_we         = 1'b0;
    end
  endtask

  task read_word(input [7:0] addr, output [31:0] data);
    begin
      @(negedge tb_clk);
      tb_cs      = 1'b1;
      tb_we      = 1'b0;
      tb_address = addr;
      @(negedge tb_clk);
      data       = tb_read_data;
      tb_cs      = 1'b0;
    end
  endtask


  //----------------------------------------------------------------
  // wait_ready / wait_busy / wait_valid : poll the status register.
  // wait_busy is used right after issuing next/final so we don't read
  // a stale "ready=1" from before the command was registered.
  //----------------------------------------------------------------
  task wait_ready;
    reg [31:0] s;
    begin
      s = 32'h0;
      while (s[0] == 1'b0)
        read_word(ADDR_STATUS, s);
    end
  endtask

  task wait_busy;
    reg [31:0] s;
    begin
      s = 32'hffffffff;
      while (s[0] == 1'b1)
        read_word(ADDR_STATUS, s);
    end
  endtask

  task wait_valid;
    reg [31:0] s;
    begin
      s = 32'h0;
      while (s[1] == 1'b0)
        read_word(ADDR_STATUS, s);
    end
  endtask


  //----------------------------------------------------------------
  // set_counter : write the 64-bit bits-processed counter.
  //----------------------------------------------------------------
  task set_counter(input [63:0] c);
    begin
      write_word(ADDR_COUNTER0, c[31 : 0]);
      write_word(ADDR_COUNTER1, c[63 : 32]);
    end
  endtask


  //----------------------------------------------------------------
  // pulse_init : preload IV (single cycle, core stays ready).
  //----------------------------------------------------------------
  task pulse_init;
    begin
      write_word(ADDR_CTRL, CTRL_INIT);
      @(negedge tb_clk);
      wait_ready;
    end
  endtask


  //----------------------------------------------------------------
  // load_block : write a 1024-bit block (32 x 32-bit words, MSB word
  // first) into BLOCK0..BLOCK31.
  //----------------------------------------------------------------
  task load_block(input [1023:0] blk);
    integer i;
    begin
      for (i = 0; i < 32; i = i + 1)
        write_word(ADDR_BLOCK0 + i[7:0], blk[(31 - i)*32 +: 32]);
    end
  endtask


  //----------------------------------------------------------------
  // load_tail : write a 768-bit tail (24 x 32-bit words) into
  // TAIL0..TAIL23, MSB word first.
  //----------------------------------------------------------------
  task load_tail(input [767:0] tail);
    integer i;
    begin
      for (i = 0; i < 24; i = i + 1)
        write_word(ADDR_TAIL0 + i[7:0], tail[(23 - i)*32 +: 32]);
    end
  endtask


  //----------------------------------------------------------------
  // run_block : feed one compression block (the real "next" path that
  // tb_cuishen.v's short vectors never reach).
  //----------------------------------------------------------------
  task run_block(input [1023:0] blk, input [63:0] counter_bits);
    begin
      set_counter(counter_bits);
      load_block(blk);
      write_word(ADDR_CTRL, CTRL_NEXT);
      wait_busy;
      wait_ready;
    end
  endtask


  //----------------------------------------------------------------
  // run_final : run the finalization and capture the digest.
  //----------------------------------------------------------------
  task run_final(input [767:0] tail, input [63:0] counter_bits);
    integer i;
    reg [31:0] w;
    begin
      set_counter(counter_bits);
      load_tail(tail);
      write_word(ADDR_CTRL, CTRL_FINAL);
      @(negedge tb_clk);
      wait_valid;
      digest_result = 512'h0;
      for (i = 0; i < 16; i = i + 1)
        begin
          read_word(ADDR_DIGEST0 + i[7:0], w);
          digest_result[(15 - i)*32 +: 32] = w;
        end
      wait_ready;
    end
  endtask


  //----------------------------------------------------------------
  // hash_long : hash an 8388608-bit message made of NUM_BLOCKS repeats
  // of the same 1024-bit fill pattern (used for the all-0 / all-1
  // vectors). The remainder is exactly 0, so the tail is empty.
  //----------------------------------------------------------------
  task hash_long(input [1023:0] fill_block);
    integer blk;
    begin
      pulse_init;
      for (blk = 0; blk < NUM_BLOCKS; blk = blk + 1)
        run_block(fill_block, (blk + 1) * 1024);
      run_final(768'h0, MSG_LEN_BITS);
    end
  endtask


  //----------------------------------------------------------------
  // check : compare digest against expected, report.
  //----------------------------------------------------------------
  task check(input [8*32-1:0] name, input [511:0] expected);
    begin
      tests = tests + 1;
      if (digest_result === expected)
        $display("  [PASS] %0s", name);
      else
        begin
          errors = errors + 1;
          $display("  [FAIL] %0s", name);
          $display("         got = %h", digest_result);
          $display("         exp = %h", expected);
        end
    end
  endtask


  //----------------------------------------------------------------
  // Test sequence.
  //----------------------------------------------------------------
  initial
    begin : main
      $display("==================================================");
      $display(" Cuishen-512 testbench (KAT_2_23, first two vectors)");
      $display(" msg_len = 8388608 bit (8192 full compression blocks)");
      $display("==================================================");

      tb_clk        = 1'b0;
      tb_reset_n    = 1'b0;
      tb_cs         = 1'b0;
      tb_we         = 1'b0;
      tb_address    = 8'h0;
      tb_write_data = 32'h0;
      errors        = 0;
      tests         = 0;

      // reset
      repeat (4) @(negedge tb_clk);
      tb_reset_n = 1'b1;
      repeat (2) @(negedge tb_clk);
      wait_ready;

      //--------------------------------------------------------
      // KAT_2_23 #1 : msg_len = 8388608, msg = all-zero
      //--------------------------------------------------------
      $display(" running #1 (all-zero, %0d blocks)...", NUM_BLOCKS);
      hash_long(1024'h0);
      check("KAT_2_23 #1 (all-zero)",
            512'hDFFD60B08E67DE7EE2103397DFB04AC06299285ECC4A37AEBDCC00C8ED0A8CACF442B5FEB83471AE28318E592607873E72E970F9322980B7EE75DFBA2A8ECD77);

      //--------------------------------------------------------
      // KAT_2_23 #2 : msg_len = 8388608, msg = all-one
      //--------------------------------------------------------
      $display(" running #2 (all-one, %0d blocks)...", NUM_BLOCKS);
      hash_long({1024{1'b1}});
      check("KAT_2_23 #2 (all-one)",
            512'h17A552E5166B7973E2527A578A87B723D21A28BB8E6551E8719EE99A16143EBA7ADF309B3B75E9C9D8A7FCE2A936CA80F64E29708C8360ED5D7B2A5065C9AF7B

);


      //--------------------------------------------------------
      // Summary.
      //--------------------------------------------------------
      $display("--------------------------------------------------");
      $display(" Tests run : %0d", tests);
      $display(" Failures  : %0d", errors);
      if (errors == 0)
        $display(" RESULT    : ALL TESTS PASSED");
      else
        $display(" RESULT    : %0d TEST(S) FAILED", errors);
      $display("==================================================");
      $finish;
    end

endmodule // tb_cuishen_2_23

//======================================================================
// EOF tb_cuishen_2_23.v
//======================================================================
