#include <quaternion.h>
#include <stdlib.h>
#include "internal.h"
#include "internal_quaternion_headers/lll_internals.h"

// assumes parent order and lattice correctly set, computes and sets the norm
void
quat_lideal_norm(quat_left_ideal_t *lideal)
{
    quat_lattice_index(&(lideal->norm), &(lideal->lattice), (lideal->parent_order));
    int ok UNUSED = ibz_sqrt(&(lideal->norm), &(lideal->norm));
    assert(ok);
}

// assumes parent order and lattice correctly set, recomputes and verifies its norm
static int
quat_lideal_norm_verify(const quat_left_ideal_t *lideal)
{
    int res;
    ibz_t index;
    ibz_init(&index);
    quat_lattice_index(&index, &(lideal->lattice), (lideal->parent_order));
    ibz_sqrt(&index, &index);
    res = (ibz_cmp(&(lideal->norm), &index) == 0);
    ibz_finalize(&index);
    return (res);
}

void
quat_lideal_copy(quat_left_ideal_t *copy, const quat_left_ideal_t *copied)
{
    copy->parent_order = copied->parent_order;
    ibz_copy(&copy->norm, &copied->norm);
    ibz_copy(&copy->lattice.denom, &copied->lattice.denom);
    for (int i = 0; i < 4; i++) {
        for (int j = 0; j < 4; j++) {
            ibz_copy(&copy->lattice.basis[i][j], &copied->lattice.basis[i][j]);
        }
    }
}

void
quat_lideal_create_principal(quat_left_ideal_t *lideal,
                             const quat_alg_elem_t *x,
                             const quat_lattice_t *order,
                             const quat_alg_t *alg)
{
    assert(quat_order_is_maximal(order, alg));
    assert(quat_lattice_contains(NULL, order, x));
    ibz_t norm_n, norm_d;
    ibz_init(&norm_n);
    ibz_init(&norm_d);

    // Multiply order on the right by x
    quat_lattice_alg_elem_mul(&(lideal->lattice), order, x, alg);

    // Reduce denominator. This conserves HNF
    quat_lattice_reduce_denom(&lideal->lattice, &lideal->lattice);

    // Compute norm and check it's integral
    quat_alg_norm(&norm_n, &norm_d, x, alg);
    assert(ibz_is_one(&norm_d));
    ibz_copy(&lideal->norm, &norm_n);

    // Set order
    lideal->parent_order = order;
    ibz_finalize(&norm_n);
    ibz_finalize(&norm_d);
}

void
quat_lideal_create(quat_left_ideal_t *lideal,
                   const quat_alg_elem_t *x,
                   const ibz_t *N,
                   const quat_lattice_t *order,
                   const quat_alg_t *alg)
{
    assert(quat_order_is_maximal(order, alg));
    assert(!quat_alg_elem_is_zero(x));

    quat_lattice_t ON;
    quat_lattice_init(&ON);

    // Compute ideal generated by x
    quat_lideal_create_principal(lideal, x, order, alg);

    // Compute ideal generated by N (without reducing denominator)
    ibz_mat_4x4_scalar_mul(&ON.basis, N, &order->basis);
    ibz_copy(&ON.denom, &order->denom);

    // Add lattices (reduces denominators)
    quat_lattice_add(&lideal->lattice, &lideal->lattice, &ON);
    // Set order
    lideal->parent_order = order;
    // Compute norm
    quat_lideal_norm(lideal);

    quat_lattice_finalize(&ON);
}

int
quat_lideal_generator(quat_alg_elem_t *gen, const quat_left_ideal_t *lideal, const quat_alg_t *alg)
{
    ibz_t norm_int, norm_n, gcd, r, q, norm_denom;
    ibz_vec_4_t vec;
    ibz_vec_4_init(&vec);
    ibz_init(&norm_denom);
    ibz_init(&norm_int);
    ibz_init(&norm_n);
    ibz_init(&r);
    ibz_init(&q);
    ibz_init(&gcd);
    int a, b, c, d;
    int found = 0;
    int int_norm = 0;
    while (1) {
        int_norm++;
        for (a = -int_norm; a <= int_norm; a++) {
            for (b = -int_norm + abs(a); b <= int_norm - abs(a); b++) {
                for (c = -int_norm + abs(a) + abs(b); c <= int_norm - abs(a) - abs(b); c++) {
                    d = int_norm - abs(a) - abs(b) - abs(c);
                    ibz_vec_4_set(&vec, a, b, c, d);
                    ibz_vec_4_content(&gcd, &vec);
                    if (ibz_is_one(&gcd)) {
                        ibz_mat_4x4_eval(&(gen->coord), &(lideal->lattice.basis), &vec);
                        ibz_copy(&(gen->denom), &(lideal->lattice.denom));
                        quat_alg_norm(&norm_int, &norm_denom, gen, alg);
                        assert(ibz_is_one(&norm_denom));
                        ibz_div(&q, &r, &norm_int, &(lideal->norm));
                        assert(ibz_is_zero(&r));
                        ibz_gcd(&gcd, &(lideal->norm), &q);
                        found = (0 == ibz_cmp(&gcd, &ibz_const_one));
                        if (found)
                            goto fin;
                    }
                }
            }
        }
    }
fin:;
    ibz_finalize(&r);
    ibz_finalize(&q);
    ibz_finalize(&norm_denom);
    ibz_finalize(&norm_int);
    ibz_finalize(&norm_n);
    ibz_vec_4_finalize(&vec);
    ibz_finalize(&gcd);
    return (found);
}

void
quat_lideal_mul(quat_left_ideal_t *product,
                const quat_left_ideal_t *lideal,
                const quat_alg_elem_t *alpha,
                const quat_alg_t *alg)
{
    assert(quat_order_is_maximal((lideal->parent_order), alg));
    ibz_t norm, norm_d;
    ibz_init(&norm);
    ibz_init(&norm_d);
    quat_lattice_alg_elem_mul(&(product->lattice), &(lideal->lattice), alpha, alg);
    product->parent_order = lideal->parent_order;
    quat_alg_norm(&norm, &norm_d, alpha, alg);
    ibz_mul(&(product->norm), &(lideal->norm), &norm);
    assert(ibz_divides(&(product->norm), &norm_d));
    ibz_div(&(product->norm), &norm, &(product->norm), &norm_d);
    assert(quat_lideal_norm_verify(lideal));
    ibz_finalize(&norm_d);
    ibz_finalize(&norm);
}

void
quat_lideal_add(quat_left_ideal_t *sum, const quat_left_ideal_t *I1, const quat_left_ideal_t *I2, const quat_alg_t *alg)
{
    assert(I1->parent_order == I2->parent_order);
    assert(quat_order_is_maximal((I2->parent_order), alg));
    quat_lattice_add(&sum->lattice, &I1->lattice, &I2->lattice);
    sum->parent_order = I1->parent_order;
    quat_lideal_norm(sum);
}

void
quat_lideal_inter(quat_left_ideal_t *inter,
                  const quat_left_ideal_t *I1,
                  const quat_left_ideal_t *I2,
                  const quat_alg_t *alg)
{
    assert(I1->parent_order == I2->parent_order);
    assert(quat_order_is_maximal((I2->parent_order), alg));
    quat_lattice_intersect(&inter->lattice, &I1->lattice, &I2->lattice);
    inter->parent_order = I1->parent_order;
    quat_lideal_norm(inter);
}

int
quat_lideal_equals(const quat_left_ideal_t *I1, const quat_left_ideal_t *I2, const quat_alg_t *alg)
{
    assert(quat_order_is_maximal((I2->parent_order), alg));
    assert(quat_order_is_maximal((I1->parent_order), alg));
    return (I1->parent_order == I2->parent_order) & (ibz_cmp(&I1->norm, &I2->norm) == 0) &
           quat_lattice_equal(&I1->lattice, &I2->lattice);
}

void
quat_lideal_inverse_lattice_without_hnf(quat_lattice_t *inv, const quat_left_ideal_t *lideal, const quat_alg_t *alg)
{
    assert(quat_order_is_maximal((lideal->parent_order), alg));
    quat_lattice_conjugate_without_hnf(inv, &(lideal->lattice));
    ibz_mul(&(inv->denom), &(inv->denom), &(lideal->norm));
}

// following the implementation of ideal isomorphisms in the code of LearningToSQI's sage
// implementation of SQIsign
void
quat_lideal_right_transporter(quat_lattice_t *trans,
                              const quat_left_ideal_t *lideal1,
                              const quat_left_ideal_t *lideal2,
                              const quat_alg_t *alg)
{
    assert(quat_order_is_maximal((lideal1->parent_order), alg));
    assert(quat_order_is_maximal((lideal2->parent_order), alg));
    assert(lideal1->parent_order == lideal2->parent_order);
    quat_lattice_t inv;
    quat_lattice_init(&inv);
    quat_lideal_inverse_lattice_without_hnf(&inv, lideal1, alg);
    quat_lattice_mul(trans, &inv, &(lideal2->lattice), alg);
    quat_lattice_finalize(&inv);
}

void
quat_lideal_right_order(quat_lattice_t *order, const quat_left_ideal_t *lideal, const quat_alg_t *alg)
{
    assert(quat_order_is_maximal((lideal->parent_order), alg));
    quat_lideal_right_transporter(order, lideal, lideal, alg);
}

void
quat_lideal_class_gram(ibz_mat_4x4_t *G, const quat_left_ideal_t *lideal, const quat_alg_t *alg)
{
    quat_lattice_gram(G, &(lideal->lattice), alg);

    // divide by norm · denominator²
    ibz_t divisor, rmd;
    ibz_init(&divisor);
    ibz_init(&rmd);

    ibz_mul(&divisor, &(lideal->lattice.denom), &(lideal->lattice.denom));
    ibz_mul(&divisor, &divisor, &(lideal->norm));

    for (int i = 0; i < 4; i++) {
        for (int j = 0; j <= i; j++) {
            ibz_div(&(*G)[i][j], &rmd, &(*G)[i][j], &divisor);
            assert(ibz_is_zero(&rmd));
        }
    }
    for (int i = 0; i < 4; i++) {
        for (int j = 0; j <= i - 1; j++) {
            ibz_copy(&(*G)[j][i], &(*G)[i][j]);
        }
    }

    ibz_finalize(&rmd);
    ibz_finalize(&divisor);
}

void
quat_lideal_conjugate_without_hnf(quat_left_ideal_t *conj,
                                  quat_lattice_t *new_parent_order,
                                  const quat_left_ideal_t *lideal,
                                  const quat_alg_t *alg)
{
    quat_lideal_right_order(new_parent_order, lideal, alg);
    quat_lattice_conjugate_without_hnf(&(conj->lattice), &(lideal->lattice));
    conj->parent_order = new_parent_order;
    ibz_copy(&(conj->norm), &(lideal->norm));
}

int
quat_order_discriminant(ibz_t *disc, const quat_lattice_t *order, const quat_alg_t *alg)
{
    int ok = 0;
    ibz_t det, sqr, div;
    ibz_mat_4x4_t transposed, norm, prod;
    ibz_init(&det);
    ibz_init(&sqr);
    ibz_init(&div);
    ibz_mat_4x4_init(&transposed);
    ibz_mat_4x4_init(&norm);
    ibz_mat_4x4_init(&prod);
    ibz_mat_4x4_transpose(&transposed, &(order->basis));
    // multiply gram matrix by 2 because of reduced trace
    ibz_mat_4x4_identity(&norm);
    ibz_copy(&(norm[2][2]), &(alg->p));
    ibz_copy(&(norm[3][3]), &(alg->p));
    ibz_mat_4x4_scalar_mul(&norm, &ibz_const_two, &norm);
    ibz_mat_4x4_mul(&prod, &transposed, &norm);
    ibz_mat_4x4_mul(&prod, &prod, &(order->basis));
    ibz_mat_4x4_inv_with_det_as_denom(NULL, &det, &prod);
    ibz_mul(&div, &(order->denom), &(order->denom));
    ibz_mul(&div, &div, &div);
    ibz_mul(&div, &div, &div);
    ibz_div(&sqr, &div, &det, &div);
    ok = ibz_is_zero(&div);
    ok = ok & ibz_sqrt(disc, &sqr);
    ibz_finalize(&det);
    ibz_finalize(&div);
    ibz_finalize(&sqr);
    ibz_mat_4x4_finalize(&transposed);
    ibz_mat_4x4_finalize(&norm);
    ibz_mat_4x4_finalize(&prod);
    return (ok);
}

int
quat_order_is_maximal(const quat_lattice_t *order, const quat_alg_t *alg)
{
    int res;
    ibz_t disc;
    ibz_init(&disc);
    quat_order_discriminant(&disc, order, alg);
    res = (ibz_cmp(&disc, &(alg->p)) == 0);
    ibz_finalize(&disc);
    return (res);
}

/*
compute M_Gram = B^T*D*B / N(I) mod d1 = B_basis^T*D*B_basis / (demon^2*N(I)) mod d1
B = [b0, b1, b2, b3] is the basis of I
D = diag(1, 1, p, p)
*/
static int
quat_compute_gram_matrix_mod(ibz_mat_4x4_t *M_Gram, const quat_left_ideal_t *I, const ibz_t *d1, const quat_alg_t *alg)
{
    int success = 0;
    ibz_t rem;

    ibz_init(&rem);

    // compute gram matrix: M_Gram[i, j] = Tr(bi * bj_conj) / N(I) = 2*bi^T*D*bj / N(I)
    quat_lideal_class_gram(M_Gram, I, alg);

    // compute M_Gram / 2 mod d1
    for (int i = 0; i < 4; i++) {
        for (int j = 0; j <= i; j++) {
            ibz_t *elem = &((*M_Gram)[i][j]);
            // compute elem / 2 mod d1
            ibz_mod(elem, elem, d1);
            if (ibz_cmp(elem, &ibz_const_zero) < 0) {
                ibz_add(elem, elem, d1);
            }
            ibz_mod(&rem, elem, &ibz_const_two); 
            if (ibz_cmp(&rem, &ibz_const_zero) != 0) {
                ibz_add(elem, elem, d1);
            }
            ibz_div(elem, &rem, elem, &ibz_const_two);

            if (i != j) {
                ibz_copy(&((*M_Gram)[j][i]), elem);
            }
        }
    }
    success = 1;

    ibz_finalize(&rem);
    
    return success;
}

/*
compute Q(u) = d2 (mod d1), u \in F_{d1^4}, Q(u) = u*M_Gram*u^T = Nrd(u) / Nrd(I)
*/
static int 
quat_sample_norm_vector_mod(ibz_vec_4_t *u, const ibz_mat_4x4_t *M_Gram, const ibz_t *d1, const ibz_t *d2)
{
    int success = 0;
    ibz_t A, B, C, Delta, inv2A, fourA, exp, rem, temp1, temp2, four;
    
    ibz_t M01x2, M02x2, M03x2, M12x2, M13x2, M23x2;
    ibz_t T1, T2, T3;

    ibz_init(&A); ibz_init(&B); ibz_init(&C); ibz_init(&Delta);
    ibz_init(&inv2A); ibz_init(&fourA); ibz_init(&exp); 
    ibz_init(&rem); ibz_init(&temp1); ibz_init(&temp2); ibz_init(&four);
    
    ibz_init(&M01x2); ibz_init(&M02x2); ibz_init(&M03x2);
    ibz_init(&M12x2); ibz_init(&M13x2); ibz_init(&M23x2);
    ibz_init(&T1); ibz_init(&T2); ibz_init(&T3);

    ibz_set(&four, 4);

    // A = M_Gram[0][0]
    ibz_copy(&A, &((*M_Gram)[0][0]));
    // inv2A = (2A)^(-1) mod d1
    ibz_add(&temp1, &A, &A);
    if (!ibz_invmod(&inv2A, &temp1, d1)) {
        goto cleanup; 
    }
    // 4A mod d1
    ibz_add(&fourA, &temp1, &temp1); 
    ibz_mod(&fourA, &fourA, d1);
    // exp = (d1 + 1) / 4 
    ibz_add(&temp1, d1, &ibz_const_one);
    ibz_div(&exp, &rem, &temp1, &four);

    // precomputed constants
    ibz_add(&M01x2, &((*M_Gram)[0][1]), &((*M_Gram)[0][1])); ibz_mod(&M01x2, &M01x2, d1);
    ibz_add(&M02x2, &((*M_Gram)[0][2]), &((*M_Gram)[0][2])); ibz_mod(&M02x2, &M02x2, d1);
    ibz_add(&M03x2, &((*M_Gram)[0][3]), &((*M_Gram)[0][3])); ibz_mod(&M03x2, &M03x2, d1);
    ibz_add(&M12x2, &((*M_Gram)[1][2]), &((*M_Gram)[1][2])); ibz_mod(&M12x2, &M12x2, d1);
    ibz_add(&M13x2, &((*M_Gram)[1][3]), &((*M_Gram)[1][3])); ibz_mod(&M13x2, &M13x2, d1);
    ibz_add(&M23x2, &((*M_Gram)[2][3]), &((*M_Gram)[2][3])); ibz_mod(&M23x2, &M23x2, d1);

    // randomly sample in F_{d1} 
    while (1) {
        ibz_rand_interval(&((*u)[1]), &ibz_const_zero, d1);
        ibz_rand_interval(&((*u)[2]), &ibz_const_zero, d1);
        ibz_rand_interval(&((*u)[3]), &ibz_const_zero, d1);
        
        // B = u1*M01 + u2*M02 + u3*M03
        ibz_mul(&B, &((*u)[1]), &M01x2);
        ibz_mul(&temp1, &((*u)[2]), &M02x2);
        ibz_add(&B, &B, &temp1);
        ibz_mul(&temp1, &((*u)[3]), &M03x2);
        ibz_add(&B, &B, &temp1);
        ibz_mod(&B, &B, d1); 

        // T1 = u1*M11 + u2*(2*M12) + u3*(2*M13)  
        ibz_mul(&T1, &((*u)[1]), &((*M_Gram)[1][1]));
        ibz_mul(&temp1, &((*u)[2]), &M12x2);
        ibz_add(&T1, &T1, &temp1);
        ibz_mul(&temp1, &((*u)[3]), &M13x2);
        ibz_add(&T1, &T1, &temp1);
        // T2 = u2*M22 + u3*(2*M23)  
        ibz_mul(&T2, &((*u)[2]), &((*M_Gram)[2][2]));
        ibz_mul(&temp1, &((*u)[3]), &M23x2);
        ibz_add(&T2, &T2, &temp1);
        // T3 = u3*M33 
        ibz_mul(&T3, &((*u)[3]), &((*M_Gram)[3][3]));

        // C = u1*T1 + u2*T2 + u3*T3 - d2 mod d1 
        ibz_mul(&C, &((*u)[1]), &T1);
        ibz_mul(&temp1, &((*u)[2]), &T2);
        ibz_add(&C, &C, &temp1);
        ibz_mul(&temp1, &((*u)[3]), &T3);
        ibz_add(&C, &C, &temp1);
        ibz_sub(&C, &C, d2);
        ibz_mod(&C, &C, d1); 
        if (ibz_cmp(&C, &ibz_const_zero) < 0) ibz_add(&C, &C, d1);

        // compute Delta = B^2 - 4AC mod d1 
        ibz_mul(&temp1, &B, &B);             
        ibz_mul(&temp2, &fourA, &C);            
        ibz_sub(&Delta, &temp1, &temp2);   
        ibz_mod(&Delta, &Delta, d1); 
        if (ibz_cmp(&Delta, &ibz_const_zero) < 0) ibz_add(&Delta, &Delta, d1);

        // Kronecker check
        int kr = mpz_kronecker(Delta, *d1);
        if (kr < 0) {
            continue;
        }
        // temp1 = sqrt(Delta)
        ibz_pow_mod(&temp1, &Delta, &exp, d1); 
        
        // u0 = (sqrt(Delta) - B) * inv2A mod d1
        ibz_sub(&((*u)[0]), &temp1, &B);
        ibz_mul(&((*u)[0]), &((*u)[0]), &inv2A);
        ibz_mod(&((*u)[0]), &((*u)[0]), d1);
        
        if (ibz_cmp(&((*u)[0]), &ibz_const_zero) < 0) {
            ibz_add(&((*u)[0]), &((*u)[0]), d1);
        }
        success = 1;
        break; 
        
    }

cleanup:
    ibz_finalize(&A); ibz_finalize(&B); ibz_finalize(&C); ibz_finalize(&Delta);
    ibz_finalize(&inv2A); ibz_finalize(&fourA); ibz_finalize(&exp); 
    ibz_finalize(&rem); ibz_finalize(&temp1); ibz_finalize(&temp2); ibz_finalize(&four);
    
    ibz_finalize(&M01x2); ibz_finalize(&M02x2); ibz_finalize(&M03x2);
    ibz_finalize(&M12x2); ibz_finalize(&M13x2); ibz_finalize(&M23x2);
    ibz_finalize(&T1); ibz_finalize(&T2); ibz_finalize(&T3);
    
    return success;
}

/*
compute w ∈ F_{d1^4} satisfies B(u, w) = u*(M_Gram + M_Gram^T)*w^T = 0 (mod d1), Q(w) = w*M_Gram*w^T = 0 (mod d1)
*/
static int 
quat_sample_isotropic_orthogonal_vector_mod(ibz_vec_4_t *w, 
                                            const ibz_vec_4_t *u, 
                                            const ibz_mat_4x4_t *M_Gram, 
                                            const ibz_t *d1)
{
    int success = 0;
    ibz_vec_4_t C, V1, V0, U; 
    ibz_t inv_C, QA, QB, QC, Delta, inv2QA, fourQA, exp, rem, temp1, temp2, four;
    ibz_t Ta, Tb, Tc, x;      
    int pivot = -1, idx_x, idx_r1, idx_r2;

    ibz_vec_4_init(&C); ibz_vec_4_init(&V1); ibz_vec_4_init(&V0); ibz_vec_4_init(&U);
    ibz_init(&inv_C); ibz_init(&QA); ibz_init(&QB); ibz_init(&QC);
    ibz_init(&Delta); ibz_init(&inv2QA); ibz_init(&fourQA);
    ibz_init(&exp); ibz_init(&rem); ibz_init(&temp1); ibz_init(&temp2); ibz_init(&four);
    ibz_init(&Ta); ibz_init(&Tb); ibz_init(&Tc); ibz_init(&x);
    ibz_set(&four, 4);

    // Algorithm principle:
    // C = u*(M_Gram + M_Gram^T) = [C0, C1, C2, C3]
    // w0 = -C0^(-1)*(C1*w1 + C2*w2 + C3*w3) (mod d1)
    // w = [-C0^(-1)*(C1*w1 + C2*w2 + C3*w3), w1, w2, w3]
    //   = [-C0^(-1)*C1, 1, 0, 0] * w1 + [-C0^(-1)*(C2*w2 + C3*w3), 0, w2, w3]
    //   = V1 * x + V0 (let w1 = x, w2 = r1, w3 = r2)
    // V1 = [-C0^(-1)*C1, 1, 0, 0], V0 = [-C0^(-1)*(C2*w2 + C3*w3), 0, r1, r2]
    // randomly sample r1, r2, then compute Q(w) = (V1*x + V0) * M_Gram * (V1*x + V0) = 0 mod d1
    // equals to solve QA * x^2 + QB * x + QC = 0
    // QA = V1 * M_Gram * V1^T (mod d1), 
    // QB = 2 * V1 * M_Gram * V0^T (mod d1),
    // QC = V0 * M_Gram * V0^T (mod d1), 

    // compute C = u * (M_Gram + M_Gram^T) = 2 * u * M_Gram, M_Gram is symmetric
    for (int j = 0; j < 4; j++) {
        ibz_set(&(C[j]), 0);
        for (int i = 0; i < 4; i++) {
            ibz_mul(&temp1, &((*M_Gram)[i][j]), &((*u)[i]));
            ibz_add(&(C[j]), &(C[j]), &temp1);
        }
        ibz_add(&(C[j]), &(C[j]), &(C[j])); // double
        ibz_mod(&(C[j]), &(C[j]), d1);
        if (pivot == -1 && ibz_cmp(&(C[j]), &ibz_const_zero) != 0) {
            pivot = j;
        }
    }
    if (pivot == -1) {
        goto cleanup; 
    }

    idx_x  = (pivot + 1) % 4;
    idx_r1 = (pivot + 2) % 4;
    idx_r2 = (pivot + 3) % 4;
    ibz_invmod(&inv_C, &(C[pivot]), d1);
    
    // compute V1
    for (int i = 0; i < 4; i++) ibz_set(&(V1[i]), 0);
    ibz_set(&(V1[idx_x]), 1); 
    ibz_mul(&temp1, &(C[idx_x]), &inv_C);
    ibz_mod(&temp1, &temp1, d1);
    if (ibz_cmp(&temp1, &ibz_const_zero) > 0) {
        ibz_sub(&(V1[pivot]), d1, &temp1);
    }

    // precompute U = V1 * M_Gram 
    for (int j = 0; j < 4; j++) {
        ibz_mul(&(U[j]), &((*M_Gram)[idx_x][j]), &(V1[idx_x]));
        ibz_mul(&temp1, &((*M_Gram)[pivot][j]), &(V1[pivot]));
        ibz_add(&(U[j]), &(U[j]), &temp1);
    }

    // QA = U * V1^T (mod d1)
    ibz_mul(&QA, &(U[idx_x]), &(V1[idx_x]));
    ibz_mul(&temp1, &(U[pivot]), &(V1[pivot]));
    ibz_add(&QA, &QA, &temp1);
    ibz_mod(&QA, &QA, d1);
    // if QA = V1 * M_Gram * V1^T (mod d1) = 0, then w = V1.
    if (ibz_cmp(&QA, &ibz_const_zero) == 0) {
        for (int i = 0; i < 4; i++) ibz_copy(&((*w)[i]), &(V1[i]));
        success = 1;
        goto cleanup;
    }

    ibz_add(&temp1, &QA, &QA); // 2QA
    ibz_invmod(&inv2QA, &temp1, d1); // 1/2QA
    ibz_add(&fourQA, &temp1, &temp1); 
    ibz_mod(&fourQA, &fourQA, d1); // 4QA
    ibz_add(&temp1, d1, &ibz_const_one);
    ibz_div(&exp, &rem, &temp1, &four); // exp = (d1 + 1)/4

    // randomly sample r1, t2 ∈ V0 and solve the quadratic equation
    while (1) {
        ibz_rand_interval(&(V0[idx_r1]), &ibz_const_zero, d1);
        ibz_rand_interval(&(V0[idx_r2]), &ibz_const_zero, d1);
        ibz_set(&(V0[idx_x]), 0);
        
        // V0[pivot] = - (C[idx_r1]*V0[idx_r1] + C[idx_r2]*V0[idx_r2]) * inv_C mod d1
        ibz_mul(&temp1, &(C[idx_r1]), &(V0[idx_r1]));
        ibz_mul(&temp2, &(C[idx_r2]), &(V0[idx_r2]));
        ibz_add(&temp1, &temp1, &temp2);
        ibz_mod(&temp1, &temp1, d1);
        ibz_mul(&temp1, &temp1, &inv_C);
        ibz_mod(&temp1, &temp1, d1);
        ibz_set(&(V0[pivot]), 0);
        if (ibz_cmp(&temp1, &ibz_const_zero) > 0) {
            ibz_sub(&(V0[pivot]), d1, &temp1);
        }

        // QB = 2 * U * V0^T mod d1 
        ibz_mul(&QB, &(U[idx_r1]), &(V0[idx_r1]));
        ibz_mul(&temp1, &(U[idx_r2]), &(V0[idx_r2]));
        ibz_add(&QB, &QB, &temp1);
        ibz_mul(&temp1, &(U[pivot]), &(V0[pivot]));
        ibz_add(&QB, &QB, &temp1);
        ibz_add(&QB, &QB, &QB); 
        ibz_mod(&QB, &QB, d1);

        // QC = V0 * M_Gram * V0^T mod d1 
        // Ta = V0[idx_r1]*M[idx_r1][idx_r1] + V0[idx_r2]*2*M[idx_r1][idx_r2] + V0[pivot]*2*M[idx_r1][pivot]
        ibz_mul(&Ta, &(V0[idx_r1]), &((*M_Gram)[idx_r1][idx_r1]));
        ibz_add(&temp1, &((*M_Gram)[idx_r1][idx_r2]), &((*M_Gram)[idx_r1][idx_r2])); // 2 * M[idx_r1][idx_r2]
        ibz_mul(&temp2, &(V0[idx_r2]), &temp1);
        ibz_add(&Ta, &Ta, &temp2);
        ibz_add(&temp1, &((*M_Gram)[idx_r1][pivot]), &((*M_Gram)[idx_r1][pivot])); // 2 * M[idx_r1][pivot]
        ibz_mul(&temp2, &(V0[pivot]), &temp1);
        ibz_add(&Ta, &Ta, &temp2);
        // Tb = V0[idx_r2]*M[idx_r2][idx_r2] + V0[pivot]*2*M[idx_r2][pivot]
        ibz_mul(&Tb, &(V0[idx_r2]), &((*M_Gram)[idx_r2][idx_r2]));
        ibz_add(&temp1, &((*M_Gram)[idx_r2][pivot]), &((*M_Gram)[idx_r2][pivot])); // 2 * M[idx_r2][pivot]
        ibz_mul(&temp2, &(V0[pivot]), &temp1);
        ibz_add(&Tb, &Tb, &temp2);
        // Tc = V0[pivot]*M[pivot][pivot]
        ibz_mul(&Tc, &(V0[pivot]), &((*M_Gram)[pivot][pivot]));
        // QC = V0[idx_r1]*Ta + V0[idx_r2]*Tb + V0[pivot]*Tc mod d1 
        ibz_mul(&QC, &(V0[idx_r1]), &Ta);
        ibz_mul(&temp1, &(V0[idx_r2]), &Tb);
        ibz_add(&QC, &QC, &temp1);
        ibz_mul(&temp1, &(V0[pivot]), &Tc);
        ibz_add(&QC, &QC, &temp1);
        ibz_mod(&QC, &QC, d1);

        // Delta = QB^2 - 4*QA*QC mod d1
        ibz_mul(&temp1, &QB, &QB);
        ibz_mul(&temp2, &fourQA, &QC);
        ibz_sub(&Delta, &temp1, &temp2);
        ibz_mod(&Delta, &Delta, d1);
        if (ibz_cmp(&Delta, &ibz_const_zero) < 0) ibz_add(&Delta, &Delta, d1);

        // Kronecker check
        if (mpz_kronecker(Delta, *d1) < 0) {
            continue; 
        }
        // temp1 = sqrt(Delta) 
        ibz_pow_mod(&temp1, &Delta, &exp, d1); 
        // x = (sqrt(Delta) - QB) * inv2QA mod d1
        ibz_sub(&x, &temp1, &QB);
        ibz_mul(&x, &x, &inv2QA);
        ibz_mod(&x, &x, d1);
        if (ibz_cmp(&x, &ibz_const_zero) < 0) ibz_add(&x, &x, d1);
        // construct w = V1 * x + V0 mod d1
        int is_zero = 1;
        for (int i = 0; i < 4; i++) {
            ibz_mul(&temp2, &(V1[i]), &x);
            ibz_add(&((*w)[i]), &temp2, &(V0[i]));
            ibz_mod(&((*w)[i]), &((*w)[i]), d1);
            if (ibz_cmp(&((*w)[i]), &ibz_const_zero) != 0) is_zero = 0;
        }
        if (!is_zero) {
            success = 1;
            break; 
        }
        
    }

cleanup:
    ibz_vec_4_finalize(&C); ibz_vec_4_finalize(&V1); ibz_vec_4_finalize(&V0); ibz_vec_4_finalize(&U);
    ibz_finalize(&inv_C); ibz_finalize(&QA); ibz_finalize(&QB); ibz_finalize(&QC);
    ibz_finalize(&Delta); ibz_finalize(&inv2QA); ibz_finalize(&fourQA);
    ibz_finalize(&exp); ibz_finalize(&rem); ibz_finalize(&temp1); ibz_finalize(&temp2); ibz_finalize(&four);
    ibz_finalize(&Ta); ibz_finalize(&Tb); ibz_finalize(&Tc); ibz_finalize(&x);

    return success;
}

/*
construct HNF of the basis of Lambda_w
the p-th column is the normalized vector w',
for the other columns, the diagonal elements are d_1, and the rest are 0.
for example, if pivot = 1, then HNF is: 
[d1,   0,  0,  0] 
[ 0,   1,  0,  0]
[ 0, w2', d1,  0]
[ 0, w3',  0, d1]
*/
static int 
quat_construct_sublattice_basis(ibz_mat_4x4_t *B_sublat,
                                const ibz_vec_4_t *w,
                                const ibz_t *d1)
{
    int success = 0;
    int pivot = -1;
    ibz_t inv_wp; 

    ibz_init(&inv_wp); 

    // find pivot，compute inv_wp = w[pivot] mod d1
    for (int i = 0; i < 4; i++) {
        ibz_mod(&inv_wp, &((*w)[i]), d1);
        if (ibz_cmp(&inv_wp, &ibz_const_zero) != 0) {
            pivot = i;
            break;
        }
    }
    if (pivot == -1) {
        goto cleanup; 
    }
    //if w[pivot] mod d1 = 1, then inv_wp = 1 
    if (ibz_cmp(&inv_wp, &ibz_const_one) != 0) {
        if (!ibz_invmod(&inv_wp, &inv_wp, d1)) {
            goto cleanup;
        }
    }

    // construct HNF matrix 
    for (int j = 0; j < 4; j++) {
        if (j == pivot) {
            // pivot-th column
            for (int i = 0; i < 4; i++) {
                if (i < pivot) {
                    ibz_set(&((*B_sublat)[i][j]), 0);
                } else if (i == pivot) {
                    ibz_set(&((*B_sublat)[i][j]), 1);
                } else {
                    ibz_mul(&((*B_sublat)[i][j]), &((*w)[i]), &inv_wp);
                    ibz_mod(&((*B_sublat)[i][j]), &((*B_sublat)[i][j]), d1);
                }
            }
        } 
        else {
            // other columns
            for (int i = 0; i < 4; i++) {
                if (i == j) {
                    ibz_copy(&((*B_sublat)[i][j]), d1);
                } else {
                    ibz_set(&((*B_sublat)[i][j]), 0);
                }
            }
        }
    }

    success = 1;

cleanup:
    ibz_finalize(&inv_wp);
    return success;
}

/*
perform LLL reduction and return absolute coordinates
*/
static int 
quat_perform_lll(ibz_mat_4x4_t *B_red_abs,
                 const ibz_mat_4x4_t *B_sublat,
                 const quat_left_ideal_t *I,
                 const quat_alg_t *alg)
{
    int success = 0;
    quat_lattice_t Lat_abs; 

    quat_lattice_init(&Lat_abs); 

    // Lat_abs = I_basis * B_sublat
    ibz_mat_4x4_mul(&Lat_abs.basis, &(I->lattice.basis), B_sublat);
    ibz_copy(&(Lat_abs.denom), &(I->lattice.denom));

    //  LLL reduction
    if (quat_lattice_lll(B_red_abs, &Lat_abs, alg)) {
        goto cleanup; 
    }
    success = 1;

cleanup:
    quat_lattice_finalize(&Lat_abs);

    return success;
}

/*
solve CVP and construct equivalent left-ideal with special norm
*/
static int 
quat_solve_cvp_and_compute_ideal(quat_left_ideal_t *J,
                                 ibz_t *k,
                                 const ibz_mat_4x4_t *B_red_abs, 
                                 const ibz_vec_4_t *u,
                                 const quat_left_ideal_t *I,
                                 const ibz_t *d1,
                                 const ibz_t *d2,
                                 const quat_alg_t *alg) 
{
    int success = 0;
    ibz_mat_4x4_t B_abj; 
    ibz_t B_det, num_i, temp, norm_num, norm_denom, reduced_norm, rem;
    ibz_vec_4_t u_abs, c_round, v_abs;
    quat_alg_elem_t alpha, alpha_conj;

    ibz_mat_4x4_init(&B_abj);
    ibz_init(&B_det); ibz_init(&num_i); ibz_init(&temp); 
    ibz_init(&norm_num); ibz_init(&norm_denom); ibz_init(&reduced_norm); ibz_init(&rem); 

    ibz_vec_4_init(&u_abs); ibz_vec_4_init(&c_round); ibz_vec_4_init(&v_abs); 
    quat_alg_elem_init(&alpha); quat_alg_elem_init(&alpha_conj);

    // u_abs = I_basis * u
    ibz_mat_4x4_eval(&u_abs, &(I->lattice.basis), u);
    // B_abj / B_det = B_red_abs^(-1)
    ibz_mat_4x4_inv_with_det_as_denom(&B_abj, &B_det, B_red_abs);
    if (ibz_cmp(&B_det, &ibz_const_zero) == 0) goto cleanup;
    // compute c = B_red_abs^(-1) * (-u_abs) = B_abj * (-u_abs) / B_det
    for (int i = 0; i < 4; i++) {
        ibz_set(&num_i, 0);
        for (int j = 0; j < 4; j++) {
            ibz_mul(&temp, &B_abj[i][j], &u_abs[j]);
            ibz_sub(&num_i, &num_i, &temp); 
        }
        ibz_div(&c_round[i], &rem, &num_i, &B_det);
    }

    // v_abs = B_red_abs * c_round 
    ibz_mat_4x4_eval(&v_abs, B_red_abs, &c_round); 
    // alpha = u_abs + v_abs
    for (int i = 0; i < 4; i++) {
        ibz_add(&alpha.coord[i], &u_abs[i], &v_abs[i]); 
    }
    ibz_copy(&alpha.denom, &(I->lattice.denom));

    // check nrd(alpha)
    quat_alg_norm(&norm_num, &norm_denom, &alpha, alg);
    if (ibz_cmp(&norm_denom, &ibz_const_one) != 0) goto cleanup; 
    // check n(J) = k*d1 + d2
    ibz_div(&reduced_norm, &temp, &norm_num, &(I->norm)); 
    if (ibz_cmp(&temp, &ibz_const_zero) != 0) goto cleanup; 
    ibz_sub(&temp, &reduced_norm, d2); 
    ibz_div(k, &temp, &temp, d1); 
    if (ibz_cmp(&temp, &ibz_const_zero) != 0) goto cleanup;
    
    // construct equivalent ideal J = I * conj(alpha) / N(I)
    quat_alg_conj(&alpha_conj, &alpha);
    ibz_mul(&alpha_conj.denom, &alpha_conj.denom, &I->norm);
    quat_lideal_mul(J, I, &alpha_conj, alg);
    
    success = 1;

cleanup:
    ibz_mat_4x4_finalize(&B_abj);
    ibz_finalize(&B_det); ibz_finalize(&num_i); ibz_finalize(&temp); 
    ibz_finalize(&norm_num); ibz_finalize(&norm_denom); ibz_finalize(&reduced_norm);
    ibz_finalize(&rem); 
    ibz_vec_4_finalize(&u_abs); ibz_vec_4_finalize(&c_round); ibz_vec_4_finalize(&v_abs); 
    quat_alg_elem_finalize(&alpha); quat_alg_elem_finalize(&alpha_conj);
    
    return success;
}

int 
quat_equivalent_special_norm_ideal(quat_left_ideal_t *J,
                                   ibz_t *k,
                                   const quat_left_ideal_t *I,
                                   const ibz_t *d1,
                                   const ibz_t *d2,
                                   const quat_alg_t *alg)
{
    int success = 0;
    ibz_mat_4x4_t M_Gram, B_sublat, B_sublat_lll;
    ibz_vec_4_t u, w;

    ibz_mat_4x4_init(&M_Gram);
    ibz_mat_4x4_init(&B_sublat);
    ibz_mat_4x4_init(&B_sublat_lll);
    ibz_vec_4_init(&u);
    ibz_vec_4_init(&w);

    /*
    Step 0: compute M_Gram = B*D*B^T / N(I) mod d1
    */
    if (!quat_compute_gram_matrix_mod(&M_Gram, I, d1, alg)) {
        goto cleanup; // Exit safely if Step 0 fails
    }

    /*
    Step 1: compute Q(u) = d2 (mod d1)
    for u = [u0, u1, u2, u3] (ui ∈ F_{d1}) ∈ I, Q(u) = u*M_Gram*u^T = Nrd(u) / Nrd(I)
    randomly sample u1, u2, u3, then solve a quadratic equation ∈ u0.
    */
    if (!quat_sample_norm_vector_mod(&u, &M_Gram, d1, d2)) {
        goto cleanup; 
    }

    /*
    Step 2: compute Q(w) = 0 (mod d1), and satisfies Q(u + Lambda*w) = d2 (mod d1), Lambda ∈ Z
    Q(u + Lambda* w) = (u + Lambda* w)*M_Gram*(u + Lambda* w)^T
                    = u*M_Gram*u^T + Lambda*u*(M_Gram + M_Gram^T)*w^T + Lambda^2*(w*M*w^T)
    it is required B(u, w) = u*(M_Gram + M_Gram^T)*w^T = 0 (mod d1)
                   Q(w) = w*M_Gram*w^T = 0 (mod d1)
    */
    if (!quat_sample_isotropic_orthogonal_vector_mod(&w, &u, &M_Gram, d1)) {
        goto cleanup; 
    }

    /*
    Step 3: construct sublattice basis
    Lambda_w = {v ∈ Z^4 | v = lambda*w (mod d1), lambda ∈ Z}
    for any v ∈ Lambda_w, v = [v1, v2, v3, v4] = lambda*[w0, w1, w2, w3] + d1*[k0, k1, k2, k3], ki ∈ Z.
    abstract basis of Lambda_w under the basis of I = [alpha0, alpha1, alpha2, alpha3]: 
    [d1,  0,  0,  0, w1]
    [ 0, d1,  0,  0, w2]
    [ 0,  0, d1,  0, w3]
    [ 0,  0,  0, d1, w4]
    */
    if (!quat_construct_sublattice_basis(&B_sublat, &w, d1)) {
        goto cleanup;
    }

    /*
    Step 4: perform LLL-reduction under the quaternion norm
    */
    if (!quat_perform_lll(&B_sublat_lll, &B_sublat, I, alg)) {
        goto cleanup;
    }

    /*
    Step 5: solve the CVP using exact Babai rounding and compute the equivalent left-ideal J with n(J) = k*d1 + d2
    */
    if (!quat_solve_cvp_and_compute_ideal(J, k, &B_sublat_lll, &u, I, d1, d2, alg)) {
        goto cleanup; 
    }

    success = 1;

cleanup:
    ibz_mat_4x4_finalize(&M_Gram);
    ibz_mat_4x4_finalize(&B_sublat);
    ibz_mat_4x4_finalize(&B_sublat_lll);
    ibz_vec_4_finalize(&u);
    ibz_vec_4_finalize(&w);

    return success;
}
