PROJECT_NAME           = "BAG-PIGLET"
OUTPUT_DIRECTORY       = doc/generated
INPUT                  = src
RECURSIVE              = YES
GENERATE_HTML           = YES
GENERATE_LATEX          = NO
QUIET                   = YES
