/*
 * Generated AFS-LMDS-1600-S6 opt64 code.
 * Generated on: 2026-06-08
 * Generated by: python3 tools/s6_codegen/generate_s6_opt64.py --root /home/weibh/Codex/AFS-TrEDM_Submission_v2.0
 * Semantic source: Implementations/Reference_Implementation/AFS-TrEDM-512/afs_lmds1600_s6.c
 * Semantic source SHA-256: ef08151c42390fb69e8c98bc855e6ce8bf839af22f7884fddcb0512d8b8f32cb
 */

#include "afs_lmds1600_s6_opt64.h"

#include <stdint.h>

/* Function rotr64: rotates a 64-bit word right by a constant-count modulo 64 amount. */
static inline uint64_t rotr64(uint64_t x, unsigned n)
{
    n &= 63U;
    return (uint64_t)((x >> n) | (x << ((64U - n) & 63U)));
}

#include "generated/afs_lmds_s6_round_0.inc"
#include "generated/afs_lmds_s6_round_1.inc"
#include "generated/afs_lmds_s6_round_2.inc"
#include "generated/afs_lmds_s6_round_3.inc"
#include "generated/afs_lmds_s6_round_4.inc"
#include "generated/afs_lmds_s6_round_5.inc"

/* Function afs_lmds1600_s6_opt64: dispatches to the generated opt64 S6 linear layer for the selected round phase. */
void afs_lmds1600_s6_opt64(uint64_t A[25], unsigned round)
{
    switch (round % 6U) {
    case 0U:
        afs_lmds_s6_round_0(A);
        break;
    case 1U:
        afs_lmds_s6_round_1(A);
        break;
    case 2U:
        afs_lmds_s6_round_2(A);
        break;
    case 3U:
        afs_lmds_s6_round_3(A);
        break;
    case 4U:
        afs_lmds_s6_round_4(A);
        break;
    default:
        afs_lmds_s6_round_5(A);
        break;
    }
}
