/*
 * Generated AFS-LMDS-1600-S6 opt64 code.
 * Generated on: 2026-06-08
 * Generated by: python3 tools/s6_codegen/generate_s6_opt64.py --root /home/weibh/Codex/AFS-TrEDM_Submission_v2.0
 * Semantic source: Implementations/Reference_Implementation/AFS-TrEDM-512/afs_lmds1600_s6.c
 * Semantic source SHA-256: ef08151c42390fb69e8c98bc855e6ce8bf839af22f7884fddcb0512d8b8f32cb
 */

#ifndef AFS_LMDS1600_S6_OPT64_H
#define AFS_LMDS1600_S6_OPT64_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

void afs_lmds1600_s6_opt64(uint64_t A[25], unsigned round);

#ifdef __cplusplus
}
#endif

#endif /* AFS_LMDS1600_S6_OPT64_H */
