#ifndef PARAMS_H
#define PARAMS_H

#define NTRUOAEP_N 2592
#define NTRUOAEP_Q 28513

#define NTRUOAEP_SSBYTES 64
#define NTRUOAEP_SYMBYTES  128
#define KeyConfirmation_BYTES (NTRUOAEP_SSBYTES + NTRUOAEP_SYMBYTES)
#define NTRUOAEP_POLYBYTES 4860
#define NTRUOAEP_MAXPLAINTEXT 324

#define NTRUOAEP_PUBLICKEYBYTES  NTRUOAEP_POLYBYTES
#define NTRUOAEP_SECRETKEYBYTES  ((NTRUOAEP_POLYBYTES << 1) + NTRUOAEP_SYMBYTES)
#define NTRUOAEP_CIPHERTEXTBYTES  (NTRUOAEP_POLYBYTES + NTRUOAEP_SYMBYTES)

#define NTRUOAEP_PKEM_CIPHERTEXTBYTES  (NTRUOAEP_POLYBYTES + NTRUOAEP_SYMBYTES)


#endif
