#ifndef PARAMS_H
#define PARAMS_H

#define SCABBARD_L 8
#define SCABBARD_N 256
#define SCABBARD_Q 8191
#define SCABBARD_P 2047

#define SCABBARD_EQ 13 
#define SCABBARD_EP 11
#define SCABBARD_ET 6 
#define SCABBARD_B 2 /* bits per encoded secret coefficient */
#define SCABBARD_ETA 4 /* CBD: sample from 2 * \eta bits */
#define SCABBARD_ETA_ENCODE 4 /* Compress secret-key coefficients */

#define SCABBARD_SYMBYTES 64 /* Size in bytes of hashes and seeds */
#define SCABBARD_SSBYTES 64  /* Size in bytes of shared key */

#define SCABBARD_POLYBYTES ((SCABBARD_EQ * SCABBARD_N) / 8)       
#define SCABBARD_P_POLYBYTES ((SCABBARD_EP * SCABBARD_N) / 8)
#define SCABBARD_S_POLYBYTES ((SCABBARD_ETA_ENCODE * SCABBARD_N) / 8)
#define SCABBARD_CBD_POLYBYTES ((SCABBARD_ETA * SCABBARD_N) / 8)

#define SCABBARD_POLYVECBYTES (SCABBARD_L * SCABBARD_POLYBYTES)  
#define SCABBARD_S_POLYVECBYTES (SCABBARD_L * SCABBARD_S_POLYBYTES)

#define SCABBARD_POLYCOMPRESSEDBYTES (((SCABBARD_ET + SCABBARD_B) *  SCABBARD_N) / 8) 
#define SCABBARD_POLYVECCOMPRESSEDBYTES (SCABBARD_L * SCABBARD_P_POLYBYTES) 

#define SCABBARD_INDCPA_MSGBYTES SCABBARD_SYMBYTES
#define SCABBARD_INDCPA_PUBLICKEYBYTES (SCABBARD_POLYVECCOMPRESSEDBYTES + SCABBARD_SYMBYTES) 
#define SCABBARD_INDCPA_SECRETKEYBYTES SCABBARD_S_POLYVECBYTES 
#define SCABBARD_INDCPA_BYTES (SCABBARD_POLYVECCOMPRESSEDBYTES + SCABBARD_POLYCOMPRESSEDBYTES) 

#define SCABBARD_PUBLICKEYBYTES SCABBARD_INDCPA_PUBLICKEYBYTES
#define SCABBARD_SECRETKEYBYTES (SCABBARD_INDCPA_SECRETKEYBYTES + SCABBARD_INDCPA_PUBLICKEYBYTES + 2 * SCABBARD_SYMBYTES) 
#define SCABBARD_CIPHERTEXTBYTES SCABBARD_INDCPA_BYTES

#define KEM_L SCABBARD_L
#define KEM_N SCABBARD_N
#define KEM_Q SCABBARD_Q
#define KEM_P SCABBARD_P
#define KEM_EQ SCABBARD_EQ
#define KEM_EP SCABBARD_EP
#define KEM_ET SCABBARD_ET
#define KEM_B SCABBARD_B
#define KEM_ETA SCABBARD_ETA
#define KEM_ETA_ENCODE SCABBARD_ETA_ENCODE
#define KEM_SYMBYTES SCABBARD_SYMBYTES
#define KEM_SSBYTES SCABBARD_SSBYTES
#define KEM_POLYBYTES SCABBARD_POLYBYTES
#define KEM_P_POLYBYTES SCABBARD_P_POLYBYTES
#define KEM_S_POLYBYTES SCABBARD_S_POLYBYTES
#define KEM_CBD_POLYBYTES SCABBARD_CBD_POLYBYTES
#define KEM_POLYVECBYTES SCABBARD_POLYVECBYTES
#define KEM_S_POLYVECBYTES SCABBARD_S_POLYVECBYTES
#define KEM_POLYCOMPRESSEDBYTES SCABBARD_POLYCOMPRESSEDBYTES
#define KEM_POLYVECCOMPRESSEDBYTES SCABBARD_POLYVECCOMPRESSEDBYTES
#define KEM_INDCPA_MSGBYTES SCABBARD_INDCPA_MSGBYTES
#define KEM_INDCPA_PUBLICKEYBYTES SCABBARD_INDCPA_PUBLICKEYBYTES
#define KEM_INDCPA_SECRETKEYBYTES SCABBARD_INDCPA_SECRETKEYBYTES
#define KEM_INDCPA_BYTES SCABBARD_INDCPA_BYTES
#define KEM_PUBLICKEYBYTES SCABBARD_PUBLICKEYBYTES
#define KEM_SECRETKEYBYTES SCABBARD_SECRETKEYBYTES
#define KEM_CIPHERTEXTBYTES SCABBARD_CIPHERTEXTBYTES

#endif
