#ifndef PARAMS_H
#define PARAMS_H

#define NTRUOAEP_N 648
#define NTRUOAEP_Q 7129

#define NTRUOAEP_SSBYTES 32
#define NTRUOAEP_SYMBYTES  32
#define KeyConfirmation_BYTES 64
#define NTRUOAEP_POLYBYTES 1053
#define NTRUOAEP_MAXPLAINTEXT 81

#define NTRUOAEP_PUBLICKEYBYTES  NTRUOAEP_POLYBYTES
#define NTRUOAEP_SECRETKEYBYTES  ((NTRUOAEP_POLYBYTES << 1) + NTRUOAEP_SYMBYTES)
#define NTRUOAEP_CIPHERTEXTBYTES  (NTRUOAEP_POLYBYTES + NTRUOAEP_SYMBYTES)

#define NTRUOAEP_PKEM_CIPHERTEXTBYTES  (NTRUOAEP_POLYBYTES + NTRUOAEP_SYMBYTES)


#endif
