

# This file was *autogenerated* from the file precompute_klpt_constants.sage
from sage.all_cmdline import *   # import sage library

_sage_const_9 = Integer(9); _sage_const_8 = Integer(8); _sage_const_2 = Integer(2); _sage_const_64 = Integer(64); _sage_const_1 = Integer(1); _sage_const_4 = Integer(4); _sage_const_15 = Integer(15); _sage_const_25 = Integer(25); _sage_const_0 = Integer(0); _sage_const_13 = Integer(13); _sage_const_5 = Integer(5); _sage_const_3 = Integer(3); _sage_const_10 = Integer(10); _sage_const_100 = Integer(100)#!/usr/bin/env sage
proof.all(False)  # faster

from sage.misc.banner import require_version
if not require_version(_sage_const_9 , _sage_const_8 , print_message=True):
    exit('')

################################################################

from parameters import f, p, Tpls, Tmin
negl = _sage_const_2 **-_sage_const_64    #TODO optimize

################################################################

logp = ceil(log(p, _sage_const_2 ))
logT = ceil(log(Tpls*Tmin, _sage_const_2 ))
tors2val = (p+_sage_const_1 ).valuation(_sage_const_2 )

defs = dict()

# lideal_equiv

defs['KLPT_equiv_bound_coeff'] = ceil((log(negl, _sage_const_1 -_sage_const_2 /logp) ** (_sage_const_1 /_sage_const_4 ) - _sage_const_1 ) / _sage_const_2 ) + _sage_const_2 
assert (_sage_const_1  - _sage_const_2 /logp) ** ((_sage_const_2  * defs['KLPT_equiv_bound_coeff'] + _sage_const_1 ) ** _sage_const_4 ) <= negl

defs['KLPT_equiv_num_iter'] = (_sage_const_2  * defs['KLPT_equiv_bound_coeff'] + _sage_const_1 ) ** _sage_const_4 

defs['KLPT_primality_num_iter'] = ceil(-log(negl, _sage_const_4 ))

# signing KLPT

defs['KLPT_signing_klpt_length'] = f * ceil (ceil((log(negl, _sage_const_2 ) / -_sage_const_2 ) + _sage_const_15 /_sage_const_4 *logp + _sage_const_25 )/f)
assert _sage_const_2 **(-_sage_const_2  * (defs['KLPT_signing_klpt_length'] - _sage_const_15 /_sage_const_4 *logp - _sage_const_25 )) <= negl

defs['KLPT_signing_num_gamma_trial'] = ceil(log(negl, _sage_const_2 ) / -_sage_const_1 )
assert _sage_const_2  ** ( - defs['KLPT_signing_num_gamma_trial']) <= negl

defs['KLPT_gamma_exponent_interval_size'] = _sage_const_0 

defs['KLPT_gamma_exponent_center_shift'] = ceil(log(log(negl, _sage_const_1 -_sage_const_1 /logp) + defs['KLPT_signing_num_gamma_trial'], _sage_const_2 ) + defs['KLPT_gamma_exponent_interval_size'])
assert (_sage_const_1  - _sage_const_1 /logp) ** (_sage_const_2 **(defs['KLPT_gamma_exponent_center_shift'] - defs['KLPT_gamma_exponent_interval_size']) - defs['KLPT_signing_num_gamma_trial']) <= negl

defs['KLPT_repres_num_gamma_trial'] = _sage_const_2 **(defs['KLPT_gamma_exponent_center_shift'] + defs['KLPT_gamma_exponent_interval_size'])

defs['KLPT_signing_number_strong_approx'] = ceil(log(_sage_const_1 /_sage_const_64 , _sage_const_1 -_sage_const_4 /_sage_const_13 /logp))
assert (_sage_const_1  - _sage_const_4 /_sage_const_13 /logp) ** defs['KLPT_signing_number_strong_approx'] <= _sage_const_1 /_sage_const_64 

# keygen KLPT

defs['KLPT_random_prime_attempts'] = _sage_const_64 

defs['KLPT_secret_key_prime_size'] = ceil(logp / _sage_const_4 )

defs['KLPT_keygen_length'] =   f* ceil ( ceil(log(negl, _sage_const_2 ) / -_sage_const_2  + _sage_const_5 /_sage_const_2 *logp -_sage_const_25  ) / f)
assert _sage_const_2  ** (-_sage_const_2  * (defs['KLPT_keygen_length'] - _sage_const_5 /_sage_const_2 *logp +_sage_const_25 )) <= negl

defs['KLPT_keygen_num_gamma_trial'] = ceil(log(negl, _sage_const_2 ) / -_sage_const_1 )

defs['KLPT_eichler_smallnorm_bitsize'] = ceil(_sage_const_1 /_sage_const_2 *logp - _sage_const_4 /_sage_const_3 *( logT - _sage_const_5 /_sage_const_4 *logp))

defs['KLPT_keygen_number_strong_approx'] = ceil(log(_sage_const_1 /_sage_const_64 , _sage_const_1 -_sage_const_2 /_sage_const_5 /logp))
assert (_sage_const_1  - _sage_const_2 /_sage_const_5 /logp) ** defs['KLPT_keygen_number_strong_approx'] <= _sage_const_1 /_sage_const_64 

# Eichler

defs['KLPT_eichler_number_mu_norm'] = max(ceil((logT - _sage_const_5 /_sage_const_4 *logp) / log(_sage_const_3 ,_sage_const_2 )),_sage_const_0 )

defs['KLPT_eichler_strong_approx_log_margin'] = _sage_const_2 

defs['KLPT_eichler_num_equiv_ideal'] = ceil(logp / _sage_const_10 )

defs['KLPT_eichler_number_strong_approx'] = ceil(_sage_const_10  * logp)

# signature response

defs['SQISIGN_response_attempts'] = _sage_const_64 

# signature isogeny degrees

defs['SQISIGN_random_length'] = _sage_const_0 
defs['SQISIGN_signing_total_length'] = defs['KLPT_signing_klpt_length']
defs['SQISIGN_signing_length'] = ZZ(defs['SQISIGN_signing_total_length'] / tors2val)
defs['SQISIGN_keygen_length'] = ZZ(defs['KLPT_keygen_length'] / tors2val)

# prime data for Cornacchia

primes_1mod4 = [p for p in primes(_sage_const_100 ) if p%_sage_const_4 ==_sage_const_1 ]
prod_primes_3mod4 = prod(p for p in primes(_sage_const_100 ) if p%_sage_const_4 ==_sage_const_3 )

################################################################

from cformat import Ibz, Object, ObjectFormatter

objs = ObjectFormatter([
        Object('short[]', 'SMALL_PRIMES_1MOD4', [int(v) for v in primes_1mod4]),
        Object('ibz_t', 'PROD_SMALL_PRIMES_3MOD4', Ibz(prod_primes_3mod4)),
    ])

################################################################

with open('include/klpt_constants.h','w') as hfile:
    with open('klpt_constants.c','w') as cfile:
        print(f'#include <intbig.h>', file=hfile)
        print(f'#include <stddef.h>', file=cfile)
        print(f'#include <stdint.h>', file=cfile)
        print(f'#include <klpt_constants.h>', file=cfile)

        for k,v in defs.items():
            v = ZZ(v)
            print(f'#define {k} {v}', file=hfile)

        objs.header(file=hfile)
        objs.implementation(file=cfile)


