

# This file was *autogenerated* from the file precompute_gf_constants.sage
from sage.all_cmdline import *   # import sage library

_sage_const_20 = Integer(20); _sage_const_0 = Integer(0); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_64 = Integer(64)#!/usr/bin/env sage
proof.all(False)  # faster

from parameters import p

num_entries = _sage_const_20   # as specified in paper

set_random_seed(_sage_const_0 )

################################################################

Fp2 = GF((p,_sage_const_2 ), modulus=[_sage_const_1 ,_sage_const_0 ,_sage_const_1 ], names=('i',)); (i,) = Fp2._first_ngens(1)

nqr_table = []
while len(nqr_table) < num_entries:
    elt = Fp2.random_element()
    if not elt.is_square():
        nqr_table.append(elt)

z_nqr_table = []
while len(z_nqr_table) < num_entries:
    elt = Fp2.random_element()
    if elt.is_square() and not (elt-_sage_const_1 ).is_square():
        z_nqr_table.append(elt)

################################################################

from cformat import Object, ObjectFormatter

def field2limbs(el):
    l = _sage_const_1  + floor(log(p, _sage_const_2 **_sage_const_64 ))
    el = Fp2(el)
    el = [_sage_const_2 **(_sage_const_64 *ceil(log(p,_sage_const_2 **_sage_const_64 ))) * c for c in el]  #FIXME this is such a hack! assumes Montgomery
    vs = [[(int(c) >> _sage_const_64 *i) % _sage_const_2 **_sage_const_64  for i in range(l)] for c in el]
    return vs

objs = ObjectFormatter([
        Object('fp2_t[]', 'NQR_TABLE', list(map(field2limbs, nqr_table))),
        Object('fp2_t[]', 'Z_NQR_TABLE', list(map(field2limbs, z_nqr_table))),
    ])

with open('include/gf_constants.h','w') as hfile:
    with open('gf_constants.c','w') as cfile:

        print(f'#include <fp2.h>', file=hfile)

        print(f'#include <stddef.h>', file=cfile)
        print(f'#include <stdint.h>', file=cfile)
        print(f'#include <tutil.h>', file=cfile)
        print(f'#include <fp2.h>', file=cfile)

        objs.header(file=hfile)
        objs.implementation(file=cfile)


