#ifndef CRETAKE_PARAMS_H
#define CRETAKE_PARAMS_H

#include "primitive_interfaces.h"

#define PKI_LEN ZEN_PUBLICKEY_LEN_BYTES
#define SKI_LEN ZEN_SECREKEY_LEN_BYTES
#define PKR_LEN ZEN_PUBLICKEY_LEN_BYTES
#define SKR_LEN ZEN_SECREKEY_LEN_BYTES

#define TPK_LEN ZEN_INDCPA_PUBLICKEY_LEN_BYTES
#define TSK_LEN ZEN_INDCPA_SECREKEY_LEN_BYTES

#define C_I_LEN ZEN_CIPHERTEXT_LEN_BYTES + ZEN_INDCPA_CIPHERTEXT_LEN_BYTES
#define C_R_LEN ZEN_CIPHERTEXT_LEN_BYTES
#define K_LEN 2 * ZEN_SHAREDKEY_LEN_BYTES
#define KEM_K_LEN ZEN_SHAREDKEY_LEN_BYTES

#define MSG_LEN_BYTES ZEN_INDCPA_MSG_LEN_BYTES
#define SEED_BYTES SEED_LEN_BYTES

#endif
