// SPDX-FileCopyrightText: Copyright 2023 the SQIsign team. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
 * This file is derived from xisog.c in the SQIsign (version 1.0) 
 * project (https://github.com/SQIsign/the-sqisign/tree/nist-v1),
 * which is licensed under the Apache-2.0 license.
 *
 * Modifications made:
 *   - Deleted some unused functions
 *   - Changed the data structure to SoA
 */

#include "bundle_isog.h"
#include "bundle_ec.h"
#include <assert.h>
#include <stdio.h>

// -------------------------------------------------------------------------
// -------------------------------------------------------------------------

// Degree-2 isogeny with kernel generated by P != (0 ,0)
// Outputs the curve coefficient in the form A24=(A+2C:4C)
void bundlexisog_2(bundleec_point_t* B, bundleec_point_t const P, int len)
{
	// for (int i = 0; i < len; i++)
	// {
	// 	assert(!fp2_is_zero(&(P.x.list[i])));
	// }
    bundlefp2_sqr(&B->x, &P.x, len);
    bundlefp2_sqr(&B->z, &P.z, len);
    bundlefp2_sub(&B->x, &B->z, &B->x, len);
	// fp2_print(B->x.list[len-1]);
	// printf("\n");
	// fp2_print(B->z.list[len-1]);
	// fflush(stdout);
    bundlefp2_add(&bundleK[0].x, &P.x, &P.z, len);
    bundlefp2_sub(&bundleK[0].z, &P.x, &P.z, len);
}

void bundlexisog_2_singular(bundleec_point_t *B24, bundleec_point_t A24, int len)
{
    // No need to check the square root, only used for signing.
    bundlefp2_t t0, four, invA24z;
    bundlefp2_set(&four, 4, len);
    bundlefp2_add(&t0, &A24.x, &A24.x, len);
    bundlefp2_sub(&t0, &t0, &A24.z, len);
    bundlefp2_add(&t0, &t0, &t0, len);
	bundlefp2_copy(&invA24z, &A24.z, len);
    bundlefp2_inv(&invA24z, len);
    bundlefp2_mul(&t0, &t0, &invA24z, len);
    bundlefp2_copy(&bundleK[2].x, &t0, len);
    bundlefp2_add(&B24->x, &t0, &t0, len);
    bundlefp2_sqr(&t0, &t0, len);
    bundlefp2_sub(&t0, &t0, &four, len);
    bundlefp2_sqrt(&t0, len);
    bundlefp2_neg(&bundleK[2].z, &t0, len);
    bundlefp2_add(&B24->z, &t0, &t0, len);
    bundlefp2_add(&B24->x, &B24->x, &B24->z, len);
    bundlefp2_add(&B24->z, &B24->z, &B24->z, len);
	// fp2_print(B24->x.list[CYCLE_LENGTH-1]);
	// printf("\n");
	// fp2_print(B24->z.list[CYCLE_LENGTH-1]);
	// fflush(stdout);
}

// xISOG procedure, which is a hybrid between Montgomery and Twisted Edwards
// This tradition fomulae corresponds with the Twisted Edwards formulae but 
// mapping the output into Montgomery form
void bundlexisog_t(bundleec_point_t* B, uint64_t const i, bundleec_point_t const A, int len)
{
	if (TORSION_ODD_PRIMES[i] == 2)
	{
		bundleec_point_t res1, res2;
		bundlexisog_2(&res1, bundleK[1], len);
		bundlexisog_2_singular(&res2, A, len);
		uint32_t iszero[CYCLE_LENGTH];
		// fp2_print(bundleK[1].x.list[13]);
		// printf("\n");
		// fp2_print(bundleK[1].z.list[13]);
		// fflush(stdout);
		bundlefp2_is_zero_mask(iszero, &(bundleK[1].x), len);
		bundleec_point_select(B, &res1, &res2, iszero, len);
		return;
	}
	int j;
	int d = ((int)TORSION_ODD_PRIMES[i] - 1) / 2;	// Here, l = 2d + 1

	bundlefp2_t By, Bz, constant_d_edwards, tmp_a, tmp_d;

	bundlefp2_copy(&By, &bundleK[0].x, len);
	bundlefp2_copy(&Bz, &bundleK[0].z, len);

	for (j = 1; j < d; j++)
	{
		bundlefp2_mul(&By, &By, &bundleK[j].x, len);
		bundlefp2_mul(&Bz, &Bz, &bundleK[j].z, len);
	};

	// Mapping Montgomery curve coefficients into Twisted Edwards form
	bundlefp2_sub(&constant_d_edwards, &A.x, &A.z, len);
	bundlefp2_copy(&tmp_a, &A.x, len);
	bundlefp2_copy(&tmp_d, &constant_d_edwards, len);

	// left-to-right method for computing a^l and d^l
	for (j = 1; j < (int)p_plus_minus_bitlength[i]; j++)
	{
		bundlefp2_sqr(&tmp_a, &tmp_a, len);
		bundlefp2_sqr(&tmp_d, &tmp_d, len);
		if( ( ((int)TORSION_ODD_PRIMES[i] >> ((int)p_plus_minus_bitlength[i] - j - 1)) & 1 ) != 0 )
		{
			bundlefp2_mul(&tmp_a, &tmp_a, &A.x, len);
			bundlefp2_mul(&tmp_d, &tmp_d, &constant_d_edwards, len);
		};
	};

	// raising to 8-th power
	for (j = 0; j < 3; j++)
	{
		bundlefp2_sqr(&By, &By, len);
		bundlefp2_sqr(&Bz, &Bz, len);
	};

	// Mapping Twisted Edwards curve coefficients into Montgomery form
	bundlefp2_mul(&(B->x), &tmp_a, &Bz, len);
	bundlefp2_mul(&(B->z), &tmp_d, &By, len);
	bundlefp2_sub(&(B->z), &(B->x), &(B->z), len);
}

// -------------------------------------------------------------------------
// -------------------------------------------------------------------------
//  Isogeny construction (xISOG) used in velu SQRT

void bundlexisog_s(bundleec_point_t* B, uint64_t const i, bundleec_point_t const A, int len)
{
	// =================================================================================
	assert(TORSION_ODD_PRIMES[i] > gap);     // Ensuring velusqrt is used for l_i > gap
	bundlesI = sizeI[i];          // size of I
	bundlesJ = sizeJ[i];          // size of J
	bundlesK = sizeK[i];          // size of K

	assert(bundlesI >= bundlesJ);       // Ensuring #I >= #J
	assert(bundlesK >= 0);         // Recall, L is a prime and therefore it must be that #K > 0
	assert(bundlesJ > 1);         // ensuring sI >= sJ > 1
	// =================================================================================
	
	// We require the curve coefficient A = A'/C ... well, a multiple of these ones
	bundlefp2_t Ap;
	bundlefp2_add(&Ap, &A.x, &A.x, len);	// 2A' + 4C
	bundlefp2_sub(&Ap, &Ap, &A.z, len);	// 2A'
	bundlefp2_add(&Ap, &Ap, &Ap, len);	// 4A'

	bundlefp2_t ADD_SQUARED[sJ_max],	// (Xj + Zj)^2
	   SUB_SQUARED[sJ_max];	// (Xj - Zj)^2

	int j;
	// Next loop precompute some variables to be used in the reaminder of xisog
	for (j = 0; j < bundlesJ; j++)
	{
		bundlefp2_sub(&SUB_SQUARED[j], &bundleJ[j].x, &bundleJ[j].z, len);		// (Xj - Zj)
		bundlefp2_sqr(&SUB_SQUARED[j], &SUB_SQUARED[j], len);		// (Xj - Zj)^2
		bundlefp2_sub(&ADD_SQUARED[j], &SUB_SQUARED[j], &bundleXZJ4[j], len);	// (Xj + Zj)^2
	};

	//  --------------------------------------------------------------------------------------------------
	//                   ~~~~~~~~
	//                    |    | 
	// Computing E_J(W) = |    | [ F0(W, x([j]P)) * alpha^2 + F1(W, x([j]P)) * alpha + F2(W, x([j]P)) ]
	//                    j in J 
	// In order to avoid costly inverse computations in fp, we are gonna work with projective coordinates
	// In particular, for a degree-l isogeny construction, we need alpha = 1 and alpha = -1

	//fp2_t EJ_0[sJ][3],	// quadratic factors of one polynomial to be used in a resultant 
	//   EJ_1[sJ][3];	// quadratic factors of one polynomial to be used in a resultant

	// Next loop computes all the quadratic factors of EJ_0 and EJ_1
	bundlefp2_t t1;
	for (j = 0; j < bundlesJ; j++)
	{
		// Each SUB_SQUARED[j] and ADD_SQUARED[j] should be multiplied by C
		bundlefp2_mul(&bundleEJ_1[j][0], &ADD_SQUARED[j], &A.z, len);
		bundlefp2_mul(&bundleEJ_0[j][0], &SUB_SQUARED[j], &A.z, len);
		// We require the double of tadd and tsub
		bundlefp2_add(&bundleEJ_0[j][1], &bundleEJ_1[j][0], &bundleEJ_1[j][0], len);
		bundlefp2_add(&bundleEJ_1[j][1], &bundleEJ_0[j][0], &bundleEJ_0[j][0], len);

		bundlefp2_mul(&t1, &bundleXZJ4[j], &Ap, len);			// A' *(-4*Xj*Zj)

		// Case alpha = 1
		bundlefp2_sub(&bundleEJ_0[j][1], &t1, &bundleEJ_0[j][1], len);
		bundlefp2_copy(&bundleEJ_0[j][2], &bundleEJ_0[j][0], len);		// E_[0,j} is a palindrome
		
		// Case alpha = -1
		bundlefp2_sub(&bundleEJ_1[j][1], &bundleEJ_1[j][1], &t1, len);
		bundlefp2_copy(&bundleEJ_1[j][2], &bundleEJ_1[j][0], len);		// E_{1,j} is a palindrome
	};

	// ---------------------------------------------------------------------
	// The faster way for multiplying is using a divide-and-conquer approach
	
	// selfreciprocal product tree of EJ_0 (we only require the root)
	bundleproduct_tree_selfreciprocal_LENFeq3(bundleptree_EJ, bundledeg_ptree_EJ, 0, bundleEJ_0, bundlesJ, len);
	assert( bundledeg_ptree_EJ[0] == (2*bundlesJ) );
	if (!scaled)
	{
		// (unscaled) remainder tree approach
		bundlemultieval_unscaled(bundleleaves, bundleptree_EJ[0], 2*bundlesJ + 1, bundlertree_hI, (const bundlefp2_t*)bundlertree_A, bundleptree_hI, bundledeg_ptree_hI, 0, bundlesI, len);
	}
	else
	{
		// scaled remainder tree approach
		bundlefp2_t G[sI_max], G_rev[sI_max];
		bundlepoly_redc(G, bundleptree_EJ[0], 2*bundlesJ + 1, bundleptree_hI[0], bundlesI + 1, bundleR0, bundleA0, len);
		for (j = 0; j < bundlesI; j++)
			bundlefp2_copy(&G_rev[j], &G[bundlesI - 1 - j], len);

		bundlepoly_mul_middle(G_rev, G_rev, bundlesI, bundleR0, bundlesI, len);
		for (j = 0; j < bundlesI; j++)
			bundlefp2_copy(&G[j], &G_rev[bundlesI - 1 - j], len);

		bundlemultieval_scaled(bundleleaves, G, bundleptree_hI, bundledeg_ptree_hI, 0, bundlesI, len);
	};
	bundleclear_tree(bundleptree_EJ, 0, bundlesJ);
	// Finally, we must multiply the leaves of the outpur of remainders
	bundlefp2_t r0;
	bundleproduct(&r0, (const bundlefp2_t*)bundleleaves, bundlesI, len);

	// selfreciprocal product tree of EJ_1 (we only require the root)
	bundleproduct_tree_selfreciprocal_LENFeq3(bundleptree_EJ, bundledeg_ptree_EJ, 0, bundleEJ_1, bundlesJ, len);
	assert( bundledeg_ptree_EJ[0] == (2*bundlesJ) );
	if (!scaled)
	{
		// (unscaled) remainder tree approach
		bundlemultieval_unscaled(bundleleaves, bundleptree_EJ[0], 2*bundlesJ + 1, bundlertree_hI, (const bundlefp2_t*)bundlertree_A, bundleptree_hI, bundledeg_ptree_hI, 0, bundlesI, len);
	}
	else
	{
		// scaled remainder tree approach
		bundlefp2_t G[sI_max], G_rev[sI_max];
		bundlepoly_redc(G, bundleptree_EJ[0], 2*bundlesJ + 1, bundleptree_hI[0], bundlesI + 1, bundleR0, bundleA0, len);
		for (j = 0; j < bundlesI; j++)
			bundlefp2_copy(&G_rev[j], &G[bundlesI - 1 - j], len);

		bundlepoly_mul_middle(G_rev, G_rev, bundlesI, bundleR0, bundlesI, len);
		for (j = 0; j < bundlesI; j++)
			bundlefp2_copy(&G[j], &G_rev[bundlesI - 1 - j], len);

		bundlemultieval_scaled(bundleleaves, G, bundleptree_hI, bundledeg_ptree_hI, 0, bundlesI, len);
	};
	bundleclear_tree(bundleptree_EJ, 0, bundlesJ);
	// Finally, we must multiply the leaves of the outpur of remainders
	bundlefp2_t r1;
	bundleproduct(&r1, (const bundlefp2_t*)bundleleaves, bundlesI, len);

	// -------------------------------
	// Sometimes the public value sK is equal to zero,
	// Thus for avoing runtime error we add one when sK =0
	bundlefp2_t hK_0[sK_max + 1], hK_1[sK_max + 1], hk_0, hk_1;
	for (j = 0; j < bundlesK; j++)
	{
		bundlefp2_sub(&hK_0[j], &bundleK[j].z, &bundleK[j].x, len);
		bundlefp2_add(&hK_1[j], &bundleK[j].z, &bundleK[j].x, len);
	};

	// hk_0 <- use product to mulitiply all the elements in hK_0
	bundleproduct(&hk_0, (const bundlefp2_t*)hK_0, bundlesK, len);
	// hk_1 <- use product to mulitiply all the elements in hK_1
	bundleproduct(&hk_1, (const bundlefp2_t*)hK_1, bundlesK, len);
	
	// --------------------------------------------------------------
	// Now, we have all the ingredients for computing the image curve
	bundlefp2_t A24, A24m,
	   t24, t24m;	// <---- JORGE creo que podemos omitir estas variables, se usan cuando ya no se requiren los valores de la entrada A (podemos cambiar estos t's por B[0] y B[1]

	bundlefp2_copy(&A24, &A.x, len);			// A' + 2C
	bundlefp2_sub(&A24m, &A.x, &A.z, len);		// A' - 2C
	bundlefp2_copy(&Ap, &A24m, len);

	// left-to-right method for computing (A' + 2C)^l and (A' - 2C)^l
	for (j = 1; j < (int)p_plus_minus_bitlength[i]; j++)
	{
		bundlefp2_sqr(&A24, &A24, len);
		bundlefp2_sqr(&A24m, &A24m, len);
		if( ( ((int)TORSION_ODD_PRIMES[i] >> ((int)p_plus_minus_bitlength[i] - j - 1)) & 1 ) != 0 )
		{
			bundlefp2_mul(&A24, &A24, &A.x, len);
			bundlefp2_mul(&A24m, &A24m, &Ap, len);
		};
	};

	bundlefp2_mul(&t24m, &hk_1, &r1, len);			// output of algorithm 2 with alpha =-1 and without the demoninator
	bundlefp2_sqr(&t24m, &t24m, len);			// raised at 2
	bundlefp2_sqr(&t24m, &t24m, len);			// raised at 4
	bundlefp2_sqr(&t24m, &t24m, len);			// raised at 8

	bundlefp2_mul(&t24, &hk_0, &r0, len);			// output of algorithm 2 with alpha = 1 and without the demoninator 
	bundlefp2_sqr(&t24, &t24, len);			// raised at 2
	bundlefp2_sqr(&t24, &t24, len);			// raised at 4
	bundlefp2_sqr(&t24, &t24, len);			// raised at 8

	bundlefp2_mul(&A24, &A24, &t24m, len);
	bundlefp2_mul(&A24m, &A24m, &t24, len);

	// Now, we have d = (A24m / A24) where the image Montgomery cuve coefficient is
	//      B'   2*(1 + d)   2*(A24 + A24m)
	// B = ---- = --------- = --------------
	//      C      (1 - d)     (A24 - A24m)
	// However, we required B' + 2C = 4*A24 and 4C = 4 * (A24 - A24m)

	bundlefp2_sub(&t24m, &A24, &A24m, len);		//   (A24 - A24m)
	bundlefp2_add(&t24m, &t24m, &t24m, len);		// 2*(A24 - A24m)
	bundlefp2_add(&t24m, &t24m, &t24m, len);		// 4*(A24 - A24m)

	bundlefp2_add(&t24, &A24, &A24, len);			// 2 * A24
	bundlefp2_add(&t24, &t24, &t24, len);			// 4 * A24

	bundlefp2_copy(&(B->x), &t24, len);
	bundlefp2_copy(&(B->z), &t24m, len);
}
