// SPDX-FileCopyrightText: Copyright 2023 the SQIsign team. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
 * This file is derived from xeval.c in the SQIsign (version 1.0) 
 * project (https://github.com/SQIsign/the-sqisign/tree/nist-v1),
 * which is licensed under the Apache-2.0 license.
 *
 * Modifications made:
 *   - Deleted some unused functions
 *   - Changed the data structure to SoA
 */

#include "bundle_isog.h"
#include "bundle_ec.h"
#include <assert.h>

// -----------------------------------------------------------------------------------------
// -----------------------------------------------------------------------------------------
// Traditional isogeny evaluation (xEVAL)

// CrissCross procedure as described in Hisil and Costello paper
void bundleCrissCross(bundlefp2_t *r0, bundlefp2_t *r1, bundlefp2_t const alpha, bundlefp2_t const beta, bundlefp2_t const gamma, bundlefp2_t const delta, int len)
{
	bundlefp2_t t_1, t_2;

	bundlefp2_mul(&t_1, &alpha, &delta, len);
    	bundlefp2_mul(&t_2, &beta, &gamma, len);
	bundlefp2_add(&*r0, &t_1, &t_2, len);
	bundlefp2_sub(&*r1, &t_1, &t_2, len);
}

// Degree-2 isogeny evaluation with kenerl generated by P != (0, 0)
void bundlexeval_2(bundleec_point_t* R, bundleec_point_t const Q, int len)
{
	// for (int i = 0; i < len; i++)
	// {
	// 	assert(!fp2_is_zero(&(Q.x.list[i])));
	// }
	bundlefp2_t t0, t1, t2;

	bundlefp2_add(&t0, &Q.x, &Q.z, len);
	bundlefp2_sub(&t1, &Q.x, &Q.z, len);
	bundlefp2_mul(&t2, &bundleK[0].x, &t1, len);
	bundlefp2_mul(&t1, &bundleK[0].z, &t0, len);
	bundlefp2_add(&t0, &t2, &t1, len);
	bundlefp2_sub(&t1, &t2, &t1, len);
	bundlefp2_mul(&(R->x), &Q.x, &t0, len);
	bundlefp2_mul(&(R->z), &Q.z, &t1, len);
}

void bundlexeval_2_singular(bundleec_point_t *R, const bundleec_point_t Q, int len)
{
    bundlefp2_t t0, t1;
    bundlefp2_mul(&t0, &Q.x, &Q.z, len);
    bundlefp2_mul(&t1, &bundleK[2].x, &Q.z, len);
    bundlefp2_add(&t1, &t1, &Q.x, len);
    bundlefp2_mul(&t1, &t1, &Q.x, len);
    bundlefp2_sqr(&(R->x), &Q.z, len);
    bundlefp2_add(&(R->x), &(R->x), &t1, len);
    bundlefp2_mul(&(R->z), &t0, &bundleK[2].z, len);
}

// Isogeny evaluation on Montgomery curves
// Recall: K has been computed in Twisted Edwards model and none extra additions are required.
void bundlexeval_t(bundleec_point_t* Q, uint64_t const i, bundleec_point_t const P, int len)
{
	if (TORSION_ODD_PRIMES[i] == 2)
	{
		bundleec_point_t res1, res2;
		bundlexeval_2(&res1, P, len);
		bundlexeval_2_singular(&res2, P, len);
		uint32_t iszero[CYCLE_LENGTH];
		bundlefp2_is_zero_mask(iszero, &(bundleK[1].x), len);
		bundleec_point_select(Q, &res1, &res2, iszero, len);
		return;
	}
	int j;
	int d = ((int)TORSION_ODD_PRIMES[i] - 1) / 2;	// Here, l = 2d + 1

	bundlefp2_t R0, R1, S0, S1, T0, T1;
	bundlefp2_add(&S0, &P.x, &P.z, len);
	bundlefp2_sub(&S1, &P.x, &P.z, len);

	bundleCrissCross(&R0, &R1, bundleK[0].z, bundleK[0].x, S0, S1, len);
	for (j = 1; j < d; j++)
	{
		bundleCrissCross(&T0, &T1, bundleK[j].z, bundleK[j].x, S0, S1, len);
		bundlefp2_mul(&R0, &T0, &R0, len);
		bundlefp2_mul(&R1, &T1, &R1, len);
	};

	bundlefp2_sqr(&R0, &R0, len);
	bundlefp2_sqr(&R1, &R1, len);

	bundlefp2_mul(&(Q->x), &P.x, &R0, len);
	bundlefp2_mul(&(Q->z), &P.z, &R1, len);
}

// -----------------------------------------------------------------------------------------
// -----------------------------------------------------------------------------------------
// Isogeny evaluation (xEVAL) used in velu SQRT

void bundlexeval_s(bundleec_point_t* Q, uint64_t const i, bundleec_point_t const P, bundleec_point_t const A, int len)
{
	// =================================================================================
	assert(TORSION_ODD_PRIMES[i] > gap);     // Ensuring velusqrt is used for l_i > gap
	bundlesI = sizeI[i];          // size of I
	bundlesJ = sizeJ[i];          // size of J
	bundlesK = sizeK[i];          // size of K

	assert(bundlesI >= bundlesJ);       // Ensuring #I >= #J
	assert(bundlesK >= 0);        // Recall, it must be that #K >= 0
	assert(bundlesJ > 1);         // ensuring sI >= sJ > 1
	// =================================================================================

	// We require the curve coefficient A = A'/C ... well, a multiple of these ones
	bundlefp2_t Ap;
	bundlefp2_add(&Ap, &A.x, &A.x, len); // 2A' + 4C
	bundlefp2_sub(&Ap, &Ap, &A.z, len);   // 2A'
	bundlefp2_add(&Ap, &Ap, &Ap, len);     // 4A'

	//  --------------------------------------------------------------------------------------------------
	//                   ~~~~~~~~
	//                    |    | 
	// Computing E_J(W) = |    | [ F0(W, x([j]P)) * alpha^2 + F1(W, x([j]P)) * alpha + F2(W, x([j]P)) ]
	//                    j in J 
	// In order to avoid costly inverse computations in fp, we are gonna work with projective coordinates
	// In particular, for a degree-l isogeny construction, we need alpha = X/Z and alpha = Z/X (i.e., 1/alpha)

	//fp2_t EJ_0[sJ][3]; // EJ_0[j][2] factors of one polynomial to be used in a resultant 

	bundlefp2_t XZ_add, XZj_add,
	   XZ_sub, XZj_sub,
	   AXZ2,
	   CXZ2,
	   CX2Z2,
	   t1, t2;

	bundlefp2_add(&XZ_add, &P.x, &P.z, len);	// X + Z
	bundlefp2_sub(&XZ_sub, &P.x, &P.z, len);	// X - Z

	bundlefp2_mul(&AXZ2, &P.x, &P.z, len);	// X * Z
	bundlefp2_sqr(&t1, &P.x, len);		// X ^ 2
	bundlefp2_sqr(&t2, &P.z, len);		// Z ^ 2

	bundlefp2_add(&CX2Z2, &t1, &t2, len);		//      X^2 + Z^2
	bundlefp2_mul(&CX2Z2, &CX2Z2, &A.z, len);	// C * (X^2 + Z^2)

	bundlefp2_add(&AXZ2, &AXZ2, &AXZ2, len);	//       2 * (X * Z)
	bundlefp2_mul(&CXZ2, &AXZ2, &A.z, len);	// C  * [2 * (X * Z)]
	bundlefp2_mul(&AXZ2, &AXZ2, &Ap, len);		// A' * [2 * (X * Z)]

	int j;
	for (j = 0; j < bundlesJ; j++)
	{
		bundlefp2_add(&XZj_add, &bundleJ[j].x, &bundleJ[j].z, len);		// Xj + Zj
		bundlefp2_sub(&XZj_sub, &bundleJ[j].x, &bundleJ[j].z, len);		// Xj - Zj

		bundlefp2_mul(&t1, &XZ_sub, &XZj_add, len);			// (X - Z) * (Xj + Zj)
		bundlefp2_mul(&t2, &XZ_add, &XZj_sub, len);			// (X + Z) * (Xj - Zj)

		// ...................................
		// Computing the quadratic coefficient
		bundlefp2_sub(&bundleEJ_0[j][2], &t1, &t2, len);			//       2 * [(X*Zj) - (Z*Xj)]
		bundlefp2_sqr(&bundleEJ_0[j][2], &bundleEJ_0[j][2], len);			//     ( 2 * [(X*Zj) - (Z*Xj)] )^2
		bundlefp2_mul(&bundleEJ_0[j][2], &A.z, &bundleEJ_0[j][2], len);		// C * ( 2 * [(X*Zj) - (Z*Xj)] )^2

		// ..................................
		// Computing the constant coefficient
		bundlefp2_add(&bundleEJ_0[j][0], &t1, &t2, len);			//       2 * [(X*Xj) - (Z*Zj)]
		bundlefp2_sqr(&bundleEJ_0[j][0], &bundleEJ_0[j][0], len);			//     ( 2 * [(X*Xj) - (Z*Zj)] )^2
		bundlefp2_mul(&bundleEJ_0[j][0], &A.z, &bundleEJ_0[j][0], len);		// C * ( 2 * [(X*Xj) - (Z*Zj)] )^2

		// ................................
		// Computing the linear coefficient
	
		// C * [ (-2*Xj*Zj)*(alpha^2 + 1) + (-2*alpha)*(Xj^2 + Zj^2)] + [A' * (-2*Xj*Zj) * (2*X*Z)] where alpha = X/Z
		bundlefp2_add(&t1, &bundleJ[j].x, &bundleJ[j].z, len);			//      (Xj + Zj)
		bundlefp2_sqr(&t1, &t1, len);					//      (Xj + Zj)^2
		bundlefp2_add(&t1, &t1, &t1, len);				//  2 * (Xj + Zj)^2
		bundlefp2_add(&t1, &t1, &bundleXZJ4[j], len);			//  2 * (Xj + Zj)^2 - (4*Xj*Zj) := 2 * (Xj^2 + Zj^2)
		bundlefp2_mul(&t1, &t1, &CXZ2, len);				// [2 * (Xj^2 + Zj^2)] * (2 * [ C * (X * Z)])

		bundlefp2_mul(&t2, &CX2Z2, &bundleXZJ4[j], len);			// [C * (X^2 + Z^2)] * (-4 * Xj * Zj)
		bundlefp2_sub(&t1, &t2, &t1, len);				// [C * (X^2 + Z^2)] * (-4 * Xj * Zj) - [2 * (Xj^2 + Zj^2)] * (2 * [ C * (X * Z)])

		bundlefp2_mul(&t2, &AXZ2, &bundleXZJ4[j], len);			// (2 * [A' * (X * Z)]) * (-4 * Xj * Zj)
		bundlefp2_add(&bundleEJ_0[j][1], &t1, &t2, len);			// This is our desired equation but multiplied by 2
		bundlefp2_add(&bundleEJ_0[j][1], &bundleEJ_0[j][1], &bundleEJ_0[j][1], len);	// This is our desired equation but multiplied by 4
	};

        // ---------------------------------------------------------------------
        // The faster way for multiplying is using a divide-and-conquer approach

	// product tree of EJ_0 (we only require the root)
	bundleproduct_tree_LENFeq3(bundleptree_EJ, bundledeg_ptree_EJ, 0, bundleEJ_0, bundlesJ, len);
	assert( bundledeg_ptree_EJ[0] == (2*bundlesJ) );
	if (!scaled)
	{
		// unscaled remainder tree approach
		bundlemultieval_unscaled(bundleleaves, bundleptree_EJ[0], 2*bundlesJ + 1, bundlertree_hI, (const bundlefp2_t*)bundlertree_A, bundleptree_hI, bundledeg_ptree_hI, 0, bundlesI, len);
	}
	else
	{
		// scaled remainder tree approach
		bundlefp2_t G[sI_max], G_rev[sI_max];
		bundlepoly_redc(G, bundleptree_EJ[0], 2*bundlesJ + 1, bundleptree_hI[0], bundlesI + 1, bundleR0, bundleA0, len);
		for (j = 0; j < bundlesI; j++)
			bundlefp2_copy(&G_rev[j], &G[bundlesI - 1 - j], len);

		bundlepoly_mul_middle(G_rev, G_rev, bundlesI, bundleR0, bundlesI, len);
		for (j = 0; j < bundlesI; j++)
			bundlefp2_copy(&G[j], &G_rev[bundlesI - 1 - j], len);

		bundlemultieval_scaled(bundleleaves, G, bundleptree_hI, bundledeg_ptree_hI, 0, bundlesI, len);
        };

	// Finally, we must multiply the leaves of the outpur of remainders
	bundlefp2_t r0;
	bundleproduct(&r0, (const bundlefp2_t*)bundleleaves, bundlesI, len);
	// EJ_1 is just reverting the ordering in the coefficients of EJ_0
	for (j = 0; j < bundlesJ; j++){
		bundlefp2_copy(&t1, &bundleptree_EJ[0][j], len);
		bundlefp2_copy(&bundleptree_EJ[0][j], &bundleptree_EJ[0][2*bundlesJ - j], len);
		bundlefp2_copy(&bundleptree_EJ[0][2*bundlesJ - j], &t1, len);
	}

	if (!scaled)
	{
		// unscaled remainder tree approach
		bundlemultieval_unscaled(bundleleaves, bundleptree_EJ[0], 2*bundlesJ + 1, bundlertree_hI, (const bundlefp2_t*)bundlertree_A, bundleptree_hI, bundledeg_ptree_hI, 0, bundlesI, len);
	}
	else
	{
		// scaled remainder tree approach
		bundlefp2_t G[sI_max], G_rev[sI_max];
		bundlepoly_redc(G, bundleptree_EJ[0], 2*bundlesJ + 1, bundleptree_hI[0], bundlesI + 1, bundleR0, bundleA0, len);
		for (j = 0; j < bundlesI; j++)
			bundlefp2_copy(&G_rev[j], &G[bundlesI - 1 - j], len);

		bundlepoly_mul_middle(G_rev, G_rev, bundlesI, bundleR0, bundlesI, len);
		for (j = 0; j < bundlesI; j++)
			bundlefp2_copy(&G[j], &G_rev[bundlesI - 1 - j], len);

		bundlemultieval_scaled(bundleleaves, G, bundleptree_hI, bundledeg_ptree_hI, 0, bundlesI, len);
        };
	bundleclear_tree(bundleptree_EJ, 0, bundlesJ);
	// Finally, we must multiply the leaves of the outpur of remainders
	bundlefp2_t r1;
	bundleproduct(&r1, (const bundlefp2_t*)bundleleaves, bundlesI, len);

	// -------------------------------
	// Sometimes the public value sK is equal to zero,
	// Thus for avoing runtime error we add one when sK =0
	bundlefp2_t hK_0[sK_max + 1], hK_1[sK_max + 1], hk_0, hk_1;
	for (j = 0; j < bundlesK; j++)
	{
		bundlefp2_add(&XZj_add, &bundleK[j].x, &bundleK[j].z, len);	// Xk + Zk
		bundlefp2_sub(&XZj_sub, &bundleK[j].x, &bundleK[j].z, len);	// Xk - Zk
		bundlefp2_mul(&t1, &XZ_sub, &XZj_add, len);		// (X - Z) * (Xk + Zk)
		bundlefp2_mul(&t2, &XZ_add, &XZj_sub, len);		// (X + Z) * (Xk - Zk)

		// Case alpha = X/Z
		bundlefp2_sub(&hK_0[j], &t1, &t2, len);		// 2 * [(X*Zk) - (Z*Xk)]

		// Case 1/alpha = Z/X
		bundlefp2_add(&hK_1[j], &t1, &t2, len);		// 2 * [(X*Xk) - (Z*Zk)]
	};

	// hk_0 <- use product to mulitiply all the elements in hK_0
	bundleproduct(&hk_0, (const bundlefp2_t*)hK_0, bundlesK, len);
	// hk_1 <- use product to mulitiply all the elements in hK_1
	bundleproduct(&hk_1, (const bundlefp2_t*)hK_1, bundlesK, len);

	// ---------------------------------------------------------------------------------
	// Now, unifying all the computations
	bundlefp2_mul(&t1, &hk_1, &r1, len);				// output of algorithm 2 with 1/alpha = Z/X and without the demoninator
	bundlefp2_sqr(&t1, &t1, len);
	bundlefp2_mul(&(Q->x), &t1, &P.x, len);

	bundlefp2_mul(&t2, &hk_0, &r0, len);				// output of algorithm 2 with alpha = X/Z and without the demoninator
	bundlefp2_sqr(&t2, &t2, len);
	bundlefp2_mul(&(Q->z), &t2, &P.z, len);
}
