#ifndef ORIGAMI_PARAMS_H
#define ORIGAMI_PARAMS_H

#define ORIGAMI_PARAM_ID 0x4F4D0100u
#define ORIGAMI_SECURITY_BITS 256
#define ORIGAMI_CLASSICAL_BITS 256
#define ORIGAMI_QUANTUM_BITS 128
#define ORIGAMI_MU_RED 81
#define ORIGAMI_MAIN_ZONES 6

#define ORIGAMI_q 16

#define ORIGAMI_SEED_SK_BYTES 32
#define ORIGAMI_SEED_PK_BYTES 32
#define ORIGAMI_SALT_BYTES 32
#define ORIGAMI_RPK_BYTES 14932

#define ORIGAMI_MAIN_K 5
#define ORIGAMI_MAIN_V 3
#define ORIGAMI_MAIN_O 5
#define ORIGAMI_MAIN_M 20
#define ORIGAMI_MAIN_L 2
#define ORIGAMI_MAIN_A 20
#define ORIGAMI_MAIN_B 80
#define ORIGAMI_MAIN_DELTA 0

#define ORIGAMI_TAIL_K 1
#define ORIGAMI_TAIL_V 0
#define ORIGAMI_TAIL_O 2
#define ORIGAMI_TAIL_M 2
#define ORIGAMI_TAIL_L 2
#define ORIGAMI_TAIL_A 0
#define ORIGAMI_TAIL_B 8
#define ORIGAMI_TAIL_DELTA 0

#endif