/*
 * approx_log.h -- SHUTTLE SamplerU base-2 logarithm, integer-only CT.
 *
 * In-tree wrapper around the byte-frozen, audited kernel body in
 * tools/approx_log_poly.h (generated by tools/gen_approx_log_poly.py;
 * verified by tools/verify_approx_log_poly.c against a __float128
 * reference).  Re-exports the entry points under the project namespace so
 * the SamplerU / R caller never includes the raw tools header.  Shared
 * VERBATIM across all three parameter sets (SHUTTLE-128/256/512) -- no
 * per-set table, no per-set #if; log2(b) on [1,2) is
 * parameter-set-independent.
 *
 * ============================ WHAT IT COMPUTES
 * ============================
 *
 * SamplerU writes a uniform u in (0,1] as u = 2^-a * b, where the integer
 * exponent a >= 1 is the leading-zero count of the exponent stream rho_a and
 * the mantissa b = 1 + m/2^kappa_b lies in [1,2) (kappa_b = 57).  The
 * R-transition test only COMPARES log u, so a base-2 additive budget
 * eta_log <= 2^-57 is enough.  shuttle_log2_frac_q62(j, x_q64) returns the
 * FRACTIONAL part
 *
 *     frac = round(2^62 * log2(b))   as a Q62 SIGNED int64,
 *
 * and the caller forms log2(u) = -a + frac*2^-62.  Working in base-2 (NOT
 * natural log) makes the exponent term exact: log2(2^-a) = -a is a pure
 * integer subtraction with ZERO stored-constant error. The SamplerU R
 * caller restores the natural-log test variable with ONE multiply u_test =
 * (2 r^2 ln2) * log2(u),   2 r^2 ln2 = 943546.5995372256..., which is NOT
 * done here -- this module returns log2 only.
 *
 * ===================== CALLER-SIDE ARGUMENT DERIVATION
 * ====================
 *
 * This module does NOT compute (j, x) from m -- that MSB-first derivation
 * is SamplerU's responsibility.  The contract this signature
 * assumes (g = SHUTTLE_LOG_POLY_G = 2, kappa_b = 57): j     = floor(m /
 * 2^(kappa_b - g))   = top g=2 bits of the mantissa
 *             -> segment index, beta_j = 1 + j/2^g in {1, 1.25, 1.5, 1.75}
 *     x_q64 = (m mod 2^(kappa_b - g)) << (64 - (kappa_b - g))
 *             = (low 55 mantissa bits) << 9, a Q64 fraction in [0,1)
 * Constraints the caller must respect: g <= kappa_b and kappa_b - g <= 64;
 * monotonicity holds for kappa_b <= 61 (kappa_b = 57 has > 3 bits margin).
 *
 * =========================== FIXED-POINT Q-FORMAT
 * =========================
 *
 * Top-g-bit SEGMENTATION (g=2 -> 4 segments), per-segment degree-13
 * minimax polynomial, Q62 signed coefficients in kShuttleLogPoly[4][14]
 * (448 bytes). The endpoint-ratio of log on [beta, 2 beta) is the only
 * thing that drives minimax convergence, so segmentation (ratio 2 ->
 * 1+2^-g) is the real lever; the segment offset log2(beta_j) is ABSORBED
 * into c_{j,0} (no extra add, no reciprocal table).  x = (b - beta_j)*2^g
 * in [0,1) is supplied as the Q64 multiplier x_q64.  Evaluation: Horner
 * k=13..0 in an __int128 accumulator, acc <- c_k + shuttle_log_mulhi(acc,
 * x_q64), where shuttle_log_mulhi is the ROUNDED high-half
 * ((a*x)+2^63)>>64 -- round-to-nearest, NOT truncate; the rounding is
 * unbiased and halves the Horner error accumulation, and it is part of the
 * FROZEN semantics (it changes the bits).  128-bit overflow is safe:
 * per-segment sum|c_{j,k}| < 1 so |acc| <~ 2^62, *x < 2^64 gives < 2^126.1
 * (peak ~2^122.5, ~4.5-bit margin)
 * -- this is why single-segment g=0 (sum|c_k| ~ 5.3) is rejected.
 *
 * The c_{0,0} = 0 PIN (segment-0 Remez forced with basis x^1..x^d) makes
 * shuttle_log2_frac_q62(0, 0) == 0 bit-exactly, i.e. ApproxLog(0,1) = 0.
 *
 * ============================ CONSTANT-TIME
 * =========================
 *
 * The segment row is fetched by a FULL-TABLE scan:
 * shuttle_log_fetch_row(sel,c) zeroes c then ORs every segment's row
 * masked by shuttle_log_eqmask(jj, sel) (all-ones iff jj==sel via pure
 * arithmetic z=a^b; nz=(z|(~z+1))>>63; nz-1). It touches all 4x14 entries
 * regardless of the secret sel, so the load address is DATA-INDEPENDENT --
 * no secret-indexed memory, no branch, no cmov. -O2/-O3 may refold the
 * eqmask into cmp+sbb/sete, but the flags only feed ARITHMETIC, never a
 * conditional jump (gcc/clang x O0/O2/O3 disasm audited). Scan cost =
 * 2^g(d+1) = 4*14 = 56 mask AND/OR ops, decoupled from the Horner
 * dependency chain (issued early).  NO division, NO float.
 *
 * ====================== PRECISION vs SECURITY GATE ======================
 *
 * Measured worst-case ABSOLUTE error: 2^-59.45 (generator) / 2^-59.37
 * (independent __float128 verifier, worst j=0 x~0.62), vs gate eta_log <=
 * 2^-57
 * -- ~2.4 bits margin.  Strictly increasing at the kappa_b=57 mantissa
 * grid (cross-segment wobble <= 2 ULP = 2^-61, non-binding).
 *
 * ============================ BATCH WIRING (lane-equivalence)
 * ==========================
 *
 * shuttle_log2_frac_q62_x2 evaluates 2 INDEPENDENT (j, x_q64) at once:
 * each table entry is loaded once and shared by both lanes, the two Horner
 * chains interleave to hide multiply latency.  CRITICAL: it FUSES the
 * per-column scan into each Horner step (only 2*2^g = 8 eqmasks + 2
 * accumulators live) -- do NOT materialise both full coefficient rows
 * first (that spills and degraded to 167 cyc).  Verified BIT-IDENTICAL to
 * two scalar calls.  Wire it in SamplerU on the ascending-j IRS loop where
 * two transitions (coefficients j, j+1) are available; fall back to scalar
 * on
 * the odd tail or a c_j=0 gap.  The reference *_x2 form IS the bit-exact
 * spec for the AVX2/AVX512 path.
 */
#ifndef SHUTTLE_APPROX_LOG_H
#define SHUTTLE_APPROX_LOG_H

#include <stdint.h>

/*
 * The frozen kernel uses GNU __int128 accumulators.  __int128 is a
 * GCC/Clang extension that ISO C does not support, so a strict -Wpedantic
 * build flags it. DOCUMENTED -Wpedantic exception: localise the
 * suppression to JUST the tools-header include (the byte-frozen autogen
 * body must not be edited).
 */
#if defined(__GNUC__) || defined(__clang__)
#    pragma GCC diagnostic push
#    pragma GCC diagnostic ignored "-Wpedantic"
#endif
#include "approx_log_poly.h" /* @@AUTOGEN-CONSUMER: kShuttleLogPoly[4][14], macros, \
                                      shuttle_log2_frac_q62{,_x2}, shuttle_log_mulhi,       \
                                      shuttle_log_eqmask, shuttle_log_fetch_row */
#if defined(__GNUC__) || defined(__clang__)
#    pragma GCC diagnostic pop
#endif

/*
 * ===================== CT-1 HARDENING (gather defense) =================
 *
 * The frozen kernel's full-table scan (shuttle_log_fetch_row and the fused
 * scan in shuttle_log2_frac_q62_x2, tools/approx_log_poly.h) is a
 * data-independent OR-mask sweep over kShuttleLogPoly[j][k].  It is
 * source-level constant-time -- the secret segment index `sel` feeds ONLY
 * the equality masks, never a load address; every call touches all
 * SEGMENTS*(DEGREE+1) entries.  But "source-level CT" is NOT the gate
 * (the constant-time policy: "do NOT rely on the compiler to preserve
 * constant-time").  Some compilers AUTO-VECTORIZE this contiguous masked
 * sweep into a SIMD GATHER: e.g.
 *
 *     clang -Os -march=skylake (and newer clang baselines under -mavx2)
 *
 * re-emits `vpgatherdq`/`vpgatherqq` over the *public* table base + a
 * *compile-time-constant* index vector (verified: gather base = .rodata
 * kShuttleLogPoly, index = constant column-stride vector; the secret `sel`
 * stays in the vpand mask).  The address is provably public, so this is a
 * BENIGN public-index vectorization -- NOT a secret-index leak.  But the
 * machine-code CT scanner (tools/ct_scan.py) cannot prove the index is
 * public, so it conservatively (and correctly, per the constant-time
 * policy) FLAGS any gather/scatter in a secret-handling object as a
 * VIOLATION.
 *
 * Fix: the SamplerU caller must use a scan whose table reads are real,
 * non-coalescable memory ops the vectorizer will NOT fold into a gather.
 * The frozen autogen body (tools/approx_log_poly.h) is byte-pinned and
 * must not be edited, so we OVERRIDE the two project-namespace entry
 * points HERE with gather-hardened twins.  They reuse the frozen
 * primitives shuttle_log_eqmask / shuttle_log_mulhi and the frozen table
 * kShuttleLogPoly with the IDENTICAL loop order, mask, Horner accumulation
 * and rounding -- so they are BIT-EXACT to the frozen kernel
 * (KAT-neutral). The ONLY difference is that the table is read through a
 * `volatile`- qualified pointer, which makes each access a side-effecting
 * memory op: C99 6.7.3 forbids the optimizer from coalescing it into a
 * gather (or eliding it), so NO compiler (gcc/clang x -O0..-O3,-Os) emits
 * a gather/scatter for the scan.  This is C99 + -Wpedantic clean -- it
 * uses NO GNU inline __asm__ (which warns under -Wpedantic and would break
 * the Reference -Werror gate); `volatile` is ISO C.
 *
 * Like the frozen kernel, the hardened twins use GNU __int128
 * accumulators, so this block reuses the SAME documented -Wpedantic
 * suppression.
 */
#if defined(__GNUC__) || defined(__clang__)
#    pragma GCC diagnostic push
#    pragma GCC diagnostic ignored "-Wpedantic"
#endif

#if defined(__GNUC__) || defined(__clang__)
#    define SHUTTLE_LOG_CT_INLINE \
        static inline __attribute__((always_inline))
#else
#    define SHUTTLE_LOG_CT_INLINE static inline
#endif

/* Gather-hardened twin of shuttle_log_fetch_row: the table is read through
 * a const-volatile pointer so the masked sweep stays a linear scan. */
SHUTTLE_LOG_CT_INLINE void shuttle_log_fetch_row_ct(
    uint32_t sel, int64_t c[SHUTTLE_LOG_POLY_DEGREE + 1])
{
    const volatile int64_t *t =
        (const volatile int64_t *)&kShuttleLogPoly[0][0];
    int k;
    uint32_t j;
    for (k = 0; k <= SHUTTLE_LOG_POLY_DEGREE; k++)
        c[k] = 0;
    for (j = 0; j < SHUTTLE_LOG_POLY_SEGMENTS; j++) {
        uint64_t m = shuttle_log_eqmask(j, sel); /* all-ones iff j==sel */
        for (k = 0; k <= SHUTTLE_LOG_POLY_DEGREE; k++)
            c[k] |=
                (int64_t)(m &
                          (uint64_t)t[(uint32_t)j *
                                          (SHUTTLE_LOG_POLY_DEGREE + 1) +
                                      (uint32_t)k]);
    }
}

/* Gather-hardened twin of shuttle_log2_frac_q62: identical Horner over the
 * hardened fetch (bit-exact; only the table-read instruction selection
 * differs). */
SHUTTLE_LOG_CT_INLINE int64_t shuttle_log2_frac_q62_ct(uint32_t j,
                                                       uint64_t x_q64)
{
    int64_t c[SHUTTLE_LOG_POLY_DEGREE + 1];
    __int128 acc;
    int k;
    shuttle_log_fetch_row_ct(j, c);
    acc = c[SHUTTLE_LOG_POLY_DEGREE];
    for (k = SHUTTLE_LOG_POLY_DEGREE - 1; k >= 0; k--)
        acc = (__int128)c[k] + (__int128)shuttle_log_mulhi(acc, x_q64);
    return (int64_t)acc;
}

/* Gather-hardened twin of shuttle_log2_frac_q62_x2: the fused per-column
 * scan reads the table through a const-volatile pointer.  Same loop order
 * / mask / accumulation as the frozen kernel -> bit-exact, KAT-neutral. */
SHUTTLE_LOG_CT_INLINE void shuttle_log2_frac_q62_x2_ct(
    const uint32_t sel[2], const uint64_t x_q64[2], int64_t out[2])
{
    const volatile int64_t *t =
        (const volatile int64_t *)&kShuttleLogPoly[0][0];
    uint64_t M0[SHUTTLE_LOG_POLY_SEGMENTS], M1[SHUTTLE_LOG_POLY_SEGMENTS];
    int64_t h0 = 0, h1 = 0;
    __int128 a0, a1;
    uint32_t j;
    int k;
    for (j = 0; j < SHUTTLE_LOG_POLY_SEGMENTS; j++) {
        M0[j] = shuttle_log_eqmask(j, sel[0]);
        M1[j] = shuttle_log_eqmask(j, sel[1]);
    }
    for (j = 0; j < SHUTTLE_LOG_POLY_SEGMENTS; j++) {
        int64_t v =
            (int64_t)t[(uint32_t)j * (SHUTTLE_LOG_POLY_DEGREE + 1) +
                       (uint32_t)SHUTTLE_LOG_POLY_DEGREE];
        h0 |= (int64_t)(M0[j] & (uint64_t)v);
        h1 |= (int64_t)(M1[j] & (uint64_t)v);
    }
    a0 = h0;
    a1 = h1;
    for (k = SHUTTLE_LOG_POLY_DEGREE - 1; k >= 0; k--) {
        int64_t c0 = 0, c1 = 0;
        for (j = 0; j < SHUTTLE_LOG_POLY_SEGMENTS; j++) {
            int64_t v =
                (int64_t)t[(uint32_t)j * (SHUTTLE_LOG_POLY_DEGREE + 1) +
                           (uint32_t)k];
            c0 |= (int64_t)(M0[j] & (uint64_t)v);
            c1 |= (int64_t)(M1[j] & (uint64_t)v);
        }
        a0 = (__int128)c0 + (__int128)shuttle_log_mulhi(a0, x_q64[0]);
        a1 = (__int128)c1 + (__int128)shuttle_log_mulhi(a1, x_q64[1]);
    }
    out[0] = (int64_t)a0;
    out[1] = (int64_t)a1;
}

#undef SHUTTLE_LOG_CT_INLINE

#if defined(__GNUC__) || defined(__clang__)
#    pragma GCC diagnostic pop
#endif

/*
 * Re-export under the project namespace (namespace.h renames at compile
 * time).  The aliases point at the gather-hardened twins above
 * (see the gather-hardened block) so the SamplerU caller never compiles to
 * a gather; the hardened twins are bit-exact to the frozen kernel.
 */
#define approx_log2_frac_q62 \
    shuttle_log2_frac_q62_ct /* (uint32 j, uint64 x_q64) -> int64 Q62 */
#define approx_log2_frac_q62_x2                                       \
    shuttle_log2_frac_q62_x2_ct /* (const uint32 sel[2], const uint64 \
                                   x_q64[2], int64 out[2]) */

/*
 * Compile-time guards pinning the integration contract (the
 * SHUTTLE_LOG_POLY_* structural constants are OWNED by the autogen header
 * and are BINDING).
 */
_Static_assert(SHUTTLE_LOG_POLY_G == 2,
               "ApproxLog g must be 2 (4 segments)");
_Static_assert(SHUTTLE_LOG_POLY_SEGMENTS == (1 << SHUTTLE_LOG_POLY_G),
               "segments must equal 2^g");
_Static_assert(SHUTTLE_LOG_POLY_DEGREE == 13,
               "ApproxLog per-segment degree must be 13");
_Static_assert(SHUTTLE_LOG_POLY_QBITS == 62, "ApproxLog output is Q62");

#endif /* SHUTTLE_APPROX_LOG_H */
