#include "faest.inc"

namespace faest
{

// clang-format off

template bool faest_unpack_secret_key(secret_key<v1::faest_128_s>*, const uint8_t*);
template bool faest_unpack_secret_key(secret_key<v1::faest_128_f>*, const uint8_t*);
template bool faest_unpack_secret_key(secret_key<v1::faest_192_s>*, const uint8_t*);
template bool faest_unpack_secret_key(secret_key<v1::faest_192_f>*, const uint8_t*);
template bool faest_unpack_secret_key(secret_key<v1::faest_256_s>*, const uint8_t*);
template bool faest_unpack_secret_key(secret_key<v1::faest_256_f>*, const uint8_t*);
template bool faest_unpack_secret_key(secret_key<v1::faest_em_128_s>*, const uint8_t*);
template bool faest_unpack_secret_key(secret_key<v1::faest_em_128_f>*, const uint8_t*);
template bool faest_unpack_secret_key(secret_key<v1::faest_em_192_s>*, const uint8_t*);
template bool faest_unpack_secret_key(secret_key<v1::faest_em_192_f>*, const uint8_t*);
template bool faest_unpack_secret_key(secret_key<v1::faest_em_256_s>*, const uint8_t*);
template bool faest_unpack_secret_key(secret_key<v1::faest_em_256_f>*, const uint8_t*);
template bool faest_unpack_secret_key(secret_key<v2::faest_128_s>*, const uint8_t*);
template bool faest_unpack_secret_key(secret_key<v2::faest_128_f>*, const uint8_t*);
template bool faest_unpack_secret_key(secret_key<v2::faest_192_s>*, const uint8_t*);
template bool faest_unpack_secret_key(secret_key<v2::faest_192_f>*, const uint8_t*);
template bool faest_unpack_secret_key(secret_key<v2::faest_256_s>*, const uint8_t*);
template bool faest_unpack_secret_key(secret_key<v2::faest_256_f>*, const uint8_t*);
template bool faest_unpack_secret_key(secret_key<v2::faest_em_128_s>*, const uint8_t*);
template bool faest_unpack_secret_key(secret_key<v2::faest_em_128_f>*, const uint8_t*);
template bool faest_unpack_secret_key(secret_key<v2::faest_em_192_s>*, const uint8_t*);
template bool faest_unpack_secret_key(secret_key<v2::faest_em_192_f>*, const uint8_t*);
template bool faest_unpack_secret_key(secret_key<v2::faest_em_256_s>*, const uint8_t*);
template bool faest_unpack_secret_key(secret_key<v2::faest_em_256_f>*, const uint8_t*);
template bool faest_unpack_secret_key(secret_key<galas::galas_128s>*, const uint8_t*);
template bool faest_unpack_secret_key(secret_key<galas::galas_128f>*, const uint8_t*);
template bool faest_unpack_secret_key(secret_key<galas::galas_192s>*, const uint8_t*);
template bool faest_unpack_secret_key(secret_key<galas::galas_192f>*, const uint8_t*);
template bool faest_unpack_secret_key(secret_key<galas::galas_256s>*, const uint8_t*);
template bool faest_unpack_secret_key(secret_key<galas::galas_ngcc_160s>*, const uint8_t*);
template bool faest_unpack_secret_key(secret_key<galas::galas_ngcc_384s>*, const uint8_t*);
template bool faest_unpack_secret_key(secret_key<galas::galas_ngcc_512s>*, const uint8_t*);
template bool faest_unpack_secret_key(secret_key<galas::galas_ngcc_256s>*, const uint8_t*);
template bool faest_unpack_secret_key(secret_key<galas::galas_256f>*, const uint8_t*);
template bool faest_unpack_secret_key(secret_key<galas::galas_ngcc_160f>*, const uint8_t*);
template bool faest_unpack_secret_key(secret_key<galas::galas_ngcc_384f>*, const uint8_t*);
template bool faest_unpack_secret_key(secret_key<galas::galas_ngcc_512f>*, const uint8_t*);
template bool faest_unpack_secret_key(secret_key<galas::galas_ngcc_256f>*, const uint8_t*);

template bool faest_unpack_sk_and_get_pubkey<galas::galas_ngcc_160s>(uint8_t*, const uint8_t*, secret_key<galas::galas_ngcc_160s>*);
template bool faest_unpack_sk_and_get_pubkey<galas::galas_ngcc_384s>(uint8_t*, const uint8_t*, secret_key<galas::galas_ngcc_384s>*);
template bool faest_unpack_sk_and_get_pubkey<galas::galas_ngcc_512s>(uint8_t*, const uint8_t*, secret_key<galas::galas_ngcc_512s>*);
template bool faest_unpack_sk_and_get_pubkey<galas::galas_ngcc_256s>(uint8_t*, const uint8_t*, secret_key<galas::galas_ngcc_256s>*);
template bool faest_unpack_sk_and_get_pubkey<galas::galas_ngcc_160f>(uint8_t*, const uint8_t*, secret_key<galas::galas_ngcc_160f>*);
template bool faest_unpack_sk_and_get_pubkey<galas::galas_ngcc_384f>(uint8_t*, const uint8_t*, secret_key<galas::galas_ngcc_384f>*);
template bool faest_unpack_sk_and_get_pubkey<galas::galas_ngcc_512f>(uint8_t*, const uint8_t*, secret_key<galas::galas_ngcc_512f>*);
template bool faest_unpack_sk_and_get_pubkey<galas::galas_ngcc_256f>(uint8_t*, const uint8_t*, secret_key<galas::galas_ngcc_256f>*);

template void faest_pack_public_key(uint8_t*, const public_key<v1::faest_128_s>*);
template void faest_pack_public_key(uint8_t*, const public_key<v1::faest_128_f>*);
template void faest_pack_public_key(uint8_t*, const public_key<v1::faest_192_s>*);
template void faest_pack_public_key(uint8_t*, const public_key<v1::faest_192_f>*);
template void faest_pack_public_key(uint8_t*, const public_key<v1::faest_256_s>*);
template void faest_pack_public_key(uint8_t*, const public_key<v1::faest_256_f>*);
template void faest_pack_public_key(uint8_t*, const public_key<v1::faest_em_128_s>*);
template void faest_pack_public_key(uint8_t*, const public_key<v1::faest_em_128_f>*);
template void faest_pack_public_key(uint8_t*, const public_key<v1::faest_em_192_s>*);
template void faest_pack_public_key(uint8_t*, const public_key<v1::faest_em_192_f>*);
template void faest_pack_public_key(uint8_t*, const public_key<v1::faest_em_256_s>*);
template void faest_pack_public_key(uint8_t*, const public_key<v1::faest_em_256_f>*);
template void faest_pack_public_key(uint8_t*, const public_key<v2::faest_128_s>*);
template void faest_pack_public_key(uint8_t*, const public_key<v2::faest_128_f>*);
template void faest_pack_public_key(uint8_t*, const public_key<v2::faest_192_s>*);
template void faest_pack_public_key(uint8_t*, const public_key<v2::faest_192_f>*);
template void faest_pack_public_key(uint8_t*, const public_key<v2::faest_256_s>*);
template void faest_pack_public_key(uint8_t*, const public_key<v2::faest_256_f>*);
template void faest_pack_public_key(uint8_t*, const public_key<v2::faest_em_128_s>*);
template void faest_pack_public_key(uint8_t*, const public_key<v2::faest_em_128_f>*);
template void faest_pack_public_key(uint8_t*, const public_key<v2::faest_em_192_s>*);
template void faest_pack_public_key(uint8_t*, const public_key<v2::faest_em_192_f>*);
template void faest_pack_public_key(uint8_t*, const public_key<v2::faest_em_256_s>*);
template void faest_pack_public_key(uint8_t*, const public_key<v2::faest_em_256_f>*);
template void faest_pack_public_key(uint8_t*, const public_key<galas::galas_128s>*);
template void faest_pack_public_key(uint8_t*, const public_key<galas::galas_128f>*);
template void faest_pack_public_key(uint8_t*, const public_key<galas::galas_192s>*);
template void faest_pack_public_key(uint8_t*, const public_key<galas::galas_192f>*);
template void faest_pack_public_key(uint8_t*, const public_key<galas::galas_256s>*);
template void faest_pack_public_key(uint8_t*, const public_key<galas::galas_ngcc_160s>*);
template void faest_pack_public_key(uint8_t*, const public_key<galas::galas_ngcc_384s>*);
template void faest_pack_public_key(uint8_t*, const public_key<galas::galas_ngcc_512s>*);
template void faest_pack_public_key(uint8_t*, const public_key<galas::galas_ngcc_256s>*);
template void faest_pack_public_key(uint8_t*, const public_key<galas::galas_256f>*);
template void faest_pack_public_key(uint8_t*, const public_key<galas::galas_ngcc_160f>*);
template void faest_pack_public_key(uint8_t*, const public_key<galas::galas_ngcc_384f>*);
template void faest_pack_public_key(uint8_t*, const public_key<galas::galas_ngcc_512f>*);
template void faest_pack_public_key(uint8_t*, const public_key<galas::galas_ngcc_256f>*);

template void faest_unpack_public_key(public_key<v1::faest_128_s>*, const uint8_t*);
template void faest_unpack_public_key(public_key<v1::faest_128_f>*, const uint8_t*);
template void faest_unpack_public_key(public_key<v1::faest_192_s>*, const uint8_t*);
template void faest_unpack_public_key(public_key<v1::faest_192_f>*, const uint8_t*);
template void faest_unpack_public_key(public_key<v1::faest_256_s>*, const uint8_t*);
template void faest_unpack_public_key(public_key<v1::faest_256_f>*, const uint8_t*);
template void faest_unpack_public_key(public_key<v1::faest_em_128_s>*, const uint8_t*);
template void faest_unpack_public_key(public_key<v1::faest_em_128_f>*, const uint8_t*);
template void faest_unpack_public_key(public_key<v1::faest_em_192_s>*, const uint8_t*);
template void faest_unpack_public_key(public_key<v1::faest_em_192_f>*, const uint8_t*);
template void faest_unpack_public_key(public_key<v1::faest_em_256_s>*, const uint8_t*);
template void faest_unpack_public_key(public_key<v1::faest_em_256_f>*, const uint8_t*);
template void faest_unpack_public_key(public_key<v2::faest_128_s>*, const uint8_t*);
template void faest_unpack_public_key(public_key<v2::faest_128_f>*, const uint8_t*);
template void faest_unpack_public_key(public_key<v2::faest_192_s>*, const uint8_t*);
template void faest_unpack_public_key(public_key<v2::faest_192_f>*, const uint8_t*);
template void faest_unpack_public_key(public_key<v2::faest_256_s>*, const uint8_t*);
template void faest_unpack_public_key(public_key<v2::faest_256_f>*, const uint8_t*);
template void faest_unpack_public_key(public_key<v2::faest_em_128_s>*, const uint8_t*);
template void faest_unpack_public_key(public_key<v2::faest_em_128_f>*, const uint8_t*);
template void faest_unpack_public_key(public_key<v2::faest_em_192_s>*, const uint8_t*);
template void faest_unpack_public_key(public_key<v2::faest_em_192_f>*, const uint8_t*);
template void faest_unpack_public_key(public_key<v2::faest_em_256_s>*, const uint8_t*);
template void faest_unpack_public_key(public_key<v2::faest_em_256_f>*, const uint8_t*);
template void faest_unpack_public_key(public_key<galas::galas_128s>*, const uint8_t*);
template void faest_unpack_public_key(public_key<galas::galas_128f>*, const uint8_t*);
template void faest_unpack_public_key(public_key<galas::galas_192s>*, const uint8_t*);
template void faest_unpack_public_key(public_key<galas::galas_192f>*, const uint8_t*);
template void faest_unpack_public_key(public_key<galas::galas_256s>*, const uint8_t*);
template void faest_unpack_public_key(public_key<galas::galas_ngcc_160s>*, const uint8_t*);
template void faest_unpack_public_key(public_key<galas::galas_ngcc_384s>*, const uint8_t*);
template void faest_unpack_public_key(public_key<galas::galas_ngcc_512s>*, const uint8_t*);
template void faest_unpack_public_key(public_key<galas::galas_ngcc_256s>*, const uint8_t*);
template void faest_unpack_public_key(public_key<galas::galas_256f>*, const uint8_t*);
template void faest_unpack_public_key(public_key<galas::galas_ngcc_160f>*, const uint8_t*);
template void faest_unpack_public_key(public_key<galas::galas_ngcc_384f>*, const uint8_t*);
template void faest_unpack_public_key(public_key<galas::galas_ngcc_512f>*, const uint8_t*);
template void faest_unpack_public_key(public_key<galas::galas_ngcc_256f>*, const uint8_t*);

template bool faest_seckey<v1::faest_128_s>(const uint8_t*);
template bool faest_seckey<v1::faest_128_f>(const uint8_t*);
template bool faest_seckey<v1::faest_192_s>(const uint8_t*);
template bool faest_seckey<v1::faest_192_f>(const uint8_t*);
template bool faest_seckey<v1::faest_256_s>(const uint8_t*);
template bool faest_seckey<v1::faest_256_f>(const uint8_t*);
template bool faest_seckey<v1::faest_em_128_s>(const uint8_t*);
template bool faest_seckey<v1::faest_em_128_f>(const uint8_t*);
template bool faest_seckey<v1::faest_em_192_s>(const uint8_t*);
template bool faest_seckey<v1::faest_em_192_f>(const uint8_t*);
template bool faest_seckey<v1::faest_em_256_s>(const uint8_t*);
template bool faest_seckey<v1::faest_em_256_f>(const uint8_t*);
template bool faest_seckey<v2::faest_128_s>(const uint8_t*);
template bool faest_seckey<v2::faest_128_f>(const uint8_t*);
template bool faest_seckey<v2::faest_192_s>(const uint8_t*);
template bool faest_seckey<v2::faest_192_f>(const uint8_t*);
template bool faest_seckey<v2::faest_256_s>(const uint8_t*);
template bool faest_seckey<v2::faest_256_f>(const uint8_t*);
template bool faest_seckey<v2::faest_em_128_s>(const uint8_t*);
template bool faest_seckey<v2::faest_em_128_f>(const uint8_t*);
template bool faest_seckey<v2::faest_em_192_s>(const uint8_t*);
template bool faest_seckey<v2::faest_em_192_f>(const uint8_t*);
template bool faest_seckey<v2::faest_em_256_s>(const uint8_t*);
template bool faest_seckey<v2::faest_em_256_f>(const uint8_t*);
template bool faest_seckey<galas::galas_128s>(const uint8_t*);
template bool faest_seckey<galas::galas_128f>(const uint8_t*);
template bool faest_seckey<galas::galas_192s>(const uint8_t*);
template bool faest_seckey<galas::galas_192f>(const uint8_t*);
template bool faest_seckey<galas::galas_256s>(const uint8_t*);
template bool faest_seckey<galas::galas_ngcc_160s>(const uint8_t*);
template bool faest_seckey<galas::galas_ngcc_384s>(const uint8_t*);
template bool faest_seckey<galas::galas_ngcc_512s>(const uint8_t*);
template bool faest_seckey<galas::galas_ngcc_256s>(const uint8_t*);
template bool faest_seckey<galas::galas_256f>(const uint8_t*);
template bool faest_seckey<galas::galas_ngcc_160f>(const uint8_t*);
template bool faest_seckey<galas::galas_ngcc_384f>(const uint8_t*);
template bool faest_seckey<galas::galas_ngcc_512f>(const uint8_t*);
template bool faest_seckey<galas::galas_ngcc_256f>(const uint8_t*);

template bool faest_pubkey<v1::faest_128_s>(uint8_t*, const uint8_t*);
template bool faest_pubkey<v1::faest_128_f>(uint8_t*, const uint8_t*);
template bool faest_pubkey<v1::faest_192_s>(uint8_t*, const uint8_t*);
template bool faest_pubkey<v1::faest_192_f>(uint8_t*, const uint8_t*);
template bool faest_pubkey<v1::faest_256_s>(uint8_t*, const uint8_t*);
template bool faest_pubkey<v1::faest_256_f>(uint8_t*, const uint8_t*);
template bool faest_pubkey<v1::faest_em_128_s>(uint8_t*, const uint8_t*);
template bool faest_pubkey<v1::faest_em_128_f>(uint8_t*, const uint8_t*);
template bool faest_pubkey<v1::faest_em_192_s>(uint8_t*, const uint8_t*);
template bool faest_pubkey<v1::faest_em_192_f>(uint8_t*, const uint8_t*);
template bool faest_pubkey<v1::faest_em_256_s>(uint8_t*, const uint8_t*);
template bool faest_pubkey<v1::faest_em_256_f>(uint8_t*, const uint8_t*);
template bool faest_pubkey<v2::faest_128_s>(uint8_t*, const uint8_t*);
template bool faest_pubkey<v2::faest_128_f>(uint8_t*, const uint8_t*);
template bool faest_pubkey<v2::faest_192_s>(uint8_t*, const uint8_t*);
template bool faest_pubkey<v2::faest_192_f>(uint8_t*, const uint8_t*);
template bool faest_pubkey<v2::faest_256_s>(uint8_t*, const uint8_t*);
template bool faest_pubkey<v2::faest_256_f>(uint8_t*, const uint8_t*);
template bool faest_pubkey<v2::faest_em_128_s>(uint8_t*, const uint8_t*);
template bool faest_pubkey<v2::faest_em_128_f>(uint8_t*, const uint8_t*);
template bool faest_pubkey<v2::faest_em_192_s>(uint8_t*, const uint8_t*);
template bool faest_pubkey<v2::faest_em_192_f>(uint8_t*, const uint8_t*);
template bool faest_pubkey<v2::faest_em_256_s>(uint8_t*, const uint8_t*);
template bool faest_pubkey<v2::faest_em_256_f>(uint8_t*, const uint8_t*);
template bool faest_pubkey<galas::galas_128s>(uint8_t*, const uint8_t*);
template bool faest_pubkey<galas::galas_128f>(uint8_t*, const uint8_t*);
template bool faest_pubkey<galas::galas_192s>(uint8_t*, const uint8_t*);
template bool faest_pubkey<galas::galas_192f>(uint8_t*, const uint8_t*);
template bool faest_pubkey<galas::galas_256s>(uint8_t*, const uint8_t*);
template bool faest_pubkey<galas::galas_ngcc_160s>(uint8_t*, const uint8_t*);
template bool faest_pubkey<galas::galas_ngcc_384s>(uint8_t*, const uint8_t*);
template bool faest_pubkey<galas::galas_ngcc_512s>(uint8_t*, const uint8_t*);
template bool faest_pubkey<galas::galas_ngcc_256s>(uint8_t*, const uint8_t*);
template bool faest_pubkey<galas::galas_256f>(uint8_t*, const uint8_t*);
template bool faest_pubkey<galas::galas_ngcc_160f>(uint8_t*, const uint8_t*);
template bool faest_pubkey<galas::galas_ngcc_384f>(uint8_t*, const uint8_t*);
template bool faest_pubkey<galas::galas_ngcc_512f>(uint8_t*, const uint8_t*);
template bool faest_pubkey<galas::galas_ngcc_256f>(uint8_t*, const uint8_t*);

template bool faest_sign<v1::faest_128_s>( uint8_t*, const uint8_t*, size_t, const uint8_t*, const uint8_t*, size_t);
template bool faest_sign<v1::faest_128_f>( uint8_t*, const uint8_t*, size_t, const uint8_t*, const uint8_t*, size_t);
template bool faest_sign<v1::faest_192_s>( uint8_t*, const uint8_t*, size_t, const uint8_t*, const uint8_t*, size_t);
template bool faest_sign<v1::faest_192_f>( uint8_t*, const uint8_t*, size_t, const uint8_t*, const uint8_t*, size_t);
template bool faest_sign<v1::faest_256_s>( uint8_t*, const uint8_t*, size_t, const uint8_t*, const uint8_t*, size_t);
template bool faest_sign<v1::faest_256_f>( uint8_t*, const uint8_t*, size_t, const uint8_t*, const uint8_t*, size_t);
template bool faest_sign<v1::faest_em_128_s>(uint8_t*, const uint8_t*, size_t, const uint8_t*, const uint8_t*, size_t);
template bool faest_sign<v1::faest_em_128_f>(uint8_t*, const uint8_t*, size_t, const uint8_t*, const uint8_t*, size_t);
template bool faest_sign<v1::faest_em_192_s>(uint8_t*, const uint8_t*, size_t, const uint8_t*, const uint8_t*, size_t);
template bool faest_sign<v1::faest_em_192_f>(uint8_t*, const uint8_t*, size_t, const uint8_t*, const uint8_t*, size_t);
template bool faest_sign<v1::faest_em_256_s>(uint8_t*, const uint8_t*, size_t, const uint8_t*, const uint8_t*, size_t);
template bool faest_sign<v1::faest_em_256_f>(uint8_t*, const uint8_t*, size_t, const uint8_t*, const uint8_t*, size_t);
template bool faest_sign<v2::faest_128_s>( uint8_t*, const uint8_t*, size_t, const uint8_t*, const uint8_t*, size_t);
template bool faest_sign<v2::faest_128_f>( uint8_t*, const uint8_t*, size_t, const uint8_t*, const uint8_t*, size_t);
template bool faest_sign<v2::faest_192_s>( uint8_t*, const uint8_t*, size_t, const uint8_t*, const uint8_t*, size_t);
template bool faest_sign<v2::faest_192_f>( uint8_t*, const uint8_t*, size_t, const uint8_t*, const uint8_t*, size_t);
template bool faest_sign<v2::faest_256_s>( uint8_t*, const uint8_t*, size_t, const uint8_t*, const uint8_t*, size_t);
template bool faest_sign<v2::faest_256_f>( uint8_t*, const uint8_t*, size_t, const uint8_t*, const uint8_t*, size_t);
template bool faest_sign<v2::faest_em_128_s>(uint8_t*, const uint8_t*, size_t, const uint8_t*, const uint8_t*, size_t);
template bool faest_sign<v2::faest_em_128_f>(uint8_t*, const uint8_t*, size_t, const uint8_t*, const uint8_t*, size_t);
template bool faest_sign<v2::faest_em_192_s>(uint8_t*, const uint8_t*, size_t, const uint8_t*, const uint8_t*, size_t);
template bool faest_sign<v2::faest_em_192_f>(uint8_t*, const uint8_t*, size_t, const uint8_t*, const uint8_t*, size_t);
template bool faest_sign<v2::faest_em_256_s>(uint8_t*, const uint8_t*, size_t, const uint8_t*, const uint8_t*, size_t);
template bool faest_sign<v2::faest_em_256_f>(uint8_t*, const uint8_t*, size_t, const uint8_t*, const uint8_t*, size_t);
template bool faest_sign<galas::galas_128s>(uint8_t*, const uint8_t*, size_t, const uint8_t*, const uint8_t*, size_t);
template bool faest_sign<galas::galas_128f>(uint8_t*, const uint8_t*, size_t, const uint8_t*, const uint8_t*, size_t);
template bool faest_sign<galas::galas_192s>(uint8_t*, const uint8_t*, size_t, const uint8_t*, const uint8_t*, size_t);
template bool faest_sign<galas::galas_192f>(uint8_t*, const uint8_t*, size_t, const uint8_t*, const uint8_t*, size_t);
template bool faest_sign<galas::galas_256s>(uint8_t*, const uint8_t*, size_t, const uint8_t*, const uint8_t*, size_t);
template bool faest_sign<galas::galas_ngcc_160s>(uint8_t*, const uint8_t*, size_t, const uint8_t*, const uint8_t*, size_t);
template bool faest_sign<galas::galas_ngcc_384s>(uint8_t*, const uint8_t*, size_t, const uint8_t*, const uint8_t*, size_t);
template bool faest_sign<galas::galas_ngcc_512s>(uint8_t*, const uint8_t*, size_t, const uint8_t*, const uint8_t*, size_t);
template bool faest_sign<galas::galas_ngcc_256s>(uint8_t*, const uint8_t*, size_t, const uint8_t*, const uint8_t*, size_t);
template bool faest_sign<galas::galas_256f>(uint8_t*, const uint8_t*, size_t, const uint8_t*, const uint8_t*, size_t);
template bool faest_sign<galas::galas_ngcc_160f>(uint8_t*, const uint8_t*, size_t, const uint8_t*, const uint8_t*, size_t);
template bool faest_sign<galas::galas_ngcc_384f>(uint8_t*, const uint8_t*, size_t, const uint8_t*, const uint8_t*, size_t);
template bool faest_sign<galas::galas_ngcc_512f>(uint8_t*, const uint8_t*, size_t, const uint8_t*, const uint8_t*, size_t);
template bool faest_sign<galas::galas_ngcc_256f>(uint8_t*, const uint8_t*, size_t, const uint8_t*, const uint8_t*, size_t);

template bool faest_verify<v1::faest_128_s>(const uint8_t*, const uint8_t*, size_t, const uint8_t*);
template bool faest_verify<v1::faest_128_f>(const uint8_t*, const uint8_t*, size_t, const uint8_t*);
template bool faest_verify<v1::faest_192_s>(const uint8_t*, const uint8_t*, size_t, const uint8_t*);
template bool faest_verify<v1::faest_192_f>(const uint8_t*, const uint8_t*, size_t, const uint8_t*);
template bool faest_verify<v1::faest_256_s>(const uint8_t*, const uint8_t*, size_t, const uint8_t*);
template bool faest_verify<v1::faest_256_f>(const uint8_t*, const uint8_t*, size_t, const uint8_t*);
template bool faest_verify<v1::faest_em_128_s>(const uint8_t*, const uint8_t*, size_t, const uint8_t*);
template bool faest_verify<v1::faest_em_128_f>(const uint8_t*, const uint8_t*, size_t, const uint8_t*);
template bool faest_verify<v1::faest_em_192_s>(const uint8_t*, const uint8_t*, size_t, const uint8_t*);
template bool faest_verify<v1::faest_em_192_f>(const uint8_t*, const uint8_t*, size_t, const uint8_t*);
template bool faest_verify<v1::faest_em_256_s>(const uint8_t*, const uint8_t*, size_t, const uint8_t*);
template bool faest_verify<v1::faest_em_256_f>(const uint8_t*, const uint8_t*, size_t, const uint8_t*);
template bool faest_verify<v2::faest_128_s>(const uint8_t*, const uint8_t*, size_t, const uint8_t*);
template bool faest_verify<v2::faest_128_f>(const uint8_t*, const uint8_t*, size_t, const uint8_t*);
template bool faest_verify<v2::faest_192_s>(const uint8_t*, const uint8_t*, size_t, const uint8_t*);
template bool faest_verify<v2::faest_192_f>(const uint8_t*, const uint8_t*, size_t, const uint8_t*);
template bool faest_verify<v2::faest_256_s>(const uint8_t*, const uint8_t*, size_t, const uint8_t*);
template bool faest_verify<v2::faest_256_f>(const uint8_t*, const uint8_t*, size_t, const uint8_t*);
template bool faest_verify<v2::faest_em_128_s>(const uint8_t*, const uint8_t*, size_t, const uint8_t*);
template bool faest_verify<v2::faest_em_128_f>(const uint8_t*, const uint8_t*, size_t, const uint8_t*);
template bool faest_verify<v2::faest_em_192_s>(const uint8_t*, const uint8_t*, size_t, const uint8_t*);
template bool faest_verify<v2::faest_em_192_f>(const uint8_t*, const uint8_t*, size_t, const uint8_t*);
template bool faest_verify<v2::faest_em_256_s>(const uint8_t*, const uint8_t*, size_t, const uint8_t*);
template bool faest_verify<v2::faest_em_256_f>(const uint8_t*, const uint8_t*, size_t, const uint8_t*);
template bool faest_verify<galas::galas_128s>(const uint8_t*, const uint8_t*, size_t, const uint8_t*);
template bool faest_verify<galas::galas_128f>(const uint8_t*, const uint8_t*, size_t, const uint8_t*);
template bool faest_verify<galas::galas_192s>(const uint8_t*, const uint8_t*, size_t, const uint8_t*);
template bool faest_verify<galas::galas_192f>(const uint8_t*, const uint8_t*, size_t, const uint8_t*);
template bool faest_verify<galas::galas_256s>(const uint8_t*, const uint8_t*, size_t, const uint8_t*);
template bool faest_verify<galas::galas_ngcc_160s>(const uint8_t*, const uint8_t*, size_t, const uint8_t*);
template bool faest_verify<galas::galas_ngcc_384s>(const uint8_t*, const uint8_t*, size_t, const uint8_t*);
template bool faest_verify<galas::galas_ngcc_512s>(const uint8_t*, const uint8_t*, size_t, const uint8_t*);
template bool faest_verify<galas::galas_ngcc_256s>(const uint8_t*, const uint8_t*, size_t, const uint8_t*);
template bool faest_verify<galas::galas_256f>(const uint8_t*, const uint8_t*, size_t, const uint8_t*);
template bool faest_verify<galas::galas_ngcc_160f>(const uint8_t*, const uint8_t*, size_t, const uint8_t*);
template bool faest_verify<galas::galas_ngcc_384f>(const uint8_t*, const uint8_t*, size_t, const uint8_t*);
template bool faest_verify<galas::galas_ngcc_512f>(const uint8_t*, const uint8_t*, size_t, const uint8_t*);
template bool faest_verify<galas::galas_ngcc_256f>(const uint8_t*, const uint8_t*, size_t, const uint8_t*);
// clang-format on

} // namespace faest
