
#define FP_ENCODED_BYTES 131
#define FP2_ENCODED_BYTES 262
#define EC_CURVE_ENCODED_BYTES 262
#define EC_POINT_ENCODED_BYTES 262
#define EC_BASIS_ENCODED_BYTES 816
#define CHAIN_LENGTH 5
#define QUAT_ALG_ELEM_ENCODED_BITS 1503
#define QUAT_ALG_ELEM_ENCODED_BYTES 188
#define ID2ISO_LONG_TWO_ISOG_ENCODED_BYTES 2730
#define ZIP_CHAIN_LEN 8
#define ID2ISO_COMPRESSED_LONG_TWO_ISOG_ZIP_CHAIN_BYTES 66
#define ID2ISO_COMPRESSED_LONG_TWO_ISOG_BYTES 529
#define SIGNATURE_LEN (2 * FP_ENCODED_BYTES + 4 * TORSION_2POWER_BYTES + TORSION_3POWER_BYTES + 2)
#define PUBLICKEY_BYTES (2 * FP_ENCODED_BYTES)
//#define SECRETKEY_BYTES (10 * FP_ENCODED_BYTES + 6 * TORSION_2POWER_BYTES + 6 * TORSION_3POWER_BYTES)
#define SECRETKEY_BYTES 1838