

# This file was *autogenerated* from the file /home/xingtingyu/code/temp/C-implementation/scripts/precomp/precompute_sizes.sage
from sage.all_cmdline import *   # import sage library

_sage_const_9 = Integer(9); _sage_const_8 = Integer(8); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_3 = Integer(3); _sage_const_7 = Integer(7); _sage_const_128 = Integer(128); _sage_const_64 = Integer(64); _sage_const_160 = Integer(160); _sage_const_63 = Integer(63); _sage_const_32 = Integer(32); _sage_const_4 = Integer(4); _sage_const_5 = Integer(5)#!/usr/bin/env sage
proof.all(False)  # faster

from sage.misc.banner import require_version
if not require_version(_sage_const_9 , _sage_const_8 , print_message=True):
    exit('')

################################################################

from parameters import lvl, f, p

################################################################

logp = ceil(log(p, _sage_const_2 ))
tors2val = (p+_sage_const_1 ).valuation(_sage_const_2 )
tors2part = (p+_sage_const_1 ).p_primary_part(_sage_const_2 )
tors3part = (p+_sage_const_1 ).p_primary_part(_sage_const_3 )

defs = dict()

TORSION_2POWER_BYTES = (tors2part.bit_length() + _sage_const_7 ) // _sage_const_8 
SECURITY_BITS = round(p.bit_length() / _sage_const_128 ) * _sage_const_64 
# lvl2 (lambda=160) is not a multiple of 64, so the rounding formula above yields
# 128; override it to the intended security level. (lvl6 -> 512 is correct already.)
if lvl == _sage_const_2 :
    SECURITY_BITS = _sage_const_160 
RESPONSE_LENGTH = ceil(p.bit_length()/_sage_const_2 )
RESPONSE_BYTES = (RESPONSE_LENGTH + _sage_const_9 ) // _sage_const_8 

fpsz = (logp + _sage_const_63 )//_sage_const_64 *_sage_const_8 
fp2sz = _sage_const_2  * fpsz
defs['SECURITY_BITS'] = SECURITY_BITS
defs['SQIsign_response_length'] = ceil(logp/_sage_const_2 )
defs['HASH_ITERATIONS'] = _sage_const_2 **(_sage_const_32  * ceil( logp/_sage_const_64  ) - (tors2val - ceil(logp/_sage_const_2 )))
defs['FP_ENCODED_BYTES'] = fpsz
defs['FP2_ENCODED_BYTES'] = fp2sz
defs['EC_CURVE_ENCODED_BYTES'] = fp2sz  # just the A
defs['EC_POINT_ENCODED_BYTES'] = fp2sz  # just the x
defs['EC_BASIS_ENCODED_BYTES'] = _sage_const_3  * defs['EC_POINT_ENCODED_BYTES']

# SQIsignTriangle-specific encoding sizes. The signature is (challenge curve A) +
# a compressed torsion basis of 4 scalar coefficients + a scalar q. Each scalar is
# encoded in 7 bytes per 64-bit limb of the field, i.e. 7 * (number of 64-bit limbs
# needed for p). This reproduces the committed lvl1/3/5 values exactly:
#   lvl1 (4 limbs): COEFF=28, COMPRESSED=112, Q=28, NEW_SIGNATURE=204
#   lvl3 (6 limbs): COEFF=42, COMPRESSED=168, Q=42, NEW_SIGNATURE=306
#   lvl5 (8 limbs): COEFF=56, COMPRESSED=224, Q=56, NEW_SIGNATURE=408
NWORDS_FIELD_SAT = (logp + _sage_const_63 )//_sage_const_64 
defs['SQISIGNTRIANGLE_BASIS_COEFF_BYTES'] = _sage_const_7  * NWORDS_FIELD_SAT
defs['SQISIGNTRIANGLE_COMPRESSED_BASIS_BYTES'] = _sage_const_4  * defs['SQISIGNTRIANGLE_BASIS_COEFF_BYTES']
defs['SQISIGNTRIANGLE_Q_BYTES'] = defs['SQISIGNTRIANGLE_BASIS_COEFF_BYTES']

defs['PUBLICKEY_BYTES'] = defs['EC_CURVE_ENCODED_BYTES'] + _sage_const_1   # extra byte for hint
defs['SECRETKEY_BYTES'] = defs['PUBLICKEY_BYTES'] + _sage_const_5 *defs['FP_ENCODED_BYTES'] + _sage_const_4 *TORSION_2POWER_BYTES
defs['NEW_SIGNATURE_BYTES'] = defs['EC_CURVE_ENCODED_BYTES']     + defs['SQISIGNTRIANGLE_COMPRESSED_BASIS_BYTES'] + defs['SQISIGNTRIANGLE_Q_BYTES']

size_privkey = defs['SECRETKEY_BYTES']
size_pubkey = defs['PUBLICKEY_BYTES']
size_signature = defs['NEW_SIGNATURE_BYTES']

algname = f'SQIsign_lvl{lvl}'

################################################################

with open('include/encoded_sizes.h','w') as hfile:
    for k,v in defs.items():
        v = ZZ(v)
        print(f'#define {k} {v}', file=hfile)

################################################################

api = f'''
// SPDX-License-Identifier: Apache-2.0

#ifndef api_h
#define api_h

#include <sqisign_namespace.h>

#define CRYPTO_SECRETKEYBYTES {size_privkey}
#define CRYPTO_PUBLICKEYBYTES {size_pubkey}
#define CRYPTO_BYTES {size_signature}

#define CRYPTO_ALGNAME "{algname}"

#if defined(ENABLE_SIGN)
SQISIGN_API
int
crypto_sign_keypair(unsigned char *pk, unsigned char *sk);

SQISIGN_API
int
crypto_sign(unsigned char *sm, unsigned long long *smlen,
            const unsigned char *m, unsigned long long mlen,
            const unsigned char *sk);
#endif

SQISIGN_API
int
crypto_sign_open(unsigned char *m, unsigned long long *mlen,
                 const unsigned char *sm, unsigned long long smlen,
                 const unsigned char *pk);

#endif /* api_h */
'''.strip()

with open(f'../../../nistapi/lvl{lvl}/api.h', 'w') as f:
    print(api, file=f)


