

# This file was *autogenerated* from the file /home/xingtingyu/code/temp/C-implementation/scripts/precomp/precompute_E0_basis.sage
from sage.all_cmdline import *   # import sage library

_sage_const_4 = Integer(4); _sage_const_3 = Integer(3); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_0 = Integer(0)#!/usr/bin/env sage
proof.all(False)  # faster

################################################################

from parameters import p, f

if p % _sage_const_4  != _sage_const_3 :
    raise NotImplementedError('requires p ≡ 3 (mod 4)')

assert (_sage_const_1  << f).divides(p + _sage_const_1 )
Fp2 = GF((p,_sage_const_2 ), modulus=[_sage_const_1 ,_sage_const_0 ,_sage_const_1 ], names=('i',)); (i,) = Fp2._first_ngens(1)
E0 = EllipticCurve(Fp2, [_sage_const_1 , _sage_const_0 ])

from torsion_basis import even_torsion_basis_E0
P, Q = even_torsion_basis_E0(E0, f)

################################################################

from cformat import FpEl, Object, ObjectFormatter

def Fp2_to_list(el):
    return [FpEl(int(c), p, True) for c in Fp2(el)]

objs = ObjectFormatter([
        Object('fp2_t', 'BASIS_E0_PX', Fp2_to_list(P.x())),
        Object('fp2_t', 'BASIS_E0_QX', Fp2_to_list(Q.x())),
    ])

################################################################

with open('include/e0_basis.h','w') as hfile:
    with open('e0_basis.c','w') as cfile:
        print(f'#include <fp2.h>', file=hfile)
        print(f'#include <e0_basis.h>', file=cfile)

        objs.header(file=hfile)
        objs.implementation(file=cfile)

