#include "small_vole.inc"

namespace faest
{

// clang-format off

template void vole_sender<v1::faest_128_s>(unsigned int, const block_secpar<v1::faest_128_s::secpar_v>* __restrict__, typename v1::faest_128_s::vole_prg_t::iv_t, typename v1::faest_128_s::vole_prg_t::tweak_t, const vole_block* __restrict__, vole_block* __restrict__, vole_block* __restrict__);
template void vole_sender<v1::faest_128_f>(unsigned int, const block_secpar<v1::faest_128_f::secpar_v>* __restrict__, typename v1::faest_128_f::vole_prg_t::iv_t, typename v1::faest_128_f::vole_prg_t::tweak_t, const vole_block* __restrict__, vole_block* __restrict__, vole_block* __restrict__);
template void vole_sender<v1::faest_192_s>(unsigned int, const block_secpar<v1::faest_192_s::secpar_v>* __restrict__, typename v1::faest_192_s::vole_prg_t::iv_t, typename v1::faest_192_s::vole_prg_t::tweak_t, const vole_block* __restrict__, vole_block* __restrict__, vole_block* __restrict__);
template void vole_sender<v1::faest_192_f>(unsigned int, const block_secpar<v1::faest_192_f::secpar_v>* __restrict__, typename v1::faest_192_f::vole_prg_t::iv_t, typename v1::faest_192_f::vole_prg_t::tweak_t, const vole_block* __restrict__, vole_block* __restrict__, vole_block* __restrict__);
template void vole_sender<v1::faest_256_s>(unsigned int, const block_secpar<v1::faest_256_s::secpar_v>* __restrict__, typename v1::faest_256_s::vole_prg_t::iv_t, typename v1::faest_256_s::vole_prg_t::tweak_t, const vole_block* __restrict__, vole_block* __restrict__, vole_block* __restrict__);
template void vole_sender<v1::faest_256_f>(unsigned int, const block_secpar<v1::faest_256_f::secpar_v>* __restrict__, typename v1::faest_256_f::vole_prg_t::iv_t, typename v1::faest_256_f::vole_prg_t::tweak_t, const vole_block* __restrict__, vole_block* __restrict__, vole_block* __restrict__);
template void vole_sender<v1::faest_em_128_s>(unsigned int, const block_secpar<v1::faest_em_128_s::secpar_v>* __restrict__, typename v1::faest_em_128_s::vole_prg_t::iv_t, typename v1::faest_em_128_s::vole_prg_t::tweak_t, const vole_block* __restrict__, vole_block* __restrict__, vole_block* __restrict__);
template void vole_sender<v1::faest_em_128_f>(unsigned int, const block_secpar<v1::faest_em_128_f::secpar_v>* __restrict__, typename v1::faest_em_128_f::vole_prg_t::iv_t, typename v1::faest_em_128_f::vole_prg_t::tweak_t, const vole_block* __restrict__, vole_block* __restrict__, vole_block* __restrict__);
template void vole_sender<v1::faest_em_192_s>(unsigned int, const block_secpar<v1::faest_em_192_s::secpar_v>* __restrict__, typename v1::faest_em_192_s::vole_prg_t::iv_t, typename v1::faest_em_192_s::vole_prg_t::tweak_t, const vole_block* __restrict__, vole_block* __restrict__, vole_block* __restrict__);
template void vole_sender<v1::faest_em_192_f>(unsigned int, const block_secpar<v1::faest_em_192_f::secpar_v>* __restrict__, typename v1::faest_em_192_f::vole_prg_t::iv_t, typename v1::faest_em_192_f::vole_prg_t::tweak_t, const vole_block* __restrict__, vole_block* __restrict__, vole_block* __restrict__);
template void vole_sender<v1::faest_em_256_s>(unsigned int, const block_secpar<v1::faest_em_256_s::secpar_v>* __restrict__, typename v1::faest_em_256_s::vole_prg_t::iv_t, typename v1::faest_em_256_s::vole_prg_t::tweak_t, const vole_block* __restrict__, vole_block* __restrict__, vole_block* __restrict__);
template void vole_sender<v1::faest_em_256_f>(unsigned int, const block_secpar<v1::faest_em_256_f::secpar_v>* __restrict__, typename v1::faest_em_256_f::vole_prg_t::iv_t, typename v1::faest_em_256_f::vole_prg_t::tweak_t, const vole_block* __restrict__, vole_block* __restrict__, vole_block* __restrict__);
template void vole_sender<v2::faest_128_s>(unsigned int, const block_secpar<v2::faest_128_s::secpar_v>* __restrict__, typename v2::faest_128_s::vole_prg_t::iv_t, typename v2::faest_128_s::vole_prg_t::tweak_t, const vole_block* __restrict__, vole_block* __restrict__, vole_block* __restrict__);
template void vole_sender<v2::faest_128_f>(unsigned int, const block_secpar<v2::faest_128_f::secpar_v>* __restrict__, typename v2::faest_128_f::vole_prg_t::iv_t, typename v2::faest_128_f::vole_prg_t::tweak_t, const vole_block* __restrict__, vole_block* __restrict__, vole_block* __restrict__);
template void vole_sender<v2::faest_192_s>(unsigned int, const block_secpar<v2::faest_192_s::secpar_v>* __restrict__, typename v2::faest_192_s::vole_prg_t::iv_t, typename v2::faest_192_s::vole_prg_t::tweak_t, const vole_block* __restrict__, vole_block* __restrict__, vole_block* __restrict__);
template void vole_sender<v2::faest_192_f>(unsigned int, const block_secpar<v2::faest_192_f::secpar_v>* __restrict__, typename v2::faest_192_f::vole_prg_t::iv_t, typename v2::faest_192_f::vole_prg_t::tweak_t, const vole_block* __restrict__, vole_block* __restrict__, vole_block* __restrict__);
template void vole_sender<v2::faest_256_s>(unsigned int, const block_secpar<v2::faest_256_s::secpar_v>* __restrict__, typename v2::faest_256_s::vole_prg_t::iv_t, typename v2::faest_256_s::vole_prg_t::tweak_t, const vole_block* __restrict__, vole_block* __restrict__, vole_block* __restrict__);
template void vole_sender<v2::faest_256_f>(unsigned int, const block_secpar<v2::faest_256_f::secpar_v>* __restrict__, typename v2::faest_256_f::vole_prg_t::iv_t, typename v2::faest_256_f::vole_prg_t::tweak_t, const vole_block* __restrict__, vole_block* __restrict__, vole_block* __restrict__);
template void vole_sender<v2::faest_em_128_s>(unsigned int, const block_secpar<v2::faest_em_128_s::secpar_v>* __restrict__, typename v2::faest_em_128_s::vole_prg_t::iv_t, typename v2::faest_em_128_s::vole_prg_t::tweak_t, const vole_block* __restrict__, vole_block* __restrict__, vole_block* __restrict__);
template void vole_sender<v2::faest_em_128_f>(unsigned int, const block_secpar<v2::faest_em_128_f::secpar_v>* __restrict__, typename v2::faest_em_128_f::vole_prg_t::iv_t, typename v2::faest_em_128_f::vole_prg_t::tweak_t, const vole_block* __restrict__, vole_block* __restrict__, vole_block* __restrict__);
template void vole_sender<v2::faest_em_192_s>(unsigned int, const block_secpar<v2::faest_em_192_s::secpar_v>* __restrict__, typename v2::faest_em_192_s::vole_prg_t::iv_t, typename v2::faest_em_192_s::vole_prg_t::tweak_t, const vole_block* __restrict__, vole_block* __restrict__, vole_block* __restrict__);
template void vole_sender<v2::faest_em_192_f>(unsigned int, const block_secpar<v2::faest_em_192_f::secpar_v>* __restrict__, typename v2::faest_em_192_f::vole_prg_t::iv_t, typename v2::faest_em_192_f::vole_prg_t::tweak_t, const vole_block* __restrict__, vole_block* __restrict__, vole_block* __restrict__);
template void vole_sender<v2::faest_em_256_s>(unsigned int, const block_secpar<v2::faest_em_256_s::secpar_v>* __restrict__, typename v2::faest_em_256_s::vole_prg_t::iv_t, typename v2::faest_em_256_s::vole_prg_t::tweak_t, const vole_block* __restrict__, vole_block* __restrict__, vole_block* __restrict__);
template void vole_sender<v2::faest_em_256_f>(unsigned int, const block_secpar<v2::faest_em_256_f::secpar_v>* __restrict__, typename v2::faest_em_256_f::vole_prg_t::iv_t, typename v2::faest_em_256_f::vole_prg_t::tweak_t, const vole_block* __restrict__, vole_block* __restrict__, vole_block* __restrict__);
template void vole_sender<galas::galas_128s>(unsigned int, const block_secpar<galas::galas_128s::secpar_v>* __restrict__, typename galas::galas_128s::vole_prg_t::iv_t, typename galas::galas_128s::vole_prg_t::tweak_t, const vole_block* __restrict__, vole_block* __restrict__, vole_block* __restrict__);
template void vole_sender<galas::galas_128f>(unsigned int, const block_secpar<galas::galas_128f::secpar_v>* __restrict__, typename galas::galas_128f::vole_prg_t::iv_t, typename galas::galas_128f::vole_prg_t::tweak_t, const vole_block* __restrict__, vole_block* __restrict__, vole_block* __restrict__);
template void vole_sender<galas::galas_192s>(unsigned int, const block_secpar<galas::galas_192s::secpar_v>* __restrict__, typename galas::galas_192s::vole_prg_t::iv_t, typename galas::galas_192s::vole_prg_t::tweak_t, const vole_block* __restrict__, vole_block* __restrict__, vole_block* __restrict__);
template void vole_sender<galas::galas_192f>(unsigned int, const block_secpar<galas::galas_192f::secpar_v>* __restrict__, typename galas::galas_192f::vole_prg_t::iv_t, typename galas::galas_192f::vole_prg_t::tweak_t, const vole_block* __restrict__, vole_block* __restrict__, vole_block* __restrict__);
template void vole_sender<galas::galas_256s>(unsigned int, const block_secpar<galas::galas_256s::secpar_v>* __restrict__, typename galas::galas_256s::vole_prg_t::iv_t, typename galas::galas_256s::vole_prg_t::tweak_t, const vole_block* __restrict__, vole_block* __restrict__, vole_block* __restrict__);
template void vole_sender<galas::galas_ngcc_160s>(unsigned int, const block_secpar<galas::galas_ngcc_160s::secpar_v>* __restrict__, typename galas::galas_ngcc_160s::vole_prg_t::iv_t, typename galas::galas_ngcc_160s::vole_prg_t::tweak_t, const vole_block* __restrict__, vole_block* __restrict__, vole_block* __restrict__);
template void vole_sender<galas::galas_ngcc_384s>(unsigned int, const block_secpar<galas::galas_ngcc_384s::secpar_v>* __restrict__, typename galas::galas_ngcc_384s::vole_prg_t::iv_t, typename galas::galas_ngcc_384s::vole_prg_t::tweak_t, const vole_block* __restrict__, vole_block* __restrict__, vole_block* __restrict__);
template void vole_sender<galas::galas_ngcc_512s>(unsigned int, const block_secpar<galas::galas_ngcc_512s::secpar_v>* __restrict__, typename galas::galas_ngcc_512s::vole_prg_t::iv_t, typename galas::galas_ngcc_512s::vole_prg_t::tweak_t, const vole_block* __restrict__, vole_block* __restrict__, vole_block* __restrict__);
template void vole_sender<galas::galas_ngcc_256s>(unsigned int, const block_secpar<galas::galas_ngcc_256s::secpar_v>* __restrict__, typename galas::galas_ngcc_256s::vole_prg_t::iv_t, typename galas::galas_ngcc_256s::vole_prg_t::tweak_t, const vole_block* __restrict__, vole_block* __restrict__, vole_block* __restrict__);
template void vole_sender<galas::galas_256f>(unsigned int, const block_secpar<galas::galas_256f::secpar_v>* __restrict__, typename galas::galas_256f::vole_prg_t::iv_t, typename galas::galas_256f::vole_prg_t::tweak_t, const vole_block* __restrict__, vole_block* __restrict__, vole_block* __restrict__);
template void vole_sender<galas::galas_ngcc_160f>(unsigned int, const block_secpar<galas::galas_ngcc_160f::secpar_v>* __restrict__, typename galas::galas_ngcc_160f::vole_prg_t::iv_t, typename galas::galas_ngcc_160f::vole_prg_t::tweak_t, const vole_block* __restrict__, vole_block* __restrict__, vole_block* __restrict__);
template void vole_sender<galas::galas_ngcc_384f>(unsigned int, const block_secpar<galas::galas_ngcc_384f::secpar_v>* __restrict__, typename galas::galas_ngcc_384f::vole_prg_t::iv_t, typename galas::galas_ngcc_384f::vole_prg_t::tweak_t, const vole_block* __restrict__, vole_block* __restrict__, vole_block* __restrict__);
template void vole_sender<galas::galas_ngcc_512f>(unsigned int, const block_secpar<galas::galas_ngcc_512f::secpar_v>* __restrict__, typename galas::galas_ngcc_512f::vole_prg_t::iv_t, typename galas::galas_ngcc_512f::vole_prg_t::tweak_t, const vole_block* __restrict__, vole_block* __restrict__, vole_block* __restrict__);
template void vole_sender<galas::galas_ngcc_256f>(unsigned int, const block_secpar<galas::galas_ngcc_256f::secpar_v>* __restrict__, typename galas::galas_ngcc_256f::vole_prg_t::iv_t, typename galas::galas_ngcc_256f::vole_prg_t::tweak_t, const vole_block* __restrict__, vole_block* __restrict__, vole_block* __restrict__);

template void vole_receiver<v1::faest_128_s>(unsigned int, const block_secpar<v1::faest_128_s::secpar_v>* __restrict__, typename v1::faest_128_s::vole_prg_t::iv_t, typename v1::faest_128_s::vole_prg_t::tweak_t, const vole_block* __restrict__, vole_block* __restrict__, const uint8_t* __restrict__);
template void vole_receiver<v1::faest_128_f>(unsigned int, const block_secpar<v1::faest_128_f::secpar_v>* __restrict__, typename v1::faest_128_f::vole_prg_t::iv_t, typename v1::faest_128_f::vole_prg_t::tweak_t, const vole_block* __restrict__, vole_block* __restrict__, const uint8_t* __restrict__);
template void vole_receiver<v1::faest_192_s>(unsigned int, const block_secpar<v1::faest_192_s::secpar_v>* __restrict__, typename v1::faest_192_s::vole_prg_t::iv_t, typename v1::faest_192_s::vole_prg_t::tweak_t, const vole_block* __restrict__, vole_block* __restrict__, const uint8_t* __restrict__);
template void vole_receiver<v1::faest_192_f>(unsigned int, const block_secpar<v1::faest_192_f::secpar_v>* __restrict__, typename v1::faest_192_f::vole_prg_t::iv_t, typename v1::faest_192_f::vole_prg_t::tweak_t, const vole_block* __restrict__, vole_block* __restrict__, const uint8_t* __restrict__);
template void vole_receiver<v1::faest_256_s>(unsigned int, const block_secpar<v1::faest_256_s::secpar_v>* __restrict__, typename v1::faest_256_s::vole_prg_t::iv_t, typename v1::faest_256_s::vole_prg_t::tweak_t, const vole_block* __restrict__, vole_block* __restrict__, const uint8_t* __restrict__);
template void vole_receiver<v1::faest_256_f>(unsigned int, const block_secpar<v1::faest_256_f::secpar_v>* __restrict__, typename v1::faest_256_f::vole_prg_t::iv_t, typename v1::faest_256_f::vole_prg_t::tweak_t, const vole_block* __restrict__, vole_block* __restrict__, const uint8_t* __restrict__);
template void vole_receiver<v1::faest_em_128_s>(unsigned int, const block_secpar<v1::faest_em_128_s::secpar_v>* __restrict__, typename v1::faest_em_128_s::vole_prg_t::iv_t, typename v1::faest_em_128_s::vole_prg_t::tweak_t, const vole_block* __restrict__, vole_block* __restrict__, const uint8_t* __restrict__);
template void vole_receiver<v1::faest_em_128_f>(unsigned int, const block_secpar<v1::faest_em_128_f::secpar_v>* __restrict__, typename v1::faest_em_128_f::vole_prg_t::iv_t, typename v1::faest_em_128_f::vole_prg_t::tweak_t, const vole_block* __restrict__, vole_block* __restrict__, const uint8_t* __restrict__);
template void vole_receiver<v1::faest_em_192_s>(unsigned int, const block_secpar<v1::faest_em_192_s::secpar_v>* __restrict__, typename v1::faest_em_192_s::vole_prg_t::iv_t, typename v1::faest_em_192_s::vole_prg_t::tweak_t, const vole_block* __restrict__, vole_block* __restrict__, const uint8_t* __restrict__);
template void vole_receiver<v1::faest_em_192_f>(unsigned int, const block_secpar<v1::faest_em_192_f::secpar_v>* __restrict__, typename v1::faest_em_192_f::vole_prg_t::iv_t, typename v1::faest_em_192_f::vole_prg_t::tweak_t, const vole_block* __restrict__, vole_block* __restrict__, const uint8_t* __restrict__);
template void vole_receiver<v1::faest_em_256_s>(unsigned int, const block_secpar<v1::faest_em_256_s::secpar_v>* __restrict__, typename v1::faest_em_256_s::vole_prg_t::iv_t, typename v1::faest_em_256_s::vole_prg_t::tweak_t, const vole_block* __restrict__, vole_block* __restrict__, const uint8_t* __restrict__);
template void vole_receiver<v1::faest_em_256_f>(unsigned int, const block_secpar<v1::faest_em_256_f::secpar_v>* __restrict__, typename v1::faest_em_256_f::vole_prg_t::iv_t, typename v1::faest_em_256_f::vole_prg_t::tweak_t, const vole_block* __restrict__, vole_block* __restrict__, const uint8_t* __restrict__);
template void vole_receiver<v2::faest_128_s>(unsigned int, const block_secpar<v2::faest_128_s::secpar_v>* __restrict__, typename v2::faest_128_s::vole_prg_t::iv_t, typename v2::faest_128_s::vole_prg_t::tweak_t, const vole_block* __restrict__, vole_block* __restrict__, const uint8_t* __restrict__);
template void vole_receiver<v2::faest_128_f>(unsigned int, const block_secpar<v2::faest_128_f::secpar_v>* __restrict__, typename v2::faest_128_f::vole_prg_t::iv_t, typename v2::faest_128_f::vole_prg_t::tweak_t, const vole_block* __restrict__, vole_block* __restrict__, const uint8_t* __restrict__);
template void vole_receiver<v2::faest_192_s>(unsigned int, const block_secpar<v2::faest_192_s::secpar_v>* __restrict__, typename v2::faest_192_s::vole_prg_t::iv_t, typename v2::faest_192_s::vole_prg_t::tweak_t, const vole_block* __restrict__, vole_block* __restrict__, const uint8_t* __restrict__);
template void vole_receiver<v2::faest_192_f>(unsigned int, const block_secpar<v2::faest_192_f::secpar_v>* __restrict__, typename v2::faest_192_f::vole_prg_t::iv_t, typename v2::faest_192_f::vole_prg_t::tweak_t, const vole_block* __restrict__, vole_block* __restrict__, const uint8_t* __restrict__);
template void vole_receiver<v2::faest_256_s>(unsigned int, const block_secpar<v2::faest_256_s::secpar_v>* __restrict__, typename v2::faest_256_s::vole_prg_t::iv_t, typename v2::faest_256_s::vole_prg_t::tweak_t, const vole_block* __restrict__, vole_block* __restrict__, const uint8_t* __restrict__);
template void vole_receiver<v2::faest_256_f>(unsigned int, const block_secpar<v2::faest_256_f::secpar_v>* __restrict__, typename v2::faest_256_f::vole_prg_t::iv_t, typename v2::faest_256_f::vole_prg_t::tweak_t, const vole_block* __restrict__, vole_block* __restrict__, const uint8_t* __restrict__);
template void vole_receiver<v2::faest_em_128_s>(unsigned int, const block_secpar<v2::faest_em_128_s::secpar_v>* __restrict__, typename v2::faest_em_128_s::vole_prg_t::iv_t, typename v2::faest_em_128_s::vole_prg_t::tweak_t, const vole_block* __restrict__, vole_block* __restrict__, const uint8_t* __restrict__);
template void vole_receiver<v2::faest_em_128_f>(unsigned int, const block_secpar<v2::faest_em_128_f::secpar_v>* __restrict__, typename v2::faest_em_128_f::vole_prg_t::iv_t, typename v2::faest_em_128_f::vole_prg_t::tweak_t, const vole_block* __restrict__, vole_block* __restrict__, const uint8_t* __restrict__);
template void vole_receiver<v2::faest_em_192_s>(unsigned int, const block_secpar<v2::faest_em_192_s::secpar_v>* __restrict__, typename v2::faest_em_192_s::vole_prg_t::iv_t, typename v2::faest_em_192_s::vole_prg_t::tweak_t, const vole_block* __restrict__, vole_block* __restrict__, const uint8_t* __restrict__);
template void vole_receiver<v2::faest_em_192_f>(unsigned int, const block_secpar<v2::faest_em_192_f::secpar_v>* __restrict__, typename v2::faest_em_192_f::vole_prg_t::iv_t, typename v2::faest_em_192_f::vole_prg_t::tweak_t, const vole_block* __restrict__, vole_block* __restrict__, const uint8_t* __restrict__);
template void vole_receiver<v2::faest_em_256_s>(unsigned int, const block_secpar<v2::faest_em_256_s::secpar_v>* __restrict__, typename v2::faest_em_256_s::vole_prg_t::iv_t, typename v2::faest_em_256_s::vole_prg_t::tweak_t, const vole_block* __restrict__, vole_block* __restrict__, const uint8_t* __restrict__);
template void vole_receiver<v2::faest_em_256_f>(unsigned int, const block_secpar<v2::faest_em_256_f::secpar_v>* __restrict__, typename v2::faest_em_256_f::vole_prg_t::iv_t, typename v2::faest_em_256_f::vole_prg_t::tweak_t, const vole_block* __restrict__, vole_block* __restrict__, const uint8_t* __restrict__);
template void vole_receiver<galas::galas_128s>(unsigned int, const block_secpar<galas::galas_128s::secpar_v>* __restrict__, typename galas::galas_128s::vole_prg_t::iv_t, typename galas::galas_128s::vole_prg_t::tweak_t, const vole_block* __restrict__, vole_block* __restrict__, const uint8_t* __restrict__);
template void vole_receiver<galas::galas_128f>(unsigned int, const block_secpar<galas::galas_128f::secpar_v>* __restrict__, typename galas::galas_128f::vole_prg_t::iv_t, typename galas::galas_128f::vole_prg_t::tweak_t, const vole_block* __restrict__, vole_block* __restrict__, const uint8_t* __restrict__);
template void vole_receiver<galas::galas_192s>(unsigned int, const block_secpar<galas::galas_192s::secpar_v>* __restrict__, typename galas::galas_192s::vole_prg_t::iv_t, typename galas::galas_192s::vole_prg_t::tweak_t, const vole_block* __restrict__, vole_block* __restrict__, const uint8_t* __restrict__);
template void vole_receiver<galas::galas_192f>(unsigned int, const block_secpar<galas::galas_192f::secpar_v>* __restrict__, typename galas::galas_192f::vole_prg_t::iv_t, typename galas::galas_192f::vole_prg_t::tweak_t, const vole_block* __restrict__, vole_block* __restrict__, const uint8_t* __restrict__);
template void vole_receiver<galas::galas_256s>(unsigned int, const block_secpar<galas::galas_256s::secpar_v>* __restrict__, typename galas::galas_256s::vole_prg_t::iv_t, typename galas::galas_256s::vole_prg_t::tweak_t, const vole_block* __restrict__, vole_block* __restrict__, const uint8_t* __restrict__);
template void vole_receiver<galas::galas_ngcc_160s>(unsigned int, const block_secpar<galas::galas_ngcc_160s::secpar_v>* __restrict__, typename galas::galas_ngcc_160s::vole_prg_t::iv_t, typename galas::galas_ngcc_160s::vole_prg_t::tweak_t, const vole_block* __restrict__, vole_block* __restrict__, const uint8_t* __restrict__);
template void vole_receiver<galas::galas_ngcc_384s>(unsigned int, const block_secpar<galas::galas_ngcc_384s::secpar_v>* __restrict__, typename galas::galas_ngcc_384s::vole_prg_t::iv_t, typename galas::galas_ngcc_384s::vole_prg_t::tweak_t, const vole_block* __restrict__, vole_block* __restrict__, const uint8_t* __restrict__);
template void vole_receiver<galas::galas_ngcc_512s>(unsigned int, const block_secpar<galas::galas_ngcc_512s::secpar_v>* __restrict__, typename galas::galas_ngcc_512s::vole_prg_t::iv_t, typename galas::galas_ngcc_512s::vole_prg_t::tweak_t, const vole_block* __restrict__, vole_block* __restrict__, const uint8_t* __restrict__);
template void vole_receiver<galas::galas_ngcc_256s>(unsigned int, const block_secpar<galas::galas_ngcc_256s::secpar_v>* __restrict__, typename galas::galas_ngcc_256s::vole_prg_t::iv_t, typename galas::galas_ngcc_256s::vole_prg_t::tweak_t, const vole_block* __restrict__, vole_block* __restrict__, const uint8_t* __restrict__);
template void vole_receiver<galas::galas_256f>(unsigned int, const block_secpar<galas::galas_256f::secpar_v>* __restrict__, typename galas::galas_256f::vole_prg_t::iv_t, typename galas::galas_256f::vole_prg_t::tweak_t, const vole_block* __restrict__, vole_block* __restrict__, const uint8_t* __restrict__);
template void vole_receiver<galas::galas_ngcc_160f>(unsigned int, const block_secpar<galas::galas_ngcc_160f::secpar_v>* __restrict__, typename galas::galas_ngcc_160f::vole_prg_t::iv_t, typename galas::galas_ngcc_160f::vole_prg_t::tweak_t, const vole_block* __restrict__, vole_block* __restrict__, const uint8_t* __restrict__);
template void vole_receiver<galas::galas_ngcc_384f>(unsigned int, const block_secpar<galas::galas_ngcc_384f::secpar_v>* __restrict__, typename galas::galas_ngcc_384f::vole_prg_t::iv_t, typename galas::galas_ngcc_384f::vole_prg_t::tweak_t, const vole_block* __restrict__, vole_block* __restrict__, const uint8_t* __restrict__);
template void vole_receiver<galas::galas_ngcc_512f>(unsigned int, const block_secpar<galas::galas_ngcc_512f::secpar_v>* __restrict__, typename galas::galas_ngcc_512f::vole_prg_t::iv_t, typename galas::galas_ngcc_512f::vole_prg_t::tweak_t, const vole_block* __restrict__, vole_block* __restrict__, const uint8_t* __restrict__);
template void vole_receiver<galas::galas_ngcc_256f>(unsigned int, const block_secpar<galas::galas_ngcc_256f::secpar_v>* __restrict__, typename galas::galas_ngcc_256f::vole_prg_t::iv_t, typename galas::galas_ngcc_256f::vole_prg_t::tweak_t, const vole_block* __restrict__, vole_block* __restrict__, const uint8_t* __restrict__);

template void vole_receiver_apply_correction<v1::faest_128_s>(size_t, size_t, const vole_block* __restrict__, vole_block* __restrict__, const uint8_t* __restrict__);
template void vole_receiver_apply_correction<v1::faest_128_f>(size_t, size_t, const vole_block* __restrict__, vole_block* __restrict__, const uint8_t* __restrict__);
template void vole_receiver_apply_correction<v1::faest_192_s>(size_t, size_t, const vole_block* __restrict__, vole_block* __restrict__, const uint8_t* __restrict__);
template void vole_receiver_apply_correction<v1::faest_192_f>(size_t, size_t, const vole_block* __restrict__, vole_block* __restrict__, const uint8_t* __restrict__);
template void vole_receiver_apply_correction<v1::faest_256_s>(size_t, size_t, const vole_block* __restrict__, vole_block* __restrict__, const uint8_t* __restrict__);
template void vole_receiver_apply_correction<v1::faest_256_f>(size_t, size_t, const vole_block* __restrict__, vole_block* __restrict__, const uint8_t* __restrict__);
template void vole_receiver_apply_correction<v1::faest_em_128_s>(size_t, size_t, const vole_block* __restrict__, vole_block* __restrict__, const uint8_t* __restrict__);
template void vole_receiver_apply_correction<v1::faest_em_128_f>(size_t, size_t, const vole_block* __restrict__, vole_block* __restrict__, const uint8_t* __restrict__);
template void vole_receiver_apply_correction<v1::faest_em_192_s>(size_t, size_t, const vole_block* __restrict__, vole_block* __restrict__, const uint8_t* __restrict__);
template void vole_receiver_apply_correction<v1::faest_em_192_f>(size_t, size_t, const vole_block* __restrict__, vole_block* __restrict__, const uint8_t* __restrict__);
template void vole_receiver_apply_correction<v1::faest_em_256_s>(size_t, size_t, const vole_block* __restrict__, vole_block* __restrict__, const uint8_t* __restrict__);
template void vole_receiver_apply_correction<v1::faest_em_256_f>(size_t, size_t, const vole_block* __restrict__, vole_block* __restrict__, const uint8_t* __restrict__);
template void vole_receiver_apply_correction<v2::faest_128_s>(size_t, size_t, const vole_block* __restrict__, vole_block* __restrict__, const uint8_t* __restrict__);
template void vole_receiver_apply_correction<v2::faest_128_f>(size_t, size_t, const vole_block* __restrict__, vole_block* __restrict__, const uint8_t* __restrict__);
template void vole_receiver_apply_correction<v2::faest_192_s>(size_t, size_t, const vole_block* __restrict__, vole_block* __restrict__, const uint8_t* __restrict__);
template void vole_receiver_apply_correction<v2::faest_192_f>(size_t, size_t, const vole_block* __restrict__, vole_block* __restrict__, const uint8_t* __restrict__);
template void vole_receiver_apply_correction<v2::faest_256_s>(size_t, size_t, const vole_block* __restrict__, vole_block* __restrict__, const uint8_t* __restrict__);
template void vole_receiver_apply_correction<v2::faest_256_f>(size_t, size_t, const vole_block* __restrict__, vole_block* __restrict__, const uint8_t* __restrict__);
template void vole_receiver_apply_correction<v2::faest_em_128_s>(size_t, size_t, const vole_block* __restrict__, vole_block* __restrict__, const uint8_t* __restrict__);
template void vole_receiver_apply_correction<v2::faest_em_128_f>(size_t, size_t, const vole_block* __restrict__, vole_block* __restrict__, const uint8_t* __restrict__);
template void vole_receiver_apply_correction<v2::faest_em_192_s>(size_t, size_t, const vole_block* __restrict__, vole_block* __restrict__, const uint8_t* __restrict__);
template void vole_receiver_apply_correction<v2::faest_em_192_f>(size_t, size_t, const vole_block* __restrict__, vole_block* __restrict__, const uint8_t* __restrict__);
template void vole_receiver_apply_correction<v2::faest_em_256_s>(size_t, size_t, const vole_block* __restrict__, vole_block* __restrict__, const uint8_t* __restrict__);
template void vole_receiver_apply_correction<v2::faest_em_256_f>(size_t, size_t, const vole_block* __restrict__, vole_block* __restrict__, const uint8_t* __restrict__);
template void vole_receiver_apply_correction<galas::galas_128s>(size_t, size_t, const vole_block* __restrict__, vole_block* __restrict__, const uint8_t* __restrict__);
template void vole_receiver_apply_correction<galas::galas_128f>(size_t, size_t, const vole_block* __restrict__, vole_block* __restrict__, const uint8_t* __restrict__);
template void vole_receiver_apply_correction<galas::galas_192s>(size_t, size_t, const vole_block* __restrict__, vole_block* __restrict__, const uint8_t* __restrict__);
template void vole_receiver_apply_correction<galas::galas_192f>(size_t, size_t, const vole_block* __restrict__, vole_block* __restrict__, const uint8_t* __restrict__);
template void vole_receiver_apply_correction<galas::galas_256s>(size_t, size_t, const vole_block* __restrict__, vole_block* __restrict__, const uint8_t* __restrict__);
template void vole_receiver_apply_correction<galas::galas_ngcc_160s>(size_t, size_t, const vole_block* __restrict__, vole_block* __restrict__, const uint8_t* __restrict__);
template void vole_receiver_apply_correction<galas::galas_ngcc_384s>(size_t, size_t, const vole_block* __restrict__, vole_block* __restrict__, const uint8_t* __restrict__);
template void vole_receiver_apply_correction<galas::galas_ngcc_512s>(size_t, size_t, const vole_block* __restrict__, vole_block* __restrict__, const uint8_t* __restrict__);
template void vole_receiver_apply_correction<galas::galas_ngcc_256s>(size_t, size_t, const vole_block* __restrict__, vole_block* __restrict__, const uint8_t* __restrict__);
template void vole_receiver_apply_correction<galas::galas_256f>(size_t, size_t, const vole_block* __restrict__, vole_block* __restrict__, const uint8_t* __restrict__);
template void vole_receiver_apply_correction<galas::galas_ngcc_160f>(size_t, size_t, const vole_block* __restrict__, vole_block* __restrict__, const uint8_t* __restrict__);
template void vole_receiver_apply_correction<galas::galas_ngcc_384f>(size_t, size_t, const vole_block* __restrict__, vole_block* __restrict__, const uint8_t* __restrict__);
template void vole_receiver_apply_correction<galas::galas_ngcc_512f>(size_t, size_t, const vole_block* __restrict__, vole_block* __restrict__, const uint8_t* __restrict__);
template void vole_receiver_apply_correction<galas::galas_ngcc_256f>(size_t, size_t, const vole_block* __restrict__, vole_block* __restrict__, const uint8_t* __restrict__);
// clang-format on

} // namespace faest
