

# This file was *autogenerated* from the file precompute_quaternion_data.sage
from sage.all_cmdline import *   # import sage library

_sage_const_9 = Integer(9); _sage_const_8 = Integer(8); _sage_const_7 = Integer(7); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_0 = Integer(0); _sage_const_3 = Integer(3); _sage_const_4 = Integer(4)#!/usr/bin/env sage
proof.all(False)  # faster

from sage.misc.banner import require_version
if not require_version(_sage_const_9 , _sage_const_8 , print_message=True):
    exit('')

################################################################

from parameters import p
num = _sage_const_7   #TODO how many extra maximal orders to precompute?

################################################################

# Underlying theory:
# - Ibukiyama, On maximal orders of division quaternion algebras with certain optimal embeddings
# - https://ia.cr/2023/106 Lemma 10

from sage.algebras.quatalg.quaternion_algebra import basis_for_quaternion_lattice
bfql = lambda els: basis_for_quaternion_lattice(els, reverse=True)

Quat = QuaternionAlgebra(-_sage_const_1 , -p, names=('i', 'j', 'k',)); (i, j, k,) = Quat._first_ngens(3)
assert Quat.discriminant() == p         # ramifies correctly

orders = []

q = _sage_const_1 
while len(orders) < num:
    q = next_prime(q)

    if q == _sage_const_2 :
        continue

    Quat2 = QuaternionAlgebra(-q, -p, names=('ii', 'jj', 'kk',)); (ii, jj, kk,) = Quat2._first_ngens(3)
    if Quat2.discriminant() != p:       # ramifies incorrectly
        continue

    x, y = QuadraticForm(QQ, _sage_const_2 , [_sage_const_1 ,_sage_const_0 ,p]).solve(q)
    gamma = x + j*y
    assert gamma.reduced_norm() == q
    ims = [Quat(_sage_const_1 ), i*gamma, j, k*gamma]
    assert ims[_sage_const_1 ]**_sage_const_2  == -q
    assert ims[_sage_const_2 ]**_sage_const_2  == -p
    assert ims[_sage_const_1 ]*ims[_sage_const_2 ] == ims[_sage_const_3 ]
    assert ims[_sage_const_2 ]*ims[_sage_const_1 ] == -ims[_sage_const_3 ]
    # (1,ii,jj,kk)->ims is an isomorphism Quat2->Quat

    r = min(map(ZZ, Mod(-p, _sage_const_4 *q).sqrt(all=True)))

    if q % _sage_const_4  == _sage_const_3 :
        bas2 = [
                Quat2(_sage_const_1 ),
                (_sage_const_1  + ii) / _sage_const_2 ,
                jj * (_sage_const_1  + ii) / _sage_const_2 ,
                (r + jj) * ii / q,
            ]
    else:
        bas2 = [
                Quat2(_sage_const_1 ),
                ii,
                (_sage_const_1  + jj) / _sage_const_2 ,
                (r + jj) * ii / _sage_const_2  / q,
            ]
    O2 = Quat2.quaternion_order(bas2)
    assert O2.discriminant() == p       # is maximal

    bas = [sum(c*im for c,im in zip(el,ims)) for el in bas2]
    bas = bfql(bas)
    O = Quat.quaternion_order(bas)
    assert O.discriminant() == p        # is maximal
    assert j in O                       # p-extremal

    mat = matrix(map(list, bas))
#    print(f'{q = }\nsqrt(-q) = {ims[1]}\n    {(chr(10)+"    ").join(map(str,bas))}', file=sys.stderr)
    assert mat[_sage_const_0 ] == vector((_sage_const_1 ,_sage_const_0 ,_sage_const_0 ,_sage_const_0 ))
    orders.append((q, ims[_sage_const_1 ], mat))

################################################################

gram = matrix(ZZ, [
    [((gi+gj).reduced_norm() - gi.reduced_norm() - gj.reduced_norm()) / _sage_const_2 
        for gi in Quat.basis()] for gj in Quat.basis()])

O0mat = matrix([list(g) for g in [Quat(_sage_const_1 ), i, (i+j)/_sage_const_2 , (_sage_const_1 +k)/_sage_const_2 ]])

################################################################

from cformat import Ibz, Object, ObjectFormatter

algobj = [Ibz(p), [[Ibz(v) for v in vs] for vs in gram]]
O0ord = [Ibz(O0mat.denominator()), [[Ibz(v*O0mat.denominator()) for v in vs] for vs in O0mat.transpose()]]
O0obj = [O0ord, [Ibz(_sage_const_1 ), [Ibz(c) for c in (_sage_const_0 ,_sage_const_1 ,_sage_const_0 ,_sage_const_0 )]], [Ibz(_sage_const_1 ), [Ibz(c) for c in (_sage_const_0 ,_sage_const_0 ,_sage_const_1 ,_sage_const_0 )]], _sage_const_1 ]

objs = [[[Ibz(mat.denominator()), [[Ibz(v*mat.denominator()) for v in vs] for vs in mat.transpose()]], [Ibz(mat.denominator()), [Ibz(c*mat.denominator()) for c in ii]], [Ibz(_sage_const_1 ), [Ibz(c) for c in (_sage_const_0 ,_sage_const_0 ,_sage_const_1 ,_sage_const_0 )]], q] for q,ii,mat in orders]

objs = ObjectFormatter([
        Object('quat_alg_t', 'QUATALG_PINFTY', algobj),
        Object('quat_order_t', 'MAXORD_O0', O0ord),
        Object('quat_p_extremal_maximal_order_t', 'STANDARD_EXTREMAL_ORDER', O0obj),
        Object('quat_p_extremal_maximal_order_t[]', 'ALTERNATE_EXTREMAL_ORDERS', objs),
    ])

with open('include/quaternion_data.h','w') as hfile:
    with open('quaternion_data.c','w') as cfile:
        print(f'#include <intbig.h>', file=hfile)
        print(f'#include <quaternion.h>', file=hfile)
        print(f'#include <stddef.h>', file=cfile)
        print(f'#include <stdint.h>', file=cfile)
        print(f'#include <quaternion_data.h>', file=cfile)

        print(f'#define NUM_ALTERNATE_EXTREMAL_ORDERS {len(orders)}', file=hfile)

        objs.header(file=hfile)
        objs.implementation(file=cfile)


