set(SOURCE_FILES_PROTOCOLS_${SVARIANT_UPPER}
    v8protocols.c
)

set(INC_PROTOCOLS_${SVARIANT_UPPER} ${COMMON_SRC_DIR}/protocols/include CACHE INTERNAL "INC")
set(LIB_PROTOCOLS_${SVARIANT_UPPER} niike_protocols_${SVARIANT} CACHE INTERNAL "LIB")
add_library(${LIB_PROTOCOLS_${SVARIANT_UPPER}} STATIC ${SOURCE_FILES_PROTOCOLS_${SVARIANT_UPPER}})
target_include_directories(${LIB_PROTOCOLS_${SVARIANT_UPPER}} PRIVATE ${INC_COMMON_${SVARIANT_UPPER}} ${INC_PROTOCOLS_${SVARIANT_UPPER}} ${INC_PRECOMP_${SVARIANT_UPPER}} ${INC_GF_${SVARIANT_UPPER}} ${INC_EC_${SVARIANT_UPPER}})
target_compile_options(${LIB_PROTOCOLS_${SVARIANT_UPPER}} PRIVATE ${C_OPT_FLAGS})
target_link_libraries(${LIB_PROTOCOLS_${SVARIANT_UPPER}} ${LIB_EC_${SVARIANT_UPPER}} ${LIB_COMMON_${SVARIANT_UPPER}})
