/* rounding_consts.h -- AUTO-GENERATED by tools/gen_rounding.py.
 * Division-free round-to-nearest (ties UP, toward +inf) magic
 * reciprocals for CompressY (alpha_1/alpha_s/alpha_e) + the alpha_h
 * highbits shift.  Round-half-up is SHIFT-INVARIANT, so it preserves
 * the CompressY translation identity for every divisor (round-half-
 * away broke it on even divisors).  Verified exact for |v| < 2^20.
 * DO NOT hand-edit; regenerate via `python3 tools/gen_rounding.py`. */
#ifndef SHUTTLE_ROUNDING_CONSTS_H
#define SHUTTLE_ROUNDING_CONSTS_H

#include <stdint.h>

#include "params.h"
/* Disable with -DDISABLE_NAMESPACE=1. */
#include "namespace.h"

#if SHUTTLE_MODE == 128
#    define RCP_ALPHA_1 INT64_C(2982617) /* alpha=90: ceil(2^29/(2*alpha)) */
#    define SH_ROUND_1 29
#    define ROUND_BIAS_1 INT64_C(6255353155590) /* alpha*RECIP (+alpha/2 tie) + 2*K*alpha*RECIP (offset) */
#    define ROUND_K_1 INT32_C(11651) /* offset quotient K = ceil(2^20/alpha) */
#    define RCP_ALPHA_S INT64_C(838861) /* alpha=10: ceil(2^24/(2*alpha)) */
#    define SH_ROUND_S 24
#    define ROUND_BIAS_S INT64_C(1759234123370) /* alpha*RECIP (+alpha/2 tie) + 2*K*alpha*RECIP (offset) */
#    define ROUND_K_S INT32_C(104858) /* offset quotient K = ceil(2^20/alpha) */
#    define RCP_ALPHA_E INT64_C(6710887) /* alpha=5: ceil(2^26/(2*alpha)) */
#    define SH_ROUND_E 26
#    define ROUND_BIAS_E INT64_C(14073837335355) /* alpha*RECIP (+alpha/2 tie) + 2*K*alpha*RECIP (offset) */
#    define ROUND_K_E INT32_C(209716) /* offset quotient K = ceil(2^20/alpha) */
#    define LOG2_ALPHA_H 10 /* alpha_h=1024 = 1<<10 */
#endif

#if SHUTTLE_MODE == 256
#    define RCP_ALPHA_1 INT64_C(1988411) /* alpha=135: ceil(2^29/(2*alpha)) */
#    define SH_ROUND_1 29
#    define ROUND_BIAS_1 INT64_C(4170682130445) /* alpha*RECIP (+alpha/2 tie) + 2*K*alpha*RECIP (offset) */
#    define ROUND_K_1 INT32_C(7768) /* offset quotient K = ceil(2^20/alpha) */
#    define RCP_ALPHA_S INT64_C(6710887) /* alpha=5: ceil(2^26/(2*alpha)) */
#    define SH_ROUND_S 26
#    define ROUND_BIAS_S INT64_C(14073837335355) /* alpha*RECIP (+alpha/2 tie) + 2*K*alpha*RECIP (offset) */
#    define ROUND_K_S INT32_C(209716) /* offset quotient K = ceil(2^20/alpha) */
#    define RCP_ALPHA_E INT64_C(6710887) /* alpha=5: ceil(2^26/(2*alpha)) */
#    define SH_ROUND_E 26
#    define ROUND_BIAS_E INT64_C(14073837335355) /* alpha*RECIP (+alpha/2 tie) + 2*K*alpha*RECIP (offset) */
#    define ROUND_K_E INT32_C(209716) /* offset quotient K = ceil(2^20/alpha) */
#    define LOG2_ALPHA_H 10 /* alpha_h=1024 = 1<<10 */
#endif

#if SHUTTLE_MODE == 512
#    define RCP_ALPHA_1 INT64_C(3728271) /* alpha=144: ceil(2^30/(2*alpha)) */
#    define SH_ROUND_1 30
#    define ROUND_BIAS_1 INT64_C(7819526464560) /* alpha*RECIP (+alpha/2 tie) + 2*K*alpha*RECIP (offset) */
#    define ROUND_K_1 INT32_C(7282) /* offset quotient K = ceil(2^20/alpha) */
#    define RCP_ALPHA_S INT64_C(2796203) /* alpha=3: ceil(2^24/(2*alpha)) */
#    define SH_ROUND_S 24
#    define ROUND_BIAS_S INT64_C(5864082287277) /* alpha*RECIP (+alpha/2 tie) + 2*K*alpha*RECIP (offset) */
#    define ROUND_K_S INT32_C(349526) /* offset quotient K = ceil(2^20/alpha) */
#    define RCP_ALPHA_E INT64_C(2796203) /* alpha=3: ceil(2^24/(2*alpha)) */
#    define SH_ROUND_E 24
#    define ROUND_BIAS_E INT64_C(5864082287277) /* alpha*RECIP (+alpha/2 tie) + 2*K*alpha*RECIP (offset) */
#    define ROUND_K_E INT32_C(349526) /* offset quotient K = ceil(2^20/alpha) */
#    define LOG2_ALPHA_H 11 /* alpha_h=2048 = 1<<11 */
#endif

/* Cross-check: alpha_h must be the power of two LOG2_ALPHA_H encodes. */
_Static_assert(ALPHA_H == (1 << LOG2_ALPHA_H),
               "alpha_h must equal 1 << LOG2_ALPHA_H");
_Static_assert((ALPHA_B & (ALPHA_B - 1)) == 0,
               "alpha_b must be a power of two");

#endif /* SHUTTLE_ROUNDING_CONSTS_H */
