#ifndef PARAMS_H
#define PARAMS_H

#define NTRUOAEP_N 1296
#define NTRUOAEP_Q 17497

#define NTRUOAEP_SSBYTES 32
#define NTRUOAEP_SYMBYTES  64
#define KeyConfirmation_BYTES (NTRUOAEP_SSBYTES + NTRUOAEP_SYMBYTES)
#define NTRUOAEP_POLYBYTES 2430
#define NTRUOAEP_MAXPLAINTEXT 162

#define NTRUOAEP_PUBLICKEYBYTES  NTRUOAEP_POLYBYTES
#define NTRUOAEP_SECRETKEYBYTES  ((NTRUOAEP_POLYBYTES << 1) + NTRUOAEP_SYMBYTES)
#define NTRUOAEP_CIPHERTEXTBYTES  (NTRUOAEP_POLYBYTES + NTRUOAEP_SYMBYTES)

#define NTRUOAEP_PKEM_CIPHERTEXTBYTES  (NTRUOAEP_POLYBYTES + NTRUOAEP_SYMBYTES)


#endif
