#!/usr/bin/env python3
"""Generate static Reed-Solomon generator polynomials for implemented HARE instances."""
import argparse
import difflib
from pathlib import Path
from typing import List

GF_POLY = 0x11D
PARAMETER_SETS = (
    (16, 32, "HARE-128 KR / HARE-2"),
    (32, 81, "HARE-256 KR / HARE-5"),
    (48, 91, "HARE-384 KR / HARE-7"),
    (64, 151, "HARE-512 KR / HARE-9"),
)


def gf_mul(a: int, b: int) -> int:
    r = 0
    while b:
        if b & 1:
            r ^= a
        b >>= 1
        a <<= 1
        if a & 0x100:
            a ^= GF_POLY
    return r & 0xFF


def gf_exp_table() -> List[int]:
    out = []
    x = 1
    for _ in range(255):
        out.append(x)
        x <<= 1
        if x & 0x100:
            x ^= GF_POLY
    return out


def generator_poly(k: int, n1: int) -> List[int]:
    parity = n1 - k
    exp = gf_exp_table()
    poly = [1]
    for i in range(1, parity + 1):
        root = exp[i % 255]
        nxt = [0] * (len(poly) + 1)
        nxt[0] = gf_mul(poly[0], root)
        for j in range(1, len(poly)):
            nxt[j] = poly[j - 1] ^ gf_mul(poly[j], root)
        nxt[len(poly)] = poly[-1]
        poly = nxt
    return poly


def wrap(values: List[int], width: int = 16) -> str:
    lines = []
    for i in range(0, len(values), width):
        lines.append("    " + ", ".join(str(v) for v in values[i:i+width]) + ",\n")
    return "".join(lines)


def generate() -> str:
    parts = ["""#ifndef HARE_RS_GENERATOR_CONSTANTS_GENERATED_H
#define HARE_RS_GENERATOR_CONSTANTS_GENERATED_H

/*
 * Generated by tools/generators/generate_rs_generator_constants.py.
 *
 * For each implemented shortened RS[n1,k] code over GF(2^8), this header
 * contains g(x)=prod_{i=1}^{n1-k}(x+alpha^i), using primitive polynomial
 * x^8+x^4+x^3+x^2+1 (0x11D). All selectors are public compile-time parameters.
 */

"""]
    for idx, (k, n1, label) in enumerate(PARAMETER_SETS):
        parts.append(("#if" if idx == 0 else "#elif") + f" (PARAM_K == {k} && PARAM_N1 == {n1})\n")
        parts.append(f"/* {label}; PARAM_G={n1-k+1}. */\n")
        parts.append("static const uint16_t rs_generator_poly_const[PARAM_G] = {\n")
        parts.append(wrap(generator_poly(k, n1)))
        parts.append("};\n")
    parts.append('#else\n#error "Unsupported HARE optimized RS parameter set"\n#endif\n\n')
    parts.append("#endif /* HARE_RS_GENERATOR_CONSTANTS_GENERATED_H */\n")
    return "".join(parts)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, default=Path(__file__).resolve().parents[2] / "Implementations/_shared/hare_core/common/rs_generator_constants_generated.h")
    group = parser.add_mutually_exclusive_group()
    group.add_argument("--write", action="store_true")
    group.add_argument("--check", action="store_true")
    args = parser.parse_args()
    text = generate()
    if args.check:
        current = args.output.read_text() if args.output.exists() else ""
        if current != text:
            print("RS generator constants differ:", args.output)
            for line in difflib.unified_diff(current.splitlines(), text.splitlines(), fromfile="current", tofile="generated", n=3):
                print(line)
            return 1
        print("RS generator constants check: PASS")
        return 0
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(text)
    print(args.output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
