#!/usr/bin/env python3
"""Generate the static KR [51,41] radius-2 syndrome leader table."""
import argparse
import difflib
from pathlib import Path
from typing import List, Tuple

KR_N = 51
KR_K = 41
KR_R = 10
KR_M_ROWS = (
    0xA8FE70FC2A,
    0x52C05A8E7B,
    0x17DDD5D677D,
    0x1D2E904544,
    0x1A4D94F4333,
    0xCFA303A571,
    0x1F3506F20F4,
    0x14BD402923F,
    0xB17A40F8DF,
    0xD75EC73E00,
)


def build() -> Tuple[List[int], List[int], List[int]]:
    cols = [0] * KR_N
    for i in range(KR_R):
        cols[i] = 1 << i
    for j in range(KR_K):
        col = 0
        for r, row in enumerate(KR_M_ROWS):
            col |= ((row >> j) & 1) << r
        cols[KR_R + j] = col

    weights = [0xFF] * (1 << KR_R)
    leaders = [0] * (1 << KR_R)
    weights[0] = 0
    for i, syndrome in enumerate(cols):
        if weights[syndrome] > 1:
            weights[syndrome] = 1
            leaders[syndrome] = 1 << i
    for i in range(KR_N):
        for j in range(i + 1, KR_N):
            syndrome = cols[i] ^ cols[j]
            if weights[syndrome] > 2:
                weights[syndrome] = 2
                leaders[syndrome] = (1 << i) | (1 << j)
    if max(weights) > 2:
        raise RuntimeError("KR table does not cover all syndromes with radius 2")
    return cols, weights, leaders


def format_array(name: str, ctype: str, values: List[int], per_line: int, formatter) -> str:
    lines = [f"static const {ctype} {name}[{len(values)}] = {{\n"]
    for i in range(0, len(values), per_line):
        chunk = ", ".join(formatter(v) for v in values[i:i+per_line])
        lines.append(f"    {chunk},\n")
    lines.append("};\n")
    return "".join(lines)


def generate() -> str:
    cols, weights, leaders = build()
    text = """#ifndef HARE_KR_SYNDROME_TABLE_GENERATED_H
#define HARE_KR_SYNDROME_TABLE_GENERATED_H

/*
 * Generated by tools/generators/generate_kr_syndrome_table.py from the public
 * H_KR=[I_10|M_KR] matrix. The leader table contains the deterministic first
 * minimum-weight (0, 1, or 2) leader for every 10-bit syndrome.
 */

#include <stdint.h>

"""
    text += format_array("KR_COLUMN_SYNDROME", "uint16_t", cols, 8, lambda v: f"UINT16_C(0x{v:03x})")
    text += "\n"
    text += format_array("KR_SYNDROME_WEIGHT", "uint8_t", weights, 16, lambda v: f"UINT8_C({v})")
    text += "\n"
    text += format_array("KR_SYNDROME_LEADER", "uint64_t", leaders, 4, lambda v: f"UINT64_C(0x{v:013x})")
    text += "\n#endif /* HARE_KR_SYNDROME_TABLE_GENERATED_H */\n"
    return text


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, default=Path(__file__).resolve().parents[2] / "Implementations/_shared/hare_core/ref/kr_syndrome_table_generated.h")
    group = parser.add_mutually_exclusive_group()
    group.add_argument("--write", action="store_true")
    group.add_argument("--check", action="store_true")
    args = parser.parse_args()
    text = generate()
    if args.check:
        current = args.output.read_text() if args.output.exists() else ""
        if current != text:
            print("KR generated table differs:", args.output)
            for line in difflib.unified_diff(current.splitlines(), text.splitlines(), fromfile="current", tofile="generated", n=3):
                print(line)
            return 1
        print("KR syndrome table check: PASS")
        return 0
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(text)
    print(args.output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
