####  Makefile for compilation on Unix-like operative systems  ####

CC=gcc
ifeq "$(CC)" "gcc"
    COMPILER=gcc
else ifeq "$(CC)" "clang"
    COMPILER=clang
endif

ARCHITECTURE=_AMD64_
ifeq "$(ARCH)" "x64"
    ARCHITECTURE=_AMD64_
else ifeq "$(ARCH)" "x86"
    ARCHITECTURE=_X86_
    USE_OPT_LEVEL=_FAST_GENERIC_
else ifeq "$(ARCH)" "ARM"
    ARCHITECTURE=_ARM_
    USE_OPT_LEVEL=_FAST_GENERIC_
else ifeq "$(ARCH)" "PPC"
    ARCHITECTURE=_PPC_
    USE_OPT_LEVEL=_REFERENCE_
else ifeq "$(ARCH)" "s390x"
    ARCHITECTURE=_S390X_
    USE_OPT_LEVEL=_REFERENCE_
endif

ifeq "$(ARCHITECTURE)" "_AMD64_"
    USE_OPT_LEVEL=_FAST_
endif

ifeq "$(OPT_LEVEL)" "REFERENCE"
    USE_OPT_LEVEL=_REFERENCE_
else ifeq "$(OPT_LEVEL)" "FAST_GENERIC"
    USE_OPT_LEVEL=_FAST_GENERIC_
else ifeq "$(OPT_LEVEL)" "FAST"
    ifeq "$(ARCHITECTURE)" "_AMD64_"
        USE_OPT_LEVEL=_FAST_
    endif
endif

MATRIX_A_BACKEND ?= $(if $(GENERATION_A),$(GENERATION_A),AES128)
USE_MATRIX_A_BACKEND=_AES128_FOR_A_
ifeq "$(MATRIX_A_BACKEND)" "AES128"
    USE_MATRIX_A_BACKEND=_AES128_FOR_A_
else ifeq "$(MATRIX_A_BACKEND)" "SHAKE128"
    USE_MATRIX_A_BACKEND=_SHAKE128_FOR_A_
endif

ifeq "$(ARCH)" "ARM"
    ARM_SETTING=-lrt
endif

USING_OPENSSL=_USE_OPENSSL_
ifeq "$(USE_OPENSSL)" "FALSE"
    USING_OPENSSL=NO_OPENSSL
endif

OPENSSL_INCLUDE_DIR=/usr/include
OPENSSL_LIB_DIR=/usr/lib

AR=ar rcs
RANLIB=ranlib
LN=ln -s

FROST_USE_E8_CODE ?= 1
FROST_CODEC_TRACE ?= 0

VALGRIND_CFLAGS=
ifeq "$(DO_VALGRIND_CHECK)" "TRUE"
VALGRIND_CFLAGS= -g -O0 -DDO_VALGRIND_CHECK
endif

ifeq "$(EXTRA_CFLAGS)" ""
CFLAGS= -O3
else
CFLAGS= $(EXTRA_CFLAGS)
endif
CFLAGS+= $(VALGRIND_CFLAGS)
ifeq "$(FROST_USE_E8_CODE)" "1"
CFLAGS+= -DFROST_USE_E8_CODE
endif
ifeq "$(FROST_CODEC_TRACE)" "1"
CFLAGS+= -DFROST_CODEC_TRACE
endif
CFLAGS+= -std=gnu11 -Wall -Wextra -DNIX -D $(ARCHITECTURE) -D $(USE_OPT_LEVEL) -D $(USE_MATRIX_A_BACKEND) -D $(USING_OPENSSL)
ifeq "$(USE_OPT_LEVEL)" "_REFERENCE_"
ifeq "$(FROST_U16_MATERIALIZED_A_MATMUL)" "1"
CFLAGS+= -DFROST_U16_MATERIALIZED_A_MATMUL
else
CFLAGS+= -DFROST_U16_STREAMING_MATMUL
endif
endif
ifeq "$(CC)" "gcc"
ifneq "$(ARCHITECTURE)" "_PPC_"
ifneq "$(ARCHITECTURE)" "_S390X_"
CFLAGS+= -march=native
endif
endif
endif

ifeq "$(USE_OPENSSL)" "FALSE"
LDFLAGS=-lm
else
CFLAGS+= -I$(OPENSSL_INCLUDE_DIR)
LDFLAGS=-lm -L$(OPENSSL_LIB_DIR) -lssl -lcrypto
endif

ifeq "$(ARCHITECTURE)" "_AMD64_"
ifeq "$(USE_OPT_LEVEL)" "_FAST_"
CFLAGS += -mavx2 -maes -msse2
endif
endif

.PHONY: all check clean prettyprint size_test test_e8_codec test_codec_identity test_codec_identity_scalar test_codec_identity_e8

all: lib128 lib192 lib256 lib384 lib512 tests KATS size_test

BUILD_CONFIG_TAG := objs/.build_config_e8$(FROST_USE_E8_CODE)_trace$(FROST_CODEC_TRACE)_opt$(USE_OPT_LEVEL)_matrix$(USE_MATRIX_A_BACKEND)

$(BUILD_CONFIG_TAG):
	@mkdir -p $(@D)
	@touch $@

objs/%.o: src/%.c
	@mkdir -p $(@D)
	$(CC) -c  $(CFLAGS) $< -o $@

objs/frostcc128.o: src/frostcc128.c
	@mkdir -p $(@D)
	$(CC) -c  $(CFLAGS) $< -o $@

objs/frostcc192.o: src/frostcc192.c
	@mkdir -p $(@D)
	$(CC) -c  $(CFLAGS) $< -o $@

objs/frostcc256.o: src/frostcc256.c
	@mkdir -p $(@D)
	$(CC) -c  $(CFLAGS) $< -o $@

objs/frostcc384.o: src/frostcc384.c
	@mkdir -p $(@D)
	$(CC) -c  $(CFLAGS) $< -o $@

objs/frostcc512.o: src/frostcc512.c
	@mkdir -p $(@D)
	$(CC) -c  $(CFLAGS) $< -o $@

# RAND
objs/random/random.o: ../common/random/random.c ../common/random/random.h
	@mkdir -p $(@D)
	$(CC) -c $(CFLAGS) ../common/random/random.c -o objs/random/random.o
RAND_OBJS := objs/random/random.o

# KEM_FROST u16
KEM_FROST128_OBJS := $(addprefix objs/, frostcc128.o util.o)
KEM_FROST128_HEADERS := $(addprefix src/, api_frostcc128.h config.h frost_macrify.h)
$(KEM_FROST128_OBJS): $(KEM_FROST128_HEADERS) $(addprefix src/, kem.c noise.c util.c)

KEM_FROST192_OBJS := $(addprefix objs/, frostcc192.o util.o)
KEM_FROST192_HEADERS := $(addprefix src/, api_frostcc192.h config.h frost_macrify.h)
$(KEM_FROST192_OBJS): $(KEM_FROST192_HEADERS) $(addprefix src/, kem.c noise.c util.c)

KEM_FROST256_OBJS := $(addprefix objs/, frostcc256.o util.o)
KEM_FROST256_HEADERS := $(addprefix src/, api_frostcc256.h config.h frost_macrify.h)
$(KEM_FROST256_OBJS): $(KEM_FROST256_HEADERS) $(addprefix src/, kem.c noise.c util.c)

KEM_FROST384_OBJS := $(addprefix objs/, frostcc384.o util.o)
KEM_FROST384_HEADERS := $(addprefix src/, api_frostcc384.h config.h frost_macrify.h)
$(KEM_FROST384_OBJS): $(KEM_FROST384_HEADERS) $(addprefix src/, kem.c noise.c util.c)

KEM_FROST512_OBJS := $(addprefix objs/, frostcc512.o util.o)
KEM_FROST512_HEADERS := $(addprefix src/, api_frostcc512.h config.h frost_macrify.h)
$(KEM_FROST512_OBJS): $(KEM_FROST512_HEADERS) $(addprefix src/, kem.c noise.c util.c)

$(KEM_FROST128_OBJS) $(KEM_FROST192_OBJS) $(KEM_FROST256_OBJS) $(KEM_FROST384_OBJS) $(KEM_FROST512_OBJS): $(BUILD_CONFIG_TAG)

# AES
ifeq "$(USE_OPENSSL)" "FALSE"
ifeq "$(USE_OPT_LEVEL)" "_FAST_"
# AES_NI
objs/aes/aes_ni.o: ../common/aes/aes_ni.c ../common/aes/aes.h
	@mkdir -p $(@D)
	$(CC) -c $(CFLAGS) ../common/aes/aes_ni.c -o objs/aes/aes_ni.o
AES_OBJS := objs/aes/aes_ni.o
else
objs/aes/aes_c.o: ../common/aes/aes_c.c ../common/aes/aes.h
	@mkdir -p $(@D)
	$(CC) -c $(CFLAGS) ../common/aes/aes_c.c -o objs/aes/aes_c.o
AES_OBJS := objs/aes/aes_c.o
endif
else
objs/aes/aes_openssl.o: ../common/aes/aes_openssl.c ../common/aes/aes_openssl.h
	@mkdir -p $(@D)
	$(CC) -c $(CFLAGS) ../common/aes/aes_openssl.c -o objs/aes/aes_openssl.o
AES_OBJS := objs/aes/aes_openssl.o
endif

# SHAKE
objs/sha3/fips202.o: ../common/sha3/fips202.c ../common/sha3/fips202.h
	@mkdir -p $(@D)
	$(CC) -c $(CFLAGS) ../common/sha3/fips202.c -o objs/sha3/fips202.o
SHAKE_OBJS := objs/sha3/fips202.o

ifeq "$(USE_OPT_LEVEL)" "_FAST_"
ifeq "$(MATRIX_A_BACKEND)" "SHAKE128"
# SHAKEx4
objs/sha3/fips202x4.o: ../common/sha3/fips202x4.c ../common/sha3/fips202x4.h
	@mkdir -p $(@D)
	$(CC) -c $(CFLAGS) ../common/sha3/fips202x4.c -o objs/sha3/fips202x4.o

objs/sha3/keccak4x/KeccakP-1600-times4-SIMD256.o: ../common/sha3/keccak4x/KeccakP-1600-times4-SIMD256.c ../common/sha3/keccak4x/KeccakP-1600-times4-SnP.h
	@mkdir -p $(@D)
	$(CC) -c $(CFLAGS) ../common/sha3/keccak4x/KeccakP-1600-times4-SIMD256.c -o objs/sha3/keccak4x/KeccakP-1600-times4-SIMD256.o

SHAKEx4_OBJS := objs/sha3/fips202x4.o objs/sha3/keccak4x/KeccakP-1600-times4-SIMD256.o
endif
endif

ifndef SHAKEx4_OBJS
objs/sha3/fips202x4.o: ../common/sha3/fips202x4.c ../common/sha3/fips202x4.h
	@mkdir -p $(@D)
	$(CC) -c $(CFLAGS) ../common/sha3/fips202x4.c -o objs/sha3/fips202x4.o

objs/sha3/keccak4x/KeccakP-1600-times4-SIMD256.o: ../common/sha3/keccak4x/KeccakP-1600-times4-SIMD256.c ../common/sha3/keccak4x/KeccakP-1600-times4-SnP.h
	@mkdir -p $(@D)
	$(CC) -c $(CFLAGS) ../common/sha3/keccak4x/KeccakP-1600-times4-SIMD256.c -o objs/sha3/keccak4x/KeccakP-1600-times4-SIMD256.o

SHAKEx4_OBJS := objs/sha3/fips202x4.o objs/sha3/keccak4x/KeccakP-1600-times4-SIMD256.o
endif

lib128: $(KEM_FROST128_OBJS) $(RAND_OBJS) $(AES_OBJS) $(SHAKE_OBJS) $(SHAKEx4_OBJS)
	rm -rf frostcc128
	mkdir frostcc128
	$(AR) frostcc128/libfrost.a $^
	$(RANLIB) frostcc128/libfrost.a

lib192: $(KEM_FROST192_OBJS) $(RAND_OBJS) $(AES_OBJS) $(SHAKE_OBJS) $(SHAKEx4_OBJS)
	rm -rf frostcc192
	mkdir frostcc192
	$(AR) frostcc192/libfrost.a $^
	$(RANLIB) frostcc192/libfrost.a

lib256: $(KEM_FROST256_OBJS) $(RAND_OBJS) $(AES_OBJS) $(SHAKE_OBJS) $(SHAKEx4_OBJS)
	rm -rf frostcc256
	mkdir frostcc256
	$(AR) frostcc256/libfrost.a $^
	$(RANLIB) frostcc256/libfrost.a

lib384: $(KEM_FROST384_OBJS) $(RAND_OBJS) $(AES_OBJS) $(SHAKE_OBJS) $(SHAKEx4_OBJS)
	rm -rf frostcc384
	mkdir frostcc384
	$(AR) frostcc384/libfrost.a $^
	$(RANLIB) frostcc384/libfrost.a

lib512: $(KEM_FROST512_OBJS) $(RAND_OBJS) $(AES_OBJS) $(SHAKE_OBJS) $(SHAKEx4_OBJS)
	rm -rf frostcc512
	mkdir frostcc512
	$(AR) frostcc512/libfrost.a $^
	$(RANLIB) frostcc512/libfrost.a

tests: lib128 lib192 lib256 lib384 lib512 tests/ds_benchmark.h
	$(CC) $(CFLAGS) -L./frostcc128 tests/test_KEM128.c -lfrost $(LDFLAGS) -o frostcc128/test_KEM $(ARM_SETTING)
	$(CC) $(CFLAGS) -L./frostcc192 tests/test_KEM192.c -lfrost $(LDFLAGS) -o frostcc192/test_KEM $(ARM_SETTING)
	$(CC) $(CFLAGS) -L./frostcc256 tests/test_KEM256.c -lfrost $(LDFLAGS) -o frostcc256/test_KEM $(ARM_SETTING)
	$(CC) $(CFLAGS) -L./frostcc384 tests/test_KEM384.c -lfrost $(LDFLAGS) -o frostcc384/test_KEM $(ARM_SETTING)
	$(CC) $(CFLAGS) -L./frostcc512 tests/test_KEM512.c -lfrost $(LDFLAGS) -o frostcc512/test_KEM $(ARM_SETTING)

lib128_for_KATs: $(KEM_FROST128_OBJS) $(AES_OBJS) $(SHAKE_OBJS) $(SHAKEx4_OBJS)
	@mkdir -p frostcc128
	$(AR) frostcc128/libfrost_for_testing.a $^
	$(RANLIB) frostcc128/libfrost_for_testing.a

lib192_for_KATs: $(KEM_FROST192_OBJS) $(AES_OBJS) $(SHAKE_OBJS) $(SHAKEx4_OBJS)
	@mkdir -p frostcc192
	$(AR) frostcc192/libfrost_for_testing.a $^
	$(RANLIB) frostcc192/libfrost_for_testing.a

lib256_for_KATs: $(KEM_FROST256_OBJS) $(AES_OBJS) $(SHAKE_OBJS) $(SHAKEx4_OBJS)
	@mkdir -p frostcc256
	$(AR) frostcc256/libfrost_for_testing.a $^
	$(RANLIB) frostcc256/libfrost_for_testing.a

lib384_for_KATs: $(KEM_FROST384_OBJS) $(AES_OBJS) $(SHAKE_OBJS) $(SHAKEx4_OBJS)
	@mkdir -p frostcc384
	$(AR) frostcc384/libfrost_for_testing.a $^
	$(RANLIB) frostcc384/libfrost_for_testing.a

lib512_for_KATs: $(KEM_FROST512_OBJS) $(AES_OBJS) $(SHAKE_OBJS) $(SHAKEx4_OBJS)
	@mkdir -p frostcc512
	$(AR) frostcc512/libfrost_for_testing.a $^
	$(RANLIB) frostcc512/libfrost_for_testing.a

KATS: lib128_for_KATs lib192_for_KATs lib256_for_KATs lib384_for_KATs lib512_for_KATs
	@mkdir -p frostcc128/KAT frostcc192/KAT frostcc256/KAT frostcc384/KAT frostcc512/KAT
ifeq "$(MATRIX_A_BACKEND)" "SHAKE128"
	$(CC) $(CFLAGS) -L./frostcc128 tests/PQCtestKAT_kem128_shake.c tests/rng.c -lfrost_for_testing $(LDFLAGS) -o frostcc128/PQCtestKAT_kem_shake $(ARM_SETTING)
	$(CC) $(CFLAGS) -L./frostcc192 tests/PQCtestKAT_kem192_shake.c tests/rng.c -lfrost_for_testing $(LDFLAGS) -o frostcc192/PQCtestKAT_kem_shake $(ARM_SETTING)
	$(CC) $(CFLAGS) -L./frostcc256 tests/PQCtestKAT_kem256_shake.c tests/rng.c -lfrost_for_testing $(LDFLAGS) -o frostcc256/PQCtestKAT_kem_shake $(ARM_SETTING)
	$(CC) $(CFLAGS) -L./frostcc384 tests/PQCtestKAT_kem384_shake.c tests/rng.c -lfrost_for_testing $(LDFLAGS) -o frostcc384/PQCtestKAT_kem_shake $(ARM_SETTING)
	$(CC) $(CFLAGS) -L./frostcc512 tests/PQCtestKAT_kem512_shake.c tests/rng.c -lfrost_for_testing $(LDFLAGS) -o frostcc512/PQCtestKAT_kem_shake $(ARM_SETTING)
else
	$(CC) $(CFLAGS) -L./frostcc128 tests/PQCtestKAT_kem128.c tests/rng.c -lfrost_for_testing $(LDFLAGS) -o frostcc128/PQCtestKAT_kem $(ARM_SETTING)
	$(CC) $(CFLAGS) -L./frostcc192 tests/PQCtestKAT_kem192.c tests/rng.c -lfrost_for_testing $(LDFLAGS) -o frostcc192/PQCtestKAT_kem $(ARM_SETTING)
	$(CC) $(CFLAGS) -L./frostcc256 tests/PQCtestKAT_kem256.c tests/rng.c -lfrost_for_testing $(LDFLAGS) -o frostcc256/PQCtestKAT_kem $(ARM_SETTING)
	$(CC) $(CFLAGS) -L./frostcc384 tests/PQCtestKAT_kem384.c tests/rng.c -lfrost_for_testing $(LDFLAGS) -o frostcc384/PQCtestKAT_kem $(ARM_SETTING)
	$(CC) $(CFLAGS) -L./frostcc512 tests/PQCtestKAT_kem512.c tests/rng.c -lfrost_for_testing $(LDFLAGS) -o frostcc512/PQCtestKAT_kem $(ARM_SETTING)
endif

size_test:
	$(CC) $(CFLAGS) tests/test_sizes.c -o test_sizes $(LDFLAGS) $(ARM_SETTING)
	./test_sizes

check: tests size_test

test128: tests
ifeq "$(DO_VALGRIND_CHECK)" "TRUE"
	valgrind --tool=memcheck --error-exitcode=1 --max-stackframe=20480000 frostcc128/test_KEM
else
	frostcc128/test_KEM
endif

test192: tests
ifeq "$(DO_VALGRIND_CHECK)" "TRUE"
	valgrind --tool=memcheck --error-exitcode=1 --max-stackframe=20480000 frostcc192/test_KEM
else
	frostcc192/test_KEM
endif

test256: tests
ifeq "$(DO_VALGRIND_CHECK)" "TRUE"
	valgrind --tool=memcheck --error-exitcode=1 --max-stackframe=20480000 frostcc256/test_KEM
else
	frostcc256/test_KEM
endif

test384:
ifeq "$(DO_VALGRIND_CHECK)" "TRUE"
	valgrind --tool=memcheck --error-exitcode=1 --max-stackframe=20480000 frostcc384/test_KEM
else
	frostcc384/test_KEM
endif

test512:
ifeq "$(DO_VALGRIND_CHECK)" "TRUE"
	valgrind --tool=memcheck --error-exitcode=1 --max-stackframe=20480000 frostcc512/test_KEM
else
	frostcc512/test_KEM
endif

clean:
	rm -rf objs *.req frostcc128 frostcc192 frostcc256 frostcc384 frostcc512 test_sizes
	find . -name .DS_Store -type f -delete

prettyprint:
	astyle --style=java --indent=tab --pad-header --pad-oper --align-pointer=name --align-reference=name --suffix=none src/*.h src/*/*.h src/*/*.c

test_codec_identity: test_e8_codec

test_codec_identity_scalar:
	$(MAKE) clean
	$(MAKE) FROST_USE_E8_CODE=0 FROST_CODEC_TRACE=1 test_codec_identity

test_codec_identity_e8:
	$(MAKE) clean
	$(MAKE) FROST_USE_E8_CODE=1 FROST_CODEC_TRACE=1 test_codec_identity

test_e8_codec: lib128 lib192 lib256 lib384 lib512
	$(CC) $(CFLAGS) -DFROST_TEST_LEVEL=128 -L./frostcc128 tests/test_e8_codec.c -lfrost $(LDFLAGS) -o frostcc128/test_e8_codec $(ARM_SETTING)
	$(CC) $(CFLAGS) -DFROST_TEST_LEVEL=192 -L./frostcc192 tests/test_e8_codec.c -lfrost $(LDFLAGS) -o frostcc192/test_e8_codec $(ARM_SETTING)
	$(CC) $(CFLAGS) -DFROST_TEST_LEVEL=256 -L./frostcc256 tests/test_e8_codec.c -lfrost $(LDFLAGS) -o frostcc256/test_e8_codec $(ARM_SETTING)
	$(CC) $(CFLAGS) -DFROST_TEST_LEVEL=384 -L./frostcc384 tests/test_e8_codec.c -lfrost $(LDFLAGS) -o frostcc384/test_e8_codec $(ARM_SETTING)
	$(CC) $(CFLAGS) -DFROST_TEST_LEVEL=512 -L./frostcc512 tests/test_e8_codec.c -lfrost $(LDFLAGS) -o frostcc512/test_e8_codec $(ARM_SETTING)
