add_executable(KAT_KEX_${SVARIANT} ${COMMON_SRC_DIR}/ngccapi/KAT_KEX.c ${COMMON_SRC_DIR}/ngccapi/KEX_AlgorithmInstance.c)
target_include_directories(KAT_KEX_${SVARIANT} PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}/include ${INC_COMMON_${SVARIANT_UPPER}} ${INC_GF_${SVARIANT_UPPER}} ${INC_PRECOMP_${SVARIANT_UPPER}} ${INC_EC_${SVARIANT_UPPER}} ${INC_PROTOCOLS_${SVARIANT_UPPER}})
target_link_libraries(KAT_KEX_${SVARIANT} ${LIB_PROTOCOLS_${SVARIANT_UPPER}} ${LIB_EC_${SVARIANT_UPPER}} ${LIB_PRECOMP_${SVARIANT_UPPER}} ${LIB_GF_${SVARIANT_UPPER}})
