#ifndef ORIGAMI_PARAMS_H
#define ORIGAMI_PARAMS_H

#define ORIGAMI_PARAM_ID 0x4F4D0200u
#define ORIGAMI_SECURITY_BITS 512
#define ORIGAMI_CLASSICAL_BITS 512
#define ORIGAMI_QUANTUM_BITS 256
#define ORIGAMI_MU_RED 146
#define ORIGAMI_MAIN_ZONES 9

#define ORIGAMI_q 16

#define ORIGAMI_SEED_SK_BYTES 64
#define ORIGAMI_SEED_PK_BYTES 64
#define ORIGAMI_SALT_BYTES 64
#define ORIGAMI_RPK_BYTES 35856

#define ORIGAMI_MAIN_K 8
#define ORIGAMI_MAIN_V 3
#define ORIGAMI_MAIN_O 5
#define ORIGAMI_MAIN_M 32
#define ORIGAMI_MAIN_L 2
#define ORIGAMI_MAIN_A 32
#define ORIGAMI_MAIN_B 128
#define ORIGAMI_MAIN_DELTA 0

#define ORIGAMI_TAIL_K 1
#define ORIGAMI_TAIL_V 0
#define ORIGAMI_TAIL_O 2
#define ORIGAMI_TAIL_M 2
#define ORIGAMI_TAIL_L 2
#define ORIGAMI_TAIL_A 0
#define ORIGAMI_TAIL_B 8
#define ORIGAMI_TAIL_DELTA 0

#endif