#include <stdint.h>
#include "params.h"
#include "ntt.h"
#include "reduce.h"

/* Tables generated by gen/ntt_tables.py (Montgomery domain, R = 2^32). */
#if RHYME_MODE == 128
extern const int32_t rhyme_zetas_3329_256[64];
extern const int32_t rhyme_izetas_3329_256[64];
extern const int32_t rhyme_broots_3329_256[64];
extern const int32_t rhyme_intt_f_3329_256;
#define ZETAS rhyme_zetas_3329_256
#define IZETAS rhyme_izetas_3329_256
#define BROOTS rhyme_broots_3329_256
#define INTT_F rhyme_intt_f_3329_256
#elif RHYME_MODE == 256
extern const int32_t rhyme_zetas_9473_512[128];
extern const int32_t rhyme_izetas_9473_512[128];
extern const int32_t rhyme_broots_9473_512[128];
extern const int32_t rhyme_intt_f_9473_512;
#define ZETAS rhyme_zetas_9473_512
#define IZETAS rhyme_izetas_9473_512
#define BROOTS rhyme_broots_9473_512
#define INTT_F rhyme_intt_f_9473_512
#elif RHYME_MODE == 384
extern const int32_t rhyme_zetas_11777_512[128];
extern const int32_t rhyme_izetas_11777_512[128];
extern const int32_t rhyme_broots_11777_512[128];
extern const int32_t rhyme_intt_f_11777_512;
#define ZETAS rhyme_zetas_11777_512
#define IZETAS rhyme_izetas_11777_512
#define BROOTS rhyme_broots_11777_512
#define INTT_F rhyme_intt_f_11777_512
#elif RHYME_MODE == 512
extern const int32_t rhyme_zetas_18433_1024[256];
extern const int32_t rhyme_izetas_18433_1024[256];
extern const int32_t rhyme_broots_18433_1024[256];
extern const int32_t rhyme_intt_f_18433_1024;
#define ZETAS rhyme_zetas_18433_1024
#define IZETAS rhyme_izetas_18433_1024
#define BROOTS rhyme_broots_18433_1024
#define INTT_F rhyme_intt_f_18433_1024
#endif

#define NBLOCKS (N / 4)

/* Forward incomplete NTT: x^N+1 -> NBLOCKS factors (x^4 - r_i).
 * CT butterflies, zetas bit-reversed.  Coefficients stay in standard domain
 * (zetas are Montgomery so fqmul(zeta, x) = zeta*x). */
void ntt(int32_t a[N]) {
    unsigned int len, start, j, k;
    int32_t t, zeta;
    for (j = 0; j < N; j++) a[j] = creduce(a[j]);
    k = 1;
    for (len = N / 2; len >= 4; len >>= 1) {
        for (start = 0; start < N; start = j + len) {
            zeta = ZETAS[k++];
            for (j = start; j < start + len; j++) {
                t = fqmul(zeta, a[j + len]);
                a[j + len] = creduce(a[j] - t);
                a[j] = creduce(a[j] + t);
            }
        }
    }
}

/* Inverse: GS butterflies; the zeta for (len, start) equals the forward
 * assignment k = N/(2*len) + start/(2*len); table IZETAS holds inverses.
 * Output is (input deficit R^{-1}) * R: ntt -> basemul -> invntt_tomont
 * yields the plain product (Kyber convention). */
void invntt_tomont(int32_t a[N]) {
    unsigned int len, start, j;
    int32_t t, zeta;
    for (len = 4; len <= N / 2; len <<= 1) {
        unsigned int kbase = N / (2 * len);
        for (start = 0; start < N; start = j + len) {
            zeta = IZETAS[kbase + start / (2 * len)];
            for (j = start; j < start + len; j++) {
                t = a[j];
                a[j] = creduce(t + a[j + len]);
                a[j + len] = fqmul(zeta, creduce(t - a[j + len]));
            }
        }
    }
    for (j = 0; j < N; j++) a[j] = fqmul(a[j], INTT_F);
}

/* c = a*b mod (x^4 - r), Montgomery semantics: output = ab * R^{-1}. */
static void basemul_block(int32_t c[4], const int32_t a[4], const int32_t b[4], int32_t r_mont) {
    int32_t h0 = montgomery_reduce((int64_t)a[1]*b[3] + (int64_t)a[2]*b[2] + (int64_t)a[3]*b[1]);
    int32_t h1 = montgomery_reduce((int64_t)a[2]*b[3] + (int64_t)a[3]*b[2]);
    int32_t h2 = montgomery_reduce((int64_t)a[3]*b[3]);
    c[0] = creduce(montgomery_reduce((int64_t)a[0]*b[0]) + fqmul(h0, r_mont));
    c[1] = creduce(montgomery_reduce((int64_t)a[0]*b[1] + (int64_t)a[1]*b[0]) + fqmul(h1, r_mont));
    c[2] = creduce(montgomery_reduce((int64_t)a[0]*b[2] + (int64_t)a[1]*b[1] + (int64_t)a[2]*b[0]) + fqmul(h2, r_mont));
    c[3] = creduce(montgomery_reduce((int64_t)a[0]*b[3] + (int64_t)a[1]*b[2] + (int64_t)a[2]*b[1] + (int64_t)a[3]*b[0]));
}

void basemul(int32_t c[N], const int32_t a[N], const int32_t b[N]) {
    unsigned int i;
    for (i = 0; i < NBLOCKS; i++)
        basemul_block(c + 4*i, a + 4*i, b + 4*i, BROOTS[i]);
}

void ntt_pointwise_acc(int32_t c[N], const int32_t a[N], const int32_t b[N]) {
    unsigned int i, j;
    int32_t t[4];
    for (i = 0; i < NBLOCKS; i++) {
        basemul_block(t, a + 4*i, b + 4*i, BROOTS[i]);
        for (j = 0; j < 4; j++)
            c[4*i+j] = creduce(c[4*i+j] + t[j]);
    }
}
