#include "isog.h"
#include "ec.h"
#include <assert.h>

// -------------------------------------------------------------------------
// -------------------------------------------------------------------------

// Degree-2 isogeny with kernel generated by P != (0 ,0)
// Outputs the curve coefficient in the form A24=(A+2C:4C)
void
xisog_2(ec_kps2_t *kps, ec_point_t *B, const ec_point_t P)
{
    fp2_sqr(&B->x, &P.x);
    fp2_sqr(&B->z, &P.z);
    fp2_sub(&B->x, &B->z, &B->x);
    fp2_add(&kps->K.x, &P.x, &P.z);
    fp2_sub(&kps->K.z, &P.x, &P.z);
}

// TODO we may be more efficient than that ?
void
xisog_2_singular(ec_kps2_t *kps, ec_point_t *B24, ec_point_t A24)
{
    fp2_t t0, four;
    fp2_set_small(&four, 4);
    fp2_add(&t0, &A24.x, &A24.x);
    fp2_sub(&t0, &t0, &A24.z);
    fp2_add(&t0, &t0, &t0);
    fp2_inv(&A24.z);
    fp2_mul(&t0, &t0, &A24.z);
    fp2_copy(&kps->K.x, &t0);
    fp2_add(&B24->x, &t0, &t0);
    fp2_sqr(&t0, &t0);
    fp2_sub(&t0, &t0, &four);
    fp2_sqrt(&t0);
    fp2_neg(&kps->K.z, &t0);
    fp2_add(&B24->z, &t0, &t0);
    fp2_add(&B24->x, &B24->x, &B24->z);
    fp2_add(&B24->z, &B24->z, &B24->z);
}

// Degree-4 isogeny with kernel generated by P such that [2]P != (0 ,0)
// Outputs the curve coefficient in the form A24=(A+2C:4C)
void
xisog_4(ec_kps4_t *kps, ec_point_t *B, const ec_point_t P)
{
    ec_point_t *K = kps->K;

    fp2_sqr(&K[0].x, &P.x);
    fp2_sqr(&K[0].z, &P.z);
    fp2_add(&K[1].x, &K[0].z, &K[0].x);
    fp2_sub(&K[1].z, &K[0].z, &K[0].x);
    fp2_mul(&B->x, &K[1].x, &K[1].z);
    fp2_sqr(&B->z, &K[0].z);

    // Constants for xeval_4
    fp2_add(&K[2].x, &P.x, &P.z);
    fp2_sub(&K[1].x, &P.x, &P.z);
    fp2_add(&K[0].x, &K[0].z, &K[0].z);
    fp2_add(&K[0].x, &K[0].x, &K[0].x);
}

// Degree-4 isogeny with kernel generated by P such that [2]P = (0 ,0)
void
xisog_4_singular(ec_kps4_t *kps, ec_point_t *B24, const ec_point_t P, ec_point_t A24)
{
    ec_point_t *K = kps->K;
    fp2_copy(&K[0].z, &A24.z);
    // If Px == Pz then
    // K[0].x = A24.x
    // K[1].x = A24.x - A24.z
    // B24.z  = -K[1].x
    // Otherwise
    // K[1].x = A24.x
    // K[0].x = A24.x - A24.z
    // B24.z  = K[1].x

    // Check whether P.x == P.z
    uint32_t xz_equal = fp2_is_equal(&P.x, &P.z);

    // Compute K[i].x as above
    fp2_copy(&K[1].x, &A24.x);
    fp2_sub(&K[0].x, &A24.x, &A24.z);
    fp2_cswap(&K[0].x, &K[1].x, xz_equal);

    // Compute B24
    fp2_t tmp;
    fp2_neg(&tmp, &K[1].x);
    fp2_select(&B24->z, &K[1].x, &tmp, xz_equal);
    fp2_copy(&B24->x, &K[0].z);
}

// Degree-3 isogeny with kernel generated by P
// Outputs the curve coefficient in the form B=(A+2C:A-2C)
void
xisog_3(ec_kps3_t* kps, ec_point_t* B, const ec_point_t P)
{
    fp2_t t0, t1, t2, t3, t4;

    fp2_sub(&kps->K.x, &P.x, &P.z);
    fp2_sqr(&t0, &kps->K.x);
    fp2_add(&kps->K.z, &P.x, &P.z);
    fp2_sqr(&t1, &kps->K.z);
    fp2_add(&t2, &t0, &t1);
    fp2_add(&t3, &kps->K.x, &kps->K.z);
    fp2_sqr(&t3, &t3);
    fp2_sub(&t3, &t3, &t2);
    fp2_add(&t2, &t1, &t3);
    fp2_add(&t3, &t3, &t0);
    fp2_add(&t4, &t3, &t0);
    fp2_add(&t4, &t4, &t4);
    fp2_add(&t4, &t4, &t1);
    fp2_mul(&B->z, &t2, &t4);
    fp2_add(&t4, &t1, &t2);
    fp2_add(&t4, &t4, &t4);
    fp2_add(&t4, &t4, &t0);
    fp2_mul(&B->x, &t3, &t4);
}

// Degree-3 isogeny with kernel generated by P.
// @param B Input starting curve coefficient B=(A+2C:A-2C).
// @param P Input isogeny kernel generator.
// @param kps Output data used for evaluating the isogeny on points later.
// @param B Output image curve coefficient B=(A:C), updated in place.
// @param dual Output dual-isogeny kernel generator.
void
xisog_3_with_dual(ec_kps3_t* kps, ec_point_t* B, ec_point_t* dual,const ec_point_t P)
{
	fp2_t t0, t1, t2, t3, t4;
	fp2_t A1, A2, C1, C2, A1C1, A2_3, C1_2, A2_2, C2_3, A1_2, A2C2_2, A2_2C2;

	fp2_add(&A1, &B->x, &B->z);
	fp2_add(&A1, &A1, &A1);
	fp2_sub(&C1, &B->x, &B->z);

	fp2_sub(&kps->K.x, &P.x, &P.z);
	fp2_sqr(&t0, &kps->K.x);
	fp2_add(&kps->K.z, &P.x, &P.z);
	fp2_sqr(&t1, &kps->K.z);
	fp2_add(&t2, &t0, &t1);
	fp2_add(&t3, &kps->K.x, &kps->K.z);
	fp2_sqr(&t3, &t3);
	fp2_sub(&t3, &t3, &t2);
	fp2_add(&t2, &t1, &t3);
	fp2_add(&t3, &t3, &t0);
	fp2_add(&t4, &t3, &t0);
	fp2_add(&t4, &t4, &t4);
	fp2_add(&t4, &t4, &t1);
	fp2_mul(&B->z, &t2, &t4);
	fp2_add(&t4, &t1, &t2);
	fp2_add(&t4, &t4, &t4);
	fp2_add(&t4, &t4, &t0);
	fp2_mul(&B->x, &t3, &t4);

	fp2_add(&A2, &B->x, &B->z);
	fp2_add(&A2, &A2, &A2);
	fp2_sub(&C2, &B->x, &B->z);

	fp2_copy(&B->x, &A2);
	fp2_copy(&B->z, &C2);

	fp2_mul(&A1C1, &A1, &C1);
	fp2_sqr(&C1_2, &C1);
	fp2_sqr(&A2_2, &A2);
	fp2_mul(&A2_3, &A2_2, &A2);
	fp2_sqr(&A1_2, &A1);
	fp2_mul(&A2_2C2, &A2_2, &C2);
	fp2_sqr(&t0, &C2);
	fp2_mul(&A2C2_2, &A2, &t0);
	fp2_mul(&C2_3, &C2, &t0);

	fp2_add(&t0, &C1_2, &C1_2);
	fp2_add(&t0, &t0, &t0);
	fp2_add(&t0, &t0, &t0);
	fp2_add(&t0, &t0, &t0);
	fp2_sub(&t0, &t0, &A1_2);
	fp2_mul(&t0, &A2C2_2, &t0);
	fp2_add(&t1, &t0, &t0);
	fp2_add(&t0, &t0, &t1);
	fp2_add(&t1, &C2_3, &C2_3);
	fp2_add(&t1, &t1, &t1);
	fp2_add(&t1, &t1, &t1);
	fp2_sub(&t1, &t1, &C2_3);
	fp2_sub(&t1, &A2_2C2, &t1);
	fp2_add(&t1, &t1, &t1);
	fp2_add(&t1, &t1, &t1);
	fp2_add(&t1, &t1, &t1);
	fp2_add(&t1, &t1, &A2_2C2);
	fp2_add(&t1, &t1, &t1);
	fp2_mul(&t1, &t1, &A1C1);
	fp2_add(&t0, &t0, &t1);
	fp2_mul(&t1, &A2_3, &C1_2);
	fp2_add(&dual->x, &t1, &t0);
#if _DEBUG
	fp2_t small;
	fp2_mul(&t0, &A2_3, &C1_2);
	fp2_mul(&t1, &A2_2C2, &A1C1);
	fp2_mul(&t2, &A2C2_2, &A1_2);
	fp2_mul(&t3, &A2C2_2, &C1_2);
	fp2_mul(&t4, &C2_3, &A1C1);
	fp2_set_small(&small, 18);
	fp2_mul(&t1, &t1, &small);
	fp2_add(&t0, &t0, &t1);
	fp2_set_small(&small, 3);
	fp2_mul(&t2, &t2, &small);
	fp2_sub(&t0, &t0, &t2);
	fp2_set_small(&small, 48);
	fp2_mul(&t3, &t3, &small);
	fp2_add(&t0, &t0, &t3);
	fp2_set_small(&small, 112);
	fp2_mul(&t4, &t4, &small);
	fp2_sub(&t0, &t0, &t4);
	assert(fp2_is_equal(&t0, &dual->x));
#endif

	fp2_add(&t2, &C2_3, &C2_3);
	fp2_add(&t2, &t2, &t2);
	fp2_add(&t1, &C2_3, &t2);
	fp2_sub(&t0, &A2_2C2, &t1);
	fp2_add(&t1, &t0, &t0);
	fp2_add(&t1, &t1, &t1);
	fp2_add(&t1, &t1, &t1);
	fp2_sub(&t0, &t1, &t0);
	fp2_sub(&t0, &t0, &C2_3);
	fp2_add(&t0, &t0, &t0);
	fp2_add(&t0, &t0, &t0);
	fp2_add(&t0, &t0, &t0);
	fp2_add(&t0, &t0, &A2_2C2);
	fp2_mul(&t0, &t0, &C1_2);
	fp2_add(&t1, &A2C2_2, &A2C2_2);
	fp2_add(&t1, &t1, &A2C2_2);
	fp2_add(&t1, &t1, &A2_3);
	fp2_add(&t1, &t1, &t1);
	fp2_mul(&t1, &t1, &A1C1);
	fp2_add(&t0, &t0, &t1);
	fp2_mul(&t1, &C2_3, &A1_2);
	fp2_add(&t0, &t0, &t1);
	fp2_add(&dual->z, &t0, &t0);
#if _DEBUG
	fp2_mul(&t0, &A2_3, &A1C1);
	fp2_mul(&t1, &A2_2C2, &C1_2);
	fp2_mul(&t2, &A2C2_2, &A1C1);
	fp2_mul(&t3, &A1_2, &C2_3);
	fp2_mul(&t4, &C2_3, &C1_2);
	fp2_set_small(&small, 4);
	fp2_mul(&t0, &t0, &small);
	fp2_set_small(&small, 114);
	fp2_mul(&t1, &t1, &small);
	fp2_add(&t0, &t0, &t1);
	fp2_set_small(&small, 12);
	fp2_mul(&t2, &t2, &small);
	fp2_add(&t0, &t0, &t2);
	fp2_set_small(&small, 2);
	fp2_mul(&t3, &t3, &small);
	fp2_add(&t0, &t0, &t3);
	fp2_set_small(&small, 576);
	fp2_mul(&t4, &t4, &small);
	fp2_sub(&t0, &t0, &t4);
	assert(fp2_is_equal(&t0, &dual->z));
#endif
}
