set(SOURCE_FILES_GF_${SVARIANT_UPPER}
    fp511.c fp.c fp2.c bundle_fp2.c
)

if(CMAKE_SYSTEM_NAME STREQUAL "Darwin")
    list(APPEND SOURCE_FILES_GF_${SVARIANT_UPPER} fp511_macos.S)
else()
    list(APPEND SOURCE_FILES_GF_${SVARIANT_UPPER} fp511.S)
endif()

set(INC_GF_${SVARIANT_UPPER} ${CMAKE_CURRENT_SOURCE_DIR}/include CACHE INTERNAL "INC")
set(LIB_GF_${SVARIANT_UPPER} niike_gf_${SVARIANT} CACHE INTERNAL "LIB")
add_library(${LIB_GF_${SVARIANT_UPPER}} ${SOURCE_FILES_GF_${SVARIANT_UPPER}})
target_include_directories(${LIB_GF_${SVARIANT_UPPER}} PRIVATE ${INC_COMMON_${SVARIANT_UPPER}} ${INC_PRECOMP_${SVARIANT_UPPER}} ${INC_GF_${SVARIANT_UPPER}})
target_compile_options(${LIB_GF_${SVARIANT_UPPER}} PRIVATE ${C_OPT_FLAGS})
