# Modarith unsaturated radix parameters keyed by prime bit length
# Generated by: python3 modarith/monty.py 64 <prime>
MODARITH_PARAMS_BY_BITS = {
    479:  {'nlimbs': 8,  'radix': 61},   # p479 (NGCC_1)
    765:  {'nlimbs': 13, 'radix': 59},   # p765 (NGCC_2)
    1534: {'nlimbs': 26, 'radix': 60},   # p1534 (NGCC_3)
}

def get_modarith_params(p):
    """Get modarith params by prime bit length."""
    bits = int(p).bit_length()
    if bits not in MODARITH_PARAMS_BY_BITS:
        raise ValueError(
            f"Unsupported prime bit length {bits}; expected one of "
            f"{sorted(MODARITH_PARAMS_BY_BITS)}"
        )
    return MODARITH_PARAMS_BY_BITS[bits]
