/**
 * @file polarkem_params.h
 * @brief Canonical byte-level parameters for the PolarKEM-256 rectification.
 */
#ifndef POLARKEM_PARAMS_H
#define POLARKEM_PARAMS_H

#include <stddef.h>
#include <stdint.h>

#define POLARKEM_INSTANCE_NAME       "PolarKEM-256"
#define POLARKEM_INSTANCE_ID         0x03u
#define POLARKEM_N                   1024u
#define POLARKEM_LOGN                10u
#define POLARKEM_Q                   12289u
#define POLARKEM_AMPLITUDE           (POLARKEM_Q / 4u)
#define POLARKEM_MESSAGE_BYTES       32u
#define POLARKEM_MESSAGE_BITS        (8u * POLARKEM_MESSAGE_BYTES)
#define POLARKEM_INFO_BITS           POLARKEM_MESSAGE_BITS
#define POLARKEM_FROZEN_BITS         (POLARKEM_N - POLARKEM_INFO_BITS)
#define POLARKEM_QUANT_BITS          9u

#define POLARKEM_PK_BYTES            2048u
#define POLARKEM_SK_BYTES            4096u
#define POLARKEM_CT_BYTES            1280u
#define POLARKEM_SS_BYTES            32u

#define POLARKEM_PUBLICKEYBYTES      POLARKEM_PK_BYTES
#define POLARKEM_SECRETKEYBYTES      POLARKEM_SK_BYTES
#define POLARKEM_CIPHERTEXTBYTES     POLARKEM_CT_BYTES
#define POLARKEM_SSBYTES             POLARKEM_SS_BYTES

#define POLARKEM_HEADER_BYTES        16u
#define POLARKEM_SEED_BYTES          32u
#define POLARKEM_HASH_BYTES          32u
#define POLARKEM_TAG_BYTES           32u
#define POLARKEM_PERM_XOF_BLOCK_BYTES 4096u
#define POLARKEM_ERROR_STREAM_BYTES  ((2u * POLARKEM_N) / 8u)

#define POLARKEM_PK_SEED_OFFSET      POLARKEM_HEADER_BYTES
#define POLARKEM_PK_PAD_OFFSET       (POLARKEM_PK_SEED_OFFSET + POLARKEM_SEED_BYTES)
#define POLARKEM_PK_PAD_BYTES        (POLARKEM_PK_BYTES - POLARKEM_PK_PAD_OFFSET)

#define POLARKEM_SK_Z_OFFSET         POLARKEM_HEADER_BYTES
#define POLARKEM_SK_PK_OFFSET        (POLARKEM_SK_Z_OFFSET + POLARKEM_SEED_BYTES)
#define POLARKEM_SK_PAD_OFFSET       (POLARKEM_SK_PK_OFFSET + POLARKEM_PK_BYTES)
#define POLARKEM_SK_PAD_BYTES        (POLARKEM_SK_BYTES - POLARKEM_SK_PAD_OFFSET)

#define POLARKEM_CT_PAYLOAD_OFFSET   POLARKEM_HEADER_BYTES
#define POLARKEM_CT_PAYLOAD_BITS     (POLARKEM_N * POLARKEM_QUANT_BITS)
#define POLARKEM_CT_PAYLOAD_BYTES    (POLARKEM_CT_PAYLOAD_BITS / 8u)
#define POLARKEM_CT_TAG_OFFSET       (POLARKEM_CT_PAYLOAD_OFFSET + POLARKEM_CT_PAYLOAD_BYTES)
#define POLARKEM_CT_PAD_OFFSET       (POLARKEM_CT_TAG_OFFSET + POLARKEM_TAG_BYTES)
#define POLARKEM_CT_PAD_BYTES        (POLARKEM_CT_BYTES - POLARKEM_CT_PAD_OFFSET)

#define POLARKEM_ASSERT(name, expression) \
    typedef char polarkem_assert_##name[(expression) ? 1 : -1]
POLARKEM_ASSERT(n_is_power_of_two, (POLARKEM_N & (POLARKEM_N - 1u)) == 0u);
POLARKEM_ASSERT(logn_matches_n, (1u << POLARKEM_LOGN) == POLARKEM_N);
POLARKEM_ASSERT(message_bits_fit, POLARKEM_MESSAGE_BITS <= POLARKEM_N);
POLARKEM_ASSERT(message_bits_match_bytes,
                 POLARKEM_MESSAGE_BITS == 8u * POLARKEM_MESSAGE_BYTES);
POLARKEM_ASSERT(payload_is_byte_aligned, (POLARKEM_CT_PAYLOAD_BITS & 7u) == 0u);
POLARKEM_ASSERT(pk_seed_offset_exact, POLARKEM_PK_SEED_OFFSET == 16u);
POLARKEM_ASSERT(pk_pad_layout_exact,
                 POLARKEM_PK_PAD_OFFSET == 48u && POLARKEM_PK_PAD_BYTES == 2000u);
POLARKEM_ASSERT(sk_field_offsets_exact,
                 POLARKEM_SK_Z_OFFSET == 16u && POLARKEM_SK_PK_OFFSET == 48u);
POLARKEM_ASSERT(sk_pad_layout_exact,
                 POLARKEM_SK_PAD_OFFSET == 2096u && POLARKEM_SK_PAD_BYTES == 2000u);
POLARKEM_ASSERT(ct_payload_layout_exact,
                 POLARKEM_CT_PAYLOAD_OFFSET == 16u && POLARKEM_CT_PAYLOAD_BYTES == 1152u);
POLARKEM_ASSERT(ct_tag_offset_exact, POLARKEM_CT_TAG_OFFSET == 1168u);
POLARKEM_ASSERT(ct_pad_layout_exact,
                 POLARKEM_CT_PAD_OFFSET == 1200u && POLARKEM_CT_PAD_BYTES == 80u);
POLARKEM_ASSERT(pk_layout_exact,
                 POLARKEM_PK_PAD_OFFSET + POLARKEM_PK_PAD_BYTES == POLARKEM_PK_BYTES);
POLARKEM_ASSERT(sk_layout_exact,
                 POLARKEM_SK_PAD_OFFSET + POLARKEM_SK_PAD_BYTES == POLARKEM_SK_BYTES);
POLARKEM_ASSERT(ct_layout_exact,
                 POLARKEM_CT_PAD_OFFSET + POLARKEM_CT_PAD_BYTES == POLARKEM_CT_BYTES);
#undef POLARKEM_ASSERT

#endif /* POLARKEM_PARAMS_H */
