#ifndef HARE_PARAMETERS_H
#define HARE_PARAMETERS_H

#include <stdint.h>

#define CEIL_DIVIDE(a,b) (((a)/(b)) + (((a)%(b))?1:0))
#define MAX2(a,b) ((a)>(b)?(a):(b))
#define BITMASK(a,size) ((1ULL << ((a) % (size))) - 1ULL)

#define PARAM_SECURITY_BYTES 32
#define SEED_BYTES 32
#define SALT_BYTES 32
#define SHARED_SECRET_BYTES 32

#define PARAM_N 52379
#define PARAM_K 32
#define PARAM_OMEGA 131
#define PARAM_OMEGA_R 131
#define PARAM_OMEGA_E 224
#define PARAM_N1 81
#define PARAM_N2 640
#define PARAM_N1N2 51840
#define PARAM_ALPHA 9

#define PARAM_COMP_N 51
#define PARAM_COMP_K 41
#define PARAM_COMP_R 2

#define PARAM_L1 (PARAM_N1 * PARAM_N2)
#define PARAM_COMP_Q (PARAM_L1 / PARAM_COMP_N)
#define PARAM_L2 (PARAM_COMP_Q * PARAM_COMP_N)
#define PARAM_NM (PARAM_COMP_K * PARAM_COMP_Q)
#define PARAM_NV2 (PARAM_L1 - PARAM_L2)
#define PARAM_NM_BITS PARAM_NM
#define PARAM_V2_BITS PARAM_NV2

#define VEC_N_SIZE_BYTES CEIL_DIVIDE(PARAM_N,8)
#define VEC_K_SIZE_BYTES PARAM_K
#define VEC_N1_SIZE_BYTES PARAM_N1
#define VEC_N1N2_SIZE_BYTES CEIL_DIVIDE(PARAM_N1N2,8)
#define VEC_NM_SIZE_BYTES CEIL_DIVIDE(PARAM_NM,8)
#define VEC_NV2_SIZE_BYTES CEIL_DIVIDE(PARAM_NV2,8)

#define VEC_N_SIZE_64 CEIL_DIVIDE(PARAM_N,64)
#define VEC_N1_SIZE_64 CEIL_DIVIDE(PARAM_N1,8)
#define VEC_N1N2_SIZE_64 CEIL_DIVIDE(PARAM_N1N2,64)
#define VEC_NM_SIZE_64 CEIL_DIVIDE(PARAM_NM,64)
#define VEC_NV2_SIZE_64 CEIL_DIVIDE(PARAM_NV2,64)
#define VEC_COMPRESSED_PAYLOAD_BITS (PARAM_NM + PARAM_NV2)
#define VEC_COMPRESSED_PAYLOAD_BYTES CEIL_DIVIDE(VEC_COMPRESSED_PAYLOAD_BITS,8)

#define PARAM_N_MU (4294967296ULL / PARAM_N)
#define UTILS_REJECTION_THRESHOLD ((16777216 / PARAM_N) * PARAM_N)
#define PARAM_OMEGA_MAX MAX2(MAX2(PARAM_OMEGA, PARAM_OMEGA_R), PARAM_OMEGA_E)

#define PARAM_M 8
#define PARAM_GF_POLY 0x11D
#define PARAM_GF_MUL_ORDER 255
#define PARAM_DELTA ((PARAM_N1 - PARAM_K) / 2)
#define PARAM_FFT 5

#define PUBLIC_KEY_BYTES 6580
#define SECRET_KEY_BYTES 6676
#define CIPHERTEXT_BYTES 11790

#endif
