/*
 * QingLuan Digital Signature Scheme
 * test/kat_gen.c - Known Answer Test vector generator
 */

#include "api.h"
#include "params.h"
#include "utils.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static void print_hex_to_file(FILE *f, const unsigned char *data, size_t len)
{
    for (size_t i = 0; i < len; i++) {
        fprintf(f, "%02X", data[i]);
    }
}

/*
 * Generate KAT vectors for the current parameter set.
 * Output format compatible with standard KAT file structure.
 */
int main(void)
{
    /* Deterministic DRBG seed so the whole KAT file is reproducible. */
    uint8_t kat_seed[48];
    for (int i = 0; i < 48; i++) kat_seed[i] = (uint8_t)i;
    drbg_seed(kat_seed, sizeof(kat_seed));

    char filename[256];
    snprintf(filename, sizeof(filename), "KAT_SIG_%s.txt", CRYPTO_ALGNAME);

    FILE *f = fopen(filename, "w");
    if (!f) {
        fprintf(stderr, "Cannot open %s for writing\n", filename);
        return 1;
    }

    fprintf(f, "# Known Answer Test Vectors for %s\n", CRYPTO_ALGNAME);
    fprintf(f, "# Generated by QingLuan KAT generator\n");
    fprintf(f, "#\n");
    fprintf(f, "# CRYPTO_PUBLICKEYBYTES = %d\n", CRYPTO_PUBLICKEYBYTES);
    fprintf(f, "# CRYPTO_SECRETKEYBYTES = %d\n", CRYPTO_SECRETKEYBYTES);
    fprintf(f, "# CRYPTO_BYTES = %d\n\n", CRYPTO_BYTES);

    /* Generate 10 test vectors */
    int num_tests = 10;
    unsigned char *pk = malloc(CRYPTO_PUBLICKEYBYTES);
    unsigned char *sk = malloc(CRYPTO_SECRETKEYBYTES);
    unsigned char *sig = malloc(CRYPTO_BYTES);

    if (!pk || !sk || !sig) {
        fprintf(stderr, "Memory allocation failed\n");
        return 1;
    }

    for (int i = 0; i < num_tests; i++) {
        fprintf(f, "count = %d\n", i);

        /* Generate keypair */
        int ret = crypto_sign_keypair(pk, sk);
        if (ret != 0) {
            fprintf(stderr, "Key generation failed at count %d\n", i);
            fclose(f);
            return 1;
        }

        fprintf(f, "pk = ");
        print_hex_to_file(f, pk, CRYPTO_PUBLICKEYBYTES);
        fprintf(f, "\n");

        fprintf(f, "sk = ");
        print_hex_to_file(f, sk, CRYPTO_SECRETKEYBYTES);
        fprintf(f, "\n");

        /* Test message: "QingLuan KAT message <count>" */
        char msg[64];
        int msg_len = snprintf(msg, sizeof(msg), "QingLuan KAT message %d", i);

        fprintf(f, "msg = ");
        print_hex_to_file(f, (unsigned char *)msg, (size_t)msg_len);
        fprintf(f, "\n");
        fprintf(f, "mlen = %d\n", msg_len);

        /* Generate signature */
        size_t sig_len;
        ret = crypto_sign_signature(sig, &sig_len,
                                    (unsigned char *)msg, (size_t)msg_len, sk);
        if (ret != 0) {
            fprintf(stderr, "Signature generation failed at count %d\n", i);
            fclose(f);
            return 1;
        }

        fprintf(f, "smlen = %zu\n", sig_len);
        fprintf(f, "sig = ");
        print_hex_to_file(f, sig, sig_len);
        fprintf(f, "\n");

        /* Verify */
        ret = crypto_sign_verify(sig, sig_len,
                                 (unsigned char *)msg, (size_t)msg_len, pk);
        fprintf(f, "verify = %s\n", ret == 0 ? "PASS" : "FAIL");
        fprintf(f, "\n");

        if (ret != 0) {
            fprintf(stderr, "WARNING: Self-verification failed at count %d\n", i);
        }

        printf("Generated test vector %d/%d\n", i + 1, num_tests);
    }

    fclose(f);
    free(pk);
    free(sk);
    free(sig);

    printf("KAT vectors written to %s\n", filename);
    return 0;
}
