#ifndef CRETAKE_PARAMS_H
#define CRETAKE_PARAMS_H

#include "primitive_interfaces.h"

#define PKI_LEN PKE_PUBLIC_KEY_BYTES
#define SKI_LEN KEM_SK_BYTES
#define PKR_LEN BIT_PUBLICKEYBYTES
#define SKR_LEN BIT_SECRETKEYBYTES

#define TPK_LEN PKE_PUBLIC_KEY_BYTES
#define TSK_LEN PKE_SECRET_KEY_BYTES

#define C_TILDE_LEN PKE_CIPHERTEXT_BYTES
#define C_I_LEN PKE_CIPHERTEXT_BYTES
#define K_LEN 2 * SS_KEY_BYTES
#define KEM_K_LEN SS_KEY_BYTES
#define SIG_LEN BIT_SIGNBYTES

#define MSG_LEN_BYTES PKE_MESSAGE_BYTES
#define SEED_BYTES KEM_SEED_LEN_BYTES

#endif
