

# This file was *autogenerated* from the file precompute_endomorphism_action.sage
from sage.all_cmdline import *   # import sage library

_sage_const_10 = Integer(10); _sage_const_0 = Integer(0); _sage_const_4 = Integer(4); _sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_10000000 = Integer(10000000); _sage_const_1728 = Integer(1728); _sage_const_64 = Integer(64)#!/usr/bin/env sage
proof.all(False)  # faster

from sage.misc.banner import require_version
if not require_version(_sage_const_10 , _sage_const_0 , print_message=True):
    exit('')

################################################################

from parameters import p, B, f, Tpls, Tmin, Dcom, Dchall, exp3
T = Tpls * Tmin

################################################################

if p % _sage_const_4  != _sage_const_3 :
    raise NotImplementedError('requires p ≡ 3 (mod 4)')

pfact = (p**_sage_const_2 -_sage_const_1 ).factor(limit = _sage_const_10000000 )
plist = [l for (l,e) in pfact]

Fp2 = GF((p,_sage_const_2 ), modulus=[_sage_const_1 ,_sage_const_0 ,_sage_const_1 ], names=('i',)); (i,) = Fp2._first_ngens(1)
Fp4 = Fp2.extension(_sage_const_2 ,'u')
E = EllipticCurve(Fp4, [_sage_const_1 ,_sage_const_0 ])
assert E.j_invariant() == _sage_const_1728 
assert E.is_supersingular()
assert E.change_ring(Fp2).frobenius() == -p
assert E.order() == (p**_sage_const_2 -_sage_const_1 )**_sage_const_2 

endo_1 = E.scalar_multiplication(_sage_const_1 )
endo_i = E.automorphisms()[-_sage_const_1 ]
endo_j = E.frobenius_isogeny()
endo_k = endo_i * endo_j

if _sage_const_0 :  # skipped for speed, for now
    assert endo_i**_sage_const_2  == E.scalar_multiplication(-_sage_const_1 )
    assert endo_j**_sage_const_2  == E.scalar_multiplication(-p)
    assert endo_j * endo_i == - endo_i * endo_j
else:
    R = E.random_point()
    assert (endo_i**_sage_const_2 )(R) == -_sage_const_1 *R
    assert (endo_j**_sage_const_2 )(R) == -p*R
    assert (endo_j*endo_i)(R) == -(endo_i*endo_j)(R)

def half_endo(summands):
    def _eval(P):
        E = P.curve()
        assert P in E
        F = E.base_field()
        if (halves := P.division_points(_sage_const_2 )):
            Q = halves[_sage_const_0 ]
        else:
            Q = E.change_ring(F.extension(_sage_const_2 ,'v'))(P)
        R = sum(endo._eval(Q) for endo in summands)
        return E(R)
    return _eval

gen1 = endo_1._eval
gen2 = endo_i._eval
gen3 = half_endo([endo_i, endo_j])
gen4 = half_endo([endo_1, endo_k])

################################################################

from sage.groups.generic import order_from_multiple
x = Fp4.gen()
while True:
    x += _sage_const_1 
    try:
        P = E.lift_x(x)
    except ValueError:
        continue
    o = order_from_multiple(P, p**_sage_const_2 -_sage_const_1 , plist)
    if (T<<f).divides(o):
        P *= o // (T<<f)
        P.set_order(T<<f)
        break
x = Fp4.gen()
while True:
    x += _sage_const_1 
    try:
        Q = E.lift_x(x)
    except ValueError:
        continue
    o = order_from_multiple(Q, p**_sage_const_2 -_sage_const_1 , plist)
    if not (T<<f).divides(o):
        continue
    Q *= o // (T<<f)
    # Q.set_order(T<<f)
    if order_from_multiple(P.weil_pairing(Q, T<<f), T<<f, operation='*') == T<<f:
        break

def dlp(P, Q, R):
    n = P.order()
    assert(n != _sage_const_0 )
    assert P.order() == Q.order()
    assert (order_from_multiple(R, p**_sage_const_2 -_sage_const_1 , plist)).divides(P.order())
    e = Fp2(P.weil_pairing(Q, n))
    a = Fp2(R.weil_pairing(Q, n))
    a = discrete_log(a,e,n)
    b = Fp2(P.weil_pairing(R, n))
    b = discrete_log(b,e,n)
    assert a*P + b*Q == R
    return a, b

def matrix_of_isogeny(phi):
    imP, imQ = map(phi, (P,Q))
    vecP = dlp(P, Q, imP)
    vecQ = dlp(P, Q, imQ)
    mat = matrix(Zmod(T<<f), [vecP, vecQ]).transpose()
    assert imP == ZZ(mat[_sage_const_0 ][_sage_const_0 ])*P + ZZ(mat[_sage_const_1 ][_sage_const_0 ])*Q
    assert imQ == ZZ(mat[_sage_const_0 ][_sage_const_1 ])*P + ZZ(mat[_sage_const_1 ][_sage_const_1 ])*Q
    return mat

#mat1 = matrix_of_isogeny(endo_1)
mati = matrix_of_isogeny(endo_i)
matj = matrix_of_isogeny(endo_j)
matk = matrix_of_isogeny(endo_k)
#assert mat1 == 1    # identity; omit

#mat1 = matrix_of_isogeny(gen1)
mat2 = matrix_of_isogeny(gen2)
mat3 = matrix_of_isogeny(gen3)
mat4 = matrix_of_isogeny(gen4)
#assert mat1 == 1    # identity; omit

################################################################

Quat = QuaternionAlgebra(-_sage_const_1 , -p, names=('i', 'j', 'k',)); (i, j, k,) = Quat._first_ngens(3)
O0 = Quat.quaternion_order([_sage_const_1 , i, (i+j)/_sage_const_2 , (_sage_const_1 +k)/_sage_const_2 ])

assert Dcom % _sage_const_2  == _sage_const_1   # odd
mat = block_matrix(Zmod(Dcom), [[identity_matrix(_sage_const_2 ), mati, matj, matk]])[:,::_sage_const_2 ]
ker = list(map(Quat, mat.right_kernel_matrix()))
idealP = sum((O0*g for g in ker), O0*Dcom)
assert idealP.norm() == Dcom
for b in idealP.basis():
    assert sum(Mod(c,Dcom)*g for c,g in zip(b,(_sage_const_1 ,mati,matj,matk)))[:,_sage_const_0 ] == _sage_const_0   # kills P

for v in (ZZ**_sage_const_4 ):
    idealPgen = sum(c*g for c,g in zip(v, idealP.basis()))
    if vector(list(idealPgen)).denominator() == _sage_const_2 :
        idealPgen *= _sage_const_2 
    if gcd(idealPgen.reduced_norm(), Dcom**_sage_const_2 ) == Dcom:
        break
assert idealP == O0*Dcom + O0*idealPgen
mat = mat   # still
rhs = vector(Zmod(Dcom), [_sage_const_0 ,_sage_const_1 ])
cs = mat.solve_right(rhs)
distorter = Quat(cs)
assert sum(Mod(c,Dcom)*g for c,g in zip(distorter,(_sage_const_1 ,mati,matj,matk))).columns()[_sage_const_0 ] == vector((_sage_const_0 ,_sage_const_1 ))  # maps P->Q

################################################################

from cformat import Ibz, Object, ObjectFormatter

def field2limbs(el):
    l = _sage_const_1  + floor(log(p, _sage_const_2 **_sage_const_64 ))
    el = Fp2(el)
    vs = [[(int(c) >> _sage_const_64 *i) % _sage_const_2 **_sage_const_64  for i in range(l)] for c in el]
    return vs

def fmt_basis(name, P, Q):
    vs = [
            [field2limbs(T[_sage_const_0 ]), field2limbs(T[_sage_const_2 ])]
            for T in (P,Q,P-Q)
        ]
    return Object('ec_basis_t', name, vs)

bases = {
        'EVEN': _sage_const_1 <<f,
        'THREE': _sage_const_3 **exp3,
        'ODD_PLUS': Tpls,
        'ODD_MINUS': Tmin,
        'COMMITMENT_PLUS': gcd(Tpls, Dcom),
        'COMMITMENT_MINUS': gcd(Tmin, Dcom),
        'CHALLENGE': Dchall,
    }
assert P.order() == Q.order()

objs = ObjectFormatter([
        fmt_basis(f'BASIS_{k}', ZZ(P.order()/v)*P, ZZ(Q.order()/v)*Q)
        for k,v in bases.items()
    ] + [
        Object('ec_curve_t', 'CURVE_E0', [[[int(_sage_const_0 )]], [[int(_sage_const_1 )]]]),
        Object('ec_point_t', 'CURVE_E0_A24', [[[int(_sage_const_0 )]], [[int(_sage_const_1 )]]]),
        Object('ibz_mat_2x2_t', 'ACTION_I', [[Ibz(v) for v in vs] for vs in mati]),
        Object('ibz_mat_2x2_t', 'ACTION_J', [[Ibz(v) for v in vs] for vs in matj]),
        Object('ibz_mat_2x2_t', 'ACTION_K', [[Ibz(v) for v in vs] for vs in matk]),
        Object('ibz_mat_2x2_t', 'ACTION_GEN2', [[Ibz(v) for v in vs] for vs in mat2]),
        Object('ibz_mat_2x2_t', 'ACTION_GEN3', [[Ibz(v) for v in vs] for vs in mat3]),
        Object('ibz_mat_2x2_t', 'ACTION_GEN4', [[Ibz(v) for v in vs] for vs in mat4]),
        Object('quat_alg_elem_t', 'COMMITMENT_IDEAL_UNDISTORTED_GEN', [Ibz(_sage_const_1 ), [Ibz(ZZ(v)) for v in idealPgen]]),
        Object('quat_alg_elem_t', 'COMMITMENT_IDEAL_DISTORTION_ENDO', [Ibz(_sage_const_1 ), [Ibz(ZZ(v)) for v in distorter]]),
    ])

with open('include/endomorphism_action.h','w') as hfile:
    with open('endomorphism_action.c','w') as cfile:
        print(f'#include <intbig.h>', file=hfile)
        print(f'#include <ec.h>', file=hfile)
        print(f'#include <quaternion.h>', file=hfile)
        print(f'#include <stddef.h>', file=cfile)
        print(f'#include <stdint.h>', file=cfile)
        print(f'#include <endomorphism_action.h>', file=cfile)

        objs.header(file=hfile)
        objs.implementation(file=cfile)


