#include "vole_commit.inc"

namespace faest
{

// clang-format off

template void vole_commit<v1::faest_128_s>(block_secpar<v1::faest_128_s::secpar_v>, const typename v1::faest_128_s::tree_prg_t::iv_t&, block_secpar<v1::faest_128_s::secpar_v>* __restrict__, unsigned char* __restrict__, vole_block* __restrict__, vole_block* __restrict__, uint8_t* __restrict__, uint8_t* __restrict__);
template void vole_commit<v1::faest_128_f>(block_secpar<v1::faest_128_f::secpar_v>, const typename v1::faest_128_f::tree_prg_t::iv_t&, block_secpar<v1::faest_128_f::secpar_v>* __restrict__, unsigned char* __restrict__, vole_block* __restrict__, vole_block* __restrict__, uint8_t* __restrict__, uint8_t* __restrict__);
template void vole_commit<v1::faest_192_s>(block_secpar<v1::faest_192_s::secpar_v>, const typename v1::faest_192_s::tree_prg_t::iv_t&, block_secpar<v1::faest_192_s::secpar_v>* __restrict__, unsigned char* __restrict__, vole_block* __restrict__, vole_block* __restrict__, uint8_t* __restrict__, uint8_t* __restrict__);
template void vole_commit<v1::faest_192_f>(block_secpar<v1::faest_192_f::secpar_v>, const typename v1::faest_192_f::tree_prg_t::iv_t&, block_secpar<v1::faest_192_f::secpar_v>* __restrict__, unsigned char* __restrict__, vole_block* __restrict__, vole_block* __restrict__, uint8_t* __restrict__, uint8_t* __restrict__);
template void vole_commit<v1::faest_256_s>(block_secpar<v1::faest_256_s::secpar_v>, const typename v1::faest_256_s::tree_prg_t::iv_t&, block_secpar<v1::faest_256_s::secpar_v>* __restrict__, unsigned char* __restrict__, vole_block* __restrict__, vole_block* __restrict__, uint8_t* __restrict__, uint8_t* __restrict__);
template void vole_commit<v1::faest_256_f>(block_secpar<v1::faest_256_f::secpar_v>, const typename v1::faest_256_f::tree_prg_t::iv_t&, block_secpar<v1::faest_256_f::secpar_v>* __restrict__, unsigned char* __restrict__, vole_block* __restrict__, vole_block* __restrict__, uint8_t* __restrict__, uint8_t* __restrict__);
template void vole_commit<v1::faest_em_128_s>(block_secpar<v1::faest_em_128_s::secpar_v>, const typename v1::faest_em_128_s::tree_prg_t::iv_t&, block_secpar<v1::faest_em_128_s::secpar_v>* __restrict__, unsigned char* __restrict__, vole_block* __restrict__, vole_block* __restrict__, uint8_t* __restrict__, uint8_t* __restrict__);
template void vole_commit<v1::faest_em_128_f>(block_secpar<v1::faest_em_128_f::secpar_v>, const typename v1::faest_em_128_f::tree_prg_t::iv_t&, block_secpar<v1::faest_em_128_f::secpar_v>* __restrict__, unsigned char* __restrict__, vole_block* __restrict__, vole_block* __restrict__, uint8_t* __restrict__, uint8_t* __restrict__);
template void vole_commit<v1::faest_em_192_s>(block_secpar<v1::faest_em_192_s::secpar_v>, const typename v1::faest_em_192_s::tree_prg_t::iv_t&, block_secpar<v1::faest_em_192_s::secpar_v>* __restrict__, unsigned char* __restrict__, vole_block* __restrict__, vole_block* __restrict__, uint8_t* __restrict__, uint8_t* __restrict__);
template void vole_commit<v1::faest_em_192_f>(block_secpar<v1::faest_em_192_f::secpar_v>, const typename v1::faest_em_192_f::tree_prg_t::iv_t&, block_secpar<v1::faest_em_192_f::secpar_v>* __restrict__, unsigned char* __restrict__, vole_block* __restrict__, vole_block* __restrict__, uint8_t* __restrict__, uint8_t* __restrict__);
template void vole_commit<v1::faest_em_256_s>(block_secpar<v1::faest_em_256_s::secpar_v>, const typename v1::faest_em_256_s::tree_prg_t::iv_t&, block_secpar<v1::faest_em_256_s::secpar_v>* __restrict__, unsigned char* __restrict__, vole_block* __restrict__, vole_block* __restrict__, uint8_t* __restrict__, uint8_t* __restrict__);
template void vole_commit<v1::faest_em_256_f>(block_secpar<v1::faest_em_256_f::secpar_v>, const typename v1::faest_em_256_f::tree_prg_t::iv_t&, block_secpar<v1::faest_em_256_f::secpar_v>* __restrict__, unsigned char* __restrict__, vole_block* __restrict__, vole_block* __restrict__, uint8_t* __restrict__, uint8_t* __restrict__);
template void vole_commit<v2::faest_128_s>(block_secpar<v2::faest_128_s::secpar_v>, const typename v2::faest_128_s::tree_prg_t::iv_t&, block_secpar<v2::faest_128_s::secpar_v>* __restrict__, unsigned char* __restrict__, vole_block* __restrict__, vole_block* __restrict__, uint8_t* __restrict__, uint8_t* __restrict__);
template void vole_commit<v2::faest_128_f>(block_secpar<v2::faest_128_f::secpar_v>, const typename v2::faest_128_f::tree_prg_t::iv_t&, block_secpar<v2::faest_128_f::secpar_v>* __restrict__, unsigned char* __restrict__, vole_block* __restrict__, vole_block* __restrict__, uint8_t* __restrict__, uint8_t* __restrict__);
template void vole_commit<v2::faest_192_s>(block_secpar<v2::faest_192_s::secpar_v>, const typename v2::faest_192_s::tree_prg_t::iv_t&, block_secpar<v2::faest_192_s::secpar_v>* __restrict__, unsigned char* __restrict__, vole_block* __restrict__, vole_block* __restrict__, uint8_t* __restrict__, uint8_t* __restrict__);
template void vole_commit<v2::faest_192_f>(block_secpar<v2::faest_192_f::secpar_v>, const typename v2::faest_192_f::tree_prg_t::iv_t&, block_secpar<v2::faest_192_f::secpar_v>* __restrict__, unsigned char* __restrict__, vole_block* __restrict__, vole_block* __restrict__, uint8_t* __restrict__, uint8_t* __restrict__);
template void vole_commit<v2::faest_256_s>(block_secpar<v2::faest_256_s::secpar_v>, const typename v2::faest_256_s::tree_prg_t::iv_t&, block_secpar<v2::faest_256_s::secpar_v>* __restrict__, unsigned char* __restrict__, vole_block* __restrict__, vole_block* __restrict__, uint8_t* __restrict__, uint8_t* __restrict__);
template void vole_commit<v2::faest_256_f>(block_secpar<v2::faest_256_f::secpar_v>, const typename v2::faest_256_f::tree_prg_t::iv_t&, block_secpar<v2::faest_256_f::secpar_v>* __restrict__, unsigned char* __restrict__, vole_block* __restrict__, vole_block* __restrict__, uint8_t* __restrict__, uint8_t* __restrict__);
template void vole_commit<v2::faest_em_128_s>(block_secpar<v2::faest_em_128_s::secpar_v>, const typename v2::faest_em_128_s::tree_prg_t::iv_t&, block_secpar<v2::faest_em_128_s::secpar_v>* __restrict__, unsigned char* __restrict__, vole_block* __restrict__, vole_block* __restrict__, uint8_t* __restrict__, uint8_t* __restrict__);
template void vole_commit<v2::faest_em_128_f>(block_secpar<v2::faest_em_128_f::secpar_v>, const typename v2::faest_em_128_f::tree_prg_t::iv_t&, block_secpar<v2::faest_em_128_f::secpar_v>* __restrict__, unsigned char* __restrict__, vole_block* __restrict__, vole_block* __restrict__, uint8_t* __restrict__, uint8_t* __restrict__);
template void vole_commit<v2::faest_em_192_s>(block_secpar<v2::faest_em_192_s::secpar_v>, const typename v2::faest_em_192_s::tree_prg_t::iv_t&, block_secpar<v2::faest_em_192_s::secpar_v>* __restrict__, unsigned char* __restrict__, vole_block* __restrict__, vole_block* __restrict__, uint8_t* __restrict__, uint8_t* __restrict__);
template void vole_commit<v2::faest_em_192_f>(block_secpar<v2::faest_em_192_f::secpar_v>, const typename v2::faest_em_192_f::tree_prg_t::iv_t&, block_secpar<v2::faest_em_192_f::secpar_v>* __restrict__, unsigned char* __restrict__, vole_block* __restrict__, vole_block* __restrict__, uint8_t* __restrict__, uint8_t* __restrict__);
template void vole_commit<v2::faest_em_256_s>(block_secpar<v2::faest_em_256_s::secpar_v>, const typename v2::faest_em_256_s::tree_prg_t::iv_t&, block_secpar<v2::faest_em_256_s::secpar_v>* __restrict__, unsigned char* __restrict__, vole_block* __restrict__, vole_block* __restrict__, uint8_t* __restrict__, uint8_t* __restrict__);
template void vole_commit<v2::faest_em_256_f>(block_secpar<v2::faest_em_256_f::secpar_v>, const typename v2::faest_em_256_f::tree_prg_t::iv_t&, block_secpar<v2::faest_em_256_f::secpar_v>* __restrict__, unsigned char* __restrict__, vole_block* __restrict__, vole_block* __restrict__, uint8_t* __restrict__, uint8_t* __restrict__);
template void vole_commit<galas::galas_128s>(block_secpar<galas::galas_128s::secpar_v>, const typename galas::galas_128s::tree_prg_t::iv_t&, block_secpar<galas::galas_128s::secpar_v>* __restrict__, unsigned char* __restrict__, vole_block* __restrict__, vole_block* __restrict__, uint8_t* __restrict__, uint8_t* __restrict__);
template void vole_commit<galas::galas_128f>(block_secpar<galas::galas_128f::secpar_v>, const typename galas::galas_128f::tree_prg_t::iv_t&, block_secpar<galas::galas_128f::secpar_v>* __restrict__, unsigned char* __restrict__, vole_block* __restrict__, vole_block* __restrict__, uint8_t* __restrict__, uint8_t* __restrict__);
template void vole_commit<galas::galas_192s>(block_secpar<galas::galas_192s::secpar_v>, const typename galas::galas_192s::tree_prg_t::iv_t&, block_secpar<galas::galas_192s::secpar_v>* __restrict__, unsigned char* __restrict__, vole_block* __restrict__, vole_block* __restrict__, uint8_t* __restrict__, uint8_t* __restrict__);
template void vole_commit<galas::galas_192f>(block_secpar<galas::galas_192f::secpar_v>, const typename galas::galas_192f::tree_prg_t::iv_t&, block_secpar<galas::galas_192f::secpar_v>* __restrict__, unsigned char* __restrict__, vole_block* __restrict__, vole_block* __restrict__, uint8_t* __restrict__, uint8_t* __restrict__);
template void vole_commit<galas::galas_256s>(block_secpar<galas::galas_256s::secpar_v>, const typename galas::galas_256s::tree_prg_t::iv_t&, block_secpar<galas::galas_256s::secpar_v>* __restrict__, unsigned char* __restrict__, vole_block* __restrict__, vole_block* __restrict__, uint8_t* __restrict__, uint8_t* __restrict__);
template void vole_commit<galas::galas_ngcc_160s>(block_secpar<galas::galas_ngcc_160s::secpar_v>, const typename galas::galas_ngcc_160s::tree_prg_t::iv_t&, block_secpar<galas::galas_ngcc_160s::secpar_v>* __restrict__, unsigned char* __restrict__, vole_block* __restrict__, vole_block* __restrict__, uint8_t* __restrict__, uint8_t* __restrict__);
template void vole_commit<galas::galas_ngcc_384s>(block_secpar<galas::galas_ngcc_384s::secpar_v>, const typename galas::galas_ngcc_384s::tree_prg_t::iv_t&, block_secpar<galas::galas_ngcc_384s::secpar_v>* __restrict__, unsigned char* __restrict__, vole_block* __restrict__, vole_block* __restrict__, uint8_t* __restrict__, uint8_t* __restrict__);
template void vole_commit<galas::galas_ngcc_512s>(block_secpar<galas::galas_ngcc_512s::secpar_v>, const typename galas::galas_ngcc_512s::tree_prg_t::iv_t&, block_secpar<galas::galas_ngcc_512s::secpar_v>* __restrict__, unsigned char* __restrict__, vole_block* __restrict__, vole_block* __restrict__, uint8_t* __restrict__, uint8_t* __restrict__);
template void vole_commit<galas::galas_ngcc_256s>(block_secpar<galas::galas_ngcc_256s::secpar_v>, const typename galas::galas_ngcc_256s::tree_prg_t::iv_t&, block_secpar<galas::galas_ngcc_256s::secpar_v>* __restrict__, unsigned char* __restrict__, vole_block* __restrict__, vole_block* __restrict__, uint8_t* __restrict__, uint8_t* __restrict__);
template void vole_commit<galas::galas_256f>(block_secpar<galas::galas_256f::secpar_v>, const typename galas::galas_256f::tree_prg_t::iv_t&, block_secpar<galas::galas_256f::secpar_v>* __restrict__, unsigned char* __restrict__, vole_block* __restrict__, vole_block* __restrict__, uint8_t* __restrict__, uint8_t* __restrict__);
template void vole_commit<galas::galas_ngcc_160f>(block_secpar<galas::galas_ngcc_160f::secpar_v>, const typename galas::galas_ngcc_160f::tree_prg_t::iv_t&, block_secpar<galas::galas_ngcc_160f::secpar_v>* __restrict__, unsigned char* __restrict__, vole_block* __restrict__, vole_block* __restrict__, uint8_t* __restrict__, uint8_t* __restrict__);
template void vole_commit<galas::galas_ngcc_384f>(block_secpar<galas::galas_ngcc_384f::secpar_v>, const typename galas::galas_ngcc_384f::tree_prg_t::iv_t&, block_secpar<galas::galas_ngcc_384f::secpar_v>* __restrict__, unsigned char* __restrict__, vole_block* __restrict__, vole_block* __restrict__, uint8_t* __restrict__, uint8_t* __restrict__);
template void vole_commit<galas::galas_ngcc_512f>(block_secpar<galas::galas_ngcc_512f::secpar_v>, const typename galas::galas_ngcc_512f::tree_prg_t::iv_t&, block_secpar<galas::galas_ngcc_512f::secpar_v>* __restrict__, unsigned char* __restrict__, vole_block* __restrict__, vole_block* __restrict__, uint8_t* __restrict__, uint8_t* __restrict__);
template void vole_commit<galas::galas_ngcc_256f>(block_secpar<galas::galas_ngcc_256f::secpar_v>, const typename galas::galas_ngcc_256f::tree_prg_t::iv_t&, block_secpar<galas::galas_ngcc_256f::secpar_v>* __restrict__, unsigned char* __restrict__, vole_block* __restrict__, vole_block* __restrict__, uint8_t* __restrict__, uint8_t* __restrict__);

template bool vole_reconstruct<v1::faest_128_s>(const typename v1::faest_128_s::tree_prg_t::iv_t&, vole_block* __restrict__, const uint8_t*, const uint8_t* __restrict__, const uint8_t* __restrict__, uint8_t* __restrict__);
template bool vole_reconstruct<v1::faest_128_f>(const typename v1::faest_128_f::tree_prg_t::iv_t&, vole_block* __restrict__, const uint8_t*, const uint8_t* __restrict__, const uint8_t* __restrict__, uint8_t* __restrict__);
template bool vole_reconstruct<v1::faest_192_s>(const typename v1::faest_192_s::tree_prg_t::iv_t&, vole_block* __restrict__, const uint8_t*, const uint8_t* __restrict__, const uint8_t* __restrict__, uint8_t* __restrict__);
template bool vole_reconstruct<v1::faest_192_f>(const typename v1::faest_192_f::tree_prg_t::iv_t&, vole_block* __restrict__, const uint8_t*, const uint8_t* __restrict__, const uint8_t* __restrict__, uint8_t* __restrict__);
template bool vole_reconstruct<v1::faest_256_s>(const typename v1::faest_256_s::tree_prg_t::iv_t&, vole_block* __restrict__, const uint8_t*, const uint8_t* __restrict__, const uint8_t* __restrict__, uint8_t* __restrict__);
template bool vole_reconstruct<v1::faest_256_f>(const typename v1::faest_256_f::tree_prg_t::iv_t&, vole_block* __restrict__, const uint8_t*, const uint8_t* __restrict__, const uint8_t* __restrict__, uint8_t* __restrict__);
template bool vole_reconstruct<v1::faest_em_128_s>(const typename v1::faest_em_128_s::tree_prg_t::iv_t&, vole_block* __restrict__, const uint8_t*, const uint8_t* __restrict__, const uint8_t* __restrict__, uint8_t* __restrict__);
template bool vole_reconstruct<v1::faest_em_128_f>(const typename v1::faest_em_128_f::tree_prg_t::iv_t&, vole_block* __restrict__, const uint8_t*, const uint8_t* __restrict__, const uint8_t* __restrict__, uint8_t* __restrict__);
template bool vole_reconstruct<v1::faest_em_192_s>(const typename v1::faest_em_192_s::tree_prg_t::iv_t&, vole_block* __restrict__, const uint8_t*, const uint8_t* __restrict__, const uint8_t* __restrict__, uint8_t* __restrict__);
template bool vole_reconstruct<v1::faest_em_192_f>(const typename v1::faest_em_192_f::tree_prg_t::iv_t&, vole_block* __restrict__, const uint8_t*, const uint8_t* __restrict__, const uint8_t* __restrict__, uint8_t* __restrict__);
template bool vole_reconstruct<v1::faest_em_256_s>(const typename v1::faest_em_256_s::tree_prg_t::iv_t&, vole_block* __restrict__, const uint8_t*, const uint8_t* __restrict__, const uint8_t* __restrict__, uint8_t* __restrict__);
template bool vole_reconstruct<v1::faest_em_256_f>(const typename v1::faest_em_256_f::tree_prg_t::iv_t&, vole_block* __restrict__, const uint8_t*, const uint8_t* __restrict__, const uint8_t* __restrict__, uint8_t* __restrict__);
template bool vole_reconstruct<v2::faest_128_s>(const typename v2::faest_128_s::tree_prg_t::iv_t&, vole_block* __restrict__, const uint8_t*, const uint8_t* __restrict__, const uint8_t* __restrict__, uint8_t* __restrict__);
template bool vole_reconstruct<v2::faest_128_f>(const typename v2::faest_128_f::tree_prg_t::iv_t&, vole_block* __restrict__, const uint8_t*, const uint8_t* __restrict__, const uint8_t* __restrict__, uint8_t* __restrict__);
template bool vole_reconstruct<v2::faest_192_s>(const typename v2::faest_192_s::tree_prg_t::iv_t&, vole_block* __restrict__, const uint8_t*, const uint8_t* __restrict__, const uint8_t* __restrict__, uint8_t* __restrict__);
template bool vole_reconstruct<v2::faest_192_f>(const typename v2::faest_192_f::tree_prg_t::iv_t&, vole_block* __restrict__, const uint8_t*, const uint8_t* __restrict__, const uint8_t* __restrict__, uint8_t* __restrict__);
template bool vole_reconstruct<v2::faest_256_s>(const typename v2::faest_256_s::tree_prg_t::iv_t&, vole_block* __restrict__, const uint8_t*, const uint8_t* __restrict__, const uint8_t* __restrict__, uint8_t* __restrict__);
template bool vole_reconstruct<v2::faest_256_f>(const typename v2::faest_256_f::tree_prg_t::iv_t&, vole_block* __restrict__, const uint8_t*, const uint8_t* __restrict__, const uint8_t* __restrict__, uint8_t* __restrict__);
template bool vole_reconstruct<v2::faest_em_128_s>(const typename v2::faest_em_128_s::tree_prg_t::iv_t&, vole_block* __restrict__, const uint8_t*, const uint8_t* __restrict__, const uint8_t* __restrict__, uint8_t* __restrict__);
template bool vole_reconstruct<v2::faest_em_128_f>(const typename v2::faest_em_128_f::tree_prg_t::iv_t&, vole_block* __restrict__, const uint8_t*, const uint8_t* __restrict__, const uint8_t* __restrict__, uint8_t* __restrict__);
template bool vole_reconstruct<v2::faest_em_192_s>(const typename v2::faest_em_192_s::tree_prg_t::iv_t&, vole_block* __restrict__, const uint8_t*, const uint8_t* __restrict__, const uint8_t* __restrict__, uint8_t* __restrict__);
template bool vole_reconstruct<v2::faest_em_192_f>(const typename v2::faest_em_192_f::tree_prg_t::iv_t&, vole_block* __restrict__, const uint8_t*, const uint8_t* __restrict__, const uint8_t* __restrict__, uint8_t* __restrict__);
template bool vole_reconstruct<v2::faest_em_256_s>(const typename v2::faest_em_256_s::tree_prg_t::iv_t&, vole_block* __restrict__, const uint8_t*, const uint8_t* __restrict__, const uint8_t* __restrict__, uint8_t* __restrict__);
template bool vole_reconstruct<v2::faest_em_256_f>(const typename v2::faest_em_256_f::tree_prg_t::iv_t&, vole_block* __restrict__, const uint8_t*, const uint8_t* __restrict__, const uint8_t* __restrict__, uint8_t* __restrict__);
template bool vole_reconstruct<galas::galas_128s>(const typename galas::galas_128s::tree_prg_t::iv_t&, vole_block* __restrict__, const uint8_t*, const uint8_t* __restrict__, const uint8_t* __restrict__, uint8_t* __restrict__);
template bool vole_reconstruct<galas::galas_128f>(const typename galas::galas_128f::tree_prg_t::iv_t&, vole_block* __restrict__, const uint8_t*, const uint8_t* __restrict__, const uint8_t* __restrict__, uint8_t* __restrict__);
template bool vole_reconstruct<galas::galas_192s>(const typename galas::galas_192s::tree_prg_t::iv_t&, vole_block* __restrict__, const uint8_t*, const uint8_t* __restrict__, const uint8_t* __restrict__, uint8_t* __restrict__);
template bool vole_reconstruct<galas::galas_192f>(const typename galas::galas_192f::tree_prg_t::iv_t&, vole_block* __restrict__, const uint8_t*, const uint8_t* __restrict__, const uint8_t* __restrict__, uint8_t* __restrict__);
template bool vole_reconstruct<galas::galas_256s>(const typename galas::galas_256s::tree_prg_t::iv_t&, vole_block* __restrict__, const uint8_t*, const uint8_t* __restrict__, const uint8_t* __restrict__, uint8_t* __restrict__);
template bool vole_reconstruct<galas::galas_ngcc_160s>(const typename galas::galas_ngcc_160s::tree_prg_t::iv_t&, vole_block* __restrict__, const uint8_t*, const uint8_t* __restrict__, const uint8_t* __restrict__, uint8_t* __restrict__);
template bool vole_reconstruct<galas::galas_ngcc_384s>(const typename galas::galas_ngcc_384s::tree_prg_t::iv_t&, vole_block* __restrict__, const uint8_t*, const uint8_t* __restrict__, const uint8_t* __restrict__, uint8_t* __restrict__);
template bool vole_reconstruct<galas::galas_ngcc_512s>(const typename galas::galas_ngcc_512s::tree_prg_t::iv_t&, vole_block* __restrict__, const uint8_t*, const uint8_t* __restrict__, const uint8_t* __restrict__, uint8_t* __restrict__);
template bool vole_reconstruct<galas::galas_ngcc_256s>(const typename galas::galas_ngcc_256s::tree_prg_t::iv_t&, vole_block* __restrict__, const uint8_t*, const uint8_t* __restrict__, const uint8_t* __restrict__, uint8_t* __restrict__);
template bool vole_reconstruct<galas::galas_256f>(const typename galas::galas_256f::tree_prg_t::iv_t&, vole_block* __restrict__, const uint8_t*, const uint8_t* __restrict__, const uint8_t* __restrict__, uint8_t* __restrict__);
template bool vole_reconstruct<galas::galas_ngcc_160f>(const typename galas::galas_ngcc_160f::tree_prg_t::iv_t&, vole_block* __restrict__, const uint8_t*, const uint8_t* __restrict__, const uint8_t* __restrict__, uint8_t* __restrict__);
template bool vole_reconstruct<galas::galas_ngcc_384f>(const typename galas::galas_ngcc_384f::tree_prg_t::iv_t&, vole_block* __restrict__, const uint8_t*, const uint8_t* __restrict__, const uint8_t* __restrict__, uint8_t* __restrict__);
template bool vole_reconstruct<galas::galas_ngcc_512f>(const typename galas::galas_ngcc_512f::tree_prg_t::iv_t&, vole_block* __restrict__, const uint8_t*, const uint8_t* __restrict__, const uint8_t* __restrict__, uint8_t* __restrict__);
template bool vole_reconstruct<galas::galas_ngcc_256f>(const typename galas::galas_ngcc_256f::tree_prg_t::iv_t&, vole_block* __restrict__, const uint8_t*, const uint8_t* __restrict__, const uint8_t* __restrict__, uint8_t* __restrict__);

} // namespace faest
