#ifndef POLARKEM_POLAR_H
#define POLARKEM_POLAR_H

#include <stdint.h>

#include "polarkem_params.h"

#ifdef __cplusplus
extern "C" {
#endif

/** Exact BEC(1/2) information positions in numeric ascending order. */
extern const uint16_t polarkem_info_positions[POLARKEM_MESSAGE_BITS];

/**
 * Apply the no-bit-reversal Arikan transform F^(tensor log2(N)) in place.
 *
 * @param[in,out] bits POLARKEM_N one-byte binary values.  On return each
 *                     element is again either zero or one.  The transform is
 *                     its own inverse over GF(2).
 * @return Nothing; the transform is applied in place to POLARKEM_N bytes.
 */
void polarkem_polar_transform(unsigned char bits[POLARKEM_N]);

/**
 * Place a message in the fixed information set and Polar-encode it.
 *
 * @param[in]  mu       POLARKEM_MESSAGE_BYTES bytes; bits are read LSB-first.
 * @param[out] codeword POLARKEM_N one-byte binary values.
 * @return Nothing; the function writes the complete codeword.
 */
void polarkem_polar_encode(
    const unsigned char mu[POLARKEM_MESSAGE_BYTES],
    unsigned char codeword[POLARKEM_N]);

/**
 * Invert the Polar transform and extract the fixed information positions.
 *
 * @param[in]  codeword POLARKEM_N one-byte binary values.
 * @param[out] mu       POLARKEM_MESSAGE_BYTES bytes, written LSB-first.
 * @return Nothing; the function writes the complete message.
 */
void polarkem_polar_decode(
    const unsigned char codeword[POLARKEM_N],
    unsigned char mu[POLARKEM_MESSAGE_BYTES]);

/**
 * Expand a transform seed into the canonical signed permutation.
 *
 * The permutation is generated by unbiased Fisher-Yates sampling from
 * 4096-byte pseudoXOF blocks.  Signs use an independent exact-N-bit XOF.
 * The convention is dst[i] = sign[i] * src[permutation[i]].
 *
 * @param[in]  seed        POLARKEM_SEED_BYTES public transform-seed bytes.
 * @param[out] permutation POLARKEM_N source indices, one per destination.
 * @param[out] sign        POLARKEM_N values, each exactly +1 or -1.
 * @return 0 on success, or -4 if pseudoXOF reports an error.
 */
int polarkem_signed_permutation(
    const unsigned char seed[POLARKEM_SEED_BYTES],
    uint16_t permutation[POLARKEM_N],
    int8_t sign[POLARKEM_N]);

#ifdef __cplusplus
}
#endif

#endif
