/*
 * QingLuan Digital Signature Scheme
 * restr.h - Restricted subgroup arithmetic over E = <g> subset F_q*
 *
 * E is the cyclic multiplicative subgroup generated by g, of order z = PARAM_Z.
 * Restricted error coordinates live in E; we represent them either by value
 * (fq_t) or by exponent (0..z-1). The group operation on E corresponds to
 * addition of exponents modulo z.
 */
#ifndef QINGLUAN_RESTR_H
#define QINGLUAN_RESTR_H

#include "params.h"
#include <stdint.h>
#include <stddef.h>

/* Build the restricted-set table from (PARAM_G, PARAM_Z, PARAM_Q). Idempotent. */
void    restr_init(void);

/* Return g^exp for exp in [0, z). Constant-time table read (no secret index). */
fq_t    restr_val(uint8_t exp);

/* (a + b) mod z, constant-time, inputs assumed in [0, z). */
uint8_t restr_exp_add(uint8_t a, uint8_t b);

/* (a - b) mod z, constant-time, inputs assumed in [0, z). Used for v = eta - eta'. */
uint8_t restr_exp_sub(uint8_t a, uint8_t b);

/* Map an exponent vector to restricted values: e[i] = g^eta[i]. */
void    restr_vec_from_exp(fq_t *e, const uint8_t *eta, size_t n);

#endif /* QINGLUAN_RESTR_H */
