/* Autogenerated: 'src/ExtractionOCaml/fiat_crypto' word-by-word-montgomery p271 64 '2^137 * 3^84 - 1' mul square add sub opp to_montgomery from_montgomery -o p271_core_64.c */
/* curve description: p271 */
/* machine_wordsize = 64 (from "64") */
/* requested operations: mul, square, add, sub, opp, to_montgomery, from_montgomery */
/* m = 0x465e3d19960596fb1e8c4c9e5305185121ffffffffffffffffffffffffffffffffff (from "2^137 * 3^84 - 1") */
/*                                                                    */
/* NOTE: In addition to the bounds specified above each function, all */
/*   functions synthesized for this Montgomery arithmetic require the */
/*   input to be strictly less than the prime modulus (m), and also   */
/*   require the input to be in the unique saturated representation.  */
/*   All functions also ensure that these two properties are true of  */
/*   return values.                                                   */
/*  */
/* Computed values: */
/*   eval z = z[0] + (z[1] << 64) + (z[2] << 128) + (z[3] << 192) + (z[4] << 256) */
/*   bytes_eval z = z[0] + (z[1] << 8) + (z[2] << 16) + (z[3] << 24) + (z[4] << 32) + (z[5] << 40) + (z[6] << 48) + (z[7] << 56) + (z[8] << 64) + (z[9] << 72) + (z[10] << 80) + (z[11] << 88) + (z[12] << 96) + (z[13] << 104) + (z[14] << 112) + (z[15] << 120) + (z[16] << 128) + (z[17] << 136) + (z[18] << 144) + (z[19] << 152) + (z[20] << 160) + (z[21] << 168) + (z[22] << 176) + (z[23] << 184) + (z[24] << 192) + (z[25] << 200) + (z[26] << 208) + (z[27] << 216) + (z[28] << 224) + (z[29] << 232) + (z[30] << 240) + (z[31] << 248) + (z[32] << 256) + (z[33] << 0x108) */
/*   twos_complement_eval z = let x1 := z[0] + (z[1] << 64) + (z[2] << 128) + (z[3] << 192) + (z[4] << 256) in */
/*                            if x1 & (2^320-1) < 2^319 then x1 & (2^320-1) else (x1 & (2^320-1)) - 2^320 */

#include <stdint.h>
#include <fp_portable.h>
typedef unsigned char fiat_p271_uint1;
typedef signed char fiat_p271_int1;
#if defined(__GNUC__) || defined(__clang__)
#define FIAT_p271_FIAT_EXTENSION __extension__
#define FIAT_p271_FIAT_INLINE __inline__
#else
#define FIAT_p271_FIAT_EXTENSION
#define FIAT_p271_FIAT_INLINE
#endif

#if SQISIGN_HAS_UINT128
FIAT_p271_FIAT_EXTENSION typedef unsigned __int128 fiat_p271_uint128;
#endif

/* The type fiat_p271_montgomery_domain_field_element is a field element in the Montgomery domain. */
/* Bounds: [[0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff]] */
typedef uint64_t fiat_p271_montgomery_domain_field_element[5];

/* The type fiat_p271_non_montgomery_domain_field_element is a field element NOT in the Montgomery domain. */
/* Bounds: [[0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff]] */
typedef uint64_t fiat_p271_non_montgomery_domain_field_element[5];

#if (-1 & 3) != 3
#error "This code only works on a two's complement system"
#endif

/*
 * The function fiat_p271_addcarryx_u64 is an addition with carry.
 *
 * Postconditions:
 *   out1 = (arg1 + arg2 + arg3) mod 2^64
 *   out2 = ?(arg1 + arg2 + arg3) / 2^64?
 *
 * Input Bounds:
 *   arg1: [0x0 ~> 0x1]
 *   arg2: [0x0 ~> 0xffffffffffffffff]
 *   arg3: [0x0 ~> 0xffffffffffffffff]
 * Output Bounds:
 *   out1: [0x0 ~> 0xffffffffffffffff]
 *   out2: [0x0 ~> 0x1]
 */
void fiat_p271_addcarryx_u64(uint64_t *out1, fiat_p271_uint1 *out2, fiat_p271_uint1 arg1, uint64_t arg2, uint64_t arg3)
{
  uint64_t tmp = arg3 + arg1;
  *out1 = arg2 + tmp;
  *out2 = (arg2 > *out1) | (arg3 > tmp);

  //*out2 = _addcarryx_u64(arg1, arg2, arg3, out1);
}

/*
 * The function fiat_p271_subborrowx_u64 is a subtraction with borrow.
 *
 * Postconditions:
 *   out1 = (-arg1 + arg2 + -arg3) mod 2^64
 *   out2 = -?(-arg1 + arg2 + -arg3) / 2^64?
 *
 * Input Bounds:
 *   arg1: [0x0 ~> 0x1]
 *   arg2: [0x0 ~> 0xffffffffffffffff]
 *   arg3: [0x0 ~> 0xffffffffffffffff]
 * Output Bounds:
 *   out1: [0x0 ~> 0xffffffffffffffff]
 *   out2: [0x0 ~> 0x1]
 */
void fiat_p271_subborrowx_u64(uint64_t *out1, fiat_p271_uint1 *out2, fiat_p271_uint1 arg1, uint64_t arg2, uint64_t arg3)
{
  uint64_t tmp = arg3 + arg1;
  *out1 = arg2 - tmp;
  *out2 = (arg2 < *out1) | (arg3 > tmp);

  //*out2 = _subborrow_u64(arg1, arg2, arg3, out1);
}

/*
 * The function fiat_p271_mulx_u64 is a multiplication, returning the full double-width result.
 *
 * Postconditions:
 *   out1 = (arg1 * arg2) mod 2^64
 *   out2 = ?arg1 * arg2 / 2^64?
 *
 * Input Bounds:
 *   arg1: [0x0 ~> 0xffffffffffffffff]
 *   arg2: [0x0 ~> 0xffffffffffffffff]
 * Output Bounds:
 *   out1: [0x0 ~> 0xffffffffffffffff]
 *   out2: [0x0 ~> 0xffffffffffffffff]
 */
void fiat_p271_mulx_u64(uint64_t *out1, uint64_t *out2, uint64_t arg1, uint64_t arg2)
{
  uint64_t a_lo = (uint32_t)arg1;
  uint64_t a_hi = arg1 >> 32;
  uint64_t b_lo = (uint32_t)arg2;
  uint64_t b_hi = arg2 >> 32;

  uint64_t a_x_b_hi = a_hi * b_hi;
  uint64_t a_x_b_mid = a_hi * b_lo;
  uint64_t b_x_a_mid = b_hi * a_lo;
  uint64_t a_x_b_lo = a_lo * b_lo;

  uint64_t carry_bit = ((uint64_t)(uint32_t)a_x_b_mid +
                        (uint64_t)(uint32_t)b_x_a_mid +
                        (a_x_b_lo >> 32)) >>
                       32;

  uint64_t multhi = a_x_b_hi +
                    (a_x_b_mid >> 32) + (b_x_a_mid >> 32) +
                    carry_bit;

  *out2 = multhi;
  // TODO: This multiplication could be avoided.
  *out1 = arg1 * arg2;

  //*out1 = _umul128(arg1, arg2, out2);
}

/*
 * The function fiat_p271_cmovznz_u64 is a single-word conditional move.
 *
 * Postconditions:
 *   out1 = (if arg1 = 0 then arg2 else arg3)
 *
 * Input Bounds:
 *   arg1: [0x0 ~> 0x1]
 *   arg2: [0x0 ~> 0xffffffffffffffff]
 *   arg3: [0x0 ~> 0xffffffffffffffff]
 * Output Bounds:
 *   out1: [0x0 ~> 0xffffffffffffffff]
 */
void fiat_p271_cmovznz_u64(uint64_t *out1, fiat_p271_uint1 arg1, uint64_t arg2, uint64_t arg3)
{
  fiat_p271_uint1 x1;
  uint64_t x2;
  uint64_t x3;
  x1 = (!(!arg1));
  x2 = ((fiat_p271_int1)(0x0 - x1) & UINT64_C(0xffffffffffffffff));
  x3 = ((x2 & arg3) | ((~x2) & arg2));
  *out1 = x3;
}

/*
 * The function fiat_p271_mul multiplies two field elements in the Montgomery domain.
 *
 * Preconditions:
 *   0 ≤ eval arg1 < m
 *   0 ≤ eval arg2 < m
 * Postconditions:
 *   eval (from_montgomery out1) mod m = (eval (from_montgomery arg1) * eval (from_montgomery arg2)) mod m
 *   0 ≤ eval out1 < m
 *
 */
#if SQISIGN_HAS_UINT128
static void
fiat_p271_mul_uint128(fiat_p271_montgomery_domain_field_element out1,
                      const fiat_p271_montgomery_domain_field_element arg1,
                      const fiat_p271_montgomery_domain_field_element arg2)
{
  const uint64_t a0 = arg1[0], a1 = arg1[1], a2 = arg1[2], a3 = arg1[3], a4 = arg1[4];
  const uint64_t b0 = arg2[0], b1 = arg2[1], b2 = arg2[2], b3 = arg2[3], b4 = arg2[4];
  const uint64_t P0 = UINT64_C(0xffffffffffffffff);
  const uint64_t P1 = UINT64_C(0xffffffffffffffff);
  const uint64_t P2 = UINT64_C(0x4c9e5305185121ff);
  const uint64_t P3 = UINT64_C(0x3d19960596fb1e8c);
  const uint64_t P4 = UINT64_C(0x000000000000465e);
  uint64_t t0, t1, t2, t3, t4, t5, t6, t7, t8, t9, t10;
  fiat_p271_uint128 p;

  p = (fiat_p271_uint128)a0 * b0;             t0 = (uint64_t)p;
  p = (fiat_p271_uint128)a0 * b1 + (p >> 64); t1 = (uint64_t)p;
  p = (fiat_p271_uint128)a0 * b2 + (p >> 64); t2 = (uint64_t)p;
  p = (fiat_p271_uint128)a0 * b3 + (p >> 64); t3 = (uint64_t)p;
  p = (fiat_p271_uint128)a0 * b4 + (p >> 64); t4 = (uint64_t)p;
  t5 = (uint64_t)(p >> 64);

  p = (fiat_p271_uint128)a1 * b0 + t1;             t1 = (uint64_t)p;
  p = (fiat_p271_uint128)a1 * b1 + t2 + (p >> 64); t2 = (uint64_t)p;
  p = (fiat_p271_uint128)a1 * b2 + t3 + (p >> 64); t3 = (uint64_t)p;
  p = (fiat_p271_uint128)a1 * b3 + t4 + (p >> 64); t4 = (uint64_t)p;
  p = (fiat_p271_uint128)a1 * b4 + t5 + (p >> 64); t5 = (uint64_t)p;
  t6 = (uint64_t)(p >> 64);

  p = (fiat_p271_uint128)a2 * b0 + t2;             t2 = (uint64_t)p;
  p = (fiat_p271_uint128)a2 * b1 + t3 + (p >> 64); t3 = (uint64_t)p;
  p = (fiat_p271_uint128)a2 * b2 + t4 + (p >> 64); t4 = (uint64_t)p;
  p = (fiat_p271_uint128)a2 * b3 + t5 + (p >> 64); t5 = (uint64_t)p;
  p = (fiat_p271_uint128)a2 * b4 + t6 + (p >> 64); t6 = (uint64_t)p;
  t7 = (uint64_t)(p >> 64);

  p = (fiat_p271_uint128)a3 * b0 + t3;             t3 = (uint64_t)p;
  p = (fiat_p271_uint128)a3 * b1 + t4 + (p >> 64); t4 = (uint64_t)p;
  p = (fiat_p271_uint128)a3 * b2 + t5 + (p >> 64); t5 = (uint64_t)p;
  p = (fiat_p271_uint128)a3 * b3 + t6 + (p >> 64); t6 = (uint64_t)p;
  p = (fiat_p271_uint128)a3 * b4 + t7 + (p >> 64); t7 = (uint64_t)p;
  t8 = (uint64_t)(p >> 64);

  p = (fiat_p271_uint128)a4 * b0 + t4;             t4 = (uint64_t)p;
  p = (fiat_p271_uint128)a4 * b1 + t5 + (p >> 64); t5 = (uint64_t)p;
  p = (fiat_p271_uint128)a4 * b2 + t6 + (p >> 64); t6 = (uint64_t)p;
  p = (fiat_p271_uint128)a4 * b3 + t7 + (p >> 64); t7 = (uint64_t)p;
  p = (fiat_p271_uint128)a4 * b4 + t8 + (p >> 64); t8 = (uint64_t)p;
  t9 = (uint64_t)(p >> 64);

  p = (fiat_p271_uint128)t0 * P2 + t2 + t0;        t2 = (uint64_t)p;
  p = (fiat_p271_uint128)t0 * P3 + t3 + (p >> 64); t3 = (uint64_t)p;
  p = (fiat_p271_uint128)t0 * P4 + t4 + (p >> 64); t4 = (uint64_t)p;
  p = (fiat_p271_uint128)t5 + (p >> 64);           t5 = (uint64_t)p;
  p = (fiat_p271_uint128)t6 + (p >> 64);           t6 = (uint64_t)p;
  p = (fiat_p271_uint128)t7 + (p >> 64);           t7 = (uint64_t)p;
  p = (fiat_p271_uint128)t8 + (p >> 64);           t8 = (uint64_t)p;
  p = (fiat_p271_uint128)t9 + (p >> 64);           t9 = (uint64_t)p;
  t10 = (uint64_t)(p >> 64);

  p = (fiat_p271_uint128)t1 * P2 + t3 + t1;        t3 = (uint64_t)p;
  p = (fiat_p271_uint128)t1 * P3 + t4 + (p >> 64); t4 = (uint64_t)p;
  p = (fiat_p271_uint128)t1 * P4 + t5 + (p >> 64); t5 = (uint64_t)p;
  p = (fiat_p271_uint128)t6 + (p >> 64);           t6 = (uint64_t)p;
  p = (fiat_p271_uint128)t7 + (p >> 64);           t7 = (uint64_t)p;
  p = (fiat_p271_uint128)t8 + (p >> 64);           t8 = (uint64_t)p;
  p = (fiat_p271_uint128)t9 + (p >> 64);           t9 = (uint64_t)p;
  t10 += (uint64_t)(p >> 64);

  p = (fiat_p271_uint128)t2 * P2 + t4 + t2;        t4 = (uint64_t)p;
  p = (fiat_p271_uint128)t2 * P3 + t5 + (p >> 64); t5 = (uint64_t)p;
  p = (fiat_p271_uint128)t2 * P4 + t6 + (p >> 64); t6 = (uint64_t)p;
  p = (fiat_p271_uint128)t7 + (p >> 64);           t7 = (uint64_t)p;
  p = (fiat_p271_uint128)t8 + (p >> 64);           t8 = (uint64_t)p;
  p = (fiat_p271_uint128)t9 + (p >> 64);           t9 = (uint64_t)p;
  t10 += (uint64_t)(p >> 64);

  p = (fiat_p271_uint128)t3 * P2 + t5 + t3;        t5 = (uint64_t)p;
  p = (fiat_p271_uint128)t3 * P3 + t6 + (p >> 64); t6 = (uint64_t)p;
  p = (fiat_p271_uint128)t3 * P4 + t7 + (p >> 64); t7 = (uint64_t)p;
  p = (fiat_p271_uint128)t8 + (p >> 64);           t8 = (uint64_t)p;
  p = (fiat_p271_uint128)t9 + (p >> 64);           t9 = (uint64_t)p;
  t10 += (uint64_t)(p >> 64);

  p = (fiat_p271_uint128)t4 * P2 + t6 + t4;        t6 = (uint64_t)p;
  p = (fiat_p271_uint128)t4 * P3 + t7 + (p >> 64); t7 = (uint64_t)p;
  p = (fiat_p271_uint128)t4 * P4 + t8 + (p >> 64); t8 = (uint64_t)p;
  p = (fiat_p271_uint128)t9 + (p >> 64);           t9 = (uint64_t)p;
  t10 += (uint64_t)(p >> 64);

  fiat_p271_uint128 d;
  d = (fiat_p271_uint128)t5 - P0;
  const uint64_t sub0 = (uint64_t)d;

  d = (fiat_p271_uint128)t6 - P1 - ((d >> 64) & 1);
  const uint64_t sub1 = (uint64_t)d;

  d = (fiat_p271_uint128)t7 - P2 - ((d >> 64) & 1);
  const uint64_t sub2 = (uint64_t)d;

  d = (fiat_p271_uint128)t8 - P3 - ((d >> 64) & 1);
  const uint64_t sub3 = (uint64_t)d;

  d = (fiat_p271_uint128)t9 - P4 - ((d >> 64) & 1);
  const uint64_t sub4 = (uint64_t)d;

  d = (fiat_p271_uint128)t10 - ((d >> 64) & 1);
  const uint64_t mask = 0ULL - ((uint64_t)(d >> 64) & 1);

  out1[0] = (t5 & mask) | (sub0 & ~mask);
  out1[1] = (t6 & mask) | (sub1 & ~mask);
  out1[2] = (t7 & mask) | (sub2 & ~mask);
  out1[3] = (t8 & mask) | (sub3 & ~mask);
  out1[4] = (t9 & mask) | (sub4 & ~mask);
}
#endif

void fiat_p271_mul(fiat_p271_montgomery_domain_field_element out1,
                   const fiat_p271_montgomery_domain_field_element arg1,
                   const fiat_p271_montgomery_domain_field_element arg2)
{

#if SQISIGN_HAS_UINT128
  fiat_p271_mul_uint128(out1, arg1, arg2);
#else
  static const uint64_t modulus[5] = {
      UINT64_C(0xffffffffffffffff),
      UINT64_C(0xffffffffffffffff),
      UINT64_C(0x4c9e5305185121ff),
      UINT64_C(0x3d19960596fb1e8c),
      UINT64_C(0x000000000000465e),
  };
  sqisign_montgomery_mul_portable(out1, arg1, arg2, modulus, 5);
#endif
}

/*
 * The function fiat_p271_square squares a field element in the Montgomery domain.
 *
 * Preconditions:
 *   0 ≤ eval arg1 < m
 * Postconditions:
 *   eval (from_montgomery out1) mod m = (eval (from_montgomery arg1) * eval (from_montgomery arg1)) mod m
 *   0 ≤ eval out1 < m
 *
 */
void fiat_p271_square(fiat_p271_montgomery_domain_field_element out1, const fiat_p271_montgomery_domain_field_element arg1)
{
  fiat_p271_mul(out1, arg1, arg1);
}

/*
 * The function fiat_p271_add adds two field elements in the Montgomery domain.
 *
 * Preconditions:
 *   0 ≤ eval arg1 < m
 *   0 ≤ eval arg2 < m
 * Postconditions:
 *   eval (from_montgomery out1) mod m = (eval (from_montgomery arg1) + eval (from_montgomery arg2)) mod m
 *   0 ≤ eval out1 < m
 *
 */
void fiat_p271_add(fiat_p271_montgomery_domain_field_element out1, const fiat_p271_montgomery_domain_field_element arg1, const fiat_p271_montgomery_domain_field_element arg2)
{
  uint64_t x1;
  fiat_p271_uint1 x2;
  uint64_t x3;
  fiat_p271_uint1 x4;
  uint64_t x5;
  fiat_p271_uint1 x6;
  uint64_t x7;
  fiat_p271_uint1 x8;
  uint64_t x9;
  fiat_p271_uint1 x10;
  uint64_t x11;
  fiat_p271_uint1 x12;
  uint64_t x13;
  fiat_p271_uint1 x14;
  uint64_t x15;
  fiat_p271_uint1 x16;
  uint64_t x17;
  fiat_p271_uint1 x18;
  uint64_t x19;
  fiat_p271_uint1 x20;
  uint64_t x21;
  fiat_p271_uint1 x22;
  uint64_t x23;
  uint64_t x24;
  uint64_t x25;
  uint64_t x26;
  uint64_t x27;
  fiat_p271_addcarryx_u64(&x1, &x2, 0x0, (arg1[0]), (arg2[0]));
  fiat_p271_addcarryx_u64(&x3, &x4, x2, (arg1[1]), (arg2[1]));
  fiat_p271_addcarryx_u64(&x5, &x6, x4, (arg1[2]), (arg2[2]));
  fiat_p271_addcarryx_u64(&x7, &x8, x6, (arg1[3]), (arg2[3]));
  fiat_p271_addcarryx_u64(&x9, &x10, x8, (arg1[4]), (arg2[4]));
  fiat_p271_subborrowx_u64(&x11, &x12, 0x0, x1, UINT64_C(0xffffffffffffffff));
  fiat_p271_subborrowx_u64(&x13, &x14, x12, x3, UINT64_C(0xffffffffffffffff));
  fiat_p271_subborrowx_u64(&x15, &x16, x14, x5, UINT64_C(0x4c9e5305185121ff));
  fiat_p271_subborrowx_u64(&x17, &x18, x16, x7, UINT64_C(0x3d19960596fb1e8c));
  fiat_p271_subborrowx_u64(&x19, &x20, x18, x9, UINT16_C(0x465e));
  fiat_p271_subborrowx_u64(&x21, &x22, x20, x10, 0x0);
  fiat_p271_cmovznz_u64(&x23, x22, x11, x1);
  fiat_p271_cmovznz_u64(&x24, x22, x13, x3);
  fiat_p271_cmovznz_u64(&x25, x22, x15, x5);
  fiat_p271_cmovznz_u64(&x26, x22, x17, x7);
  fiat_p271_cmovznz_u64(&x27, x22, x19, x9);
  out1[0] = x23;
  out1[1] = x24;
  out1[2] = x25;
  out1[3] = x26;
  out1[4] = x27;
}

/*
 * The function fiat_p271_sub subtracts two field elements in the Montgomery domain.
 *
 * Preconditions:
 *   0 ≤ eval arg1 < m
 *   0 ≤ eval arg2 < m
 * Postconditions:
 *   eval (from_montgomery out1) mod m = (eval (from_montgomery arg1) - eval (from_montgomery arg2)) mod m
 *   0 ≤ eval out1 < m
 *
 */
void fiat_p271_sub(fiat_p271_montgomery_domain_field_element out1, const fiat_p271_montgomery_domain_field_element arg1, const fiat_p271_montgomery_domain_field_element arg2)
{
  uint64_t x1;
  fiat_p271_uint1 x2;
  uint64_t x3;
  fiat_p271_uint1 x4;
  uint64_t x5;
  fiat_p271_uint1 x6;
  uint64_t x7;
  fiat_p271_uint1 x8;
  uint64_t x9;
  fiat_p271_uint1 x10;
  uint64_t x11;
  uint64_t x12;
  fiat_p271_uint1 x13;
  uint64_t x14;
  fiat_p271_uint1 x15;
  uint64_t x16;
  fiat_p271_uint1 x17;
  uint64_t x18;
  fiat_p271_uint1 x19;
  uint64_t x20;
  fiat_p271_uint1 x21;
  fiat_p271_subborrowx_u64(&x1, &x2, 0x0, (arg1[0]), (arg2[0]));
  fiat_p271_subborrowx_u64(&x3, &x4, x2, (arg1[1]), (arg2[1]));
  fiat_p271_subborrowx_u64(&x5, &x6, x4, (arg1[2]), (arg2[2]));
  fiat_p271_subborrowx_u64(&x7, &x8, x6, (arg1[3]), (arg2[3]));
  fiat_p271_subborrowx_u64(&x9, &x10, x8, (arg1[4]), (arg2[4]));
  fiat_p271_cmovznz_u64(&x11, x10, 0x0, UINT64_C(0xffffffffffffffff));
  fiat_p271_addcarryx_u64(&x12, &x13, 0x0, x1, x11);
  fiat_p271_addcarryx_u64(&x14, &x15, x13, x3, x11);
  fiat_p271_addcarryx_u64(&x16, &x17, x15, x5, (x11 & UINT64_C(0x4c9e5305185121ff)));
  fiat_p271_addcarryx_u64(&x18, &x19, x17, x7, (x11 & UINT64_C(0x3d19960596fb1e8c)));
  fiat_p271_addcarryx_u64(&x20, &x21, x19, x9, (x11 & UINT16_C(0x465e)));
  out1[0] = x12;
  out1[1] = x14;
  out1[2] = x16;
  out1[3] = x18;
  out1[4] = x20;
}

/*
 * The function fiat_p271_opp negates a field element in the Montgomery domain.
 *
 * Preconditions:
 *   0 ≤ eval arg1 < m
 * Postconditions:
 *   eval (from_montgomery out1) mod m = -eval (from_montgomery arg1) mod m
 *   0 ≤ eval out1 < m
 *
 */
void fiat_p271_opp(fiat_p271_montgomery_domain_field_element out1, const fiat_p271_montgomery_domain_field_element arg1)
{
  uint64_t x1;
  fiat_p271_uint1 x2;
  uint64_t x3;
  fiat_p271_uint1 x4;
  uint64_t x5;
  fiat_p271_uint1 x6;
  uint64_t x7;
  fiat_p271_uint1 x8;
  uint64_t x9;
  fiat_p271_uint1 x10;
  uint64_t x11;
  uint64_t x12;
  fiat_p271_uint1 x13;
  uint64_t x14;
  fiat_p271_uint1 x15;
  uint64_t x16;
  fiat_p271_uint1 x17;
  uint64_t x18;
  fiat_p271_uint1 x19;
  uint64_t x20;
  fiat_p271_uint1 x21;
  fiat_p271_subborrowx_u64(&x1, &x2, 0x0, 0x0, (arg1[0]));
  fiat_p271_subborrowx_u64(&x3, &x4, x2, 0x0, (arg1[1]));
  fiat_p271_subborrowx_u64(&x5, &x6, x4, 0x0, (arg1[2]));
  fiat_p271_subborrowx_u64(&x7, &x8, x6, 0x0, (arg1[3]));
  fiat_p271_subborrowx_u64(&x9, &x10, x8, 0x0, (arg1[4]));
  fiat_p271_cmovznz_u64(&x11, x10, 0x0, UINT64_C(0xffffffffffffffff));
  fiat_p271_addcarryx_u64(&x12, &x13, 0x0, x1, x11);
  fiat_p271_addcarryx_u64(&x14, &x15, x13, x3, x11);
  fiat_p271_addcarryx_u64(&x16, &x17, x15, x5, (x11 & UINT64_C(0x4c9e5305185121ff)));
  fiat_p271_addcarryx_u64(&x18, &x19, x17, x7, (x11 & UINT64_C(0x3d19960596fb1e8c)));
  fiat_p271_addcarryx_u64(&x20, &x21, x19, x9, (x11 & UINT16_C(0x465e)));
  out1[0] = x12;
  out1[1] = x14;
  out1[2] = x16;
  out1[3] = x18;
  out1[4] = x20;
}

/*
 * The function fiat_p271_to_montgomery translates a field element into the Montgomery domain.
 *
 * Preconditions:
 *   0 ≤ eval arg1 < m
 * Postconditions:
 *   eval (from_montgomery out1) mod m = eval arg1 mod m
 *   0 ≤ eval out1 < m
 *
 */
void fiat_p271_to_montgomery(fiat_p271_montgomery_domain_field_element out1, const fiat_p271_non_montgomery_domain_field_element arg1)
{
  uint64_t x1;
  uint64_t x2;
  uint64_t x3;
  uint64_t x4;
  uint64_t x5;
  uint64_t x6;
  uint64_t x7;
  uint64_t x8;
  uint64_t x9;
  uint64_t x10;
  uint64_t x11;
  uint64_t x12;
  uint64_t x13;
  uint64_t x14;
  uint64_t x15;
  uint64_t x16;
  fiat_p271_uint1 x17;
  uint64_t x18;
  fiat_p271_uint1 x19;
  uint64_t x20;
  fiat_p271_uint1 x21;
  uint64_t x22;
  fiat_p271_uint1 x23;
  uint64_t x24;
  uint64_t x25;
  uint64_t x26;
  uint64_t x27;
  uint64_t x28;
  uint64_t x29;
  uint64_t x30;
  uint64_t x31;
  uint64_t x32;
  uint64_t x33;
  uint64_t x34;
  fiat_p271_uint1 x35;
  uint64_t x36;
  fiat_p271_uint1 x37;
  uint64_t x38;
  fiat_p271_uint1 x39;
  uint64_t x40;
  fiat_p271_uint1 x41;
  uint64_t x42;
  fiat_p271_uint1 x43;
  uint64_t x44;
  fiat_p271_uint1 x45;
  uint64_t x46;
  fiat_p271_uint1 x47;
  uint64_t x48;
  fiat_p271_uint1 x49;
  uint64_t x50;
  fiat_p271_uint1 x51;
  uint64_t x52;
  uint64_t x53;
  uint64_t x54;
  uint64_t x55;
  uint64_t x56;
  uint64_t x57;
  uint64_t x58;
  uint64_t x59;
  uint64_t x60;
  uint64_t x61;
  uint64_t x62;
  fiat_p271_uint1 x63;
  uint64_t x64;
  fiat_p271_uint1 x65;
  uint64_t x66;
  fiat_p271_uint1 x67;
  uint64_t x68;
  fiat_p271_uint1 x69;
  uint64_t x70;
  fiat_p271_uint1 x71;
  uint64_t x72;
  fiat_p271_uint1 x73;
  uint64_t x74;
  fiat_p271_uint1 x75;
  uint64_t x76;
  fiat_p271_uint1 x77;
  uint64_t x78;
  fiat_p271_uint1 x79;
  uint64_t x80;
  uint64_t x81;
  uint64_t x82;
  uint64_t x83;
  uint64_t x84;
  uint64_t x85;
  uint64_t x86;
  uint64_t x87;
  uint64_t x88;
  uint64_t x89;
  uint64_t x90;
  fiat_p271_uint1 x91;
  uint64_t x92;
  fiat_p271_uint1 x93;
  uint64_t x94;
  fiat_p271_uint1 x95;
  uint64_t x96;
  fiat_p271_uint1 x97;
  uint64_t x98;
  fiat_p271_uint1 x99;
  uint64_t x100;
  fiat_p271_uint1 x101;
  uint64_t x102;
  fiat_p271_uint1 x103;
  uint64_t x104;
  fiat_p271_uint1 x105;
  uint64_t x106;
  fiat_p271_uint1 x107;
  uint64_t x108;
  uint64_t x109;
  uint64_t x110;
  uint64_t x111;
  uint64_t x112;
  uint64_t x113;
  uint64_t x114;
  uint64_t x115;
  uint64_t x116;
  uint64_t x117;
  uint64_t x118;
  fiat_p271_uint1 x119;
  uint64_t x120;
  fiat_p271_uint1 x121;
  uint64_t x122;
  fiat_p271_uint1 x123;
  uint64_t x124;
  fiat_p271_uint1 x125;
  uint64_t x126;
  fiat_p271_uint1 x127;
  uint64_t x128;
  fiat_p271_uint1 x129;
  uint64_t x130;
  fiat_p271_uint1 x131;
  uint64_t x132;
  fiat_p271_uint1 x133;
  uint64_t x134;
  fiat_p271_uint1 x135;
  uint64_t x136;
  uint64_t x137;
  uint64_t x138;
  uint64_t x139;
  uint64_t x140;
  uint64_t x141;
  uint64_t x142;
  uint64_t x143;
  uint64_t x144;
  uint64_t x145;
  uint64_t x146;
  fiat_p271_uint1 x147;
  uint64_t x148;
  fiat_p271_uint1 x149;
  uint64_t x150;
  fiat_p271_uint1 x151;
  uint64_t x152;
  fiat_p271_uint1 x153;
  uint64_t x154;
  fiat_p271_uint1 x155;
  uint64_t x156;
  fiat_p271_uint1 x157;
  uint64_t x158;
  fiat_p271_uint1 x159;
  uint64_t x160;
  fiat_p271_uint1 x161;
  uint64_t x162;
  fiat_p271_uint1 x163;
  uint64_t x164;
  uint64_t x165;
  uint64_t x166;
  uint64_t x167;
  uint64_t x168;
  uint64_t x169;
  uint64_t x170;
  uint64_t x171;
  uint64_t x172;
  uint64_t x173;
  uint64_t x174;
  fiat_p271_uint1 x175;
  uint64_t x176;
  fiat_p271_uint1 x177;
  uint64_t x178;
  fiat_p271_uint1 x179;
  uint64_t x180;
  fiat_p271_uint1 x181;
  uint64_t x182;
  fiat_p271_uint1 x183;
  uint64_t x184;
  fiat_p271_uint1 x185;
  uint64_t x186;
  fiat_p271_uint1 x187;
  uint64_t x188;
  fiat_p271_uint1 x189;
  uint64_t x190;
  fiat_p271_uint1 x191;
  uint64_t x192;
  uint64_t x193;
  uint64_t x194;
  uint64_t x195;
  uint64_t x196;
  uint64_t x197;
  uint64_t x198;
  uint64_t x199;
  uint64_t x200;
  uint64_t x201;
  uint64_t x202;
  fiat_p271_uint1 x203;
  uint64_t x204;
  fiat_p271_uint1 x205;
  uint64_t x206;
  fiat_p271_uint1 x207;
  uint64_t x208;
  fiat_p271_uint1 x209;
  uint64_t x210;
  fiat_p271_uint1 x211;
  uint64_t x212;
  fiat_p271_uint1 x213;
  uint64_t x214;
  fiat_p271_uint1 x215;
  uint64_t x216;
  fiat_p271_uint1 x217;
  uint64_t x218;
  fiat_p271_uint1 x219;
  uint64_t x220;
  uint64_t x221;
  uint64_t x222;
  uint64_t x223;
  uint64_t x224;
  uint64_t x225;
  uint64_t x226;
  uint64_t x227;
  uint64_t x228;
  uint64_t x229;
  uint64_t x230;
  fiat_p271_uint1 x231;
  uint64_t x232;
  fiat_p271_uint1 x233;
  uint64_t x234;
  fiat_p271_uint1 x235;
  uint64_t x236;
  fiat_p271_uint1 x237;
  uint64_t x238;
  fiat_p271_uint1 x239;
  uint64_t x240;
  fiat_p271_uint1 x241;
  uint64_t x242;
  fiat_p271_uint1 x243;
  uint64_t x244;
  fiat_p271_uint1 x245;
  uint64_t x246;
  fiat_p271_uint1 x247;
  uint64_t x248;
  uint64_t x249;
  uint64_t x250;
  uint64_t x251;
  uint64_t x252;
  uint64_t x253;
  uint64_t x254;
  uint64_t x255;
  uint64_t x256;
  uint64_t x257;
  uint64_t x258;
  fiat_p271_uint1 x259;
  uint64_t x260;
  fiat_p271_uint1 x261;
  uint64_t x262;
  fiat_p271_uint1 x263;
  uint64_t x264;
  fiat_p271_uint1 x265;
  uint64_t x266;
  fiat_p271_uint1 x267;
  uint64_t x268;
  fiat_p271_uint1 x269;
  uint64_t x270;
  fiat_p271_uint1 x271;
  uint64_t x272;
  fiat_p271_uint1 x273;
  uint64_t x274;
  fiat_p271_uint1 x275;
  uint64_t x276;
  uint64_t x277;
  fiat_p271_uint1 x278;
  uint64_t x279;
  fiat_p271_uint1 x280;
  uint64_t x281;
  fiat_p271_uint1 x282;
  uint64_t x283;
  fiat_p271_uint1 x284;
  uint64_t x285;
  fiat_p271_uint1 x286;
  uint64_t x287;
  fiat_p271_uint1 x288;
  uint64_t x289;
  uint64_t x290;
  uint64_t x291;
  uint64_t x292;
  uint64_t x293;
  x1 = (arg1[1]);
  x2 = (arg1[2]);
  x3 = (arg1[3]);
  x4 = (arg1[4]);
  x5 = (arg1[0]);
  fiat_p271_mulx_u64(&x6, &x7, x5, UINT16_C(0x1115));
  fiat_p271_mulx_u64(&x8, &x9, x5, UINT64_C(0x92b3d5860ca34e8d));
  fiat_p271_mulx_u64(&x10, &x11, x5, UINT64_C(0x88d71104d1e02cad));
  fiat_p271_mulx_u64(&x12, &x13, x5, UINT64_C(0xaf0e71bd77a8cf87));
  fiat_p271_mulx_u64(&x14, &x15, x5, UINT64_C(0xaaa9bf0b53ee45a1));
  fiat_p271_addcarryx_u64(&x16, &x17, 0x0, x15, x12);
  fiat_p271_addcarryx_u64(&x18, &x19, x17, x13, x10);
  fiat_p271_addcarryx_u64(&x20, &x21, x19, x11, x8);
  fiat_p271_addcarryx_u64(&x22, &x23, x21, x9, x6);
  fiat_p271_mulx_u64(&x24, &x25, x14, UINT16_C(0x465e));
  fiat_p271_mulx_u64(&x26, &x27, x14, UINT64_C(0x3d19960596fb1e8c));
  fiat_p271_mulx_u64(&x28, &x29, x14, UINT64_C(0x4c9e5305185121ff));
  fiat_p271_mulx_u64(&x30, &x31, x14, UINT64_C(0xffffffffffffffff));
  fiat_p271_mulx_u64(&x32, &x33, x14, UINT64_C(0xffffffffffffffff));
  fiat_p271_addcarryx_u64(&x34, &x35, 0x0, x33, x30);
  fiat_p271_addcarryx_u64(&x36, &x37, x35, x31, x28);
  fiat_p271_addcarryx_u64(&x38, &x39, x37, x29, x26);
  fiat_p271_addcarryx_u64(&x40, &x41, x39, x27, x24);
  fiat_p271_addcarryx_u64(&x42, &x43, 0x0, x14, x32);
  fiat_p271_addcarryx_u64(&x44, &x45, x43, x16, x34);
  fiat_p271_addcarryx_u64(&x46, &x47, x45, x18, x36);
  fiat_p271_addcarryx_u64(&x48, &x49, x47, x20, x38);
  fiat_p271_addcarryx_u64(&x50, &x51, x49, x22, x40);
  fiat_p271_mulx_u64(&x52, &x53, x1, UINT16_C(0x1115));
  fiat_p271_mulx_u64(&x54, &x55, x1, UINT64_C(0x92b3d5860ca34e8d));
  fiat_p271_mulx_u64(&x56, &x57, x1, UINT64_C(0x88d71104d1e02cad));
  fiat_p271_mulx_u64(&x58, &x59, x1, UINT64_C(0xaf0e71bd77a8cf87));
  fiat_p271_mulx_u64(&x60, &x61, x1, UINT64_C(0xaaa9bf0b53ee45a1));
  fiat_p271_addcarryx_u64(&x62, &x63, 0x0, x61, x58);
  fiat_p271_addcarryx_u64(&x64, &x65, x63, x59, x56);
  fiat_p271_addcarryx_u64(&x66, &x67, x65, x57, x54);
  fiat_p271_addcarryx_u64(&x68, &x69, x67, x55, x52);
  fiat_p271_addcarryx_u64(&x70, &x71, 0x0, x44, x60);
  fiat_p271_addcarryx_u64(&x72, &x73, x71, x46, x62);
  fiat_p271_addcarryx_u64(&x74, &x75, x73, x48, x64);
  fiat_p271_addcarryx_u64(&x76, &x77, x75, x50, x66);
  fiat_p271_addcarryx_u64(&x78, &x79, x77, ((x51 + (x23 + x7)) + (x41 + x25)), x68);
  fiat_p271_mulx_u64(&x80, &x81, x70, UINT16_C(0x465e));
  fiat_p271_mulx_u64(&x82, &x83, x70, UINT64_C(0x3d19960596fb1e8c));
  fiat_p271_mulx_u64(&x84, &x85, x70, UINT64_C(0x4c9e5305185121ff));
  fiat_p271_mulx_u64(&x86, &x87, x70, UINT64_C(0xffffffffffffffff));
  fiat_p271_mulx_u64(&x88, &x89, x70, UINT64_C(0xffffffffffffffff));
  fiat_p271_addcarryx_u64(&x90, &x91, 0x0, x89, x86);
  fiat_p271_addcarryx_u64(&x92, &x93, x91, x87, x84);
  fiat_p271_addcarryx_u64(&x94, &x95, x93, x85, x82);
  fiat_p271_addcarryx_u64(&x96, &x97, x95, x83, x80);
  fiat_p271_addcarryx_u64(&x98, &x99, 0x0, x70, x88);
  fiat_p271_addcarryx_u64(&x100, &x101, x99, x72, x90);
  fiat_p271_addcarryx_u64(&x102, &x103, x101, x74, x92);
  fiat_p271_addcarryx_u64(&x104, &x105, x103, x76, x94);
  fiat_p271_addcarryx_u64(&x106, &x107, x105, x78, x96);
  fiat_p271_mulx_u64(&x108, &x109, x2, UINT16_C(0x1115));
  fiat_p271_mulx_u64(&x110, &x111, x2, UINT64_C(0x92b3d5860ca34e8d));
  fiat_p271_mulx_u64(&x112, &x113, x2, UINT64_C(0x88d71104d1e02cad));
  fiat_p271_mulx_u64(&x114, &x115, x2, UINT64_C(0xaf0e71bd77a8cf87));
  fiat_p271_mulx_u64(&x116, &x117, x2, UINT64_C(0xaaa9bf0b53ee45a1));
  fiat_p271_addcarryx_u64(&x118, &x119, 0x0, x117, x114);
  fiat_p271_addcarryx_u64(&x120, &x121, x119, x115, x112);
  fiat_p271_addcarryx_u64(&x122, &x123, x121, x113, x110);
  fiat_p271_addcarryx_u64(&x124, &x125, x123, x111, x108);
  fiat_p271_addcarryx_u64(&x126, &x127, 0x0, x100, x116);
  fiat_p271_addcarryx_u64(&x128, &x129, x127, x102, x118);
  fiat_p271_addcarryx_u64(&x130, &x131, x129, x104, x120);
  fiat_p271_addcarryx_u64(&x132, &x133, x131, x106, x122);
  fiat_p271_addcarryx_u64(&x134, &x135, x133, ((x107 + (x79 + (x69 + x53))) + (x97 + x81)), x124);
  fiat_p271_mulx_u64(&x136, &x137, x126, UINT16_C(0x465e));
  fiat_p271_mulx_u64(&x138, &x139, x126, UINT64_C(0x3d19960596fb1e8c));
  fiat_p271_mulx_u64(&x140, &x141, x126, UINT64_C(0x4c9e5305185121ff));
  fiat_p271_mulx_u64(&x142, &x143, x126, UINT64_C(0xffffffffffffffff));
  fiat_p271_mulx_u64(&x144, &x145, x126, UINT64_C(0xffffffffffffffff));
  fiat_p271_addcarryx_u64(&x146, &x147, 0x0, x145, x142);
  fiat_p271_addcarryx_u64(&x148, &x149, x147, x143, x140);
  fiat_p271_addcarryx_u64(&x150, &x151, x149, x141, x138);
  fiat_p271_addcarryx_u64(&x152, &x153, x151, x139, x136);
  fiat_p271_addcarryx_u64(&x154, &x155, 0x0, x126, x144);
  fiat_p271_addcarryx_u64(&x156, &x157, x155, x128, x146);
  fiat_p271_addcarryx_u64(&x158, &x159, x157, x130, x148);
  fiat_p271_addcarryx_u64(&x160, &x161, x159, x132, x150);
  fiat_p271_addcarryx_u64(&x162, &x163, x161, x134, x152);
  fiat_p271_mulx_u64(&x164, &x165, x3, UINT16_C(0x1115));
  fiat_p271_mulx_u64(&x166, &x167, x3, UINT64_C(0x92b3d5860ca34e8d));
  fiat_p271_mulx_u64(&x168, &x169, x3, UINT64_C(0x88d71104d1e02cad));
  fiat_p271_mulx_u64(&x170, &x171, x3, UINT64_C(0xaf0e71bd77a8cf87));
  fiat_p271_mulx_u64(&x172, &x173, x3, UINT64_C(0xaaa9bf0b53ee45a1));
  fiat_p271_addcarryx_u64(&x174, &x175, 0x0, x173, x170);
  fiat_p271_addcarryx_u64(&x176, &x177, x175, x171, x168);
  fiat_p271_addcarryx_u64(&x178, &x179, x177, x169, x166);
  fiat_p271_addcarryx_u64(&x180, &x181, x179, x167, x164);
  fiat_p271_addcarryx_u64(&x182, &x183, 0x0, x156, x172);
  fiat_p271_addcarryx_u64(&x184, &x185, x183, x158, x174);
  fiat_p271_addcarryx_u64(&x186, &x187, x185, x160, x176);
  fiat_p271_addcarryx_u64(&x188, &x189, x187, x162, x178);
  fiat_p271_addcarryx_u64(&x190, &x191, x189, ((x163 + (x135 + (x125 + x109))) + (x153 + x137)), x180);
  fiat_p271_mulx_u64(&x192, &x193, x182, UINT16_C(0x465e));
  fiat_p271_mulx_u64(&x194, &x195, x182, UINT64_C(0x3d19960596fb1e8c));
  fiat_p271_mulx_u64(&x196, &x197, x182, UINT64_C(0x4c9e5305185121ff));
  fiat_p271_mulx_u64(&x198, &x199, x182, UINT64_C(0xffffffffffffffff));
  fiat_p271_mulx_u64(&x200, &x201, x182, UINT64_C(0xffffffffffffffff));
  fiat_p271_addcarryx_u64(&x202, &x203, 0x0, x201, x198);
  fiat_p271_addcarryx_u64(&x204, &x205, x203, x199, x196);
  fiat_p271_addcarryx_u64(&x206, &x207, x205, x197, x194);
  fiat_p271_addcarryx_u64(&x208, &x209, x207, x195, x192);
  fiat_p271_addcarryx_u64(&x210, &x211, 0x0, x182, x200);
  fiat_p271_addcarryx_u64(&x212, &x213, x211, x184, x202);
  fiat_p271_addcarryx_u64(&x214, &x215, x213, x186, x204);
  fiat_p271_addcarryx_u64(&x216, &x217, x215, x188, x206);
  fiat_p271_addcarryx_u64(&x218, &x219, x217, x190, x208);
  fiat_p271_mulx_u64(&x220, &x221, x4, UINT16_C(0x1115));
  fiat_p271_mulx_u64(&x222, &x223, x4, UINT64_C(0x92b3d5860ca34e8d));
  fiat_p271_mulx_u64(&x224, &x225, x4, UINT64_C(0x88d71104d1e02cad));
  fiat_p271_mulx_u64(&x226, &x227, x4, UINT64_C(0xaf0e71bd77a8cf87));
  fiat_p271_mulx_u64(&x228, &x229, x4, UINT64_C(0xaaa9bf0b53ee45a1));
  fiat_p271_addcarryx_u64(&x230, &x231, 0x0, x229, x226);
  fiat_p271_addcarryx_u64(&x232, &x233, x231, x227, x224);
  fiat_p271_addcarryx_u64(&x234, &x235, x233, x225, x222);
  fiat_p271_addcarryx_u64(&x236, &x237, x235, x223, x220);
  fiat_p271_addcarryx_u64(&x238, &x239, 0x0, x212, x228);
  fiat_p271_addcarryx_u64(&x240, &x241, x239, x214, x230);
  fiat_p271_addcarryx_u64(&x242, &x243, x241, x216, x232);
  fiat_p271_addcarryx_u64(&x244, &x245, x243, x218, x234);
  fiat_p271_addcarryx_u64(&x246, &x247, x245, ((x219 + (x191 + (x181 + x165))) + (x209 + x193)), x236);
  fiat_p271_mulx_u64(&x248, &x249, x238, UINT16_C(0x465e));
  fiat_p271_mulx_u64(&x250, &x251, x238, UINT64_C(0x3d19960596fb1e8c));
  fiat_p271_mulx_u64(&x252, &x253, x238, UINT64_C(0x4c9e5305185121ff));
  fiat_p271_mulx_u64(&x254, &x255, x238, UINT64_C(0xffffffffffffffff));
  fiat_p271_mulx_u64(&x256, &x257, x238, UINT64_C(0xffffffffffffffff));
  fiat_p271_addcarryx_u64(&x258, &x259, 0x0, x257, x254);
  fiat_p271_addcarryx_u64(&x260, &x261, x259, x255, x252);
  fiat_p271_addcarryx_u64(&x262, &x263, x261, x253, x250);
  fiat_p271_addcarryx_u64(&x264, &x265, x263, x251, x248);
  fiat_p271_addcarryx_u64(&x266, &x267, 0x0, x238, x256);
  fiat_p271_addcarryx_u64(&x268, &x269, x267, x240, x258);
  fiat_p271_addcarryx_u64(&x270, &x271, x269, x242, x260);
  fiat_p271_addcarryx_u64(&x272, &x273, x271, x244, x262);
  fiat_p271_addcarryx_u64(&x274, &x275, x273, x246, x264);
  x276 = ((x275 + (x247 + (x237 + x221))) + (x265 + x249));
  fiat_p271_subborrowx_u64(&x277, &x278, 0x0, x268, UINT64_C(0xffffffffffffffff));
  fiat_p271_subborrowx_u64(&x279, &x280, x278, x270, UINT64_C(0xffffffffffffffff));
  fiat_p271_subborrowx_u64(&x281, &x282, x280, x272, UINT64_C(0x4c9e5305185121ff));
  fiat_p271_subborrowx_u64(&x283, &x284, x282, x274, UINT64_C(0x3d19960596fb1e8c));
  fiat_p271_subborrowx_u64(&x285, &x286, x284, x276, UINT16_C(0x465e));
  fiat_p271_subborrowx_u64(&x287, &x288, x286, 0x0, 0x0);
  fiat_p271_cmovznz_u64(&x289, x288, x277, x268);
  fiat_p271_cmovznz_u64(&x290, x288, x279, x270);
  fiat_p271_cmovznz_u64(&x291, x288, x281, x272);
  fiat_p271_cmovznz_u64(&x292, x288, x283, x274);
  fiat_p271_cmovznz_u64(&x293, x288, x285, x276);
  out1[0] = x289;
  out1[1] = x290;
  out1[2] = x291;
  out1[3] = x292;
  out1[4] = x293;
}

/*
 * The function fiat_p271_from_montgomery translates a field element out of the Montgomery domain.
 *
 * Preconditions:
 *   0 ≤ eval arg1 < m
 * Postconditions:
 *   eval out1 mod m = (eval arg1 * ((2^64)?1 mod m)^5) mod m
 *   0 ≤ eval out1 < m
 *
 */
void fiat_p271_from_montgomery(fiat_p271_non_montgomery_domain_field_element out1, const fiat_p271_montgomery_domain_field_element arg1)
{
  uint64_t x1;
  uint64_t x2;
  uint64_t x3;
  uint64_t x4;
  uint64_t x5;
  uint64_t x6;
  uint64_t x7;
  uint64_t x8;
  uint64_t x9;
  uint64_t x10;
  uint64_t x11;
  uint64_t x12;
  fiat_p271_uint1 x13;
  uint64_t x14;
  fiat_p271_uint1 x15;
  uint64_t x16;
  fiat_p271_uint1 x17;
  uint64_t x18;
  fiat_p271_uint1 x19;
  uint64_t x20;
  fiat_p271_uint1 x21;
  uint64_t x22;
  fiat_p271_uint1 x23;
  uint64_t x24;
  fiat_p271_uint1 x25;
  uint64_t x26;
  fiat_p271_uint1 x27;
  uint64_t x28;
  fiat_p271_uint1 x29;
  uint64_t x30;
  fiat_p271_uint1 x31;
  uint64_t x32;
  fiat_p271_uint1 x33;
  uint64_t x34;
  fiat_p271_uint1 x35;
  uint64_t x36;
  fiat_p271_uint1 x37;
  uint64_t x38;
  uint64_t x39;
  uint64_t x40;
  uint64_t x41;
  uint64_t x42;
  uint64_t x43;
  uint64_t x44;
  uint64_t x45;
  uint64_t x46;
  uint64_t x47;
  uint64_t x48;
  fiat_p271_uint1 x49;
  uint64_t x50;
  fiat_p271_uint1 x51;
  uint64_t x52;
  fiat_p271_uint1 x53;
  uint64_t x54;
  fiat_p271_uint1 x55;
  uint64_t x56;
  fiat_p271_uint1 x57;
  uint64_t x58;
  fiat_p271_uint1 x59;
  uint64_t x60;
  fiat_p271_uint1 x61;
  uint64_t x62;
  fiat_p271_uint1 x63;
  uint64_t x64;
  fiat_p271_uint1 x65;
  uint64_t x66;
  fiat_p271_uint1 x67;
  uint64_t x68;
  fiat_p271_uint1 x69;
  uint64_t x70;
  fiat_p271_uint1 x71;
  uint64_t x72;
  fiat_p271_uint1 x73;
  uint64_t x74;
  uint64_t x75;
  uint64_t x76;
  uint64_t x77;
  uint64_t x78;
  uint64_t x79;
  uint64_t x80;
  uint64_t x81;
  uint64_t x82;
  uint64_t x83;
  uint64_t x84;
  fiat_p271_uint1 x85;
  uint64_t x86;
  fiat_p271_uint1 x87;
  uint64_t x88;
  fiat_p271_uint1 x89;
  uint64_t x90;
  fiat_p271_uint1 x91;
  uint64_t x92;
  fiat_p271_uint1 x93;
  uint64_t x94;
  fiat_p271_uint1 x95;
  uint64_t x96;
  fiat_p271_uint1 x97;
  uint64_t x98;
  fiat_p271_uint1 x99;
  uint64_t x100;
  fiat_p271_uint1 x101;
  uint64_t x102;
  fiat_p271_uint1 x103;
  uint64_t x104;
  fiat_p271_uint1 x105;
  uint64_t x106;
  fiat_p271_uint1 x107;
  uint64_t x108;
  fiat_p271_uint1 x109;
  uint64_t x110;
  uint64_t x111;
  uint64_t x112;
  uint64_t x113;
  uint64_t x114;
  uint64_t x115;
  uint64_t x116;
  uint64_t x117;
  uint64_t x118;
  uint64_t x119;
  uint64_t x120;
  fiat_p271_uint1 x121;
  uint64_t x122;
  fiat_p271_uint1 x123;
  uint64_t x124;
  fiat_p271_uint1 x125;
  uint64_t x126;
  fiat_p271_uint1 x127;
  uint64_t x128;
  fiat_p271_uint1 x129;
  uint64_t x130;
  fiat_p271_uint1 x131;
  uint64_t x132;
  fiat_p271_uint1 x133;
  uint64_t x134;
  fiat_p271_uint1 x135;
  uint64_t x136;
  fiat_p271_uint1 x137;
  uint64_t x138;
  fiat_p271_uint1 x139;
  uint64_t x140;
  fiat_p271_uint1 x141;
  uint64_t x142;
  fiat_p271_uint1 x143;
  uint64_t x144;
  fiat_p271_uint1 x145;
  uint64_t x146;
  uint64_t x147;
  uint64_t x148;
  uint64_t x149;
  uint64_t x150;
  uint64_t x151;
  uint64_t x152;
  uint64_t x153;
  uint64_t x154;
  uint64_t x155;
  uint64_t x156;
  fiat_p271_uint1 x157;
  uint64_t x158;
  fiat_p271_uint1 x159;
  uint64_t x160;
  fiat_p271_uint1 x161;
  uint64_t x162;
  fiat_p271_uint1 x163;
  uint64_t x164;
  fiat_p271_uint1 x165;
  uint64_t x166;
  fiat_p271_uint1 x167;
  uint64_t x168;
  fiat_p271_uint1 x169;
  uint64_t x170;
  fiat_p271_uint1 x171;
  uint64_t x172;
  fiat_p271_uint1 x173;
  uint64_t x174;
  uint64_t x175;
  fiat_p271_uint1 x176;
  uint64_t x177;
  fiat_p271_uint1 x178;
  uint64_t x179;
  fiat_p271_uint1 x180;
  uint64_t x181;
  fiat_p271_uint1 x182;
  uint64_t x183;
  fiat_p271_uint1 x184;
  uint64_t x185;
  fiat_p271_uint1 x186;
  uint64_t x187;
  uint64_t x188;
  uint64_t x189;
  uint64_t x190;
  uint64_t x191;
  x1 = (arg1[0]);
  fiat_p271_mulx_u64(&x2, &x3, x1, UINT16_C(0x465e));
  fiat_p271_mulx_u64(&x4, &x5, x1, UINT64_C(0x3d19960596fb1e8c));
  fiat_p271_mulx_u64(&x6, &x7, x1, UINT64_C(0x4c9e5305185121ff));
  fiat_p271_mulx_u64(&x8, &x9, x1, UINT64_C(0xffffffffffffffff));
  fiat_p271_mulx_u64(&x10, &x11, x1, UINT64_C(0xffffffffffffffff));
  fiat_p271_addcarryx_u64(&x12, &x13, 0x0, x11, x8);
  fiat_p271_addcarryx_u64(&x14, &x15, x13, x9, x6);
  fiat_p271_addcarryx_u64(&x16, &x17, x15, x7, x4);
  fiat_p271_addcarryx_u64(&x18, &x19, x17, x5, x2);
  fiat_p271_addcarryx_u64(&x20, &x21, 0x0, x1, x10);
  fiat_p271_addcarryx_u64(&x22, &x23, x21, 0x0, x12);
  fiat_p271_addcarryx_u64(&x24, &x25, x23, 0x0, x14);
  fiat_p271_addcarryx_u64(&x26, &x27, x25, 0x0, x16);
  fiat_p271_addcarryx_u64(&x28, &x29, x27, 0x0, x18);
  fiat_p271_addcarryx_u64(&x30, &x31, 0x0, x22, (arg1[1]));
  fiat_p271_addcarryx_u64(&x32, &x33, x31, x24, 0x0);
  fiat_p271_addcarryx_u64(&x34, &x35, x33, x26, 0x0);
  fiat_p271_addcarryx_u64(&x36, &x37, x35, x28, 0x0);
  fiat_p271_mulx_u64(&x38, &x39, x30, UINT16_C(0x465e));
  fiat_p271_mulx_u64(&x40, &x41, x30, UINT64_C(0x3d19960596fb1e8c));
  fiat_p271_mulx_u64(&x42, &x43, x30, UINT64_C(0x4c9e5305185121ff));
  fiat_p271_mulx_u64(&x44, &x45, x30, UINT64_C(0xffffffffffffffff));
  fiat_p271_mulx_u64(&x46, &x47, x30, UINT64_C(0xffffffffffffffff));
  fiat_p271_addcarryx_u64(&x48, &x49, 0x0, x47, x44);
  fiat_p271_addcarryx_u64(&x50, &x51, x49, x45, x42);
  fiat_p271_addcarryx_u64(&x52, &x53, x51, x43, x40);
  fiat_p271_addcarryx_u64(&x54, &x55, x53, x41, x38);
  fiat_p271_addcarryx_u64(&x56, &x57, 0x0, x30, x46);
  fiat_p271_addcarryx_u64(&x58, &x59, x57, x32, x48);
  fiat_p271_addcarryx_u64(&x60, &x61, x59, x34, x50);
  fiat_p271_addcarryx_u64(&x62, &x63, x61, x36, x52);
  fiat_p271_addcarryx_u64(&x64, &x65, x63, (x37 + (x29 + (x19 + x3))), x54);
  fiat_p271_addcarryx_u64(&x66, &x67, 0x0, x58, (arg1[2]));
  fiat_p271_addcarryx_u64(&x68, &x69, x67, x60, 0x0);
  fiat_p271_addcarryx_u64(&x70, &x71, x69, x62, 0x0);
  fiat_p271_addcarryx_u64(&x72, &x73, x71, x64, 0x0);
  fiat_p271_mulx_u64(&x74, &x75, x66, UINT16_C(0x465e));
  fiat_p271_mulx_u64(&x76, &x77, x66, UINT64_C(0x3d19960596fb1e8c));
  fiat_p271_mulx_u64(&x78, &x79, x66, UINT64_C(0x4c9e5305185121ff));
  fiat_p271_mulx_u64(&x80, &x81, x66, UINT64_C(0xffffffffffffffff));
  fiat_p271_mulx_u64(&x82, &x83, x66, UINT64_C(0xffffffffffffffff));
  fiat_p271_addcarryx_u64(&x84, &x85, 0x0, x83, x80);
  fiat_p271_addcarryx_u64(&x86, &x87, x85, x81, x78);
  fiat_p271_addcarryx_u64(&x88, &x89, x87, x79, x76);
  fiat_p271_addcarryx_u64(&x90, &x91, x89, x77, x74);
  fiat_p271_addcarryx_u64(&x92, &x93, 0x0, x66, x82);
  fiat_p271_addcarryx_u64(&x94, &x95, x93, x68, x84);
  fiat_p271_addcarryx_u64(&x96, &x97, x95, x70, x86);
  fiat_p271_addcarryx_u64(&x98, &x99, x97, x72, x88);
  fiat_p271_addcarryx_u64(&x100, &x101, x99, (x73 + (x65 + (x55 + x39))), x90);
  fiat_p271_addcarryx_u64(&x102, &x103, 0x0, x94, (arg1[3]));
  fiat_p271_addcarryx_u64(&x104, &x105, x103, x96, 0x0);
  fiat_p271_addcarryx_u64(&x106, &x107, x105, x98, 0x0);
  fiat_p271_addcarryx_u64(&x108, &x109, x107, x100, 0x0);
  fiat_p271_mulx_u64(&x110, &x111, x102, UINT16_C(0x465e));
  fiat_p271_mulx_u64(&x112, &x113, x102, UINT64_C(0x3d19960596fb1e8c));
  fiat_p271_mulx_u64(&x114, &x115, x102, UINT64_C(0x4c9e5305185121ff));
  fiat_p271_mulx_u64(&x116, &x117, x102, UINT64_C(0xffffffffffffffff));
  fiat_p271_mulx_u64(&x118, &x119, x102, UINT64_C(0xffffffffffffffff));
  fiat_p271_addcarryx_u64(&x120, &x121, 0x0, x119, x116);
  fiat_p271_addcarryx_u64(&x122, &x123, x121, x117, x114);
  fiat_p271_addcarryx_u64(&x124, &x125, x123, x115, x112);
  fiat_p271_addcarryx_u64(&x126, &x127, x125, x113, x110);
  fiat_p271_addcarryx_u64(&x128, &x129, 0x0, x102, x118);
  fiat_p271_addcarryx_u64(&x130, &x131, x129, x104, x120);
  fiat_p271_addcarryx_u64(&x132, &x133, x131, x106, x122);
  fiat_p271_addcarryx_u64(&x134, &x135, x133, x108, x124);
  fiat_p271_addcarryx_u64(&x136, &x137, x135, (x109 + (x101 + (x91 + x75))), x126);
  fiat_p271_addcarryx_u64(&x138, &x139, 0x0, x130, (arg1[4]));
  fiat_p271_addcarryx_u64(&x140, &x141, x139, x132, 0x0);
  fiat_p271_addcarryx_u64(&x142, &x143, x141, x134, 0x0);
  fiat_p271_addcarryx_u64(&x144, &x145, x143, x136, 0x0);
  fiat_p271_mulx_u64(&x146, &x147, x138, UINT16_C(0x465e));
  fiat_p271_mulx_u64(&x148, &x149, x138, UINT64_C(0x3d19960596fb1e8c));
  fiat_p271_mulx_u64(&x150, &x151, x138, UINT64_C(0x4c9e5305185121ff));
  fiat_p271_mulx_u64(&x152, &x153, x138, UINT64_C(0xffffffffffffffff));
  fiat_p271_mulx_u64(&x154, &x155, x138, UINT64_C(0xffffffffffffffff));
  fiat_p271_addcarryx_u64(&x156, &x157, 0x0, x155, x152);
  fiat_p271_addcarryx_u64(&x158, &x159, x157, x153, x150);
  fiat_p271_addcarryx_u64(&x160, &x161, x159, x151, x148);
  fiat_p271_addcarryx_u64(&x162, &x163, x161, x149, x146);
  fiat_p271_addcarryx_u64(&x164, &x165, 0x0, x138, x154);
  fiat_p271_addcarryx_u64(&x166, &x167, x165, x140, x156);
  fiat_p271_addcarryx_u64(&x168, &x169, x167, x142, x158);
  fiat_p271_addcarryx_u64(&x170, &x171, x169, x144, x160);
  fiat_p271_addcarryx_u64(&x172, &x173, x171, (x145 + (x137 + (x127 + x111))), x162);
  x174 = (x173 + (x163 + x147));
  fiat_p271_subborrowx_u64(&x175, &x176, 0x0, x166, UINT64_C(0xffffffffffffffff));
  fiat_p271_subborrowx_u64(&x177, &x178, x176, x168, UINT64_C(0xffffffffffffffff));
  fiat_p271_subborrowx_u64(&x179, &x180, x178, x170, UINT64_C(0x4c9e5305185121ff));
  fiat_p271_subborrowx_u64(&x181, &x182, x180, x172, UINT64_C(0x3d19960596fb1e8c));
  fiat_p271_subborrowx_u64(&x183, &x184, x182, x174, UINT16_C(0x465e));
  fiat_p271_subborrowx_u64(&x185, &x186, x184, 0x0, 0x0);
  fiat_p271_cmovznz_u64(&x187, x186, x175, x166);
  fiat_p271_cmovznz_u64(&x188, x186, x177, x168);
  fiat_p271_cmovznz_u64(&x189, x186, x179, x170);
  fiat_p271_cmovznz_u64(&x190, x186, x181, x172);
  fiat_p271_cmovznz_u64(&x191, x186, x183, x174);
  out1[0] = x187;
  out1[1] = x188;
  out1[2] = x189;
  out1[3] = x190;
  out1[4] = x191;
}

/*
 * The function fiat_p271_set_one returns the field element one in the Montgomery domain.
 *
 * Postconditions:
 *   eval (from_montgomery out1) mod m = 1 mod m
 *   0 ≤ eval out1 < m
 *
 */
void fiat_p271_set_one(fiat_p271_montgomery_domain_field_element out1)
{
  out1[0] = UINT64_C(0x3a354b1ce708f);
  out1[1] = 0x0;
  out1[2] = UINT64_C(0x920e93b88fce0200);
  out1[3] = UINT64_C(0x4cb161f44a9eaa33);
  out1[4] = UINT32_C(0xd67);
}

/* End of autogenerated content */

/********************************************************************/
/*      Expose above functions using our API                        */
/********************************************************************/

#include <fp.h>

const uint64_t p[NWORDS_FIELD] = {0xffffffffffffffff,
                                  0xffffffffffffffff,
                                  0x4c9e5305185121ff,
                                  0x3d19960596fb1e8c,
                                  0x465e};
const uint64_t ZERO[NWORDS_FIELD] = {0, 0, 0, 0, 0};
const uint64_t ONE[NWORDS_FIELD] = {0x3a354b1ce708f,
                                    0x0,
                                    0x920e93b88fce0200,
                                    0x4cb161f44a9eaa33,
                                    0xd67};

void fp_add(fp_t *out, const fp_t *a, const fp_t *b)
{
  fiat_p271_add(*out, *a, *b);
}

void fp_sub(fp_t *out, const fp_t *a, const fp_t *b)
{
  fiat_p271_sub(*out, *a, *b);
}

void fp_sqr(fp_t *out, const fp_t *a)
{
  fiat_p271_square(*out, *a);
}

void fp_mul(fp_t *out, const fp_t *a, const fp_t *b)
{
  fiat_p271_mul(*out, *a, *b);
}

void fp_tomont(fp_t *out, const fp_t *a)
{
  fiat_p271_to_montgomery(*out, *a);
}

void fp_frommont(fp_t *out, const fp_t *a)
{
  fiat_p271_from_montgomery(*out, *a);
}

void fp_mont_setone(fp_t *out)
{
  fiat_p271_set_one(*out);
}
