#ifndef ENCODED_SIZES_H
#define ENCODED_SIZES_H

#include <config.h>

#define SECURITY_BITS 256
#define FP_ENCODED_BYTES 64
#define FP2_ENCODED_BYTES 128
#define SECRET_NORM_BOUND_BYTES 16

#if COMPRESSED
#define PUBLICKEY_BYTES (FP2_ENCODED_BYTES + 1)
#define SECRETKEY_BYTES (PUBLICKEY_BYTES + 5*SECRET_NORM_BOUND_BYTES + 4*NWORDS_ORDER_2_BYTES + 4*NWORDS_ORDER_3_BYTES + 3)
#define SIGNATURE_BYTES (FP2_ENCODED_BYTES + 2*NWORDS_ORDER_3_BYTES + 4*NWORDS_ORDER_2_BYTES + 4)
#else
#define PUBLICKEY_BYTES FP2_ENCODED_BYTES
#define SIGNATURE_BYTES (2*FP2_ENCODED_BYTES + 4*NWORDS_ORDER_2_BYTES + 4)
#define SECRETKEY_BYTES (PUBLICKEY_BYTES + 5*SECRET_NORM_BOUND_BYTES + 6*FP2_ENCODED_BYTES)
#endif

#endif