#ifndef CONSTS_H
#define CONSTS_H
#include "params.h"
/* Assembly / C shared offsets into qdata (units of int32). Generated by gen_consts.py */
#define _8XQ            0
#define _8XQINV         8
#define _8XDIV_QINV    16
#define _8XDIV         24
#define _ZETAS_QINV    32
#define _ZETAS        608
#define _ZETAS_INV_QINV  1184
#define _ZETAS_INV       1760
#define _PW_ROOTS        2336
#define QDATA_SIZE 2848
#ifndef __ASSEMBLER__
typedef int32_t qdata_t[QDATA_SIZE] __attribute__((aligned(32)));
extern const qdata_t qdata;
#endif
#endif
