

# This file was *autogenerated* from the file /home/xingtingyu/code/temp/C-implementation/scripts/precomp/precompute_torsion_constants.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_128 = Integer(128); _sage_const_64 = Integer(64); _sage_const_160 = Integer(160); _sage_const_4 = Integer(4); _sage_const_7 = Integer(7); _sage_const_8 = Integer(8)#!/usr/bin/env sage
proof.all(False)  # faster

################################################################

from parameters import p, lvl

################################################################

tors2part = (p+_sage_const_1 ).p_primary_part(_sage_const_2 )
lambda_security = round(p.bit_length() / _sage_const_128 ) * _sage_const_64 
# lvl2 (lambda=160) is not a multiple of 64; the rounding formula yields 128.
# Override it so TWO_TO_SECURITY_BITS / SEC_DEGREE / COM_DEGREE match lambda=160.
if lvl == _sage_const_2 :
    lambda_security = _sage_const_160 
N_sec = next_prime(_sage_const_1  << _sage_const_4 *lambda_security)
N_com = N_sec

defs = {
        'TORSION_2POWER_BYTES': (tors2part.bit_length() + _sage_const_7 ) // _sage_const_8 ,
    }

from cformat import Ibz, Object, ObjectFormatter

objs = ObjectFormatter([
        Object('ibz_t', 'TWO_TO_SECURITY_BITS', Ibz(_sage_const_1  << lambda_security)),  # lambda_security = SECURITY_BITS (128, 192, 256)
        Object('ibz_t', 'TORSION_PLUS_2POWER', Ibz(tors2part)),
        Object('ibz_t', 'SEC_DEGREE', Ibz(N_sec)),
        Object('ibz_t', 'COM_DEGREE', Ibz(N_com)),
    ])

with open('include/torsion_constants.h','w') as hfile:
    with open('torsion_constants.c','w') as cfile:
        print(f'#include <quaternion.h>', file=hfile)
        print(f'#include <stddef.h>', file=cfile)
        print(f'#include <stdint.h>', file=cfile)
        print(f'#include <torsion_constants.h>', file=cfile)

        for k,v in defs.items():
            print(f'#define {k} {v}', file=hfile)

        objs.header(file=hfile)
        objs.implementation(file=cfile)


