/*
 * xof.c — GALAS XOF/hash over NGCC aux (v2: hash vs PRG separation).
 *
 * HASH domains (H0-H4, < 0x20): pseudohash selected by
 *   xof_pseudohash_size(lambda_bits).
 *   Outputs longer than one digest are generated by counter-separated calls.
 * PRG domains (≥ 0x20): pseudoXOF, 128-bit (adequate for PRG).
 */
#include "xof.h"
#include "../ngcc/auxfunc.h"
#include <stdlib.h>
#include <string.h>

static void ensure_cap(uint8_t** buf, size_t* cap, size_t need) {
    if (*cap >= need) return;
    size_t nc = *cap ? *cap : 256;
    while (nc < need) nc *= 2;
    uint8_t* nb = (uint8_t*)realloc(*buf, nc);
    if (!nb) abort();
    *buf = nb; *cap = nc;
}

void xof_init(xof_ctx* ctx, unsigned lambda_bits, xof_domain_t domain) {
    ctx->lambda_bits = lambda_bits;
    ctx->domain = (uint8_t)domain;
    ctx->buf = (uint8_t*)malloc(256);
    ctx->buf_len = 0;
    ctx->buf_cap = 256;
    ctx->finalized = 0;
    ctx->out = NULL; ctx->out_cap = 0; ctx->out_have = 0; ctx->out_used = 0;
}

void xof_update(xof_ctx* ctx, const void* data, size_t len) {
    if (ctx->finalized) return;
    ensure_cap(&ctx->buf, &ctx->buf_cap, ctx->buf_len + len);
    memcpy(ctx->buf + ctx->buf_len, data, len);
    ctx->buf_len += len;
}

void xof_update_u16(xof_ctx* ctx, uint16_t v) {
    uint8_t b[2] = { (uint8_t)(v & 0xff), (uint8_t)((v >> 8) & 0xff) };
    xof_update(ctx, b, 2);
}
void xof_update_u32(xof_ctx* ctx, uint32_t v) {
    uint8_t b[4] = { (uint8_t)(v), (uint8_t)(v >> 8), (uint8_t)(v >> 16), (uint8_t)(v >> 24) };
    xof_update(ctx, b, 4);
}

void xof_final(xof_ctx* ctx) { ctx->finalized = 1; }

static void generate_hash(xof_ctx* ctx, size_t need_total) {
    int ph_size = xof_pseudohash_size(ctx->lambda_bits);
    int ph_bytes = ph_size / 8;
    unsigned counter = 0;
    size_t generated = 0;
    ensure_cap(&ctx->out, &ctx->out_cap, need_total);
    while (generated < need_total) {
        size_t blen = ctx->buf_len;
        uint8_t* tmp = (uint8_t*)malloc(blen + 4);
        memcpy(tmp, ctx->buf, blen);
        tmp[blen]=(uint8_t)(counter); tmp[blen+1]=(uint8_t)(counter>>8);
        tmp[blen+2]=(uint8_t)(counter>>16); tmp[blen+3]=(uint8_t)(counter>>24);
        uint8_t block[128];
        pseudohash(ph_size, tmp, (unsigned long long)(blen + 4) * 8, block);
        free(tmp);
        size_t to_copy = need_total - generated;
        if (to_copy > (size_t)ph_bytes) to_copy = ph_bytes;
        memcpy(ctx->out + generated, block, to_copy);
        generated += to_copy;
        counter++;
    }
    ctx->out_have = need_total;
}

static void generate_prg(xof_ctx* ctx, size_t need_total) {
    ensure_cap(&ctx->out, &ctx->out_cap, need_total);
    pseudoXOF((unsigned long long)need_total * 8, ctx->buf,
              (unsigned long long)ctx->buf_len * 8, ctx->out);
    ctx->out_have = need_total;
}

void xof_squeeze(xof_ctx* ctx, void* out, size_t len) {
    if (!ctx->finalized) xof_final(ctx);
    size_t need_total = ctx->out_used + len;
    if (need_total > ctx->out_have) {
        if (XOF_IS_HASH_DOMAIN(ctx->domain))
            generate_hash(ctx, need_total);
        else
            generate_prg(ctx, need_total);
    }
    memcpy(out, ctx->out + ctx->out_used, len);
    ctx->out_used += len;
}

void xof_clear(xof_ctx* ctx) {
    free(ctx->buf); free(ctx->out);
    ctx->buf = NULL; ctx->out = NULL;
    ctx->buf_cap = ctx->buf_len = 0;
    ctx->out_cap = ctx->out_have = ctx->out_used = 0;
    ctx->finalized = 0;
}

void xof_oneshot(unsigned lambda_bits, xof_domain_t domain,
                 const void* data, size_t len, void* out, size_t out_len) {
    xof_ctx ctx;
    xof_init(&ctx, lambda_bits, domain);
    xof_update(&ctx, data, len);
    xof_final(&ctx);
    xof_squeeze(&ctx, out, out_len);
    xof_clear(&ctx);
}
