// SPDX-License-Identifier: Apache-2.0

/*
 * Generated by Modarith (https://github.com/mcarrickscott/modarith)
 */

// Automatically generated modular arithmetic C code
// Command line : python monty.py 64
// 0x53d1c0debdc0c1ba3edd760148d21a078008f642a9f26f65995c4d86fc6efff7 
// Python Script by Mike Scott (Technology Innovation Institute, UAE, 2025)

#include <stdint.h>
#include <stdio.h>

#define sspint int64_t
#define spint uint64_t
#define udpint __uint128_t
#define dpint __uint128_t

#define Wordlength 64
#define Nlimbs 5
#define Radix 52
#define Nbits 255
#define Nbytes 32

#define MONTGOMERY
// propagate carries
static spint inline prop(spint *n) {
  int i;
  spint mask = ((spint)1 << 52u) - (spint)1;
  sspint carry = (sspint)n[0];
  carry >>= 52u;
  n[0] &= mask;
  for (i = 1; i < 4; i++) {
    carry += (sspint)n[i];
    n[i] = (spint)carry & mask;
    carry >>= 52u;
  }
  n[4] += (spint)carry;
  return -((n[4] >> 1) >> 62u);
}

// propagate carries and add p if negative, propagate carries again
static int inline flatten(spint *n) {
  spint carry = prop(n);
  n[0] += ((spint)0xc4d86fc6efff7u) & carry;
  n[1] += ((spint)0x42a9f26f65995u) & carry;
  n[2] += ((spint)0x8d21a078008f6u) & carry;
  n[3] += ((spint)0xc1ba3edd76014u) & carry;
  n[4] += ((spint)0x53d1c0debdc0u) & carry;
  (void)prop(n);
  return (int)(carry & 1);
}

// Montgomery final subtract
static int inline modfsb(spint *n) {
  n[0] -= (spint)0xc4d86fc6efff7u;
  n[1] -= (spint)0x42a9f26f65995u;
  n[2] -= (spint)0x8d21a078008f6u;
  n[3] -= (spint)0xc1ba3edd76014u;
  n[4] -= (spint)0x53d1c0debdc0u;
  return flatten(n);
}

// Modular addition - reduce less than 2p
static void inline modadd(const spint *a, const spint *b, spint *n) {
  spint carry;
  n[0] = a[0] + b[0];
  n[1] = a[1] + b[1];
  n[2] = a[2] + b[2];
  n[3] = a[3] + b[3];
  n[4] = a[4] + b[4];
  n[0] -= (spint)0x189b0df8ddffeeu;
  n[1] -= (spint)0x8553e4decb32au;
  n[2] -= (spint)0x11a4340f0011ecu;
  n[3] -= (spint)0x183747dbaec028u;
  n[4] -= (spint)0xa7a381bd7b80u;
  carry = prop(n);
  n[0] += ((spint)0x189b0df8ddffeeu) & carry;
  n[1] += ((spint)0x8553e4decb32au) & carry;
  n[2] += ((spint)0x11a4340f0011ecu) & carry;
  n[3] += ((spint)0x183747dbaec028u) & carry;
  n[4] += ((spint)0xa7a381bd7b80u) & carry;
  (void)prop(n);
}

// Modular subtraction - reduce less than 2p
static void inline modsub(const spint *a, const spint *b, spint *n) {
  spint carry;
  n[0] = a[0] - b[0];
  n[1] = a[1] - b[1];
  n[2] = a[2] - b[2];
  n[3] = a[3] - b[3];
  n[4] = a[4] - b[4];
  carry = prop(n);
  n[0] += ((spint)0x189b0df8ddffeeu) & carry;
  n[1] += ((spint)0x8553e4decb32au) & carry;
  n[2] += ((spint)0x11a4340f0011ecu) & carry;
  n[3] += ((spint)0x183747dbaec028u) & carry;
  n[4] += ((spint)0xa7a381bd7b80u) & carry;
  (void)prop(n);
}

// Modular negation
static void inline modneg(const spint *b, spint *n) {
  spint carry;
  n[0] = (spint)0 - b[0];
  n[1] = (spint)0 - b[1];
  n[2] = (spint)0 - b[2];
  n[3] = (spint)0 - b[3];
  n[4] = (spint)0 - b[4];
  carry = prop(n);
  n[0] += ((spint)0x189b0df8ddffeeu) & carry;
  n[1] += ((spint)0x8553e4decb32au) & carry;
  n[2] += ((spint)0x11a4340f0011ecu) & carry;
  n[3] += ((spint)0x183747dbaec028u) & carry;
  n[4] += ((spint)0xa7a381bd7b80u) & carry;
  (void)prop(n);
}

// Overflow limit   = 340282366920938463463374607431768211456
// maximum possible = 149234713422457748504148296630191
// Modular multiplication, c=a*b mod 2p
static void inline modmul(const spint *a, const spint *b, spint *c) {
  dpint t = 0;
  spint p0 = 0xc4d86fc6efff7u;
  spint p1 = 0x42a9f26f65995u;
  spint p2 = 0x8d21a078008f6u;
  spint p3 = 0xc1ba3edd76014u;
  spint p4 = 0x53d1c0debdc0u;
  spint q = ((spint)1 << 52u); // q is unsaturated radix
  spint mask = (spint)(q - (spint)1);
  spint ndash = 0x3a641f9a28e39u;
  t += (dpint)a[0] * b[0];
  spint v0 = (((spint)t * ndash) & mask);
  t += (dpint)v0 * (dpint)p0;
  t >>= 52;
  t += (dpint)a[0] * b[1];
  t += (dpint)a[1] * b[0];
  t += (dpint)v0 * (dpint)p1;
  spint v1 = (((spint)t * ndash) & mask);
  t += (dpint)v1 * (dpint)p0;
  t >>= 52;
  t += (dpint)a[0] * b[2];
  t += (dpint)a[1] * b[1];
  t += (dpint)a[2] * b[0];
  t += (dpint)v0 * (dpint)p2;
  t += (dpint)v1 * (dpint)p1;
  spint v2 = (((spint)t * ndash) & mask);
  t += (dpint)v2 * (dpint)p0;
  t >>= 52;
  t += (dpint)a[0] * b[3];
  t += (dpint)a[1] * b[2];
  t += (dpint)a[2] * b[1];
  t += (dpint)a[3] * b[0];
  t += (dpint)v0 * (dpint)p3;
  t += (dpint)v1 * (dpint)p2;
  t += (dpint)v2 * (dpint)p1;
  spint v3 = (((spint)t * ndash) & mask);
  t += (dpint)v3 * (dpint)p0;
  t >>= 52;
  t += (dpint)a[0] * b[4];
  t += (dpint)a[1] * b[3];
  t += (dpint)a[2] * b[2];
  t += (dpint)a[3] * b[1];
  t += (dpint)a[4] * b[0];
  t += (dpint)v0 * (dpint)p4;
  t += (dpint)v1 * (dpint)p3;
  t += (dpint)v2 * (dpint)p2;
  t += (dpint)v3 * (dpint)p1;
  spint v4 = (((spint)t * ndash) & mask);
  t += (dpint)v4 * (dpint)p0;
  t >>= 52;
  t += (dpint)a[1] * b[4];
  t += (dpint)a[2] * b[3];
  t += (dpint)a[3] * b[2];
  t += (dpint)a[4] * b[1];
  t += (dpint)v1 * (dpint)p4;
  t += (dpint)v2 * (dpint)p3;
  t += (dpint)v3 * (dpint)p2;
  t += (dpint)v4 * (dpint)p1;
  c[0] = ((spint)t & mask);
  t >>= 52;
  t += (dpint)a[2] * b[4];
  t += (dpint)a[3] * b[3];
  t += (dpint)a[4] * b[2];
  t += (dpint)v2 * (dpint)p4;
  t += (dpint)v3 * (dpint)p3;
  t += (dpint)v4 * (dpint)p2;
  c[1] = ((spint)t & mask);
  t >>= 52;
  t += (dpint)a[3] * b[4];
  t += (dpint)a[4] * b[3];
  t += (dpint)v3 * (dpint)p4;
  t += (dpint)v4 * (dpint)p3;
  c[2] = ((spint)t & mask);
  t >>= 52;
  t += (dpint)a[4] * b[4];
  t += (dpint)v4 * (dpint)p4;
  c[3] = ((spint)t & mask);
  t >>= 52;
  c[4] = (spint)t;
}

// Modular squaring, c=a*a  mod 2p
static void inline modsqr(const spint *a, spint *c) {
  udpint tot;
  udpint t = 0;
  spint p0 = 0xc4d86fc6efff7u;
  spint p1 = 0x42a9f26f65995u;
  spint p2 = 0x8d21a078008f6u;
  spint p3 = 0xc1ba3edd76014u;
  spint p4 = 0x53d1c0debdc0u;
  spint q = ((spint)1 << 52u); // q is unsaturated radix
  spint mask = (spint)(q - (spint)1);
  spint ndash = 0x3a641f9a28e39u;
  tot = (udpint)a[0] * a[0];
  t = tot;
  spint v0 = (((spint)t * ndash) & mask);
  t += (udpint)v0 * p0;
  t >>= 52;
  tot = (udpint)a[0] * a[1];
  tot *= 2;
  t += tot;
  t += (udpint)v0 * p1;
  spint v1 = (((spint)t * ndash) & mask);
  t += (udpint)v1 * p0;
  t >>= 52;
  tot = (udpint)a[0] * a[2];
  tot *= 2;
  tot += (udpint)a[1] * a[1];
  t += tot;
  t += (udpint)v0 * p2;
  t += (udpint)v1 * p1;
  spint v2 = (((spint)t * ndash) & mask);
  t += (udpint)v2 * p0;
  t >>= 52;
  tot = (udpint)a[0] * a[3];
  tot += (udpint)a[1] * a[2];
  tot *= 2;
  t += tot;
  t += (udpint)v0 * p3;
  t += (udpint)v1 * p2;
  t += (udpint)v2 * p1;
  spint v3 = (((spint)t * ndash) & mask);
  t += (udpint)v3 * p0;
  t >>= 52;
  tot = (udpint)a[0] * a[4];
  tot += (udpint)a[1] * a[3];
  tot *= 2;
  tot += (udpint)a[2] * a[2];
  t += tot;
  t += (udpint)v0 * p4;
  t += (udpint)v1 * p3;
  t += (udpint)v2 * p2;
  t += (udpint)v3 * p1;
  spint v4 = (((spint)t * ndash) & mask);
  t += (udpint)v4 * p0;
  t >>= 52;
  tot = (udpint)a[1] * a[4];
  tot += (udpint)a[2] * a[3];
  tot *= 2;
  t += tot;
  t += (udpint)v1 * p4;
  t += (udpint)v2 * p3;
  t += (udpint)v3 * p2;
  t += (udpint)v4 * p1;
  c[0] = ((spint)t & mask);
  t >>= 52;
  tot = (udpint)a[2] * a[4];
  tot *= 2;
  tot += (udpint)a[3] * a[3];
  t += tot;
  t += (udpint)v2 * p4;
  t += (udpint)v3 * p3;
  t += (udpint)v4 * p2;
  c[1] = ((spint)t & mask);
  t >>= 52;
  tot = (udpint)a[3] * a[4];
  tot *= 2;
  t += tot;
  t += (udpint)v3 * p4;
  t += (udpint)v4 * p3;
  c[2] = ((spint)t & mask);
  t >>= 52;
  tot = (udpint)a[4] * a[4];
  t += tot;
  t += (udpint)v4 * p4;
  c[3] = ((spint)t & mask);
  t >>= 52;
  c[4] = (spint)t;
}

// copy
static void inline modcpy(const spint *a, spint *c) {
  int i;
  for (i = 0; i < 5; i++) {
    c[i] = a[i];
  }
}

// square n times
static void modnsqr(spint *a, int n) {
  int i;
  for (i = 0; i < n; i++) {
    modsqr(a, a);
  }
}

// Calculate progenitor
static void modpro(const spint *w, spint *z) {
  spint x[5];
  spint t0[5];
  spint t1[5];
  spint t2[5];
  spint t3[5];
  spint t4[5];
  spint t5[5];
  spint t6[5];
  spint t7[5];
  spint t8[5];
  spint t9[5];
  spint t10[5];
  spint t11[5];
  spint t12[5];
  spint t13[5];
  spint t14[5];
  spint t15[5];
  spint t16[5];
  spint t17[5];
  spint t18[5];
  spint t19[5];
  modcpy(w, x);
  modsqr(x, z);
  modmul(x, z, t18);
  modmul(x, t18, t7);
  modmul(x, t7, t13);
  modmul(z, t13, t1);
  modmul(t13, t1, t0);
  modmul(x, t0, t14);
  modmul(z, t14, t12);
  modmul(z, t12, t3);
  modmul(z, t3, t5);
  modmul(z, t5, t9);
  modmul(t0, t12, t2);
  modmul(z, t2, t17);
  modmul(z, t17, t8);
  modmul(z, t8, t10);
  modmul(z, t10, t11);
  modmul(z, t11, t6);
  modmul(t7, t6, t15);
  modmul(z, t15, t4);
  modmul(t0, t4, t0);
  modmul(t7, t0, t16);
  modmul(z, t16, t7);
  modmul(z, t7, z);
  modmul(t5, z, t19);
  modnsqr(t19, 4);
  modmul(t17, t19, t19);
  modnsqr(t19, 6);
  modmul(t1, t19, t19);
  modnsqr(t19, 12);
  modmul(t0, t19, t19);
  modnsqr(t19, 6);
  modmul(t4, t19, t19);
  modnsqr(t19, 6);
  modmul(t0, t19, t19);
  modnsqr(t19, 8);
  modmul(t18, t19, t18);
  modnsqr(t18, 11);
  modmul(t0, t18, t18);
  modnsqr(t18, 7);
  modmul(t11, t18, t18);
  modnsqr(t18, 6);
  modmul(t16, t18, t18);
  modnsqr(t18, 6);
  modmul(t17, t18, t17);
  modnsqr(t17, 7);
  modmul(t16, t17, t16);
  modnsqr(t16, 14);
  modmul(t15, t16, t15);
  modnsqr(t15, 7);
  modmul(t14, t15, t14);
  modnsqr(t14, 8);
  modmul(t10, t14, t14);
  modnsqr(t14, 3);
  modmul(t13, t14, t13);
  modnsqr(t13, 10);
  modmul(t12, t13, t12);
  modnsqr(t12, 17);
  modmul(t11, t12, t11);
  modnsqr(t11, 5);
  modmul(t2, t11, t11);
  modnsqr(t11, 8);
  modmul(t10, t11, t10);
  modnsqr(t10, 6);
  modmul(t9, t10, t9);
  modnsqr(t9, 7);
  modmul(t8, t9, t8);
  modnsqr(t8, 7);
  modmul(t5, t8, t8);
  modnsqr(t8, 7);
  modmul(t7, t8, t7);
  modnsqr(t7, 6);
  modmul(t6, t7, t6);
  modnsqr(t6, 5);
  modmul(t5, t6, t5);
  modnsqr(t5, 8);
  modmul(t4, t5, t4);
  modnsqr(t4, 5);
  modmul(t3, t4, t3);
  modnsqr(t3, 7);
  modmul(t2, t3, t2);
  modnsqr(t2, 10);
  modmul(t0, t2, t2);
  modnsqr(t2, 3);
  modmul(t1, t2, t1);
  modnsqr(t1, 9);
  modmul(t0, t1, t0);
  modnsqr(t0, 7);
  modmul(z, t0, t0);
  modnsqr(t0, 6);
  modmul(z, t0, z);
  modnsqr(z, 2);
  modmul(x, z, z);
}

// calculate inverse, provide progenitor h if available
static void modinv(const spint *x, const spint *h, spint *z) {
  spint s[5];
  spint t[5];
  if (h == NULL) {
    modpro(x, t);
  } else {
    modcpy(h, t);
  }
  modcpy(x, s);
  modnsqr(t, 2);
  modmul(s, t, z);
}

// Convert m to n-residue form, n=nres(m)
static void nres(const spint *m, spint *n) {
  const spint c[5] = {0x3ae328536b3a0u, 0xfea1f191ea2e7u, 0x30ea6fb384997u,
                      0xef5144546ca82u, 0x4bf76b11f801u};
  modmul(m, c, n);
}

// Convert n back to normal form, m=redc(n)
static void redc(const spint *n, spint *m) {
  int i;
  spint c[5];
  c[0] = 1;
  for (i = 1; i < 5; i++) {
    c[i] = 0;
  }
  modmul(n, c, m);
  (void)modfsb(m);
}

// is unity?
static int modis1(const spint *a) {
  int i;
  spint c[5];
  spint c0;
  spint d = 0;
  redc(a, c);
  for (i = 1; i < 5; i++) {
    d |= c[i];
  }
  c0 = (spint)c[0];
  return ((spint)1 & ((d - (spint)1) >> 52u) &
          (((c0 ^ (spint)1) - (spint)1) >> 52u));
}

// is zero?
static int modis0(const spint *a) {
  int i;
  spint c[5];
  spint d = 0;
  redc(a, c);
  for (i = 0; i < 5; i++) {
    d |= c[i];
  }
  return ((spint)1 & ((d - (spint)1) >> 52u));
}

// set to zero
static void modzer(spint *a) {
  int i;
  for (i = 0; i < 5; i++) {
    a[i] = 0;
  }
}

// set to one
static void modone(spint *a) {
  int i;
  a[0] = 1;
  for (i = 1; i < 5; i++) {
    a[i] = 0;
  }
  nres(a, a);
}

// set to integer
static void modint(int x, spint *a) {
  int i;
  a[0] = (spint)x;
  for (i = 1; i < 5; i++) {
    a[i] = 0;
  }
  nres(a, a);
}

// Modular multiplication by an integer, c=a*b mod 2p
// uses special method for trinomials, otherwise Barrett-Dhem reduction
static void inline modmli(const spint *a, int b, spint *c) {
  spint p0 = 0xc4d86fc6efff7u;
  spint p1 = 0x42a9f26f65995u;
  spint p2 = 0x8d21a078008f6u;
  spint p3 = 0xc1ba3edd76014u;
  spint p4 = 0x53d1c0debdc0u;
  spint mask = ((spint)1 << 52u) - (spint)1;
  udpint t = 0;
  spint q, h, r = 0x186ef9cd524695;
  t += (udpint)a[0] * (udpint)b;
  c[0] = (spint)t & mask;
  t = t >> 52u;
  t += (udpint)a[1] * (udpint)b;
  c[1] = (spint)t & mask;
  t = t >> 52u;
  t += (udpint)a[2] * (udpint)b;
  c[2] = (spint)t & mask;
  t = t >> 52u;
  t += (udpint)a[3] * (udpint)b;
  c[3] = (spint)t & mask;
  t = t >> 52u;
  t += (udpint)a[4] * (udpint)b;
  c[4] = (spint)t & mask;

  // Barrett-Dhem reduction
  h = (spint)(t >> 35u);
  q = (spint)(((udpint)h * (udpint)r) >> 64u);
  t = (udpint)q * (udpint)p0;
  c[0] -= (spint)t & mask;
  c[1] -= (spint)(t >> 52u);
  t = (udpint)q * (udpint)p1;
  c[1] -= (spint)t & mask;
  c[2] -= (spint)(t >> 52u);
  t = (udpint)q * (udpint)p2;
  c[2] -= (spint)t & mask;
  c[3] -= (spint)(t >> 52u);
  t = (udpint)q * (udpint)p3;
  c[3] -= (spint)t & mask;
  c[4] -= (spint)(t >> 52u);
  c[4] = (c[4] - (q * p4)) & mask;
  (void)prop(c);
}

// Test for quadratic residue
static int modqr(const spint *h, const spint *x) {
  spint r[5];
  if (h == NULL) {
    modpro(x, r);
    modsqr(r, r);
  } else {
    modsqr(h, r);
  }
  modmul(r, x, r);
  return modis1(r) | modis0(x);
}

// conditional move g to f if d=1
// strongly recommend inlining be disabled using compiler specific syntax
static void __attribute__((noinline))
modcmv(int b, const spint *g, volatile spint *f) {
  int i;
  spint c0, c1, s, t, w, aux;
  static spint R = 0;
  R += 0x3cc3c33c5aa5a55au;
  w = R;
  c0 = (~b) & (w + 1);
  c1 = b + w;
  for (i = 0; i < 5; i++) {
    s = g[i];
    t = f[i];
    f[i] = aux = c0 * t + c1 * s;
    f[i] = aux - w * (t + s);
  }
}

// conditional swap g and f if d=1
// strongly recommend inlining be disabled using compiler specific syntax
static void __attribute__((noinline))
modcsw(int b, volatile spint *g, volatile spint *f) {
  int i;
  spint c0, c1, s, t, w, v, aux;
  static spint R = 0;
  R += 0x3cc3c33c5aa5a55au;
  w = R;
  c0 = (~b) & (w + 1);
  c1 = b + w;
  for (i = 0; i < 5; i++) {
    s = g[i];
    t = f[i];
    v = w * (t + s);
    f[i] = aux = c0 * t + c1 * s;
    f[i] = aux - v;
    g[i] = aux = c0 * s + c1 * t;
    g[i] = aux - v;
  }
}

// Modular square root, provide progenitor h if available, NULL if not
static void modsqrt(const spint *x, const spint *h, spint *r) {
  spint s[5];
  spint y[5];
  if (h == NULL) {
    modpro(x, y);
  } else {
    modcpy(h, y);
  }
  modmul(y, x, s);
  modcpy(s, r);
}

// shift left by less than a word
static void modshl(unsigned int n, spint *a) {
  int i;
  a[4] = ((a[4] << n)) | (a[3] >> (52u - n));
  for (i = 3; i > 0; i--) {
    a[i] = ((a[i] << n) & (spint)0xfffffffffffff) | (a[i - 1] >> (52u - n));
  }
  a[0] = (a[0] << n) & (spint)0xfffffffffffff;
}

// shift right by less than a word. Return shifted out part
static int modshr(unsigned int n, spint *a) {
  int i;
  spint r = a[0] & (((spint)1 << n) - (spint)1);
  for (i = 0; i < 4; i++) {
    a[i] = (a[i] >> n) | ((a[i + 1] << (52u - n)) & (spint)0xfffffffffffff);
  }
  a[4] = a[4] >> n;
  return r;
}

// set a= 2^r
static void mod2r(unsigned int r, spint *a) {
  unsigned int n = r / 52u;
  unsigned int m = r % 52u;
  modzer(a);
  if (r >= 32 * 8)
    return;
  a[n] = 1;
  a[n] <<= m;
  nres(a, a);
}

// export to byte array
static void modexp(const spint *a, char *b) {
  int i;
  spint c[5];
  redc(a, c);
  for (i = 31; i >= 0; i--) {
    b[i] = c[0] & (spint)0xff;
    (void)modshr(8, c);
  }
}

// import from byte array
// returns 1 if in range, else 0
static int modimp(const char *b, spint *a) {
  int i, res;
  for (i = 0; i < 5; i++) {
    a[i] = 0;
  }
  for (i = 0; i < 32; i++) {
    modshl(8, a);
    a[0] += (spint)(unsigned char)b[i];
  }
  res = modfsb(a);
  nres(a, a);
  return res;
}

// determine sign
static int modsign(const spint *a) {
  spint c[5];
  redc(a, c);
  return c[0] % 2;
}

// return true if equal
static int modcmp(const spint *a, const spint *b) {
  spint c[5], d[5];
  int i, eq = 1;
  redc(a, c);
  redc(b, d);
  for (i = 0; i < 5; i++) {
    eq &= (((c[i] ^ d[i]) - 1) >> 52) & 1;
  }
  return eq;
}

// clang-format on
/******************************************************************************
 API functions calling generated code above
 ******************************************************************************/

#include <fp.h>

// void
// fp_set(fp_t *x, const digit_t val)
// {
//     modint((int)val, *x);
// }

void fp_set(fp_t* x, const digit_t val)
{ // Set field element x = val, where val has wordsize

    (*x)[0] = val;
    for (unsigned int i = 1; i < NWORDS_FIELD; i++) {
        (*x)[i] = 0;
    }
}

bool
fp_is_equal(const fp_t *a, const fp_t *b)
{
    // return -(uint32_t)modcmp(*a, *b);
    return (bool)modcmp(*a, *b);
}

bool
fp_is_zero(const fp_t *a)
{
    // return -(uint32_t)modis0(*a);
    return (bool)modis0(*a);
}

void
fp_copy(fp_t *out, const fp_t *a)
{
    modcpy(*a, *out);
}

void
fp_add(fp_t *out, const fp_t *a, const fp_t *b)
{
    modadd(*a, *b, *out);
}

void
fp_sub(fp_t *out, const fp_t *a, const fp_t *b)
{
    modsub(*a, *b, *out);
}

void
fp_neg(fp_t *out, const fp_t *a)
{
    modneg(*a, *out);
}

void
fp_sqr(fp_t *out, const fp_t *a)
{
    modsqr(*a, *out);
}

void
fp_mul(fp_t *out, const fp_t *a, const fp_t *b)
{
    modmul(*a, *b, *out);
}

void
fp_inv(fp_t *x)
{
    modinv(*x, NULL, *x);
}

bool
fp_is_square(const fp_t *a)
{
    return (bool)modqr(NULL, *a);
}

void
fp_sqrt(fp_t *a)
{
    modsqrt(*a, NULL, *a);
}


void
fp_tomont(fp_t* out, const fp_t* a)
{
    nres(*a, *out);
}

void
fp_frommont(fp_t* out, const fp_t* a)
{
    redc(*a, *out);
}

void
fp_mont_setone(fp_t *x)
{
    modone(*x);
}

void fp_swap(digit_t* P, digit_t* Q, const digit_t option)
{ // If option = 0 then P <- P and Q <- Q, else if option = 0xFF...FF then P <- Q and Q <- P
    digit_t temp;

    for (int i = 0; i < NWORDS_FIELD; i++) {
        temp = option & (P[i] ^ Q[i]);
        P[i] = temp ^ P[i];
        Q[i] = temp ^ Q[i];
    }
}

void
fp_encode(void *dst, const fp_t *a)
{
    // Modified version of modexp()
    int i;
    spint c[5];
    redc(*a, c);
    for (i = 0; i < 32; i++) {
        ((char *)dst)[i] = c[0] & (spint)0xff;
        (void)modshr(8, c);
    }
}

uint32_t
fp_decode(fp_t *d, const void *src)
{
    // Modified version of modimp()
    int i;
    spint res;
    const unsigned char *b = src;
    for (i = 0; i < 5; i++) {
        (*d)[i] = 0;
    }
    for (i = 31; i >= 0; i--) {
        modshl(8, *d);
        (*d)[0] += (spint)b[i];
    }
    res = (spint)-modfsb(*d);
    nres(*d, *d);
    // If the value was canonical then res = -1; otherwise, res = 0
    for (i = 0; i < 5; i++) {
        (*d)[i] &= res;
    }
    return (uint32_t)res;
}