

# This file was *autogenerated* from the file /home/xingtingyu/code/temp/C-implementation/scripts/precomp/precompute_quaternion_constants.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_64 = Integer(64); _sage_const_1 = Integer(1); _sage_const_4 = Integer(4); _sage_const_17 = Integer(17); _sage_const_20000 = Integer(20000)#!/usr/bin/env sage
proof.all(False)  # faster

################################################################

from parameters import p, primes_per_order
negl = _sage_const_2 **-_sage_const_64 

################################################################

logp = ceil(log(p, _sage_const_2 ))
loglogp = ceil(log(logp,_sage_const_2 ))
tors2val = (p+_sage_const_1 ).valuation(_sage_const_2 )

defs = dict()

# RepresentInteger data
small = ceil(log(negl, _sage_const_2 ) / -_sage_const_1 )
assert _sage_const_2 **-small <= negl

add_shift = ceil(log(log(negl, _sage_const_1 -_sage_const_1 /(_sage_const_64 *logp)), _sage_const_2 ))
assert (_sage_const_1  - _sage_const_1 /(_sage_const_64 *logp)) ** (_sage_const_2 **(add_shift)) <= negl

defs['QUAT_primality_num_iter'] = ceil(-log(negl, _sage_const_4 ))
defs['QUAT_repres_bound_input'] = add_shift

# Equivalent ideal data
defs['QUAT_equiv_bound_coeff'] = _sage_const_2 **(_sage_const_1  + add_shift//_sage_const_4 )

#qlapoti constants
defs['QUAT_good_prime_lists_length'] = primes_per_order
defs['QUAT_qlapoti_gen_bound_bits'] = _sage_const_17 
defs['QUAT_qlapoti_used_power_of_two'] = tors2val-_sage_const_2 
defs['QUAT_qlapoti_iteration_bound'] = _sage_const_20000 


# Find_uv constants
m = _sage_const_2  + floor((logp - tors2val) / _sage_const_4 )
defs['FINDUV_box_size'] = m
defs['FINDUV_cube_size'] = (_sage_const_2  * m + _sage_const_1 )**_sage_const_4  - _sage_const_1 

################################################################

with open('include/quaternion_constants.h','w') as hfile:
    print(f'#include <quaternion.h>', file=hfile)

    for k,v in defs.items():
        v = ZZ(v)
        print(f'#define {k} {v}', file=hfile)



