#ifndef BWKEM128_PARAMS_H
#define BWKEM128_PARAMS_H

#ifndef BWKEM128_K
#define BWKEM128_K 2
#endif

#if (BWKEM128_K != 2)
#error "This implementation tree is fixed to the BW_KEM_C128 instance (l = 2)"
#endif

#define BWKEM128_NAMESPACE(s) bwkem128_avx2_##s

#define BWKEM128_NAME "BW_KEM_C128_AVX2"

#define BWKEM128_N 256
#define BWKEM128_Q 3329
#define BWKEM128_QHAT 4096
#define BWKEM128_QHAT_BITS 12
#define BWKEM128_QHAT_HALF (BWKEM128_QHAT / 2)

#define BWKEM128_SYMBYTES 16
#define BWKEM128_PUBLICSEEDBYTES 16
#define BWKEM128_SSBYTES 16
#define BWKEM128_INDCPA_MSGBYTES 16
#define BWKEM128_PREFIXHASHBYTES 17

#define BWKEM128_POLYBYTES 384
#define BWKEM128_POLYVECBYTES (BWKEM128_K * BWKEM128_POLYBYTES)

#define BWKEM128_EQ 12
#define BWKEM128_P_BITS 10
#define BWKEM128_G_BITS 4

#define BWKEM128_POLYVECCOMPRESSEDBYTES \
  ((BWKEM128_K * BWKEM128_N * BWKEM128_P_BITS) / 8)
#define BWKEM128_POLYCOMPRESSEDBYTES \
  ((BWKEM128_N * BWKEM128_G_BITS) / 8)

#define BWKEM128_INDCPA_PUBLICKEYBYTES \
  (BWKEM128_POLYVECBYTES + BWKEM128_PUBLICSEEDBYTES)
#define BWKEM128_INDCPA_SECRETKEYBYTES (BWKEM128_POLYVECBYTES)
#define BWKEM128_INDCPA_BYTES \
  (BWKEM128_POLYVECCOMPRESSEDBYTES + BWKEM128_POLYCOMPRESSEDBYTES)

#define BWKEM128_PUBLICKEYBYTES (BWKEM128_INDCPA_PUBLICKEYBYTES)
#define BWKEM128_TARGET_SECRETKEYBYTES 1585
#define BWKEM128_SECRETKEYBYTES \
  (BWKEM128_INDCPA_SECRETKEYBYTES + BWKEM128_PUBLICKEYBYTES + \
   BWKEM128_PREFIXHASHBYTES + BWKEM128_SYMBYTES)
#define BWKEM128_CIPHERTEXTBYTES (BWKEM128_INDCPA_BYTES)

#define BWKEM128_ETA_S 6
#define BWKEM128_ETA_E 6
#define BWKEM128_ETA_CT 5
#define BWKEM128_MAX_SUPPORTED_ETA 6

#define BWKEM128_NOISE_ETA_KEY_SECRET BWKEM128_ETA_S
#define BWKEM128_NOISE_ETA_KEY_ERROR  BWKEM128_ETA_E
#define BWKEM128_NOISE_ETA_ENC_SECRET BWKEM128_ETA_S
#define BWKEM128_NOISE_ETA_ENC_ERROR  BWKEM128_ETA_E
#define BWKEM128_NOISE_ETA_ENC_V      BWKEM128_ETA_CT

/*
 * Internal compatibility aliases for the retained imported module layout.
 * These are implementation details of this implementation tree, not part of
 * the intended external interface. The default Makefile enables them via
 * BWKEM128_INTERNAL_COMPAT so that the imported source files do not need a
 * large-scale mechanical rewrite.
 */
#ifdef BWKEM128_INTERNAL_COMPAT
#define KYBER_K BWKEM128_K
#define KYBER_NAMESPACE(s) BWKEM128_NAMESPACE(s)

#define KYBER_N BWKEM128_N
#define KYBER_Q BWKEM128_Q

#define KYBER_SYMBYTES BWKEM128_SYMBYTES
#define KYBER_SSBYTES BWKEM128_SSBYTES

#define KYBER_POLYBYTES BWKEM128_POLYBYTES
#define KYBER_POLYVECBYTES BWKEM128_POLYVECBYTES

#define KYBER_EQ BWKEM128_EQ
#define KYBER_POLYVECCOMPRESSEDBYTES BWKEM128_POLYVECCOMPRESSEDBYTES
#define KYBER_POLYCOMPRESSEDBYTES BWKEM128_POLYCOMPRESSEDBYTES

#define KYBER_ETA1 BWKEM128_ETA_S
#define KYBER_ETA2 BWKEM128_ETA_CT

#define KYBER_INDCPA_MSGBYTES BWKEM128_INDCPA_MSGBYTES
#define KYBER_INDCPA_PUBLICKEYBYTES BWKEM128_INDCPA_PUBLICKEYBYTES
#define KYBER_INDCPA_SECRETKEYBYTES BWKEM128_INDCPA_SECRETKEYBYTES
#define KYBER_INDCPA_BYTES BWKEM128_INDCPA_BYTES

#define KYBER_PUBLICKEYBYTES BWKEM128_PUBLICKEYBYTES
#define PREFIXHASHBYTES BWKEM128_PREFIXHASHBYTES
#define KYBER_SECRETKEYBYTES BWKEM128_SECRETKEYBYTES
#define KYBER_CIPHERTEXTBYTES BWKEM128_CIPHERTEXTBYTES
#endif

#ifndef KYBER_K
#define KYBER_K BWKEM128_K
#endif
#ifndef KYBER_NAMESPACE
#define KYBER_NAMESPACE(s) BWKEM128_NAMESPACE(s)
#endif

#ifndef KYBER_N
#define KYBER_N BWKEM128_N
#endif
#ifndef KYBER_Q
#define KYBER_Q BWKEM128_Q
#endif

#ifndef KYBER_SYMBYTES
#define KYBER_SYMBYTES BWKEM128_SYMBYTES
#endif
#ifndef KYBER_SSBYTES
#define KYBER_SSBYTES BWKEM128_SSBYTES
#endif

#ifndef KYBER_POLYBYTES
#define KYBER_POLYBYTES BWKEM128_POLYBYTES
#endif
#ifndef KYBER_POLYVECBYTES
#define KYBER_POLYVECBYTES BWKEM128_POLYVECBYTES
#endif

#ifndef KYBER_EQ
#define KYBER_EQ BWKEM128_EQ
#endif
#ifndef KYBER_POLYVECCOMPRESSEDBYTES
#define KYBER_POLYVECCOMPRESSEDBYTES BWKEM128_POLYVECCOMPRESSEDBYTES
#endif
#ifndef KYBER_POLYCOMPRESSEDBYTES
#define KYBER_POLYCOMPRESSEDBYTES BWKEM128_POLYCOMPRESSEDBYTES
#endif

#ifndef KYBER_ETA1
#define KYBER_ETA1 BWKEM128_ETA_S
#endif
#ifndef KYBER_ETA2
#define KYBER_ETA2 BWKEM128_ETA_CT
#endif

#ifndef KYBER_INDCPA_MSGBYTES
#define KYBER_INDCPA_MSGBYTES BWKEM128_INDCPA_MSGBYTES
#endif
#ifndef KYBER_INDCPA_PUBLICKEYBYTES
#define KYBER_INDCPA_PUBLICKEYBYTES BWKEM128_INDCPA_PUBLICKEYBYTES
#endif
#ifndef KYBER_INDCPA_SECRETKEYBYTES
#define KYBER_INDCPA_SECRETKEYBYTES BWKEM128_INDCPA_SECRETKEYBYTES
#endif
#ifndef KYBER_INDCPA_BYTES
#define KYBER_INDCPA_BYTES BWKEM128_INDCPA_BYTES
#endif

#ifndef KYBER_PUBLICKEYBYTES
#define KYBER_PUBLICKEYBYTES BWKEM128_PUBLICKEYBYTES
#endif
#ifndef PREFIXHASHBYTES
#define PREFIXHASHBYTES BWKEM128_PREFIXHASHBYTES
#endif
#ifndef KYBER_SECRETKEYBYTES
#define KYBER_SECRETKEYBYTES BWKEM128_SECRETKEYBYTES
#endif
#ifndef KYBER_CIPHERTEXTBYTES
#define KYBER_CIPHERTEXTBYTES BWKEM128_CIPHERTEXTBYTES
#endif

#endif
