#ifndef PARAMS_H
#define PARAMS_H

#define DTRU_N 1087

#define DTRU_Q 2017
#define DTRU_LOGQ 11

#define DTRU_Q2 1024
#define DTRU_LOGQ2 10

#define DTRU_ETA 1
#define DTRU_BOUND (2 * DTRU_ETA + 1)



#define DTRU_MSGBYTES 32 /* floor(DTRU_N / 32) * 8 bits = 33 * 8 bits = 33 bytes -> 32 bytes */
#define DTRU_SEEDBYTES 32

#define SHA3512_OUTPUTBYTES 64
#define DTRU_Z_BYTES 32
#define DTRU_SHAREDKEYBYTES 32
#define DTRU_PREFIXHASHBYTES 33



#define DTRU_CBD1_BYTES (DTRU_N * 2 + 7) / 8
#define DTRU_CBD2_BYTES (DTRU_N * 4 + 7) / 8
#define DTRU_COINBYTES_KEYGEN (DTRU_CBD1_BYTES + DTRU_CBD2_BYTES)
#define DTRU_COINBYTES_ENC (DTRU_CBD1_BYTES + DTRU_CBD2_BYTES)

#define DTRU_PKE_PUBLICKEYBYTES (DTRU_N * DTRU_LOGQ + 7) / 8
#define DTRU_PKE_CIPHERTEXTBYTES (DTRU_N * DTRU_LOGQ2 + 7) / 8

#define DTRU_PKE_SECRETKEYBYTES (DTRU_N * 3 + 7) / 8

#define DTRU_KEM_PUBLICKEYBYTES DTRU_PKE_PUBLICKEYBYTES
#define DTRU_KEM_SECRETKEYBYTES (DTRU_PKE_SECRETKEYBYTES + DTRU_PKE_PUBLICKEYBYTES + DTRU_Z_BYTES)
#define DTRU_KEM_CIPHERTEXTBYTES DTRU_PKE_CIPHERTEXTBYTES

#endif
